<html>
  <head>
    <META http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="topic-type" content="reference-adsk">
    <meta name="helpsystempath" content="/view/INVNTOR/2026/ENU/">
    <link rel="canonical" href="/cloudhelp/2026/ENU/Inventor-API/files/AddiPartMember_Sample.htm#!">
    <meta name="product" content="INVNTOR">
    <meta name="release" content="2026">
    <meta name="book" content="Developer">
    <meta name="component" content="Inventor-API">
    <meta name="created" content="">
    <meta name="user-comments" content="enable">
    <meta name="contextid" content="AddiPartMember_Sample">
    <meta name="description" content="Adding iPart occurrences to an assembly Sample">
    <meta name="topicid" content="AddiPartMember_Sample">
    <meta name="experiencelevel" content="expert">
    <meta name="audience" content="programmer">
    <meta name="language" content="ENU">
    <title>Adding iPart occurrences to an assembly</title>
    <link rel="stylesheet" href="../Style/jquery-ui.css"><script src="../Scripts/jquery-1.11.1.js"></script><script src="../Scripts/jquery-ui.js"></script><link rel="stylesheet" type="text/css" href="../Style/APIHelp-chm.css">
    <link rel="stylesheet" type="text/css" href="/view/clientframework/client.css"><script type="text/javascript" src="/view/clientframework/client.js"></script><script>
          // This turns on the display of the copyright notice which is not visible by default.
          // Because the head is removed when used in the web help, this function will only exists
          // when the chm help is being created.
          window.onload = function() {
          copyrightElement = document.getElementById('CopyrightNotice');
          copyrightElement.style.display = 'block';
          };
        </script><script>
          $(function() {
          $( "#tabs" ).tabs();
          });
        </script></head>
  <body><script>
          function copyCode(language) {
          // Get the pre element for the specified language.
          var preElement = document.getElementById(language);

          // Get the text from the element and copy it to the clipboard.
          var preText = preElement.innerText;

          var isIE = /*@cc_on!@*/false || !!document.documentMode;

          if (isIE)
          {
            window.clipboardData.setData('Text', preText);
          }
          else
          {
            navigator.clipboard.writeText(preText);
          }

          //alert("Code copied to clipboard");
          }
        </script><link rel="stylesheet" type="text/css" href="../Style/APIHelp.css">
    <h1 class="api">Adding iPart occurrences to an assembly</h1>
    <h2 class="api">
          Description
        </h2>This sample demonstrates adding iPart occurrences to an assembly.<h2 class="api">
          Code Samples
        </h2>
    <div id="tabs">
      <ul>
        <li><a href="#VBA">VBA</a></li>
        <li><a href="#iLogic">iLogic</a></li>
        <li><a href="#C#">C#</a></li>
      </ul>
      <div id="VBA" class="api-code">Before running the sample, make sure that C:\temp\iPartFactory.ipt exists and that it is an iPart factory.<table width="100%" style="font-size:15">
          <tr>
            <td align="right"><button onclick="copyCode('VBA_code')" class="copy-code">Copy Code</button></td>
          </tr>
        </table>
        <pre class="api-code" id="VBA_code">Public Sub AddiPartOccurrence()
    <span style="color:blue">' Open the factory document invisible.</span>
    Dim oFactoryDoc As PartDocument
    Set oFactoryDoc = ThisApplication.Documents.Open("C:\temp\iPartFactory.ipt", False)

    <span style="color:blue">' Set a reference to the component definition.</span>
    Dim oCompDef As PartComponentDefinition
    Set oCompDef = oFactoryDoc.ComponentDefinition

    <span style="color:blue">' Make sure we have an iPart factory.</span>
    If oCompDef.IsiPartFactory = False Then
        MsgBox "Chosen document is not a factory.", vbExclamation
        Exit Sub
    End If

    <span style="color:blue">' Set a reference to the factory.</span>
    Dim oiPartFactory As iPartFactory
    Set oiPartFactory = oCompDef.iPartFactory

    <span style="color:blue">' Get the number of rows in the factory.</span>
    Dim iNumRows As Integer
    iNumRows = oiPartFactory.TableRows.Count

    <span style="color:blue">' Create a new assembly document</span>
    Dim oDoc As AssemblyDocument
    Set oDoc = ThisApplication.Documents.Add(kAssemblyDocumentObject, , True)

    Dim oOccs As ComponentOccurrences
    Set oOccs = oDoc.ComponentDefinition.Occurrences

    Dim oPos As Matrix
    Set oPos = ThisApplication.TransientGeometry.CreateMatrix

    Dim oStep As Double
    oStep = 0#
    Dim iRow As Long

    <span style="color:blue">' Add an occurrence for each member in the factory.</span>
    For iRow = 1 To iNumRows

        oStep = oStep + 10

        <span style="color:blue">' Add a translation along X axis</span>
        oPos.SetTranslation ThisApplication.TransientGeometry.CreateVector(oStep, oStep, 0)

        Dim oOcc As ComponentOccurrence
        Set oOcc = oOccs.AddiPartMember("C:\temp\iPartFactory.ipt ", oPos, iRow)
    Next
End Sub</pre>
      </div>
      <div id="iLogic" class="api-code">Before running the sample, make sure that C:\temp\iPartFactory.ipt exists and that it is an iPart factory.<table width="100%" style="font-size:15">
          <tr>
            <td align="right"><button onclick="copyCode('iLogic_code')" class="copy-code">Copy Code</button></td>
          </tr>
        </table>
        <pre class="api-code" id="iLogic_code">    <span style="color:blue">' Open the factory document invisible.</span>
    Dim oFactoryDoc As PartDocument
    oFactoryDoc = ThisApplication.Documents.Open("C:\temp\iPartFactory.ipt", False)

    <span style="color:blue">' Set a reference to the component definition.</span>
    Dim oCompDef As PartComponentDefinition
    oCompDef = oFactoryDoc.ComponentDefinition

    <span style="color:blue">' Make sure we have an iPart factory.</span>
    If oCompDef.IsiPartFactory = False Then
        MsgBox("Chosen document is not a factory.", vbExclamation)
        Exit Sub
    End If

    <span style="color:blue">' Set a reference to the factory.</span>
    Dim oiPartFactory As iPartFactory
    oiPartFactory = oCompDef.iPartFactory

    <span style="color:blue">' Get the number of rows in the factory.</span>
    Dim iNumRows As Integer
    iNumRows = oiPartFactory.TableRows.Count

    <span style="color:blue">' Create a new assembly document</span>
    Dim oDoc As AssemblyDocument
    oDoc = ThisApplication.Documents.Add(kAssemblyDocumentObject, , True)

    Dim oOccs As ComponentOccurrences
    oOccs = oDoc.ComponentDefinition.Occurrences

    Dim oPos As Matrix
    oPos = ThisApplication.TransientGeometry.CreateMatrix

    Dim oStep As Double
    oStep = 0#
    Dim iRow As Long

    <span style="color:blue">' Add an occurrence for each member in the factory.</span>
    For iRow = 1 To iNumRows

        oStep = oStep + 10

        <span style="color:blue">' Add a translation along X axis</span>
        oPos.SetTranslation(ThisApplication.TransientGeometry.CreateVector(oStep, oStep, 0))

        Dim oOcc As ComponentOccurrence
        oOcc = oOccs.AddiPartMember("C:\temp\iPartFactory.ipt ", oPos, iRow)
    Next</pre>
      </div>
      <div id="C#" class="api-code">Before running the sample, make sure that C:/temp/iPartFactory.ipt exists and that it is an iPart factory. The first line of the C# sample sets the oApp variable to ThisApplication - this should be appropriately changed.<table width="100%" style="font-size:15">
          <tr>
            <td align="right"><button onclick="copyCode('C#_code')" class="copy-code">Copy Code</button></td>
          </tr>
        </table>
        <pre class="api-code" id="C#_code">Sub Main()
    ' Open the factory document invisible.
    Dim oFactoryDoc As PartDocument
    oFactoryDoc = ThisApplication.Documents.Open("C:\temp\iPartFactory.ipt", False)

    ' Set a reference to the component definition.
    Dim oCompDef As PartComponentDefinition
    oCompDef = oFactoryDoc.ComponentDefinition

    ' Make sure we have an iPart factory.
    If oCompDef.IsiPartFactory = False Then
        MsgBox("Chosen document is not a factory.", vbExclamation)
        Exit Sub
    End If

    ' Set a reference to the factory.
    Dim oiPartFactory As iPartFactory
    oiPartFactory = oCompDef.iPartFactory

    ' Get the number of rows in the factory.
    Dim iNumRows As Integer
    iNumRows = oiPartFactory.TableRows.Count

    ' Create a new assembly document
    Dim oDoc As AssemblyDocument
    oDoc = ThisApplication.Documents.Add(kAssemblyDocumentObject, , True)

    Dim oOccs As ComponentOccurrences
    oOccs = oDoc.ComponentDefinition.Occurrences

    Dim oPos As Matrix
    oPos = ThisApplication.TransientGeometry.CreateMatrix

    Dim oStep As Double
    oStep = 0#
    Dim iRow As Long

    ' Add an occurrence for each member in the factory.
    For iRow = 1 To iNumRows

        oStep = oStep + 10

        ' Add a translation along X axis
        oPos.SetTranslation(ThisApplication.TransientGeometry.CreateVector(oStep, oStep, 0))

        Dim oOcc As ComponentOccurrence
        oOcc = oOccs.AddiPartMember("C:\temp\iPartFactory.ipt ", oPos, iRow)
    Next
End Sub</pre>
      </div>
    </div><br><br><div id="CopyrightNotice" style="display:none;">
      <hr>
      <table width="100%" style="font-size:15">
        <tr>
          <td align="left">
                Â© Copyright 2025 Autodesk, Inc.
              </td>
          <td align="right"><a href="mailto:mfg.api.help.comments@autodesk.com?subject=Inventor%202026%20API%20Help%20(AddiPartMember%20Sample%20Help%20Topic)">Comment on this page.</a></td>
        </tr>
      </table>
    </div>
  </body>
</html>