<html>
  <head>
    <META http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="topic-type" content="reference-adsk">
    <meta name="helpsystempath" content="/view/INVNTOR/2026/ENU/">
    <link rel="canonical" href="/cloudhelp/2026/ENU/Inventor-API/files/ArcLengthDimConstraint_Sample.htm#!">
    <meta name="product" content="INVNTOR">
    <meta name="release" content="2026">
    <meta name="book" content="Developer">
    <meta name="component" content="Inventor-API">
    <meta name="created" content="">
    <meta name="user-comments" content="enable">
    <meta name="contextid" content="ArcLengthDimConstraint_Sample">
    <meta name="description" content="Creates an Arc Length Dimension Constraint Sample">
    <meta name="topicid" content="ArcLengthDimConstraint_Sample">
    <meta name="experiencelevel" content="expert">
    <meta name="audience" content="programmer">
    <meta name="language" content="ENU">
    <title>Creates an Arc Length Dimension Constraint</title>
    <link rel="stylesheet" href="../Style/jquery-ui.css"><script src="../Scripts/jquery-1.11.1.js"></script><script src="../Scripts/jquery-ui.js"></script><link rel="stylesheet" type="text/css" href="../Style/APIHelp-chm.css">
    <link rel="stylesheet" type="text/css" href="/view/clientframework/client.css"><script type="text/javascript" src="/view/clientframework/client.js"></script><script>
          // This turns on the display of the copyright notice which is not visible by default.
          // Because the head is removed when used in the web help, this function will only exists
          // when the chm help is being created.
          window.onload = function() {
          copyrightElement = document.getElementById('CopyrightNotice');
          copyrightElement.style.display = 'block';
          };
        </script><script>
          $(function() {
          $( "#tabs" ).tabs();
          });
        </script></head>
  <body><script>
          function copyCode(language) {
          // Get the pre element for the specified language.
          var preElement = document.getElementById(language);

          // Get the text from the element and copy it to the clipboard.
          var preText = preElement.innerText;

          var isIE = /*@cc_on!@*/false || !!document.documentMode;

          if (isIE)
          {
            window.clipboardData.setData('Text', preText);
          }
          else
          {
            navigator.clipboard.writeText(preText);
          }

          //alert("Code copied to clipboard");
          }
        </script><link rel="stylesheet" type="text/css" href="../Style/APIHelp.css">
    <h1 class="api">Creates an Arc Length Dimension Constraint</h1>
    <h2 class="api">
          Description
        </h2>Demonstrates creating an arc length dimension constraint.<h2 class="api">
          Code Samples
        </h2>
    <div id="tabs">
      <ul>
        <li><a href="#VBA">VBA</a></li>
        <li><a href="#iLogic">iLogic</a></li>
      </ul>
      <div id="VBA" class="api-code">To use this sample a part must be active.<table width="100%" style="font-size:15">
          <tr>
            <td align="right"><button onclick="copyCode('VBA_code')" class="copy-code">Copy Code</button></td>
          </tr>
        </table>
        <pre class="api-code" id="VBA_code">Public Sub ArcLengthDimConstraintSample()
    <span style="color:blue">' Get the active part document.</span>
    Dim partDoc As PartDocument
    Set partDoc = ThisApplication.ActiveDocument
    Dim partDef As PartComponentDefinition
    Set partDef = partDoc.ComponentDefinition
    
    <span style="color:blue">' Create a new sketch.</span>
    Dim sketch As PlanarSketch
    Set sketch = partDef.Sketches.Add(partDef.WorkPlanes.Item(3))
    
    Dim tg As TransientGeometry
    Set tg = ThisApplication.TransientGeometry
    
    Dim dPi As Double
    dPi = Atn(1) * 4
    
    <span style="color:blue">' Create an arc.</span>
    Dim arc As SketchArc
    Set arc = sketch.SketchArcs.AddByCenterStartSweepAngle(tg.CreatePoint2d(0, 0), 5, dPi / 8, dPi / 4)
    
    Dim arcConstraint As ArcLengthDimConstraint
    Set arcConstraint = sketch.DimensionConstraints.AddArcLength(arc, tg.CreatePoint2d(10, 9))
End Sub</pre>
      </div>
      <div id="iLogic" class="api-code">To use this sample a part must be active.<table width="100%" style="font-size:15">
          <tr>
            <td align="right"><button onclick="copyCode('iLogic_code')" class="copy-code">Copy Code</button></td>
          </tr>
        </table>
        <pre class="api-code" id="iLogic_code">    <span style="color:blue">' Get the active part document.</span>
    Dim partDoc As PartDocument
    partDoc = ThisApplication.ActiveDocument
    Dim partDef As PartComponentDefinition
    partDef = partDoc.ComponentDefinition
    
    <span style="color:blue">' Create a new sketch.</span>
    Dim sketch As PlanarSketch
    sketch = partDef.Sketches.Add(partDef.WorkPlanes.Item(3))
    
    Dim tg As TransientGeometry
    tg = ThisApplication.TransientGeometry
    
    Dim dPi As Double
    dPi = Math.Atan(1) * 4
    
    <span style="color:blue">' Create an arc.</span>
    Dim arc As SketchArc
    arc = sketch.SketchArcs.AddByCenterStartSweepAngle(tg.CreatePoint2d(0, 0), 5, dPi / 8, dPi / 4)
    
    Dim arcConstraint As ArcLengthDimConstraint
    arcConstraint = sketch.DimensionConstraints.AddArcLength(arc, tg.CreatePoint2d(10, 9))</pre>
      </div>
    </div><br><br><div id="CopyrightNotice" style="display:none;">
      <hr>
      <table width="100%" style="font-size:15">
        <tr>
          <td align="left">
                Â© Copyright 2025 Autodesk, Inc.
              </td>
          <td align="right"><a href="mailto:mfg.api.help.comments@autodesk.com?subject=Inventor%202026%20API%20Help%20(ArcLengthDimConstraint%20Sample%20Help%20Topic)">Comment on this page.</a></td>
        </tr>
      </table>
    </div>
  </body>
</html>