<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="topic-type" content="reference-adsk">
    <meta name="helpsystempath" content="/view/INVNTOR/2026/ENU">
    <link rel="canonical" href="http://help.autodesk.com/cloudhelp/2026/ENU/Inventor-API/files/AssemblingParts_Overview.htm">
    <meta name="product" content="INVNTOR">
    <meta name="release" content="2026">
    <meta name="book" content="Developer">
    <meta name="component" content="Inventor-API">
    <meta name="created" content="27/4/2016">
    <meta name="user-comments" content="enable">
    <meta name="description" content="">
    <meta name="topicid" content="GUID-BDA5283B-D32F-462A-B8EA-8DDBE0CE2E69">
    <meta name="experiencelevel" content="expert">
    <meta name="audience" content="programmer">
    <meta name="language" content="ENU">
    <title>Assembling Parts</title>
    <link rel="stylesheet" type="text/css" href="../Style/APIHelp-chm.css">
    <link rel="stylesheet" type="text/css" href="/view/clientframework/client.css"/>
    <script type="text/javascript" src="/view/clientframework/client.js"><!--filler--></script>
	<script>
	  // This turns on the display of the copyright notice which is not visible by default.
	  // Because the head is removed when used in the web help, this function will only exists
	  // when the chm help is being created.
	  window.onload = function() {
		copyrightElement = document.getElementById('CopyrightNotice');
		copyrightElement.style.display = 'block';
	  };
	</script>
</head>
<body>
<link rel="stylesheet" type="text/css" href="../Style/APIHelp.css">
	
<H1>Assembling Parts</h1>

<h3>Introduction to parts in an assembly</h3>

<p Class="Normal">Modeling in Autodesk Inventor is more than creating part features from sketch profiles. Typically, a library of part files is created and these parts are assembled together to create a composite model - an assembly.  Assemblies themselves can be treated as discrete components, as subassemblies within a larger assembly. Autodesk Inventor has an extensive user interface for working with parts in the assembly environment, including positioning tools and assembly constraints for defining relationships between parts.</p>

<h3>The purpose of  assembling parts</h3>

<p Class="Normal">This method of gathering parts into an assembly has several advantages. It enables model components to be worked on independently, and it often means the model is considerably smaller in file size, especially when common parts are re-used. The concept it similar to blocks in AutoCAD.</p>


<!--
<br>
<table cellspacing="4" cellpadding="4" border="1">
<tr>
    <td  bgcolor="Yellow"><b>Note:</b> 

</td>
</tr>
</table>
<br>
-->

<h3>Assembly-level component occurrences and definitions - Object Model Diagram</h3>

<br>
<div align="center"> <img src="../images/ov.Component_Occurence_diag.png" border=0></div>
<br>

 
<!--
<br>
<table Class="Code">
<tr valign="middle">
	<td Class="Code">
	<pre>

</pre></td></tr>
</table>
<br>
-->

<h3>Working with assembled parts through the API</h3>

<p Class="Normal">The Autodesk Inventor API employs the concepts of component definitions and occurrences. These are somewhat analogous to AutoCAD block definitions and inserts. A component definition is also the base class for other component definition types - <a href="PartComponentDefinition.html" data-topic-id="GUID-PartComponentDefinition">PartComponentDefinition</a>, <a href="Inventor~AssemblyComponentDefinition.html" data-topic-id="GUID-AssemblyComponentDefinition">AssemblyComponentDefinition</a>, <a href="Inventor~SheetMetalComponentDefinition.html" data-topic-id="GUID-SheetMetalComponentDefinition">SheetMetalComponentDefinition</a>, <a
href="Inventor~WeldmentComponentDefinition.html" data-topic-id="GUID-WeldmentComponentDefinition">WeldmentComponentDefinition</a>, and <a href="WeldsComponentDefinition.htm" data-topic-id="GUID-WeldsComponentDefinition">WeldsComponentDefinition</a>. These are used only when accessing functionality specific to these types.</p>

<p Class="Normal">Think of a component occurrence as an instance of a component definition. The component definition can be a subassembly or a part.  The <a href="ComponentDefinition.htm" data-topic-id="GUID-ComponentDefinition">ComponentDefinition</a> object is the base class for the AssemblyComponentDefinition object.</p>

<p Class="Normal">To insert parts into an assembly, add an occurrence to the <a href="ComponentOccurrences.htm" data-topic-id="GUID-ComponentOccurrences">ComponentOccurrences</a> collection of the assembly document's AssemblyComponentDefinition object.  The ComponentOccurrences collection supports several methods to add an occurrence - by file (the <a href="Inventor~ComponentOccurrences~Add.html" data-topic-id="ComponentOccurrences_Add">Add</a> method) or by inserting another instance of an existing definition (the <a href="Inventor~ComponentOccurrences~AddByComponentDefinition.html" data-topic-id="ComponentOccurrences_AddByComponentDefinition">AddByComponentDefinition</a> method).  It also supports iParts and adding through iMates.</p>

<h3>Adding occurrences is the first step</h3>

<p Class="Normal">Assembling parts also requires a means to specify their positions, and to define how the parts fit together. The add methods described previously support matrices, allowing ComponentOccurrences to be positioned within the assembly document. However, it is typically more convenient to define assembly constraints to indicate how parts should position themselves relative to each other.  Creating an assembly of parts through the API is therefore a two-stage process, since it is through the UI.  First, assemble the parts, and then fit them together. The following sample code demonstrates both processes.</p>

<p Class="Normal">This code assumes a part file named cylinder.ipt exists in a C:\Temp directory.  Use Autodesk Inventor to create and save this part file (a sketched circle extruded to form a cylinder) before running this code. The code omits error checking for the sake of clarity and brevity.  Always check that return values are of the expected type.</p>

<p Class="Normal">First, create a new assembly document:</p>

<br>
<table Class="Code">
<tr valign="middle">
	<td Class="Code">
	<pre>
Dim oApp As Inventor.Application
Set oApp = ThisApplication

Dim oAssyDoc As AssemblyDocument
Set oAssyDoc = oApp.Documents.Add(kAssemblyDocumentObject, _
   oApp.GetTemplateFile(kAssemblyDocumentObject))
</pre></td></tr>
</table>
<br>

<p Class="Normal">Inserting component occurrences requires a matrix, even if it does nothing, so create the matrix object.</p>

<br>
<table Class="Code">
<tr valign="middle">
	<td Class="Code">
	<pre>
Dim oPositionMatrix As Matrix
Set oPositionMatrix = oApp.TransientGeometry.CreateMatrix
</pre></td></tr>
</table>
<br>

<p Class="Normal">Now create the component occurrence by calling the Add method of the ComponentOccurrences collection, referencing the part file previously created manually in Autodesk Inventor.</p>

<br>
<table Class="Code">
<tr valign="middle">
	<td Class="Code">
	<pre>
Dim sFileName As String
sFileName = "c:\temp\cylinder.ipt"

Dim oCylinder1 As ComponentOccurrence
Set oCylinder1 = oAssyDoc.ComponentDefinition.Occurrences.Add(sFileName, oPositionMatrix)
</pre></td></tr>
</table>
<br>

<p Class="Normal">This created the first occurrence of the cylinder part in the assembly. Now add another, but this time, move it to one side. Otherwise it occupies the same space as the first one and is not visible.  Use the matrix object to adjust its insertion position slightly. Here, the matrix also reverses the direction of the cyclinder.</p>

<br>
<table Class="Code">
<tr valign="middle">
	<td Class="Code">
	<pre>
Dim oTrans As Vector
Set oTrans = oApp.TransientGeometry.CreateVector(2, 0, -1)
oPositionMatrix.SetTranslation oTrans
</pre></td></tr>
</table>
<br>

<p Class="Normal">Now add the second occurrence of the cylinder component. </p>

<br>
<table cellspacing="4" cellpadding="4" border="1">
<tr>
    <td  bgcolor="Yellow"><b>Note:</b> 
The reference to the part file is no longer needed when inserting the second cylinder, since there is already an instance of the part in the assembly. Simply reference the same ComponentDefinition, in this case that of the previously inserted ComponentOccurrence.
</td>
</tr>
</table>
<br>

<br>
<table Class="Code">
<tr valign="middle">
	<td Class="Code">
	<pre>
Dim oCylinder2 As ComponentOccurrence
Set oCylinder2 = oAssyDoc.ComponentDefinition.Occurrences.AddByComponentDefinition _
   (oCylinder1.Definition, oPositionMatrix)
</pre></td></tr>
</table>
<br>

<p Class="Normal">In Autodesk Inventor, the preceding code results in two cylinders in the assembly, looking something like the following figure.</p>

<br>
<div align="center"> <img src="../images/ov.parts1.png" border=0></div>
<br>

<p Class="Normal">The intention is to get these cylinders to line up and butt together, and for Autodesk Inventor to ensure they stay that way despite future recomputes of the assembly model. Use assembly constraints to achieve this, in much the same way geometric constraints can define the shape of a sketch.  Apply mate constraints to remove two degrees of freedom, aligning the cylinders to each other, and then mating the ends of the cylinders together. The AssemblyComponentDefinition maintains a collection of constraints to apply to the component occurrences, so add the mate constraints to this collection. First, obtain the assembly component definition.</p>

<br>
<table Class="Code">
<tr valign="middle">
	<td Class="Code">
	<pre>
Dim oAxisDef As AssemblyComponentDefinition
Set oAxisDef = oApp.ActiveDocument.ComponentDefinition
</pre></td></tr>
</table>
<br>

<p Class="Normal">The first constraint will be applied between the curved faces of the two cylinders, to align them. One way to obtain these faces is by iterating through all the faces that make up the surface body of each component occurrence, checking for a cylindrical surface. For more information on faces and surface bodies, refer to the Boundary Representation (<a href="Brep_Overview.htm" data-topic-id="GUID-0CA52532-DD70-4DFD-A79B-1DC2D370E6EC">BRep</a>) sections of the Autodesk Inventor API documentation.</p>

<br>
<table Class="Code">
<tr valign="middle">
	<td Class="Code">
	<pre>
Dim oCylAxis1 As Face
Dim oCylAxis2 As Face
Dim oFace As Face

For Each oFace In oCylinder1.SurfaceBodies(1).Faces
    If oFace.SurfaceType = kCylinderSurface Then
       Set oCylAxis1 = oFace
    End If
Next

For Each oFace In oCylinder2.SurfaceBodies(1).Faces
    If oFace.SurfaceType = kCylinderSurface Then
       Set oCylAxis2 = oFace
    End If
Next
</pre></td></tr>
</table>
<br>

<p Class="Normal">So now oCylAxis1 and oCylAxis2 contain the curved cylinder faces, and can be passed to the <a href="/HTML/AssemblyConstraints_AddMateConstraint.htm" data-topic-id="AssemblyConstraints_AddMateConstraint">AddMateConstraint</a> method of the assembly component definition's <a href="AssemblyConstraints.html" data-topic-id="GUID-AssemblyConstraints">AssemblyConstraints</a> collection.</p>

<br>
<table Class="Code">
<tr valign="middle">
	<td Class="Code">
	<pre>
Dim oConstr As AssemblyConstraint
Set oConstr = oAxisDef.Constraints.AddMateConstraint(oCylAxis1, oCylAxis2, 0, kInferredLine, kInferredLine)
</pre></td></tr>
</table>
<br>

<p Class="Normal">The result of this constraint is shown in the following figure. The two cylinders now occupy the same space, and are indistinguishable from each other. Another constraint is required on the end faces to have the two cylinders butt against each other to form one long cylinder.</p>

<br>
<div align="center"> <img src="../images/ov.parts2.png" border=0></div>
<br>

<p Class="Normal">Again, iterate through the faces of the surface bodies, this time looking for planar faces.  In this case, it is safe to select the face on the same end of each cylinder as the position of the second cylinder was reversed by its insertion matrix (the two cylinder component occurrences were inserted in opposite directions).</p>

<br>
<table Class="Code">
<tr valign="middle">
	<td Class="Code">
	<pre>
Dim oCylFace1 As Face
Dim oCylFace2 As Face
    
For Each oFace In oCylinder1.SurfaceBodies(1).Faces
    If oFace.SurfaceType = kPlaneSurface Then
        Set oCylFace1 = oFace
    End If
Next
    
For Each oFace In oCylinder2.SurfaceBodies(1).Faces
    If oFace.SurfaceType = kPlaneSurface Then
       Set oCylFace2 = oFace
    End If
Next
</pre></td></tr>
</table>
<br>

<p Class="Normal">Now add a mate constraint for these two faces to the <a href="AssemblyConstraints.htm" data-topic-id="GUID-AssemblyConstraints">AssemblyConstraints</a> collection.</p>

<br>
<table Class="Code">
<tr valign="middle">
	<td Class="Code">
	<pre>
Set oConstr = oAxisDef.Constraints.AddMateConstraint _
   (oCylFace1, oCylFace2, 0, kNoInference, kNoInference)
</pre></td></tr>
</table>
<br>

<p Class="Normal">This results in the following figure with the intended relationship between the two cylinders.</p>

<br>
<div align="center"> <img src="../images/ov.parts3.png" border=0></div>
<br>

<p Class="Normal">The preceding example demonstrates insertion of parts into the assembly environment, and subsequent manipulation of those parts.  The resulting assembly can be saved to file, and itself used as a component occurrence in a new assembly with other parts and subassemblies.</p>

<h3>Summary</h3>

<p Class="Normal">To insert a part into an assembly, a ComponentOccurrence object is added to the ComponentOccurrences collection of the assembly document's AssemblyComponentDefinition object.  The position of the occurrence can be manipulated during insertion.  Final positioning is typically achieved through assembly constraints, which define how parts and subassemblies relate to each other. Multiple instances of the same ComponentOccurrence should reference the same ComponentDefinition.</p>

<h3>Also consider -</h3>

<p Class="Normal">Autodesk Inventor supports the concept of patterns, which is a uniform (circular or rectangular) or nonuniform (feature-based) repetition of parts. The API supports such patterns too, though the <a href="RectangularOccurrencePattern.htm" data-topic-id="GUID-RectangularOccurrencePattern">RectangularOccurrencePattern</a>, <a href="Inventor~CircularOccurrencePattern.html" data-topic-id="GUID-CircularOccurrencePattern">CircularOccurrencePattern</a> and <a href="Inventor~FeatureBasedOccurrencePattern.html" data-topic-id="GUID-FeatureBasedOccurrencePattern">FeatureBasedOccurrencePattern</a> objects. These contain collections of <a href="Inventor~OccurrencePatternElement.html" data-topic-id="GUID-OccurrencePatternElement">OccurrencePatternElement</a> objects that provide access to the list of ComponentOccurrences comprising that pattern.</p>

<p Class="Normal">Parts in the assembly environment are actually considered proxies. This only really matters when working with a part in the assembly context rather than the part definition context. For more information, refer to the <a href="Proxies_Overview.htm" data-topic-id="GUID-6A540540-CA8A-40AD-8EBF-C4BB1F3E7288">Proxies</a> overview.</p>

<br />
<br />
<div id="CopyrightNotice" style="display:none;">
  <hr />
  <table width="100%" style="font-size:15">
	<tr>
	  <td align="left">
		&copy; Copyright 2025 Autodesk, Inc.
	  </td>
	  <td align="right">
		<a href="mailto:mfg.api.help.comments@autodesk.com?subject=Inventor%202026%20API%20Help%20(AssemblingParts_Overview)">Comment on this page.</a>
	  </td>
	</tr>
  </table>
</div>

</body>
</html>
