<html>
  <head>
    <META http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="topic-type" content="reference-adsk">
    <meta name="helpsystempath" content="/view/INVNTOR/2026/ENU/">
    <link rel="canonical" href="/cloudhelp/2026/ENU/Inventor-API/files/BalloonValueSet_ReferencedRow_Sample.htm#!">
    <meta name="product" content="INVNTOR">
    <meta name="release" content="2026">
    <meta name="book" content="Developer">
    <meta name="component" content="Inventor-API">
    <meta name="created" content="">
    <meta name="user-comments" content="enable">
    <meta name="contextid" content="BalloonValueSet_ReferencedRow_Sample">
    <meta name="description" content="Find component referenced by balloon Sample">
    <meta name="topicid" content="BalloonValueSet_ReferencedRow_Sample">
    <meta name="experiencelevel" content="expert">
    <meta name="audience" content="programmer">
    <meta name="language" content="ENU">
    <title>Find component referenced by balloon</title>
    <link rel="stylesheet" href="../Style/jquery-ui.css"><script src="../Scripts/jquery-1.11.1.js"></script><script src="../Scripts/jquery-ui.js"></script><link rel="stylesheet" type="text/css" href="../Style/APIHelp-chm.css">
    <link rel="stylesheet" type="text/css" href="/view/clientframework/client.css"><script type="text/javascript" src="/view/clientframework/client.js"></script><script>
          // This turns on the display of the copyright notice which is not visible by default.
          // Because the head is removed when used in the web help, this function will only exists
          // when the chm help is being created.
          window.onload = function() {
          copyrightElement = document.getElementById('CopyrightNotice');
          copyrightElement.style.display = 'block';
          };
        </script><script>
          $(function() {
          $( "#tabs" ).tabs();
          });
        </script></head>
  <body><script>
          function copyCode(language) {
          // Get the pre element for the specified language.
          var preElement = document.getElementById(language);

          // Get the text from the element and copy it to the clipboard.
          var preText = preElement.innerText;

          var isIE = /*@cc_on!@*/false || !!document.documentMode;

          if (isIE)
          {
            window.clipboardData.setData('Text', preText);
          }
          else
          {
            navigator.clipboard.writeText(preText);
          }

          //alert("Code copied to clipboard");
          }
        </script><link rel="stylesheet" type="text/css" href="../Style/APIHelp.css">
    <h1 class="api">Find component referenced by balloon</h1>
    <h2 class="api">
          Description
        </h2>This sample demonstrates how to find the component that a balloon references.<h2 class="api">
          Code Samples
        </h2>
    <div id="tabs">
      <ul>
        <li><a href="#VBA">VBA</a></li>
        <li><a href="#iLogic">iLogic</a></li>
      </ul>
      <div id="VBA" class="api-code">Select a balloon in a drawing and run the following sample.<table width="100%" style="font-size:15">
          <tr>
            <td align="right"><button onclick="copyCode('VBA_code')" class="copy-code">Copy Code</button></td>
          </tr>
        </table>
        <pre class="api-code" id="VBA_code">Public Sub GetComponentReferencedByBalloon()
    <span style="color:blue">' Set a reference to the active drawing document</span>
    Dim oDoc As DrawingDocument
    Set oDoc = ThisApplication.ActiveDocument
    
    <span style="color:blue">' Get the selected balloon</span>
    Dim oBalloon As Balloon
    Set oBalloon = oDoc.SelectSet(1)
    
    Dim oBalloonValueSet As BalloonValueSet
    For Each oBalloonValueSet In oBalloon.BalloonValueSets
        Dim strDisplay As String
        strDisplay = "Balloon Item Number: "
        
        <span style="color:blue">' Add the balloon item number (the overridden value if there is one)</span>
        If oBalloonValueSet.OverrideValue = "" Then
            strDisplay = strDisplay & oBalloonValueSet.Value
        Else
            strDisplay = strDisplay & oBalloonValueSet.OverrideValue
        End If
        
        Dim oDrawingBOMRow As DrawingBOMRow
        Set oDrawingBOMRow = oBalloonValueSet.ReferencedRow
        
        If oDrawingBOMRow.Custom Then
            <span style="color:blue">' The referenced item is a custom parts list row.</span>
            strDisplay = strDisplay & vbNewLine & "Referenced Component(s):"
            strDisplay = strDisplay & vbNewLine & "     Custom PartsList Row"
        Else
            Dim oBOMRow As BOMRow
            Set oBOMRow = oDrawingBOMRow.BOMRow
            
            <span style="color:blue">' Add the Item Number from the model BOM.</span>
            strDisplay = strDisplay & vbNewLine & "BOM Item Number: " & oBOMRow.ItemNumber
            
            strDisplay = strDisplay & vbNewLine & "Referenced Component(s):"
            
            Dim oCompDefs As ComponentDefinitionsEnumerator
            Set oCompDefs = oBOMRow.ComponentDefinitions
               
            If oDrawingBOMRow.Virtual Then
                <span style="color:blue">' The referenced item is a virtual component.</span>
                strDisplay = strDisplay & vbNewLine & "     Virtual: " & oCompDefs.Item(1).DisplayName
            Else
              
                <span style="color:blue">' Add the document name of the referenced component.</span>
                <span style="color:blue">' There could be multiple if the balloon references</span>
                <span style="color:blue">' a merged BOM row in the model.</span>
                Dim oCompDef As ComponentDefinition
                For Each oCompDef In oCompDefs
                    strDisplay = strDisplay & vbNewLine & "     " & oCompDef.Document.FullDocumentName
                Next
                
            End If
        End If
        MsgBox strDisplay
    Next
End Sub</pre>
      </div>
      <div id="iLogic" class="api-code">Select a balloon in a drawing and run the following sample.<table width="100%" style="font-size:15">
          <tr>
            <td align="right"><button onclick="copyCode('iLogic_code')" class="copy-code">Copy Code</button></td>
          </tr>
        </table>
        <pre class="api-code" id="iLogic_code">    <span style="color:blue">' Set a reference to the active drawing document</span>
    Dim oDoc As DrawingDocument
    oDoc = ThisApplication.ActiveDocument
    
    <span style="color:blue">' Get the selected balloon</span>
    Dim oBalloon As Balloon
    oBalloon = oDoc.SelectSet(1)
    
    Dim oBalloonValueSet As BalloonValueSet
    For Each oBalloonValueSet In oBalloon.BalloonValueSets
        Dim strDisplay As String
        strDisplay = "Balloon Item Number: "
        
        <span style="color:blue">' Add the balloon item number (the overridden value if there is one)</span>
        If oBalloonValueSet.OverrideValue = "" Then
            strDisplay = strDisplay & oBalloonValueSet.Value
        Else
            strDisplay = strDisplay & oBalloonValueSet.OverrideValue
        End If
        
        Dim oDrawingBOMRow As DrawingBOMRow
        oDrawingBOMRow = oBalloonValueSet.ReferencedRow
        
        If oDrawingBOMRow.Custom Then
            <span style="color:blue">' The referenced item is a custom parts list row.</span>
            strDisplay = strDisplay & vbNewLine & "Referenced Component(s):"
            strDisplay = strDisplay & vbNewLine & "     Custom PartsList Row"
        Else
            Dim oBOMRow As BOMRow
            oBOMRow = oDrawingBOMRow.BOMRow
            
            <span style="color:blue">' Add the Item Number from the model BOM.</span>
            strDisplay = strDisplay & vbNewLine & "BOM Item Number: " & oBOMRow.ItemNumber
            
            strDisplay = strDisplay & vbNewLine & "Referenced Component(s):"
            
            Dim oCompDefs As ComponentDefinitionsEnumerator
            oCompDefs = oBOMRow.ComponentDefinitions
               
            If oDrawingBOMRow.Virtual Then
                <span style="color:blue">' The referenced item is a virtual component.</span>
                strDisplay = strDisplay & vbNewLine & "     Virtual: " & oCompDefs.Item(1).DisplayName
            Else
              
                <span style="color:blue">' Add the document name of the referenced component.</span>
                <span style="color:blue">' There could be multiple if the balloon references</span>
                <span style="color:blue">' a merged BOM row in the model.</span>
                Dim oCompDef As ComponentDefinition
                For Each oCompDef In oCompDefs
                    strDisplay = strDisplay & vbNewLine & "     " & oCompDef.Document.FullDocumentName
                Next
                
            End If
        End If
        MsgBox(strDisplay)
    Next</pre>
      </div>
    </div><br><br><div id="CopyrightNotice" style="display:none;">
      <hr>
      <table width="100%" style="font-size:15">
        <tr>
          <td align="left">
                Â© Copyright 2025 Autodesk, Inc.
              </td>
          <td align="right"><a href="mailto:mfg.api.help.comments@autodesk.com?subject=Inventor%202026%20API%20Help%20(BalloonValueSet_ReferencedRow%20Sample%20Help%20Topic)">Comment on this page.</a></td>
        </tr>
      </table>
    </div>
  </body>
</html>