<html>
  <head>
    <META http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="topic-type" content="reference-adsk">
    <meta name="helpsystempath" content="/view/INVNTOR/2026/ENU/">
    <link rel="canonical" href="/cloudhelp/2026/ENU/Inventor-API/files/BoundaryPatchFeatures_Add_Sample.htm#!">
    <meta name="product" content="INVNTOR">
    <meta name="release" content="2026">
    <meta name="book" content="Developer">
    <meta name="component" content="Inventor-API">
    <meta name="created" content="">
    <meta name="user-comments" content="enable">
    <meta name="contextid" content="BoundaryPatchFeatures_Add_Sample">
    <meta name="description" content="Delete Face, Boundary Patch and Stitch features Sample">
    <meta name="topicid" content="BoundaryPatchFeatures_Add_Sample">
    <meta name="experiencelevel" content="expert">
    <meta name="audience" content="programmer">
    <meta name="language" content="ENU">
    <title>Delete Face, Boundary Patch and Stitch features</title>
    <link rel="stylesheet" href="../Style/jquery-ui.css"><script src="../Scripts/jquery-1.11.1.js"></script><script src="../Scripts/jquery-ui.js"></script><link rel="stylesheet" type="text/css" href="../Style/APIHelp-chm.css">
    <link rel="stylesheet" type="text/css" href="/view/clientframework/client.css"><script type="text/javascript" src="/view/clientframework/client.js"></script><script>
          // This turns on the display of the copyright notice which is not visible by default.
          // Because the head is removed when used in the web help, this function will only exists
          // when the chm help is being created.
          window.onload = function() {
          copyrightElement = document.getElementById('CopyrightNotice');
          copyrightElement.style.display = 'block';
          };
        </script><script>
          $(function() {
          $( "#tabs" ).tabs();
          });
        </script></head>
  <body><script>
          function copyCode(language) {
          // Get the pre element for the specified language.
          var preElement = document.getElementById(language);

          // Get the text from the element and copy it to the clipboard.
          var preText = preElement.innerText;

          var isIE = /*@cc_on!@*/false || !!document.documentMode;

          if (isIE)
          {
            window.clipboardData.setData('Text', preText);
          }
          else
          {
            navigator.clipboard.writeText(preText);
          }

          //alert("Code copied to clipboard");
          }
        </script><link rel="stylesheet" type="text/css" href="../Style/APIHelp.css">
    <h1 class="api">Delete Face, Boundary Patch and Stitch features</h1>
    <h2 class="api">
          Description
        </h2>Demonstrates creating Face, Boundary Patch and Stitch features.<h2 class="api">
          Code Samples
        </h2>
    <div id="tabs">
      <ul>
        <li><a href="#VBA">VBA</a></li>
        <li><a href="#iLogic">iLogic</a></li>
      </ul>
      <div id="VBA" class="api-code">
        <table width="100%" style="font-size:15">
          <tr>
            <td align="right"><button onclick="copyCode('VBA_code')" class="copy-code">Copy Code</button></td>
          </tr>
        </table>
        <pre class="api-code" id="VBA_code">Public Sub BoundaryPatchFeature()
    <span style="color:blue">' Create a new part document, using the default part template.</span>
    Dim oPartDoc As PartDocument
    Set oPartDoc = ThisApplication.Documents.Add(kPartDocumentObject, _
                ThisApplication.FileManager.GetTemplateFile(kPartDocumentObject))

    <span style="color:blue">' Set a reference to the component definition.</span>
    Dim oCompDef As PartComponentDefinition
    Set oCompDef = oPartDoc.ComponentDefinition

    <span style="color:blue">' Create a new sketch on the X-Y work plane.</span>
    Dim oSketch As PlanarSketch
    Set oSketch = oCompDef.Sketches.Add(oCompDef.WorkPlanes(3))

    <span style="color:blue">' Set a reference to the transient geometry object.</span>
    Dim oTransGeom As TransientGeometry
    Set oTransGeom = ThisApplication.TransientGeometry

    <span style="color:blue">' Draw a 4cm x 3cm rectangle with the corner at (0,0)</span>
    Dim oRectangleLines As SketchEntitiesEnumerator
    Set oRectangleLines = oSketch.SketchLines.AddAsTwoPointRectangle( _
                                oTransGeom.CreatePoint2d(0, 0), _
                                oTransGeom.CreatePoint2d(4, 3))

    <span style="color:blue">' Create a profile.</span>
    Dim oProfile As Profile
    Set oProfile = oSketch.Profiles.AddForSolid

    <span style="color:blue">' Create a base extrusion 1cm thick.</span>
    Dim oExtrudeDef As ExtrudeDefinition
    Set oExtrudeDef = oCompDef.Features.ExtrudeFeatures.CreateExtrudeDefinition(oProfile, kJoinOperation)
    Call oExtrudeDef.SetDistanceExtent(1, kNegativeExtentDirection)
    Dim oExtrude As ExtrudeFeature
    Set oExtrude = oCompDef.Features.ExtrudeFeatures.Add(oExtrudeDef)

    <span style="color:blue">' Get the top face of the extrusion</span>
    Dim oFrontFace As Face
    Set oFrontFace = oExtrude.StartFaces.Item(1)

    Dim oEdgeColl As EdgeCollection
    Set oEdgeColl = ThisApplication.TransientObjects.CreateEdgeCollection

    <span style="color:blue">' Collect up the edges to create boundary patch.</span>
    Dim oEdge As Edge
    For Each oEdge In oFrontFace.Edges
        oEdgeColl.Add oEdge
    Next

    <span style="color:blue">' Create a Delete Face feature to delete the top face.</span>
    Dim oFaceColl As FaceCollection
    Set oFaceColl = ThisApplication.TransientObjects.CreateFaceCollection
    Call oFaceColl.Add(oFrontFace)

    Dim oDeleteFace As DeleteFaceFeature
    Set oDeleteFace = oCompDef.Features.DeleteFaceFeatures.Add(oFaceColl)

    Dim oBoundaryPatchDef As BoundaryPatchDefinition
    Set oBoundaryPatchDef = oCompDef.Features.BoundaryPatchFeatures.CreateBoundaryPatchDefinition

    <span style="color:blue">' Create a boundary patch definition based on the edges of the deleted face.</span>
    Call oBoundaryPatchDef.BoundaryPatchLoops.Add(oEdgeColl)

    <span style="color:blue">' Set the conditions on each edge to be tangent.</span>
    For Each oEdge In oEdgeColl
        Call oBoundaryPatchDef.BoundaryPatchLoops.Item(1).SetBoundaryCondition(oEdge, kTangentBoundaryPatchCondition)
    Next

    <span style="color:blue">' Create the boundary patch feature based on the definition.</span>
    Dim oBoundaryPatch As BoundaryPatchFeature
    Set oBoundaryPatch = oCompDef.Features.BoundaryPatchFeatures.Add(oBoundaryPatchDef)
    
    <span style="color:blue">' Stitch the boundary patch surface to the original body.</span>
    Dim oSurfaceToStitch As ObjectCollection
    Set oSurfaceToStitch = ThisApplication.TransientObjects.CreateObjectCollection

    Call oSurfaceToStitch.Add(oBoundaryPatch.SurfaceBodies.Item(1))
    Call oSurfaceToStitch.Add(oCompDef.SurfaceBodies.Item(1))

    Dim oStitch As KnitFeature
    Set oStitch = oCompDef.Features.KnitFeatures.Add(oSurfaceToStitch)
End Sub</pre>
      </div>
      <div id="iLogic" class="api-code">
        <table width="100%" style="font-size:15">
          <tr>
            <td align="right"><button onclick="copyCode('iLogic_code')" class="copy-code">Copy Code</button></td>
          </tr>
        </table>
        <pre class="api-code" id="iLogic_code">    <span style="color:blue">' Create a new part document, using the default part template.</span>
    Dim oPartDoc As PartDocument
    oPartDoc = ThisApplication.Documents.Add(kPartDocumentObject, _
                ThisApplication.FileManager.GetTemplateFile(kPartDocumentObject))

    <span style="color:blue">' Set a reference to the component definition.</span>
    Dim oCompDef As PartComponentDefinition
    oCompDef = oPartDoc.ComponentDefinition

    <span style="color:blue">' Create a new sketch on the X-Y work plane.</span>
    Dim oSketch As PlanarSketch
    oSketch = oCompDef.Sketches.Add(oCompDef.WorkPlanes(3))

    <span style="color:blue">' Set a reference to the transient geometry object.</span>
    Dim oTransGeom As TransientGeometry
    oTransGeom = ThisApplication.TransientGeometry

    <span style="color:blue">' Draw a 4cm x 3cm rectangle with the corner at (0,0)</span>
    Dim oRectangleLines As SketchEntitiesEnumerator
    oRectangleLines = oSketch.SketchLines.AddAsTwoPointRectangle( _
                                oTransGeom.CreatePoint2d(0, 0), _
                                oTransGeom.CreatePoint2d(4, 3))

    <span style="color:blue">' Create a profile.</span>
    Dim oProfile As Profile
    oProfile = oSketch.Profiles.AddForSolid

    <span style="color:blue">' Create a base extrusion 1cm thick.</span>
    Dim oExtrudeDef As ExtrudeDefinition
    oExtrudeDef = oCompDef.Features.ExtrudeFeatures.CreateExtrudeDefinition(oProfile, kJoinOperation)
    Call oExtrudeDef.SetDistanceExtent(1, kNegativeExtentDirection)
    Dim oExtrude As ExtrudeFeature
    oExtrude = oCompDef.Features.ExtrudeFeatures.Add(oExtrudeDef)

    <span style="color:blue">' Get the top face of the extrusion</span>
    Dim oFrontFace As Face
    oFrontFace = oExtrude.StartFaces.Item(1)

    Dim oEdgeColl As EdgeCollection
    oEdgeColl = ThisApplication.TransientObjects.CreateEdgeCollection

    <span style="color:blue">' Collect up the edges to create boundary patch.</span>
    Dim oEdge As Edge
    For Each oEdge In oFrontFace.Edges
        oEdgeColl.Add(oEdge)
    Next

    <span style="color:blue">' Create a Delete Face feature to delete the top face.</span>
    Dim oFaceColl As FaceCollection
    oFaceColl = ThisApplication.TransientObjects.CreateFaceCollection
    Call oFaceColl.Add(oFrontFace)

    Dim oDeleteFace As DeleteFaceFeature
    oDeleteFace = oCompDef.Features.DeleteFaceFeatures.Add(oFaceColl)

    Dim oBoundaryPatchDef As BoundaryPatchDefinition
    oBoundaryPatchDef = oCompDef.Features.BoundaryPatchFeatures.CreateBoundaryPatchDefinition

    <span style="color:blue">' Create a boundary patch definition based on the edges of the deleted face.</span>
    Call oBoundaryPatchDef.BoundaryPatchLoops.Add(oEdgeColl)

    <span style="color:blue">' Set the conditions on each edge to be tangent.</span>
    For Each oEdge In oEdgeColl
        Call oBoundaryPatchDef.BoundaryPatchLoops.Item(1).SetBoundaryCondition(oEdge, kTangentBoundaryPatchCondition)
    Next

    <span style="color:blue">' Create the boundary patch feature based on the definition.</span>
    Dim oBoundaryPatch As BoundaryPatchFeature
    oBoundaryPatch = oCompDef.Features.BoundaryPatchFeatures.Add(oBoundaryPatchDef)
    
    <span style="color:blue">' Stitch the boundary patch surface to the original body.</span>
    Dim oSurfaceToStitch As ObjectCollection
    oSurfaceToStitch = ThisApplication.TransientObjects.CreateObjectCollection

    Call oSurfaceToStitch.Add(oBoundaryPatch.SurfaceBodies.Item(1))
    Call oSurfaceToStitch.Add(oCompDef.SurfaceBodies.Item(1))

    Dim oStitch As KnitFeature
    oStitch = oCompDef.Features.KnitFeatures.Add(oSurfaceToStitch)</pre>
      </div>
    </div><br><br><div id="CopyrightNotice" style="display:none;">
      <hr>
      <table width="100%" style="font-size:15">
        <tr>
          <td align="left">
                Â© Copyright 2025 Autodesk, Inc.
              </td>
          <td align="right"><a href="mailto:mfg.api.help.comments@autodesk.com?subject=Inventor%202026%20API%20Help%20(BoundaryPatchFeatures_Add%20Sample%20Help%20Topic)">Comment on this page.</a></td>
        </tr>
      </table>
    </div>
  </body>
</html>