<html>
  <head>
    <META http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="topic-type" content="reference-adsk">
    <meta name="helpsystempath" content="/view/INVNTOR/2026/ENU/">
    <link rel="canonical" href="/cloudhelp/2026/ENU/Inventor-API/files/BrowserPanes_GetNativeBrowserNodeDefinition_Sample.htm#!">
    <meta name="product" content="INVNTOR">
    <meta name="release" content="2026">
    <meta name="book" content="Developer">
    <meta name="component" content="Inventor-API">
    <meta name="created" content="">
    <meta name="user-comments" content="enable">
    <meta name="contextid" content="BrowserPanes_GetNativeBrowserNodeDefinition_Sample">
    <meta name="description" content="Navigation between browser and data Sample">
    <meta name="topicid" content="BrowserPanes_GetNativeBrowserNodeDefinition_Sample">
    <meta name="experiencelevel" content="expert">
    <meta name="audience" content="programmer">
    <meta name="language" content="ENU">
    <title>Navigation between browser and data</title>
    <link rel="stylesheet" href="../Style/jquery-ui.css"><script src="../Scripts/jquery-1.11.1.js"></script><script src="../Scripts/jquery-ui.js"></script><link rel="stylesheet" type="text/css" href="../Style/APIHelp-chm.css">
    <link rel="stylesheet" type="text/css" href="/view/clientframework/client.css"><script type="text/javascript" src="/view/clientframework/client.js"></script><script>
          // This turns on the display of the copyright notice which is not visible by default.
          // Because the head is removed when used in the web help, this function will only exists
          // when the chm help is being created.
          window.onload = function() {
          copyrightElement = document.getElementById('CopyrightNotice');
          copyrightElement.style.display = 'block';
          };
        </script><script>
          $(function() {
          $( "#tabs" ).tabs();
          });
        </script></head>
  <body><script>
          function copyCode(language) {
          // Get the pre element for the specified language.
          var preElement = document.getElementById(language);

          // Get the text from the element and copy it to the clipboard.
          var preText = preElement.innerText;

          var isIE = /*@cc_on!@*/false || !!document.documentMode;

          if (isIE)
          {
            window.clipboardData.setData('Text', preText);
          }
          else
          {
            navigator.clipboard.writeText(preText);
          }

          //alert("Code copied to clipboard");
          }
        </script><link rel="stylesheet" type="text/css" href="../Style/APIHelp.css">
    <h1 class="api">Navigation between browser and data</h1>
    <h2 class="api">
          Description
        </h2>This sample demonstrates the navigation between a browser node and it's corresponding data model object and vice versa. This sample creates a work plane, finds its browser node and gets the work plane object back from the browser node.<h2 class="api">
          Code Samples
        </h2>
    <div id="tabs">
      <ul>
        <li><a href="#VBA">VBA</a></li>
        <li><a href="#iLogic">iLogic</a></li>
      </ul>
      <div id="VBA" class="api-code">
        <table width="100%" style="font-size:15">
          <tr>
            <td align="right"><button onclick="copyCode('VBA_code')" class="copy-code">Copy Code</button></td>
          </tr>
        </table>
        <pre class="api-code" id="VBA_code">Sub DataModelToBrowser()
    <span style="color:blue">' Create a new part document, using the default part template.</span>
    Dim oPartDoc As PartDocument
    Set oPartDoc = ThisApplication.Documents.Add(kPartDocumentObject)

    <span style="color:blue">' Set a reference to the component definition.</span>
    Dim oCompDef As PartComponentDefinition
    Set oCompDef = oPartDoc.ComponentDefinition
    
    <span style="color:blue">' Create a new workplane parallel to the XY plane.</span>
    Dim oWorkPlane As WorkPlane
    Set oWorkPlane = oCompDef.WorkPlanes.AddByPlaneAndOffset(oCompDef.WorkPlanes.Item(3), 1)
    
    <span style="color:blue">' Get the browser node definition associated with the work plane.</span>
    Dim oNativeBrowserNodeDef As NativeBrowserNodeDefinition
    Set oNativeBrowserNodeDef = oPartDoc.BrowserPanes.GetNativeBrowserNodeDefinition(oWorkPlane)
    
    <span style="color:blue">' Get the top browser node of the model pane.</span>
    Dim oTopBrowserNode As BrowserNode
    Set oTopBrowserNode = oPartDoc.BrowserPanes.ActivePane.TopNode
    
    <span style="color:blue">' Get the work plane browser node.</span>
    <span style="color:blue">' This assumes that only one node references the browser node definition.</span>
    <span style="color:blue">' An example of multiple nodes referencing a single definition is a shared</span>
    <span style="color:blue">' sketch. The browser may have multiple nodes that represent the same shared</span>
    <span style="color:blue">' sketch, but all of them reference the same definition.</span>
    Dim oWorkPlaneNode As BrowserNode
    Set oWorkPlaneNode = oTopBrowserNode.AllReferencedNodes(oNativeBrowserNodeDef).Item(1)
    
    <span style="color:blue">' Get the browser node definition from the browser node.</span>
    Set oNativeBrowserNodeDef = Nothing
    Set oNativeBrowserNodeDef = oWorkPlaneNode.BrowserNodeDefinition
    
    <span style="color:blue">' Get the work plane from the browser node definition.</span>
    Set oWorkPlane = Nothing
    Set oWorkPlane = oNativeBrowserNodeDef.NativeObject
    
    <span style="color:blue">' Select the work plane to make sure we have the right object.</span>
    oPartDoc.SelectSet.Select oWorkPlane
End Sub</pre>
      </div>
      <div id="iLogic" class="api-code">
        <table width="100%" style="font-size:15">
          <tr>
            <td align="right"><button onclick="copyCode('iLogic_code')" class="copy-code">Copy Code</button></td>
          </tr>
        </table>
        <pre class="api-code" id="iLogic_code">    <span style="color:blue">' Create a new part document, using the default part template.</span>
    Dim oPartDoc As PartDocument
    oPartDoc = ThisApplication.Documents.Add(kPartDocumentObject)

    <span style="color:blue">' Set a reference to the component definition.</span>
    Dim oCompDef As PartComponentDefinition
    oCompDef = oPartDoc.ComponentDefinition
    
    <span style="color:blue">' Create a new workplane parallel to the XY plane.</span>
    Dim oWorkPlane As WorkPlane
    oWorkPlane = oCompDef.WorkPlanes.AddByPlaneAndOffset(oCompDef.WorkPlanes.Item(3), 1)
    
    <span style="color:blue">' Get the browser node definition associated with the work plane.</span>
    Dim oNativeBrowserNodeDef As NativeBrowserNodeDefinition
    oNativeBrowserNodeDef = oPartDoc.BrowserPanes.GetNativeBrowserNodeDefinition(oWorkPlane)
    
    <span style="color:blue">' Get the top browser node of the model pane.</span>
    Dim oTopBrowserNode As BrowserNode
    oTopBrowserNode = oPartDoc.BrowserPanes.ActivePane.TopNode
    
    <span style="color:blue">' Get the work plane browser node.</span>
    <span style="color:blue">' This assumes that only one node references the browser node definition.</span>
    <span style="color:blue">' An example of multiple nodes referencing a single definition is a shared</span>
    <span style="color:blue">' sketch. The browser may have multiple nodes that represent the same shared</span>
    <span style="color:blue">' sketch, but all of them reference the same definition.</span>
    Dim oWorkPlaneNode As BrowserNode
    oWorkPlaneNode = oTopBrowserNode.AllReferencedNodes(oNativeBrowserNodeDef).Item(1)
    
    <span style="color:blue">' Get the browser node definition from the browser node.</span>
    oNativeBrowserNodeDef = Nothing
    oNativeBrowserNodeDef = oWorkPlaneNode.BrowserNodeDefinition
    
    <span style="color:blue">' Get the work plane from the browser node definition.</span>
    oWorkPlane = Nothing
    oWorkPlane = oNativeBrowserNodeDef.NativeObject
    
    <span style="color:blue">' Select the work plane to make sure we have the right object.</span>
    oPartDoc.SelectSet.Select(oWorkPlane)</pre>
      </div>
    </div><br><br><div id="CopyrightNotice" style="display:none;">
      <hr>
      <table width="100%" style="font-size:15">
        <tr>
          <td align="left">
                Â© Copyright 2025 Autodesk, Inc.
              </td>
          <td align="right"><a href="mailto:mfg.api.help.comments@autodesk.com?subject=Inventor%202026%20API%20Help%20(BrowserPanes_GetNativeBrowserNodeDefinition%20Sample%20Help%20Topic)">Comment on this page.</a></td>
        </tr>
      </table>
    </div>
  </body>
</html>