<html>
  <head>
    <META http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="topic-type" content="reference-adsk">
    <meta name="helpsystempath" content="/view/INVNTOR/2026/ENU/">
    <link rel="canonical" href="/cloudhelp/2026/ENU/Inventor-API/files/ClientGraphics_Sample.htm#!">
    <meta name="product" content="INVNTOR">
    <meta name="release" content="2026">
    <meta name="book" content="Developer">
    <meta name="component" content="Inventor-API">
    <meta name="created" content="">
    <meta name="user-comments" content="enable">
    <meta name="contextid" content="ClientGraphics_Sample">
    <meta name="description" content="Client Graphics - Draw Range Box Sample">
    <meta name="topicid" content="ClientGraphics_Sample">
    <meta name="experiencelevel" content="expert">
    <meta name="audience" content="programmer">
    <meta name="language" content="ENU">
    <title>Client Graphics - Draw Range Box</title>
    <link rel="stylesheet" href="../Style/jquery-ui.css"><script src="../Scripts/jquery-1.11.1.js"></script><script src="../Scripts/jquery-ui.js"></script><link rel="stylesheet" type="text/css" href="../Style/APIHelp-chm.css">
    <link rel="stylesheet" type="text/css" href="/view/clientframework/client.css"><script type="text/javascript" src="/view/clientframework/client.js"></script><script>
          // This turns on the display of the copyright notice which is not visible by default.
          // Because the head is removed when used in the web help, this function will only exists
          // when the chm help is being created.
          window.onload = function() {
          copyrightElement = document.getElementById('CopyrightNotice');
          copyrightElement.style.display = 'block';
          };
        </script><script>
          $(function() {
          $( "#tabs" ).tabs();
          });
        </script></head>
  <body><script>
          function copyCode(language) {
          // Get the pre element for the specified language.
          var preElement = document.getElementById(language);

          // Get the text from the element and copy it to the clipboard.
          var preText = preElement.innerText;

          var isIE = /*@cc_on!@*/false || !!document.documentMode;

          if (isIE)
          {
            window.clipboardData.setData('Text', preText);
          }
          else
          {
            navigator.clipboard.writeText(preText);
          }

          //alert("Code copied to clipboard");
          }
        </script><link rel="stylesheet" type="text/css" href="../Style/APIHelp.css">
    <h1 class="api">Client Graphics - Draw Range Box</h1>
    <h2 class="api">
          Description
        </h2>This sample demonstrates the use of client graphics to draw the range box of selected entities.<h2 class="api">
          Code Samples
        </h2>
    <div id="tabs">
      <ul>
        <li><a href="#VBA">VBA</a></li>
        <li><a href="#iLogic">iLogic</a></li>
      </ul>
      <div id="VBA" class="api-code">To run this sample open an assembly or part document and select the item(s) to draw a range box around. Then run the program. If you run it without any graphics selected, it will delete any existing range boxes.<table width="100%" style="font-size:15">
          <tr>
            <td align="right"><button onclick="copyCode('VBA_code')" class="copy-code">Copy Code</button></td>
          </tr>
        </table>
        <pre class="api-code" id="VBA_code">Public Sub DrawRangeBox()
    Dim oDoc As Document
    Set oDoc = ThisApplication.ActiveDocument

    <span style="color:blue">' Set a reference to component definition of the active document.</span>
    <span style="color:blue">' This assumes that a part or assembly document is active.</span>
    Dim oCompDef As ComponentDefinition
    Set oCompDef = ThisApplication.ActiveDocument.ComponentDefinition

    <span style="color:blue">' Make sure something is selected.</span>
    If oDoc.SelectSet.Count = 0 Then
        MsgBox "You must select the object(s) to display the range box."

        <span style="color:blue">' Delete any graphics, if they exist.</span>
        On Error Resume Next
        Dim oExistingGraphicsData As GraphicsDataSets
        Set oExistingGraphicsData = oDoc.GraphicsDataSetsCollection.Item("RangeBoxGraphics")
        If Err.Number = 0 Then
            On Error Goto 0
            Dim oExistingGraphics As ClientGraphics
            Set oExistingGraphics = oCompDef.ClientGraphicsCollection.Item("RangeBoxGraphics")
            oExistingGraphics.Delete
            oExistingGraphicsData.Delete
            ThisApplication.ActiveView.Update
        End If

        Exit Sub
    End If

    Redim aoRanges(1 To oDoc.SelectSet.Count) As Box
    Dim iRangeCount As Long
    Dim i As Long
    On Error Resume Next
    For i = 1 To oDoc.SelectSet.Count
       Dim oBox As Box
        Set oBox = oDoc.SelectSet.Item(i).RangeBox
        If Err Then
            Err.Clear
            <span style="color:blue">' Special case for B-Rep entities.</span>
            If oDoc.SelectSet.Item(i).Type = kFaceObject Or _
               oDoc.SelectSet.Item(i).Type = kFaceProxyObject Or _
               oDoc.SelectSet.Item(i).Type = kEdgeObject Or _
               oDoc.SelectSet.Item(i).Type = kEdgeProxyObject Then
                <span style="color:blue">' Get the range from evaluator of the BRep object.</span>
                Set oBox = oDoc.SelectSet.Item(i).Evaluator.RangeBox
                iRangeCount = iRangeCount + 1
                Set aoRanges(iRangeCount) = oBox
            End If
        Else
            iRangeCount = iRangeCount + 1
            Set aoRanges(iRangeCount) = oBox
        End If
    Next
    On Error Goto 0

    If iRangeCount = 0 Then
        MsgBox "You must pick object(s) that support a 3D RangeBox property."
        Exit Sub
    End If

    <span style="color:blue">' Check to see if range box graphics information already exists.</span>
    On Error Resume Next
    Dim oClientGraphics As ClientGraphics
    Dim oLineGraphics As LineGraphics
    Dim oBoxNode As GraphicsNode
    Dim oGraphicsData As GraphicsDataSets
    Set oGraphicsData = oDoc.GraphicsDataSetsCollection.Item("RangeBoxGraphics")
    If Err Then
        Err.Clear
        On Error Goto 0

        <span style="color:blue">' Set a reference to the transient geometry object for user later.</span>
        Dim oTransGeom As TransientGeometry
        Set oTransGeom = ThisApplication.TransientGeometry

        <span style="color:blue">' Create a graphics data set object. This object contains all of the</span>
        <span style="color:blue">' information used to define the graphics.</span>
        Dim oDataSets As GraphicsDataSets
        Set oDataSets = oDoc.GraphicsDataSetsCollection.Add("RangeBoxGraphics")

        <span style="color:blue">' Create a coordinate set.</span>
        Dim oCoordSet As GraphicsCoordinateSet
        Set oCoordSet = oDataSets.CreateCoordinateSet(1)

        <span style="color:blue">' Create the client graphics for this compdef.</span>
        Set oClientGraphics = oCompDef.ClientGraphicsCollection.Add("RangeBoxGraphics")

        <span style="color:blue">' Create a graphics node.</span>
        Set oBoxNode = oClientGraphics.AddNode(1)
        oBoxNode.Selectable = False

        <span style="color:blue">' Create line graphics.</span>
        Set oLineGraphics = oBoxNode.AddLineGraphics
        oLineGraphics.CoordinateSet = oCoordSet
    Else
        Set oCoordSet = oGraphicsData.ItemById(1)
        Set oBoxNode = oCompDef.ClientGraphicsCollection.Item("RangeBoxGraphics").ItemById(1)
    End If

    Dim dBoxLines() As Double
    Redim dBoxLines(1 To 12 * 6 * iRangeCount) As Double
    For i = 0 To iRangeCount - 1
        Dim MinPoint(1 To 3) As Double
        Dim MaxPoint(1 To 3) As Double
        Call aoRanges(i + 1).GetBoxData(MinPoint, MaxPoint)

        <span style="color:blue">' Line 1</span>
        dBoxLines(i * 72 + 1) = MinPoint(1)
        dBoxLines(i * 72 + 2) = MinPoint(2)
        dBoxLines(i * 72 + 3) = MinPoint(3)
        dBoxLines(i * 72 + 4) = MaxPoint(1)
        dBoxLines(i * 72 + 5) = MinPoint(2)
        dBoxLines(i * 72 + 6) = MinPoint(3)

        <span style="color:blue">' Line 2</span>
        dBoxLines(i * 72 + 7) = MinPoint(1)
        dBoxLines(i * 72 + 8) = MinPoint(2)
        dBoxLines(i * 72 + 9) = MinPoint(3)
        dBoxLines(i * 72 + 10) = MinPoint(1)
        dBoxLines(i * 72 + 11) = MaxPoint(2)
        dBoxLines(i * 72 + 12) = MinPoint(3)

        <span style="color:blue">' Line 3</span>
        dBoxLines(i * 72 + 13) = MinPoint(1)
        dBoxLines(i * 72 + 14) = MinPoint(2)
        dBoxLines(i * 72 + 15) = MinPoint(3)
        dBoxLines(i * 72 + 16) = MinPoint(1)
        dBoxLines(i * 72 + 17) = MinPoint(2)
        dBoxLines(i * 72 + 18) = MaxPoint(3)

        <span style="color:blue">' Line 4</span>
        dBoxLines(i * 72 + 19) = MaxPoint(1)
        dBoxLines(i * 72 + 20) = MaxPoint(2)
        dBoxLines(i * 72 + 21) = MaxPoint(3)
        dBoxLines(i * 72 + 22) = MinPoint(1)
        dBoxLines(i * 72 + 23) = MaxPoint(2)
        dBoxLines(i * 72 + 24) = MaxPoint(3)

        <span style="color:blue">' Line 5</span>
        dBoxLines(i * 72 + 25) = MaxPoint(1)
        dBoxLines(i * 72 + 26) = MaxPoint(2)
        dBoxLines(i * 72 + 27) = MaxPoint(3)
        dBoxLines(i * 72 + 28) = MaxPoint(1)
        dBoxLines(i * 72 + 29) = MinPoint(2)
        dBoxLines(i * 72 + 30) = MaxPoint(3)

        <span style="color:blue">' Line 6</span>
        dBoxLines(i * 72 + 31) = MaxPoint(1)
        dBoxLines(i * 72 + 32) = MaxPoint(2)
        dBoxLines(i * 72 + 33) = MaxPoint(3)
        dBoxLines(i * 72 + 34) = MaxPoint(1)
        dBoxLines(i * 72 + 35) = MaxPoint(2)
        dBoxLines(i * 72 + 36) = MinPoint(3)

        <span style="color:blue">' Line 7</span>
        dBoxLines(i * 72 + 37) = MinPoint(1)
        dBoxLines(i * 72 + 38) = MaxPoint(2)
        dBoxLines(i * 72 + 39) = MinPoint(3)
        dBoxLines(i * 72 + 40) = MaxPoint(1)
        dBoxLines(i * 72 + 41) = MaxPoint(2)
        dBoxLines(i * 72 + 42) = MinPoint(3)

        <span style="color:blue">' Line 8</span>
        dBoxLines(i * 72 + 43) = MinPoint(1)
        dBoxLines(i * 72 + 44) = MaxPoint(2)
        dBoxLines(i * 72 + 45) = MinPoint(3)
        dBoxLines(i * 72 + 46) = MinPoint(1)
        dBoxLines(i * 72 + 47) = MaxPoint(2)
        dBoxLines(i * 72 + 48) = MaxPoint(3)

        <span style="color:blue">' Line 9</span>
        dBoxLines(i * 72 + 49) = MaxPoint(1)
        dBoxLines(i * 72 + 50) = MinPoint(2)
        dBoxLines(i * 72 + 51) = MaxPoint(3)
        dBoxLines(i * 72 + 52) = MaxPoint(1)
        dBoxLines(i * 72 + 53) = MinPoint(2)
        dBoxLines(i * 72 + 54) = MinPoint(3)

        <span style="color:blue">' Line 10</span>
        dBoxLines(i * 72 + 55) = MaxPoint(1)
        dBoxLines(i * 72 + 56) = MinPoint(2)
        dBoxLines(i * 72 + 57) = MaxPoint(3)
        dBoxLines(i * 72 + 58) = MinPoint(1)
        dBoxLines(i * 72 + 59) = MinPoint(2)
        dBoxLines(i * 72 + 60) = MaxPoint(3)

        <span style="color:blue">' Line 11</span>
        dBoxLines(i * 72 + 61) = MinPoint(1)
        dBoxLines(i * 72 + 62) = MinPoint(2)
        dBoxLines(i * 72 + 63) = MaxPoint(3)
        dBoxLines(i * 72 + 64) = MinPoint(1)
        dBoxLines(i * 72 + 65) = MaxPoint(2)
        dBoxLines(i * 72 + 66) = MaxPoint(3)

        <span style="color:blue">' Line 12</span>
        dBoxLines(i * 72 + 67) = MaxPoint(1)
        dBoxLines(i * 72 + 68) = MinPoint(2)
        dBoxLines(i * 72 + 69) = MinPoint(3)
        dBoxLines(i * 72 + 70) = MaxPoint(1)
        dBoxLines(i * 72 + 71) = MaxPoint(2)
        dBoxLines(i * 72 + 72) = MinPoint(3)
    Next

    <span style="color:blue">' Assign the points into the coordinate set.</span>
    Call oCoordSet.PutCoordinates(dBoxLines)

    <span style="color:blue">' Update the display.</span>
    ThisApplication.ActiveView.Update
End Sub</pre>
      </div>
      <div id="iLogic" class="api-code">To run this sample open an assembly or part document and select the item(s) to draw a range box around. Then run the program. If you run it without any graphics selected, it will delete any existing range boxes.<table width="100%" style="font-size:15">
          <tr>
            <td align="right"><button onclick="copyCode('iLogic_code')" class="copy-code">Copy Code</button></td>
          </tr>
        </table>
        <pre class="api-code" id="iLogic_code">    Dim oDoc As Document
    oDoc = ThisApplication.ActiveDocument

    <span style="color:blue">' Set a reference to component definition of the active document.</span>
    <span style="color:blue">' This assumes that a part or assembly document is active.</span>
    Dim oCompDef As ComponentDefinition
    oCompDef = ThisApplication.ActiveDocument.ComponentDefinition

    <span style="color:blue">' Make sure something is selected.</span>
    If oDoc.SelectSet.Count = 0 Then
        MsgBox("You must select the object(s) to display the range box.")

        <span style="color:blue">' Delete any graphics, if they exist.</span>
        On Error Resume Next
        Dim oExistingGraphicsData As GraphicsDataSets
        oExistingGraphicsData = oDoc.GraphicsDataSetsCollection.Item("RangeBoxGraphics")
        If Err.Number = 0 Then
            On Error Goto 0
            Dim oExistingGraphics As ClientGraphics
            oExistingGraphics = oCompDef.ClientGraphicsCollection.Item("RangeBoxGraphics")
            oExistingGraphics.Delete
            oExistingGraphicsData.Delete
            ThisApplication.ActiveView.Update
        End If

        Exit Sub
    End If

    Dim aoRanges(0 To oDoc.SelectSet.Count-1) As Box
    Dim iRangeCount As Long
    Dim i As Long
    On Error Resume Next
    For i = 1 To oDoc.SelectSet.Count
       Dim oBox As Box
        oBox = oDoc.SelectSet.Item(i).RangeBox
        If Err.Number &gt; 0 Then
            Err.Clear
            <span style="color:blue">' Special case for B-Rep entities.</span>
            If oDoc.SelectSet.Item(i).Type = kFaceObject Or _
               oDoc.SelectSet.Item(i).Type = kFaceProxyObject Or _
               oDoc.SelectSet.Item(i).Type = kEdgeObject Or _
               oDoc.SelectSet.Item(i).Type = kEdgeProxyObject Then
                <span style="color:blue">' Get the range from evaluator of the BRep object.</span>
                oBox = oDoc.SelectSet.Item(i).Evaluator.RangeBox
                iRangeCount = iRangeCount + 1
                aoRanges(iRangeCount-1) = oBox
            End If
        Else
            iRangeCount = iRangeCount + 1
            aoRanges(iRangeCount-1) = oBox
        End If
    Next
    On Error Goto 0

    If iRangeCount = 0 Then
        MsgBox("You must pick object(s) that support a 3D RangeBox property.")
        Exit Sub
    End If

    <span style="color:blue">' Check to see if range box graphics information already exists.</span>
    On Error Resume Next
    Dim oClientGraphics As ClientGraphics
    Dim oLineGraphics As LineGraphics
    Dim oBoxNode As GraphicsNode
    Dim oGraphicsData As GraphicsDataSets
    oGraphicsData = oDoc.GraphicsDataSetsCollection.Item("RangeBoxGraphics")
    
    Dim oCoordSet As GraphicsCoordinateSet
    If Err.Number &gt; 0 Then
        Err.Clear
        On Error Goto 0

        <span style="color:blue">' Set a reference to the transient geometry object for user later.</span>
        Dim oTransGeom As TransientGeometry
        oTransGeom = ThisApplication.TransientGeometry

        <span style="color:blue">' Create a graphics data set object. This object contains all of the</span>
        <span style="color:blue">' information used to define the graphics.</span>
        Dim oDataSets As GraphicsDataSets
        oDataSets = oDoc.GraphicsDataSetsCollection.Add("RangeBoxGraphics")

        <span style="color:blue">' Create a coordinate set.</span>
        oCoordSet = oDataSets.CreateCoordinateSet(1)

        <span style="color:blue">' Create the client graphics for this compdef.</span>
        oClientGraphics = oCompDef.ClientGraphicsCollection.Add("RangeBoxGraphics")

        <span style="color:blue">' Create a graphics node.</span>
        oBoxNode = oClientGraphics.AddNode(1)
        oBoxNode.Selectable = False

        <span style="color:blue">' Create line graphics.</span>
        oLineGraphics = oBoxNode.AddLineGraphics
        oLineGraphics.CoordinateSet = oCoordSet
    Else
        oCoordSet = oGraphicsData.ItemById(1)
        oBoxNode = oCompDef.ClientGraphicsCollection.Item("RangeBoxGraphics").ItemById(1)
    End If
    
    Dim  dBoxLines(0 To 12 * 6 * iRangeCount-1) As Double
    For i = 0 To iRangeCount - 1
        Dim MinPoint(0 To 2) As Double
        Dim MaxPoint(0 To 2) As Double
        Call aoRanges(i).GetBoxData(MinPoint, MaxPoint)

        <span style="color:blue">' Line 1</span>
        dBoxLines(i * 72 + 0) = MinPoint(0)
        dBoxLines(i * 72 + 1) = MinPoint(1)
        dBoxLines(i * 72 + 2) = MinPoint(2)
        dBoxLines(i * 72 + 3) = MaxPoint(0)
        dBoxLines(i * 72 + 4) = MinPoint(1)
        dBoxLines(i * 72 + 5) = MinPoint(2)

        <span style="color:blue">' Line 2</span>
        dBoxLines(i * 72 + 6) = MinPoint(0)
        dBoxLines(i * 72 + 7) = MinPoint(1)
        dBoxLines(i * 72 + 8) = MinPoint(2)
        dBoxLines(i * 72 + 9) = MinPoint(0)
        dBoxLines(i * 72 + 10) = MaxPoint(1)
        dBoxLines(i * 72 + 11) = MinPoint(2)

        <span style="color:blue">' Line 3</span>
        dBoxLines(i * 72 + 12) = MinPoint(0)
        dBoxLines(i * 72 + 13) = MinPoint(1)
        dBoxLines(i * 72 + 14) = MinPoint(2)
        dBoxLines(i * 72 + 15) = MinPoint(0)
        dBoxLines(i * 72 + 16) = MinPoint(1)
        dBoxLines(i * 72 + 17) = MaxPoint(2)

        <span style="color:blue">' Line 4</span>
        dBoxLines(i * 72 + 18) = MaxPoint(0)
        dBoxLines(i * 72 + 19) = MaxPoint(1)
        dBoxLines(i * 72 + 20) = MaxPoint(2)
        dBoxLines(i * 72 + 21) = MinPoint(0)
        dBoxLines(i * 72 + 22) = MaxPoint(1)
        dBoxLines(i * 72 + 23) = MaxPoint(2)

        <span style="color:blue">' Line 5</span>
        dBoxLines(i * 72 + 24) = MaxPoint(0)
        dBoxLines(i * 72 + 25) = MaxPoint(1)
        dBoxLines(i * 72 + 26) = MaxPoint(2)
        dBoxLines(i * 72 + 27) = MaxPoint(0)
        dBoxLines(i * 72 + 28) = MinPoint(1)
        dBoxLines(i * 72 + 29) = MaxPoint(2)

        <span style="color:blue">' Line 6</span>
        dBoxLines(i * 72 + 30) = MaxPoint(0)
        dBoxLines(i * 72 + 31) = MaxPoint(1)
        dBoxLines(i * 72 + 32) = MaxPoint(2)
        dBoxLines(i * 72 + 33) = MaxPoint(0)
        dBoxLines(i * 72 + 34) = MaxPoint(1)
        dBoxLines(i * 72 + 35) = MinPoint(2)

        <span style="color:blue">' Line 7</span>
        dBoxLines(i * 72 + 36) = MinPoint(0)
        dBoxLines(i * 72 + 37) = MaxPoint(1)
        dBoxLines(i * 72 + 38) = MinPoint(2)
        dBoxLines(i * 72 + 39) = MaxPoint(0)
        dBoxLines(i * 72 + 40) = MaxPoint(1)
        dBoxLines(i * 72 + 41) = MinPoint(2)

        <span style="color:blue">' Line 8</span>
        dBoxLines(i * 72 + 42) = MinPoint(0)
        dBoxLines(i * 72 + 43) = MaxPoint(1)
        dBoxLines(i * 72 + 44) = MinPoint(2)
        dBoxLines(i * 72 + 45) = MinPoint(0)
        dBoxLines(i * 72 + 46) = MaxPoint(1)
        dBoxLines(i * 72 + 47) = MaxPoint(2)

        <span style="color:blue">' Line 9</span>
        dBoxLines(i * 72 + 48) = MaxPoint(0)
        dBoxLines(i * 72 + 49) = MinPoint(1)
        dBoxLines(i * 72 + 50) = MaxPoint(2)
        dBoxLines(i * 72 + 51) = MaxPoint(0)
        dBoxLines(i * 72 + 52) = MinPoint(1)
        dBoxLines(i * 72 + 53) = MinPoint(2)

        <span style="color:blue">' Line 10</span>
        dBoxLines(i * 72 + 54) = MaxPoint(0)
        dBoxLines(i * 72 + 55) = MinPoint(1)
        dBoxLines(i * 72 + 56) = MaxPoint(2)
        dBoxLines(i * 72 + 57) = MinPoint(0)
        dBoxLines(i * 72 + 58) = MinPoint(1)
        dBoxLines(i * 72 + 59) = MaxPoint(2)

        <span style="color:blue">' Line 11</span>
        dBoxLines(i * 72 + 60) = MinPoint(0)
        dBoxLines(i * 72 + 61) = MinPoint(1)
        dBoxLines(i * 72 + 62) = MaxPoint(2)
        dBoxLines(i * 72 + 63) = MinPoint(0)
        dBoxLines(i * 72 + 64) = MaxPoint(1)
        dBoxLines(i * 72 + 65) = MaxPoint(2)

        <span style="color:blue">' Line 12</span>
        dBoxLines(i * 72 + 66) = MaxPoint(0)
        dBoxLines(i * 72 + 67) = MinPoint(1)
        dBoxLines(i * 72 + 68) = MinPoint(2)
        dBoxLines(i * 72 + 69) = MaxPoint(0)
        dBoxLines(i * 72 + 70) = MaxPoint(1)
        dBoxLines(i * 72 + 71) = MinPoint(2)
    Next

    <span style="color:blue">' Assign the points into the coordinate set.</span>
    Call oCoordSet.PutCoordinates(dBoxLines)

    <span style="color:blue">' Update the display.</span>
    ThisApplication.ActiveView.Update</pre>
      </div>
    </div><br><br><div id="CopyrightNotice" style="display:none;">
      <hr>
      <table width="100%" style="font-size:15">
        <tr>
          <td align="left">
                Â© Copyright 2025 Autodesk, Inc.
              </td>
          <td align="right"><a href="mailto:mfg.api.help.comments@autodesk.com?subject=Inventor%202026%20API%20Help%20(ClientGraphics%20Sample%20Help%20Topic)">Comment on this page.</a></td>
        </tr>
      </table>
    </div>
  </body>
</html>