<html>
  <head>
    <META http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="topic-type" content="reference-adsk">
    <meta name="helpsystempath" content="/view/INVNTOR/2026/ENU/">
    <link rel="canonical" href="/cloudhelp/2026/ENU/Inventor-API/files/CreatePatternBoundarySettingSample_Sample.htm#!">
    <meta name="product" content="INVNTOR">
    <meta name="release" content="2026">
    <meta name="book" content="Developer">
    <meta name="component" content="Inventor-API">
    <meta name="created" content="">
    <meta name="user-comments" content="enable">
    <meta name="contextid" content="CreatePatternBoundarySettingSample_Sample">
    <meta name="description" content="Create Pattern Feature with PatternBoundarySetting Sample Sample">
    <meta name="topicid" content="CreatePatternBoundarySettingSample_Sample">
    <meta name="experiencelevel" content="expert">
    <meta name="audience" content="programmer">
    <meta name="language" content="ENU">
    <title>Create Pattern Feature with PatternBoundarySetting Sample</title>
    <link rel="stylesheet" href="../Style/jquery-ui.css"><script src="../Scripts/jquery-1.11.1.js"></script><script src="../Scripts/jquery-ui.js"></script><link rel="stylesheet" type="text/css" href="../Style/APIHelp-chm.css">
    <link rel="stylesheet" type="text/css" href="/view/clientframework/client.css"><script type="text/javascript" src="/view/clientframework/client.js"></script><script>
          // This turns on the display of the copyright notice which is not visible by default.
          // Because the head is removed when used in the web help, this function will only exists
          // when the chm help is being created.
          window.onload = function() {
          copyrightElement = document.getElementById('CopyrightNotice');
          copyrightElement.style.display = 'block';
          };
        </script><script>
          $(function() {
          $( "#tabs" ).tabs();
          });
        </script></head>
  <body><script>
          function copyCode(language) {
          // Get the pre element for the specified language.
          var preElement = document.getElementById(language);

          // Get the text from the element and copy it to the clipboard.
          var preText = preElement.innerText;

          var isIE = /*@cc_on!@*/false || !!document.documentMode;

          if (isIE)
          {
            window.clipboardData.setData('Text', preText);
          }
          else
          {
            navigator.clipboard.writeText(preText);
          }

          //alert("Code copied to clipboard");
          }
        </script><link rel="stylesheet" type="text/css" href="../Style/APIHelp.css">
    <h1 class="api">Create Pattern Feature with PatternBoundarySetting Sample</h1>
    <h2 class="api">
          Description
        </h2>This sample demonstrates how to create a rectangular pattern feature with boundary settings.<h2 class="api">
          Code Samples
        </h2>
    <div id="tabs">
      <ul>
        <li><a href="#VBA">VBA</a></li>
        <li><a href="#iLogic">iLogic</a></li>
      </ul>
      <div id="VBA" class="api-code">This sample demonstrates how to create a rectangular pattern feature with boundary settings.<table width="100%" style="font-size:15">
          <tr>
            <td align="right"><button onclick="copyCode('VBA_code')" class="copy-code">Copy Code</button></td>
          </tr>
        </table>
        <pre class="api-code" id="VBA_code">Public Sub CreatePatternBoundarySettingSample()
    <span style="color:blue">' Create a new part document, using the default part template.</span>
    Dim oPartDoc As PartDocument
    Set oPartDoc = ThisApplication.Documents.Add(kPartDocumentObject)
                    
    <span style="color:blue">' Set a reference to the component definition.</span>
    Dim oCompDef As PartComponentDefinition
    Set oCompDef = oPartDoc.ComponentDefinition
    
    <span style="color:blue">' Create a new sketch on the X-Y work plane.</span>
    Dim oSketch As PlanarSketch
    Set oSketch = oCompDef.Sketches.Add(oCompDef.WorkPlanes(3))
    
    <span style="color:blue">' Set a reference to the transient geometry object.</span>
    Dim oTransGeom As TransientGeometry
    Set oTransGeom = ThisApplication.TransientGeometry
    
    <span style="color:blue">' Draw a rectangle.</span>
    Dim oRectangleLines As SketchEntitiesEnumerator
    Set oRectangleLines = oSketch.SketchLines.AddAsTwoPointRectangle( _
                                oTransGeom.CreatePoint2d(-10, -10), _
                                oTransGeom.CreatePoint2d(10, 10))

    <span style="color:blue">' Create a profile.</span>
    Dim oProfile As Profile
    Set oProfile = oSketch.Profiles.AddForSolid
    
    <span style="color:blue">' Create a base extrusion 1cm thick.</span>
    Dim oExtrudeDef As ExtrudeDefinition
    Set oExtrudeDef = oCompDef.Features.ExtrudeFeatures.CreateExtrudeDefinition(oProfile, kJoinOperation)
    Call oExtrudeDef.SetDistanceExtent(1, kNegativeExtentDirection)
    Dim oExtrude As ExtrudeFeature
    Set oExtrude = oCompDef.Features.ExtrudeFeatures.Add(oExtrudeDef)
                        
    <span style="color:blue">' Get the top face of the extrusion to use for creating the new sketch.</span>
    Dim oFrontFace As Face
    Set oFrontFace = oExtrude.StartFaces.Item(1)
    
    <span style="color:blue">' Create a new sketch on this face.</span>
    Set oSketch = oCompDef.Sketches.AddWithOrientation(oFrontFace, _
                    oCompDef.WorkAxes.Item(1), True, True, oCompDef.WorkPoints(1))
                    
    <span style="color:blue">' Determine where in sketch space the point (0.5,0.5,0) is.</span>
    Dim oCorner As Point2d
    Set oCorner = oTransGeom.CreatePoint2d(-9, 9)
    
    Dim oTriangle As SketchEntitiesEnumerator
    Set oTriangle = oSketch.SketchLines.AddAsPolygon(3, oCorner, oTransGeom.CreatePoint2d(-9.5, 9.5), True)
                    
    <span style="color:blue">' Create a profile.</span>
    Set oProfile = oSketch.Profiles.AddForSolid
    
    <span style="color:blue">' Create a cut feature.</span>
    Set oExtrudeDef = oCompDef.Features.ExtrudeFeatures.CreateExtrudeDefinition(oProfile, kCutOperation)
    Call oExtrudeDef.SetDistanceExtent(1, kNegativeExtentDirection)
    Set oExtrude = oCompDef.Features.ExtrudeFeatures.Add(oExtrudeDef)
    
    Set oSketch = oCompDef.Sketches.AddWithOrientation(oFrontFace, _
                    oCompDef.WorkAxes.Item(1), True, True, oCompDef.WorkPoints(1))
    
    Call oSketch.SketchLines.AddAsTwoPointRectangle(oTransGeom.CreatePoint2d(-6.5, 8), oTransGeom.CreatePoint2d(8.5, -8))
    
    <span style="color:blue">' Use the cut feature as parent features for pattern feature.</span>
    Dim oParentFeatures As ObjectCollection
    Set oParentFeatures = ThisApplication.TransientObjects.CreateObjectCollection
    oParentFeatures.Add oExtrude
    
    Dim oRectPatternDef As RectangularPatternFeatureDefinition
    Set oRectPatternDef = oCompDef.Features.RectangularPatternFeatures.CreateDefinition(oParentFeatures, oFrontFace.Edges(6), False, 6, "4 cm")
    oRectPatternDef.YDirectionEntity = oFrontFace.Edges(7)
    oRectPatternDef.YCount = 6
    oRectPatternDef.YSpacing = "3 cm"
    oRectPatternDef.NaturalYDirection = True
     
    <span style="color:blue">' Set the boundary settings for the pattern feature.</span>
    Set oProfile = oSketch.Profiles.AddForSolid
    Dim oPatternBoundarySetting As PatternBoundarySetting
    Set oPatternBoundarySetting = oRectPatternDef.BoundarySetting
    Call oPatternBoundarySetting.SetBoundarySettingData(oProfile, kCentroidsInclusionType)
    
    <span style="color:blue">' Create rectangular pattern feature with boundary settings.</span>
    Dim oRectPatternFeature As RectangularPatternFeature
    Set oRectPatternFeature = oCompDef.Features.RectangularPatternFeatures.AddByDefinition(oRectPatternDef)
End Sub</pre>
      </div>
      <div id="iLogic" class="api-code">This sample demonstrates how to create a rectangular pattern feature with boundary settings.<table width="100%" style="font-size:15">
          <tr>
            <td align="right"><button onclick="copyCode('iLogic_code')" class="copy-code">Copy Code</button></td>
          </tr>
        </table>
        <pre class="api-code" id="iLogic_code">    <span style="color:blue">' Create a new part document, using the default part template.</span>
    Dim oPartDoc As PartDocument
    oPartDoc = ThisApplication.Documents.Add(kPartDocumentObject)
                    
    <span style="color:blue">' Set a reference to the component definition.</span>
    Dim oCompDef As PartComponentDefinition
    oCompDef = oPartDoc.ComponentDefinition
    
    <span style="color:blue">' Create a new sketch on the X-Y work plane.</span>
    Dim oSketch As PlanarSketch
    oSketch = oCompDef.Sketches.Add(oCompDef.WorkPlanes(3))
    
    <span style="color:blue">' Set a reference to the transient geometry object.</span>
    Dim oTransGeom As TransientGeometry
    oTransGeom = ThisApplication.TransientGeometry
    
    <span style="color:blue">' Draw a rectangle.</span>
    Dim oRectangleLines As SketchEntitiesEnumerator
    oRectangleLines = oSketch.SketchLines.AddAsTwoPointRectangle( _
                                oTransGeom.CreatePoint2d(-10, -10), _
                                oTransGeom.CreatePoint2d(10, 10))

    <span style="color:blue">' Create a profile.</span>
    Dim oProfile As Profile
    oProfile = oSketch.Profiles.AddForSolid
    
    <span style="color:blue">' Create a base extrusion 1cm thick.</span>
    Dim oExtrudeDef As ExtrudeDefinition
    oExtrudeDef = oCompDef.Features.ExtrudeFeatures.CreateExtrudeDefinition(oProfile, kJoinOperation)
    Call oExtrudeDef.SetDistanceExtent(1, kNegativeExtentDirection)
    Dim oExtrude As ExtrudeFeature
    oExtrude = oCompDef.Features.ExtrudeFeatures.Add(oExtrudeDef)
                        
    <span style="color:blue">' Get the top face of the extrusion to use for creating the new sketch.</span>
    Dim oFrontFace As Face
    oFrontFace = oExtrude.StartFaces.Item(1)
    
    <span style="color:blue">' Create a new sketch on this face.</span>
    oSketch = oCompDef.Sketches.AddWithOrientation(oFrontFace, _
                    oCompDef.WorkAxes.Item(1), True, True, oCompDef.WorkPoints(1))
                    
    <span style="color:blue">' Determine where in sketch space the point (0.5,0.5,0) is.</span>
    Dim oCorner As Point2d
    oCorner = oTransGeom.CreatePoint2d(-9, 9)
    
    Dim oTriangle As SketchEntitiesEnumerator
    oTriangle = oSketch.SketchLines.AddAsPolygon(3, oCorner, oTransGeom.CreatePoint2d(-9.5, 9.5), True)
                    
    <span style="color:blue">' Create a profile.</span>
    oProfile = oSketch.Profiles.AddForSolid
    
    <span style="color:blue">' Create a cut feature.</span>
    oExtrudeDef = oCompDef.Features.ExtrudeFeatures.CreateExtrudeDefinition(oProfile, kCutOperation)
    Call oExtrudeDef.SetDistanceExtent(1, kNegativeExtentDirection)
    oExtrude = oCompDef.Features.ExtrudeFeatures.Add(oExtrudeDef)
    
    oSketch = oCompDef.Sketches.AddWithOrientation(oFrontFace, _
                    oCompDef.WorkAxes.Item(1), True, True, oCompDef.WorkPoints(1))
    
    Call oSketch.SketchLines.AddAsTwoPointRectangle(oTransGeom.CreatePoint2d(-6.5, 8), oTransGeom.CreatePoint2d(8.5, -8))
    
    <span style="color:blue">' Use the cut feature as parent features for pattern feature.</span>
    Dim oParentFeatures As ObjectCollection
    oParentFeatures = ThisApplication.TransientObjects.CreateObjectCollection
    oParentFeatures.Add(oExtrude)
    
    Dim oRectPatternDef As RectangularPatternFeatureDefinition
    oRectPatternDef = oCompDef.Features.RectangularPatternFeatures.CreateDefinition(oParentFeatures, oFrontFace.Edges(6), False, 6, "4 cm")
    oRectPatternDef.YDirectionEntity = oFrontFace.Edges(7)
    oRectPatternDef.YCount = 6
    oRectPatternDef.YSpacing = "3 cm"
    oRectPatternDef.NaturalYDirection = True
     
    <span style="color:blue">' Set the boundary settings for the pattern feature.</span>
    oProfile = oSketch.Profiles.AddForSolid
    Dim oPatternBoundarySetting As PatternBoundarySetting
    oPatternBoundarySetting = oRectPatternDef.BoundarySetting
    Call oPatternBoundarySetting.SetBoundarySettingData(oProfile, kCentroidsInclusionType)
    
    <span style="color:blue">' Create rectangular pattern feature with boundary settings.</span>
    Dim oRectPatternFeature As RectangularPatternFeature
    oRectPatternFeature = oCompDef.Features.RectangularPatternFeatures.AddByDefinition(oRectPatternDef)</pre>
      </div>
    </div><br><br><div id="CopyrightNotice" style="display:none;">
      <hr>
      <table width="100%" style="font-size:15">
        <tr>
          <td align="left">
                Â© Copyright 2025 Autodesk, Inc.
              </td>
          <td align="right"><a href="mailto:mfg.api.help.comments@autodesk.com?subject=Inventor%202026%20API%20Help%20(CreatePatternBoundarySettingSample%20Sample%20Help%20Topic)">Comment on this page.</a></td>
        </tr>
      </table>
    </div>
  </body>
</html>