<html>
  <head>
    <META http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="topic-type" content="reference-adsk">
    <meta name="helpsystempath" content="/view/INVNTOR/2026/ENU/">
    <link rel="canonical" href="/cloudhelp/2026/ENU/Inventor-API/files/Document_CreateHighlightSet_Sample.htm#!">
    <meta name="product" content="INVNTOR">
    <meta name="release" content="2026">
    <meta name="book" content="Developer">
    <meta name="component" content="Inventor-API">
    <meta name="created" content="">
    <meta name="user-comments" content="enable">
    <meta name="contextid" content="Document_CreateHighlightSet_Sample">
    <meta name="description" content="Creating a HighlightSet Sample">
    <meta name="topicid" content="Document_CreateHighlightSet_Sample">
    <meta name="experiencelevel" content="expert">
    <meta name="audience" content="programmer">
    <meta name="language" content="ENU">
    <title>Creating a HighlightSet</title>
    <link rel="stylesheet" href="../Style/jquery-ui.css"><script src="../Scripts/jquery-1.11.1.js"></script><script src="../Scripts/jquery-ui.js"></script><link rel="stylesheet" type="text/css" href="../Style/APIHelp-chm.css">
    <link rel="stylesheet" type="text/css" href="/view/clientframework/client.css"><script type="text/javascript" src="/view/clientframework/client.js"></script><script>
          // This turns on the display of the copyright notice which is not visible by default.
          // Because the head is removed when used in the web help, this function will only exists
          // when the chm help is being created.
          window.onload = function() {
          copyrightElement = document.getElementById('CopyrightNotice');
          copyrightElement.style.display = 'block';
          };
        </script><script>
          $(function() {
          $( "#tabs" ).tabs();
          });
        </script></head>
  <body><script>
          function copyCode(language) {
          // Get the pre element for the specified language.
          var preElement = document.getElementById(language);

          // Get the text from the element and copy it to the clipboard.
          var preText = preElement.innerText;

          var isIE = /*@cc_on!@*/false || !!document.documentMode;

          if (isIE)
          {
            window.clipboardData.setData('Text', preText);
          }
          else
          {
            navigator.clipboard.writeText(preText);
          }

          //alert("Code copied to clipboard");
          }
        </script><link rel="stylesheet" type="text/css" href="../Style/APIHelp.css">
    <h1 class="api">Creating a HighlightSet</h1>
    <h2 class="api">
          Description
        </h2>Demonstrates creating a highlight set.<h2 class="api">
          Code Samples
        </h2>
    <div id="tabs">
      <ul>
        <li><a href="#VBA">VBA</a></li>
        <li><a href="#iLogic">iLogic</a></li>
      </ul>
      <div id="VBA" class="api-code">
        <table width="100%" style="font-size:15">
          <tr>
            <td align="right"><button onclick="copyCode('VBA_code')" class="copy-code">Copy Code</button></td>
          </tr>
        </table>
        <pre class="api-code" id="VBA_code">Sub Main()
  <span style="color:blue">' Check to make sure the active document is a part.</span>
  If ThisApplication.ActiveDocumentType &lt;&gt; kPartDocumentObject Then
     MsgBox "A part document must be open."
     End
  End If

  <span style="color:blue">' Set a reference to the active part document.</span>
  Dim oDoc As PartDocument
  Set oDoc = ThisApplication.ActiveDocument

  <span style="color:blue">' Arbitrarily get two faces.  (Assumes a model exists that has</span>
  <span style="color:blue">' at least 3 faces.</span>
  Dim oFace1 As Face
  Dim oFace2 As Face
  Set oFace1 = oDoc.ComponentDefinitions(1).SurfaceBodies(1).Faces(1)
  Set oFace2 = oDoc.ComponentDefinitions(1).SurfaceBodies(1).Faces(3)

  <span style="color:blue">' Create a highlight set.</span>
  Dim oSet1 As HighlightSet
  Set oSet1 = oDoc.CreateHighlightSet

  <span style="color:blue">' Add the first face to the highlight set.</span>
   Call oSet1.AddItem(oFace1)

  <span style="color:blue">' Create another highlight set.</span>
  Dim oSet2 As HighlightSet
  Set oSet2 = oDoc.CreateHighlightSet

  <span style="color:blue">' Change the color of the highlight set to green.</span>
  oSet2.Color = ThisApplication.TransientObjects.CreateColor(0, 255, 0)

  <span style="color:blue">' Add the second face to the highlight set.</span>
  Call oSet2.AddItem(oFace2)
End Sub</pre>
      </div>
      <div id="iLogic" class="api-code">
        <table width="100%" style="font-size:15">
          <tr>
            <td align="right"><button onclick="copyCode('iLogic_code')" class="copy-code">Copy Code</button></td>
          </tr>
        </table>
        <pre class="api-code" id="iLogic_code">    <span style="color:blue">' Check to make sure the active document is a part.</span>
  If ThisApplication.ActiveDocumentType &lt;&gt; kPartDocumentObject Then
     MsgBox("A part document must be open.")
     Exit Sub
  End If

  <span style="color:blue">' Set a reference to the active part document.</span>
  Dim oDoc As PartDocument
  oDoc = ThisApplication.ActiveDocument

  <span style="color:blue">' Arbitrarily get two faces.  (Assumes a model exists that has</span>
  <span style="color:blue">' at least 3 faces.</span>
  Dim oFace1 As Face
  Dim oFace2 As Face
  oFace1 = oDoc.ComponentDefinitions(1).SurfaceBodies(1).Faces(1)
  oFace2 = oDoc.ComponentDefinitions(1).SurfaceBodies(1).Faces(3)

  <span style="color:blue">' Create a highlight set.</span>
  Dim oSet1 As HighlightSet
  oSet1 = oDoc.CreateHighlightSet

  <span style="color:blue">' Add the first face to the highlight set.</span>
   Call oSet1.AddItem(oFace1)

  <span style="color:blue">' Create another highlight set.</span>
  Dim oSet2 As HighlightSet
  oSet2 = oDoc.CreateHighlightSet

  <span style="color:blue">' Change the color of the highlight set to green.</span>
  oSet2.Color = ThisApplication.TransientObjects.CreateColor(0, 255, 0)

  <span style="color:blue">' Add the second face to the highlight set.</span>
  Call oSet2.AddItem(oFace2)</pre>
      </div>
    </div><br><br><div id="CopyrightNotice" style="display:none;">
      <hr>
      <table width="100%" style="font-size:15">
        <tr>
          <td align="left">
                Â© Copyright 2025 Autodesk, Inc.
              </td>
          <td align="right"><a href="mailto:mfg.api.help.comments@autodesk.com?subject=Inventor%202026%20API%20Help%20(Document_CreateHighlightSet%20Sample%20Help%20Topic)">Comment on this page.</a></td>
        </tr>
      </table>
    </div>
  </body>
</html>