<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="topic-type" content="reference-adsk">
    <meta name="helpsystempath" content="/view/INVNTOR/2026/ENU">
    <link rel="canonical" href="http://help.autodesk.com/cloudhelp/2026/ENU/Inventor-API/files/DrawingViews_Overview.htm">
    <meta name="product" content="INVNTOR">
    <meta name="release" content="2026">
    <meta name="book" content="Developer">
    <meta name="component" content="Inventor-API">
    <meta name="created" content="27/4/2016">
    <meta name="user-comments" content="enable">
    <meta name="description" content="">
    <meta name="topicid" content="GUID-66470F9F-8563-4D53-91BE-F4769943E71C">
    <meta name="experiencelevel" content="expert">
    <meta name="audience" content="programmer">
    <meta name="language" content="ENU">
    <title>Drawing Views</title>
    <link rel="stylesheet" type="text/css" href="../Style/APIHelp-chm.css">
    <link rel="stylesheet" type="text/css" href="/view/clientframework/client.css"/>
    <script type="text/javascript" src="/view/clientframework/client.js"><!--filler--></script>
	<script>
	  // This turns on the display of the copyright notice which is not visible by default.
	  // Because the head is removed when used in the web help, this function will only exists
	  // when the chm help is being created.
	  window.onload = function() {
		copyrightElement = document.getElementById('CopyrightNotice');
		copyrightElement.style.display = 'block';
	  };
	</script>
</head>
<body>
<link rel="stylesheet" type="text/css" href="../Style/APIHelp.css">
	
<H1 class="dxH1">Drawing Views</h1>
	

<h3>Introduction to drawing views</h3>

<p Class="Normal">The Autodesk Inventor user interface allows placement of drawing views on a drawing sheet.  These views are 2D representations of the 3D model, and can be orthographic, isometric, or they can have an arbitrary view angle.  They can be scaled views to show fine detail, or they can be section views.  The API provides the same functionality through the collection of DrawingView objects.</p>

<h3>The purpose of the drawing views API </h3>

<p Class="Normal">The drawing view API enables code to create, place and manipulate drawing views, including base views, on drawing sheets.  View types supported include projected, section, and draft views.  Additionally, the API supports the OnViewUpdate event, provided through the DrawingViewEvents object, allowing application code to be notified if an associated draft view is updated due to a change to the model.</p>
 
<h3>Drawing views object model diagram</h3>

 <br>
<div align="center"> <img src="../images/ov.drawingviews_diag.png" border=0 ></div>
 <br>

<h3>Working with drawing views through the API</h3>

<p Class="Normal">The DrawingViews collection is obtained from the Sheet object. The Sheets collection is obtained from the DrawingDocument object, or if Apprentice Server is being used, from the ApprenticeServerDrawingDocument.  The latter hierarchy provides read-only access to the drawing views.</p>
<p Class="Normal">The various types of drawing views are represented by the DrawingView object, with the exception of section views, which are of type SectionDrawingView.   Section, draft, and associated draft views can only be created on the active sheet.</p>
<p Class="Normal">The DrawingView and SectionDrawingView objects provide a number of transformation methods designed to translate points between drawing view, model, and sheet spaces.  These methods include DrawingViewToModelSpace, DrawingViewToSheetSpace, ModelToDrawingViewSpace, ModelToSheetSpace, SheetToModelSpace, and SheetToDrawingViewSpace. </p>

<h3>Creating a drawing view</h3>

<p Class="Normal">The following code assumes a drawing document is open in Autodesk Inventor, and that the source part file (part.ipt) is located in the root of the C: drive.  This file reference can be changed to suit.  Here is the part used for this example.</p>

 <br>
<div align="center"> <img src="../images/ov.drawingviews_shot1.png" border=0 ></div>
 <br>

<p Class="Normal">This sample and the following code omit error checking for the sake of clarity and brevity.  Always check that return values are of the expected type.</p>
<p Class="Normal">The first step is to obtain the sheet object, in order to place a view.  The location of the view is provided by a 2D point.  The following code uses transient geometry to define a 2D point at X=5, Y=5.</p>
 
<br>
<table Class="Code">
<tr valign="middle">
	<td Class="Code">
	<pre>
Dim oDrawingDoc As DrawingDocument
Set oDrawingDoc = ThisApplication.ActiveDocument 
      
Dim oSheet As Sheet
Set oSheet = oDrawingDoc.Sheets.Item(1)
       
Dim oPoint1 As Point2d
Set oPoint1 = ThisApplication.TransientGeometry.CreatePoint2d(5#, 5#)
</pre></td></tr>
</table>
<br>

<p Class="Normal">This sample places a regular drawing view of a model part.  The following code uses an arbitrary hard-coded part file reference that should be changed as appropriate.</p>

<br>
<table cellspacing="4" cellpadding="4" border="1">
<tr>
    <td  bgcolor="Yellow"><b>Note:</b> 
 The False argument to the document Open method indicates the part file is to be opened invisibly.  In this context, there is no need to see the part in Autodesk Inventor.  It is simply the source for the drawing view.  Close the part file afterwards.
</td>
</tr>
</table>
<br>

<p Class="Normal">The new hidden line DrawingView object is added to the DrawingViews collection using a bottom view of the opened part file, at point 5,5, at a scale of 1:1.  Immediately afterwards, the part file is closed.  It is good practice to keep file references open no longer that necessary.</p>

<br>
<table Class="Code">
<tr valign="middle">
	<td Class="Code">
	<pre>
Dim oPartDoc As PartDocument
Set oPartDoc = ThisApplication.Documents.Open("c:\testpart.ipt", False)

Dim oView1 As DrawingView
Set oView1 = oSheet.DrawingViews.AddBaseView(oPartDoc, _
    oPoint1, 1#, kBottomViewOrientation, kHiddenLineDrawingViewStyle)

Call oPartDoc.Close(True)
</pre></td></tr>
</table>
<br>

<p Class="Normal">The following is an example of how this appears on the sheet.</p>

 <br>
<div align="center"> <img src="../images/ov.drawingviews_shot2.png" border=0 ></div>
 <br>

<h3>Creating a section drawing view</h3>

<p Class="Normal">The previous example placed a drawing view of a part.  The following code places a new section drawing view through the previously placed view.  Section views require that a section line be defined.  This is the line through which the part is to be cut.  However, unlike section lines created through the user interface, section lines created through the API are not constrained to the model, and therefore do not automatically update to reflect changes to the model.</p>
<p Class="Normal">The first task is to indicate the section line, either using existing geometry, or by creating a sketch containing a sketch line, as in the following code.</p>

<br>
<table Class="Code">
<tr valign="middle">
	<td Class="Code">
	<pre>
Dim oPoint2 As Point2d
Set oPoint2 = ThisApplication.TransientGeometry.CreatePoint2d(15#, 40#)

Dim oDrawingSketch As DrawingSketch
Set oDrawingSketch = oView1.Sketches.Add
    
oDrawingSketch.Edit
Dim oSketchLine As SketchLine
Set oSketchLine = oDrawingSketch.SketchLines.AddByTwoPoints(oPoint1, _
    oPoint2)
oDrawingSketch.ExitEdit
</pre></td></tr>
</table>
<br>

<p Class="Normal">For simplicity, this code reuses the view placement points to define the ends of the sketch line.  In reality, this sketch line would be placed at a specific point relative to the base view. Now to add the section view by calling AddSectionView.</p>

<br>
<table Class="Code">
<tr valign="middle">
	<td Class="Code">
	<pre>
Dim oView2 As SectionDrawingView
Set oView2 = oSheet.DrawingViews.AddSectionView(oView1, _
     oDrawingSketch, oPoint2, kHiddenLineRemovedDrawingViewStyle)

oDrawingSketch.Visible = False
</pre></td></tr>
</table>
<br>

<p Class="Normal">Note the absence of a part file reference in the preceding code.  Unlike base view creation, the previously created view is passed as an argument, together with the sketch line indicating the cut line.  The two views now look something like the following illustration.</p>

 <br>
<div align="center"> <img src="../images/ov.drawingviews_shot3.png" border=0 ></div>
 <br>

<p Class="Normal">The arrows and notation in the preceding figures were generated automatically.</p>

<h3>Summary</h3>

<p Class="Normal">The drawing view API functionality is equivalent to much of the drawing view functionality available through the user interface.  It allows for the placement of different types of views on a drawing sheet.  These views may be blank draft views, projected views, or section views.  The API also provides a means of notification if the underlying model is subject to change.</p>

<h3>Also consider</h3>

<p Class="Normal">Other drawing view API functionality includes the ability to edit drawing dimensions on a sheet through the DrawingDimension object. Sheet title blocks and templates can be edited through the use of drawing text (the TextBox object and associated styles) and drawing sketches.</p>

<br />
<br />
<div id="CopyrightNotice" style="display:none;">
  <hr />
  <table width="100%" style="font-size:15">
	<tr>
	  <td align="left">
		&copy; Copyright 2025 Autodesk, Inc.
	  </td>
	  <td align="right">
		<a href="mailto:mfg.api.help.comments@autodesk.com?subject=Inventor%202026%20API%20Help%20(DrawingViews_Overview)">Comment on this page.</a>
	  </td>
	</tr>
  </table>
</div>

</body>
</html>