<html>
  <head>
    <META http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="topic-type" content="reference-adsk">
    <meta name="helpsystempath" content="/view/INVNTOR/2026/ENU/">
    <link rel="canonical" href="/cloudhelp/2026/ENU/Inventor-API/files/DrawingDocument_BorderDefinitions_Sample.htm#!">
    <meta name="product" content="INVNTOR">
    <meta name="release" content="2026">
    <meta name="book" content="Developer">
    <meta name="component" content="Inventor-API">
    <meta name="created" content="">
    <meta name="user-comments" content="enable">
    <meta name="contextid" content="DrawingDocument_BorderDefinitions_Sample">
    <meta name="description" content="Border Create and Insert Sample">
    <meta name="topicid" content="DrawingDocument_BorderDefinitions_Sample">
    <meta name="experiencelevel" content="expert">
    <meta name="audience" content="programmer">
    <meta name="language" content="ENU">
    <title>Border Create and Insert</title>
    <link rel="stylesheet" href="../Style/jquery-ui.css"><script src="../Scripts/jquery-1.11.1.js"></script><script src="../Scripts/jquery-ui.js"></script><link rel="stylesheet" type="text/css" href="../Style/APIHelp-chm.css">
    <link rel="stylesheet" type="text/css" href="/view/clientframework/client.css"><script type="text/javascript" src="/view/clientframework/client.js"></script><script>
          // This turns on the display of the copyright notice which is not visible by default.
          // Because the head is removed when used in the web help, this function will only exists
          // when the chm help is being created.
          window.onload = function() {
          copyrightElement = document.getElementById('CopyrightNotice');
          copyrightElement.style.display = 'block';
          };
        </script><script>
          $(function() {
          $( "#tabs" ).tabs();
          });
        </script></head>
  <body><script>
          function copyCode(language) {
          // Get the pre element for the specified language.
          var preElement = document.getElementById(language);

          // Get the text from the element and copy it to the clipboard.
          var preText = preElement.innerText;

          var isIE = /*@cc_on!@*/false || !!document.documentMode;

          if (isIE)
          {
            window.clipboardData.setData('Text', preText);
          }
          else
          {
            navigator.clipboard.writeText(preText);
          }

          //alert("Code copied to clipboard");
          }
        </script><link rel="stylesheet" type="text/css" href="../Style/APIHelp.css">
    <h1 class="api">Border Create and Insert</h1>
    <h2 class="api">
          Description
        </h2>This sample illustrates creating a new border definition object and using it for a sheet.<h2 class="api">
          Code Samples
        </h2>
    <div id="tabs">
      <ul>
        <li><a href="#VBA">VBA</a></li>
        <li><a href="#iLogic">iLogic</a></li>
      </ul>
      <div id="VBA" class="api-code">This sample consists of two sub procedures. The first creates the border definition. The second inserts it into the active sheet. To run the sample have a drawing document open and run the CreateBorderDefinition first. After that you can run the InsertBorderOnSheet.<table width="100%" style="font-size:15">
          <tr>
            <td align="right"><button onclick="copyCode('VBA_code')" class="copy-code">Copy Code</button></td>
          </tr>
        </table>
        <pre class="api-code" id="VBA_code">Sub Main()
	CreateBorderDefinition()
	InsertCustomBorderOnSheet()
End Sub
	
Sub CreateBorderDefinition()
    <span style="color:blue">' Set a reference to the drawing document.</span>
    <span style="color:blue">' This assumes a drawing document is active.</span>
    Dim oDrawDoc As DrawingDocument
    oDrawDoc = ThisApplication.ActiveDocument
    
    <span style="color:blue">' Create the new borderdefinition.</span>
    Dim oBorderDef As BorderDefinition
    oBorderDef = oDrawDoc.BorderDefinitions.Add("Sample Border")
    
    <span style="color:blue">' Open the border definition's sketch for edit.  This is done by calling the Edit</span>
    <span style="color:blue">' method of the BorderDefinition to obtain a DrawingSketch.  This actually creates</span>
    <span style="color:blue">' a copy of the border definition's and opens it for edit.</span>
    Dim oSketch As DrawingSketch
    Call oBorderDef.Edit(oSketch)
    
    Dim oTG As TransientGeometry
    oTG = ThisApplication.TransientGeometry
    
    <span style="color:blue">' Use the functionality of the sketch to add geometry.</span>
    Call oSketch.SketchLines.AddAsTwoPointRectangle(oTG.CreatePoint2d(2, 2), oTG.CreatePoint2d(25.94, 19.59))
    Call oSketch.SketchLines.AddByTwoPoints(oTG.CreatePoint2d(0, 10.795), oTG.CreatePoint2d(2, 10.795))
    Call oSketch.SketchLines.AddByTwoPoints(oTG.CreatePoint2d(13.97, 0), oTG.CreatePoint2d(13.97, 2))
    Call oSketch.SketchLines.AddByTwoPoints(oTG.CreatePoint2d(25.94, 10.795), oTG.CreatePoint2d(27.94, 10.795))
    Call oSketch.SketchLines.AddByTwoPoints(oTG.CreatePoint2d(13.97, 19.59), oTG.CreatePoint2d(13.97, 21.59))
    
    <span style="color:blue">' Add some text to the border.</span>
    Dim oTextBox As TextBox
    oTextBox = oSketch.TextBoxes.AddFitted(oTG.CreatePoint2d(2, 1), "Here is a sample string")
    oTextBox.VerticalJustification = kAlignTextMiddle
    
    <span style="color:blue">' Add some prompted text to the border.</span>
    oTextBox = oSketch.TextBoxes.AddFitted(oTG.CreatePoint2d(2, 20.59), "Enter designers name:")
    oTextBox.VerticalJustification = kAlignTextMiddle
    
    Call oBorderDef.ExitEdit(True)
End Sub

Public Sub InsertCustomBorderOnSheet()
    <span style="color:blue">' Set a reference to the drawing document.</span>
    <span style="color:blue">' This assumes a drawing document is active.</span>
    Dim oDrawDoc As DrawingDocument
    oDrawDoc = ThisApplication.ActiveDocument
    
    <span style="color:blue">' Obtain a reference to the desired border definition.</span>
    Dim oBorderDef As BorderDefinition
    oBorderDef = oDrawDoc.BorderDefinitions.Item("Sample Border")
    
    Dim oSheet As Sheet
    oSheet = oDrawDoc.ActiveSheet
    
    <span style="color:blue">' Check to see if the sheet already has a border and delete it if it does.</span>
    If Not oSheet.Border Is Nothing Then
        oSheet.Border.Delete
    End If
    
    <span style="color:blue">' This border definition contains one prompted string input.  An array</span>
    <span style="color:blue">' must be input that contains the strings for the prompted strings.</span>
    Dim sPromptStrings(0 To 0) As String
    sPromptStrings(0) = "This is the input for the prompted text."
    
    <span style="color:blue">' Add an instance of the border definition to the sheet.</span>
    Dim oBorder As Border
    oBorder = oSheet.AddBorder(oBorderDef, sPromptStrings)
End Sub</pre>
      </div>
      <div id="iLogic" class="api-code">This sample consists of two sub procedures. The first creates the border definition. The second inserts it into the active sheet. To run the sample have a drawing document open and run the CreateBorderDefinition sub first. After that you can run the InsertBorderOnSheet sub.<table width="100%" style="font-size:15">
          <tr>
            <td align="right"><button onclick="copyCode('iLogic_code')" class="copy-code">Copy Code</button></td>
          </tr>
        </table>
        <pre class="api-code" id="iLogic_code">Sub Main
    <span style="color:blue">' Set a reference to the drawing document.</span>
    <span style="color:blue">' This assumes a drawing document is active.</span>
    Dim oDrawDoc As DrawingDocument
    oDrawDoc = ThisApplication.ActiveDocument
    
    <span style="color:blue">' Create the new borderdefinition.</span>
    Dim oBorderDef As BorderDefinition
    oBorderDef = oDrawDoc.BorderDefinitions.Add("Sample Border")
    
    <span style="color:blue">' Open the border definition's sketch for edit.  This is done by calling the Edit</span>
    <span style="color:blue">' method of the BorderDefinition to obtain a DrawingSketch.  This actually creates</span>
    <span style="color:blue">' a copy of the border definition's and opens it for edit.</span>
    Dim oSketch As DrawingSketch
    Call oBorderDef.Edit(oSketch)
    
    Dim oTG As TransientGeometry
    oTG = ThisApplication.TransientGeometry
    
    <span style="color:blue">' Use the functionality of the sketch to add geometry.</span>
    Call oSketch.SketchLines.AddAsTwoPointRectangle(oTG.CreatePoint2d(2, 2), oTG.CreatePoint2d(25.94, 19.59))
    Call oSketch.SketchLines.AddByTwoPoints(oTG.CreatePoint2d(0, 10.795), oTG.CreatePoint2d(2, 10.795))
    Call oSketch.SketchLines.AddByTwoPoints(oTG.CreatePoint2d(13.97, 0), oTG.CreatePoint2d(13.97, 2))
    Call oSketch.SketchLines.AddByTwoPoints(oTG.CreatePoint2d(25.94, 10.795), oTG.CreatePoint2d(27.94, 10.795))
    Call oSketch.SketchLines.AddByTwoPoints(oTG.CreatePoint2d(13.97, 19.59), oTG.CreatePoint2d(13.97, 21.59))
    
    <span style="color:blue">' Add some text to the border.</span>
    Dim oTextBox As TextBox
    oTextBox = oSketch.TextBoxes.AddFitted(oTG.CreatePoint2d(2, 1), "Here is a sample string")
    oTextBox.VerticalJustification = kAlignTextMiddle
    
    <span style="color:blue">' Add some prompted text to the border.</span>
    oTextBox = oSketch.TextBoxes.AddFitted(oTG.CreatePoint2d(2, 20.59), "Enter designers name:")
    oTextBox.VerticalJustification = kAlignTextMiddle
    
    Call oBorderDef.ExitEdit(True)
End Sub

Public Sub InsertCustomBorderOnSheet()
    <span style="color:blue">' Set a reference to the drawing document.</span>
    <span style="color:blue">' This assumes a drawing document is active.</span>
    Dim oDrawDoc As DrawingDocument
    oDrawDoc = ThisApplication.ActiveDocument
    
    <span style="color:blue">' Obtain a reference to the desired border definition.</span>
    Dim oBorderDef As BorderDefinition
    oBorderDef = oDrawDoc.BorderDefinitions.Item("Sample Border")
    
    Dim oSheet As Sheet
    oSheet = oDrawDoc.ActiveSheet
    
    <span style="color:blue">' Check to see if the sheet already has a border and delete it if it does.</span>
    If Not oSheet.Border Is Nothing Then
        oSheet.Border.Delete
    End If
    
    <span style="color:blue">' This border definition contains one prompted string input.  An array</span>
    <span style="color:blue">' must be input that contains the strings for the prompted strings.</span>
    Dim sPromptStrings(0 To 0) As String
    sPromptStrings(0) = "This is the input for the prompted text."
    
    <span style="color:blue">' Add an instance of the border definition to the sheet.</span>
    Dim oBorder As Border
    oBorder = oSheet.AddBorder(oBorderDef, sPromptStrings)
End Sub</pre>
      </div>
    </div><br><br><div id="CopyrightNotice" style="display:none;">
      <hr>
      <table width="100%" style="font-size:15">
        <tr>
          <td align="left">
                Â© Copyright 2025 Autodesk, Inc.
              </td>
          <td align="right"><a href="mailto:mfg.api.help.comments@autodesk.com?subject=Inventor%202026%20API%20Help%20(DrawingDocument_BorderDefinitions%20Sample%20Help%20Topic)">Comment on this page.</a></td>
        </tr>
      </table>
    </div>
  </body>
</html>