<html>
  <head>
    <META http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="topic-type" content="reference-adsk">
    <meta name="helpsystempath" content="/view/INVNTOR/2026/ENU/">
    <link rel="canonical" href="/cloudhelp/2026/ENU/Inventor-API/files/DriveCamera_Sample.htm#!">
    <meta name="product" content="INVNTOR">
    <meta name="release" content="2026">
    <meta name="book" content="Developer">
    <meta name="component" content="Inventor-API">
    <meta name="created" content="">
    <meta name="user-comments" content="enable">
    <meta name="contextid" content="DriveCamera_Sample">
    <meta name="description" content="Drive the camera Sample">
    <meta name="topicid" content="DriveCamera_Sample">
    <meta name="experiencelevel" content="expert">
    <meta name="audience" content="programmer">
    <meta name="language" content="ENU">
    <title>Drive the camera</title>
    <link rel="stylesheet" href="../Style/jquery-ui.css"><script src="../Scripts/jquery-1.11.1.js"></script><script src="../Scripts/jquery-ui.js"></script><link rel="stylesheet" type="text/css" href="../Style/APIHelp-chm.css">
    <link rel="stylesheet" type="text/css" href="/view/clientframework/client.css"><script type="text/javascript" src="/view/clientframework/client.js"></script><script>
          // This turns on the display of the copyright notice which is not visible by default.
          // Because the head is removed when used in the web help, this function will only exists
          // when the chm help is being created.
          window.onload = function() {
          copyrightElement = document.getElementById('CopyrightNotice');
          copyrightElement.style.display = 'block';
          };
        </script><script>
          $(function() {
          $( "#tabs" ).tabs();
          });
        </script></head>
  <body><script>
          function copyCode(language) {
          // Get the pre element for the specified language.
          var preElement = document.getElementById(language);

          // Get the text from the element and copy it to the clipboard.
          var preText = preElement.innerText;

          var isIE = /*@cc_on!@*/false || !!document.documentMode;

          if (isIE)
          {
            window.clipboardData.setData('Text', preText);
          }
          else
          {
            navigator.clipboard.writeText(preText);
          }

          //alert("Code copied to clipboard");
          }
        </script><link rel="stylesheet" type="text/css" href="../Style/APIHelp.css">
    <h1 class="api">Drive the camera</h1>
    <h2 class="api">
          Description
        </h2>This sample will fly the camera around the model.  To simplify the code, the target is hard coded at the origin and the up vector is the positive Z.<h2 class="api">
          Code Samples
        </h2>
    <div id="tabs">
      <ul>
        <li><a href="#VBA">VBA</a></li>
        <li><a href="#iLogic">iLogic</a></li>
      </ul>
      <div id="VBA" class="api-code">
        <table width="100%" style="font-size:15">
          <tr>
            <td align="right"><button onclick="copyCode('VBA_code')" class="copy-code">Copy Code</button></td>
          </tr>
        </table>
        <pre class="api-code" id="VBA_code">Public Sub RotateCamera()
    <span style="color:blue">' Get the active camera.</span>
    Dim cam As Camera
    Set cam = ThisApplication.ActiveView.Camera
    
    Dim tg As TransientGeometry
    Set tg = ThisApplication.TransientGeometry
    
    <span style="color:blue">' Define the number of steps in the animation.</span>
    Dim steps As Integer
    steps = 360
    
    <span style="color:blue">' Define the distance between the eye and target.</span>
    Dim eyeDistance As Double
    eyeDistance = 15
    
    <span style="color:blue">' Calculate pi.</span>
    Dim pi As Double
    pi = Atn(1) * 4
    
    <span style="color:blue">' Iterate the specified number of steps.</span>
    Dim i As Integer
    For i = 1 To steps
        <span style="color:blue">' Calculate the x and y coordinates of the eye.</span>
        Dim x As Double
        Dim y As Double
        x = eyeDistance * Cos(i / steps * (2 * pi))
        y = eyeDistance * Sin(i / steps * (2 * pi))
        
        <span style="color:blue">' Set the eye with a hard coded z value.</span>
        cam.Eye = tg.CreatePoint(x, y, 3)
        
        <span style="color:blue">' Define the up vector as positive z.</span>
        cam.UpVector = tg.CreateUnitVector(0, 0, 1)
        
        <span style="color:blue">' Apply the current camera definition to the view.</span>
        cam.ApplyWithoutTransition
    Next
End Sub</pre>
      </div>
      <div id="iLogic" class="api-code">
        <table width="100%" style="font-size:15">
          <tr>
            <td align="right"><button onclick="copyCode('iLogic_code')" class="copy-code">Copy Code</button></td>
          </tr>
        </table>
        <pre class="api-code" id="iLogic_code">    <span style="color:blue">' Get the active camera.</span>
    Dim cam As Camera
    cam = ThisApplication.ActiveView.Camera
    
    Dim tg As TransientGeometry
    tg = ThisApplication.TransientGeometry
    
    <span style="color:blue">' Define the number of steps in the animation.</span>
    Dim steps As Integer
    steps = 360
    
    <span style="color:blue">' Define the distance between the eye and target.</span>
    Dim eyeDistance As Double
    eyeDistance = 15
    
    <span style="color:blue">' Calculate pi.</span>
    Dim pi As Double
    pi = Math.Atan(1) * 4
    
    <span style="color:blue">' Iterate the specified number of steps.</span>
    Dim i As Integer
    For i = 1 To steps
        <span style="color:blue">' Calculate the x and y coordinates of the eye.</span>
        Dim x As Double
        Dim y As Double
        x = eyeDistance * Cos(i / steps * (2 * pi))
        y = eyeDistance * Sin(i / steps * (2 * pi))
        
        <span style="color:blue">' Set the eye with a hard coded z value.</span>
        cam.Eye = tg.CreatePoint(x, y, 3)
        
        <span style="color:blue">' Define the up vector as positive z.</span>
        cam.UpVector = tg.CreateUnitVector(0, 0, 1)
        
        <span style="color:blue">' Apply the current camera definition to the view.</span>
        cam.ApplyWithoutTransition
    Next</pre>
      </div>
    </div><br><br><div id="CopyrightNotice" style="display:none;">
      <hr>
      <table width="100%" style="font-size:15">
        <tr>
          <td align="left">
                Â© Copyright 2025 Autodesk, Inc.
              </td>
          <td align="right"><a href="mailto:mfg.api.help.comments@autodesk.com?subject=Inventor%202026%20API%20Help%20(DriveCamera%20Sample%20Help%20Topic)">Comment on this page.</a></td>
        </tr>
      </table>
    </div>
  </body>
</html>