<html>
  <head>
    <META http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="topic-type" content="reference-adsk">
    <meta name="helpsystempath" content="/view/INVNTOR/2026/ENU/">
    <link rel="canonical" href="/cloudhelp/2026/ENU/Inventor-API/files/ErrorManager_Sample.htm#!">
    <meta name="product" content="INVNTOR">
    <meta name="release" content="2026">
    <meta name="book" content="Developer">
    <meta name="component" content="Inventor-API">
    <meta name="created" content="">
    <meta name="user-comments" content="enable">
    <meta name="contextid" content="ErrorManager_Sample">
    <meta name="description" content="Using Inventor's error dialog Sample">
    <meta name="topicid" content="ErrorManager_Sample">
    <meta name="experiencelevel" content="expert">
    <meta name="audience" content="programmer">
    <meta name="language" content="ENU">
    <title>Using Inventor's error dialog</title>
    <link rel="stylesheet" href="../Style/jquery-ui.css"><script src="../Scripts/jquery-1.11.1.js"></script><script src="../Scripts/jquery-ui.js"></script><link rel="stylesheet" type="text/css" href="../Style/APIHelp-chm.css">
    <link rel="stylesheet" type="text/css" href="/view/clientframework/client.css"><script type="text/javascript" src="/view/clientframework/client.js"></script><script>
          // This turns on the display of the copyright notice which is not visible by default.
          // Because the head is removed when used in the web help, this function will only exists
          // when the chm help is being created.
          window.onload = function() {
          copyrightElement = document.getElementById('CopyrightNotice');
          copyrightElement.style.display = 'block';
          };
        </script><script>
          $(function() {
          $( "#tabs" ).tabs();
          });
        </script></head>
  <body><script>
          function copyCode(language) {
          // Get the pre element for the specified language.
          var preElement = document.getElementById(language);

          // Get the text from the element and copy it to the clipboard.
          var preText = preElement.innerText;

          var isIE = /*@cc_on!@*/false || !!document.documentMode;

          if (isIE)
          {
            window.clipboardData.setData('Text', preText);
          }
          else
          {
            navigator.clipboard.writeText(preText);
          }

          //alert("Code copied to clipboard");
          }
        </script><link rel="stylesheet" type="text/css" href="../Style/APIHelp.css">
    <h1 class="api">Using Inventor's error dialog</h1>
    <h2 class="api">
          Description
        </h2>Demonstrates using Inventor's error dialog.<h2 class="api">
          Code Samples
        </h2>
    <div id="tabs">
      <ul>
        <li><a href="#VBA">VBA</a></li>
        <li><a href="#iLogic">iLogic</a></li>
      </ul>
      <div id="VBA" class="api-code">
        <table width="100%" style="font-size:15">
          <tr>
            <td align="right"><button onclick="copyCode('VBA_code')" class="copy-code">Copy Code</button></td>
          </tr>
        </table>
        <pre class="api-code" id="VBA_code">Public Sub ErrorDialog()
    <span style="color:blue">' Create a new part document</span>
    Dim oPartDoc As PartDocument
    Set oPartDoc = ThisApplication.Documents.Add(kPartDocumentObject)

    Dim oCompDef As PartComponentDefinition
    Set oCompDef = oPartDoc.ComponentDefinition

    Dim oSketch As PlanarSketch
    Set oSketch = oCompDef.Sketches.Add(oCompDef.WorkPlanes(3))

    Dim oTransGeom As TransientGeometry
    Set oTransGeom = ThisApplication.TransientGeometry

    <span style="color:blue">' Draw a 4cm x 3cm rectangle with the corner at (0,0)</span>
    Dim oRectangleLines As SketchEntitiesEnumerator
    Set oRectangleLines = oSketch.SketchLines.AddAsTwoPointRectangle( _
                                oTransGeom.CreatePoint2d(0, 0), _
                                oTransGeom.CreatePoint2d(4, 3))

    <span style="color:blue">' Create a profile.</span>
    Dim oProfile As Profile
    Set oProfile = oSketch.Profiles.AddForSolid

    <span style="color:blue">' Create a base extrusion 1cm thick.</span>
    Dim oExtrudeDef As ExtrudeDefinition
    Set oExtrudeDef = oCompDef.Features.ExtrudeFeatures.CreateExtrudeDefinition(oProfile, kNewBodyOperation)
    Call oExtrudeDef.SetDistanceExtent(1, kNegativeExtentDirection)
    Dim oExtrude As ExtrudeFeature
    Set oExtrude = oCompDef.Features.ExtrudeFeatures.Add(oExtrudeDef)

    Dim oErrorMgr As ErrorManager
    Set oErrorMgr = ThisApplication.ErrorManager

    Dim oMessageSection As MessageSection
    Set oMessageSection = oErrorMgr.StartMessageSection

    On Error Resume Next

    Dim oTransaction As Transaction
    Set oTransaction = ThisApplication.TransactionManager.StartTransaction(oPartDoc, "Edit Feature")

    <span style="color:blue">' Delete all sketch lines making the sketch profile invalid.</span>
    Dim oSketchLine As SketchLine
    For Each oSketchLine In oRectangleLines
        oSketchLine.Delete
    Next

    oPartDoc.Update

    If oMessageSection.HasErrors Or oMessageSection.HasWarnings Then
        <span style="color:blue">' End section by adopting all messages in section</span>
        Call oMessageSection.AdoptMessages("Feature edit failed", True)
        
        <span style="color:blue">' Display the messages</span>
        Dim kButtonType As ButtonTypeEnum
        kButtonType = oErrorMgr.Show("Sample of Feature Edit Error", True, False)

        If kButtonType = kAcceptButtonType Then
            <span style="color:blue">' Go through with the invalid edit if user accepts</span>
            oTransaction.End
        Else
            oTransaction.Abort
        End If
    Else
        <span style="color:blue">' End section by clearing all messages in section</span>
        oMessageSection.ClearMessages
        oTransaction.End
    End If
End Sub</pre>
      </div>
      <div id="iLogic" class="api-code">
        <table width="100%" style="font-size:15">
          <tr>
            <td align="right"><button onclick="copyCode('iLogic_code')" class="copy-code">Copy Code</button></td>
          </tr>
        </table>
        <pre class="api-code" id="iLogic_code">    <span style="color:blue">' Create a new part document</span>
    Dim oPartDoc As PartDocument
    oPartDoc = ThisApplication.Documents.Add(kPartDocumentObject)

    Dim oCompDef As PartComponentDefinition
    oCompDef = oPartDoc.ComponentDefinition

    Dim oSketch As PlanarSketch
    oSketch = oCompDef.Sketches.Add(oCompDef.WorkPlanes(3))

    Dim oTransGeom As TransientGeometry
    oTransGeom = ThisApplication.TransientGeometry

    <span style="color:blue">' Draw a 4cm x 3cm rectangle with the corner at (0,0)</span>
    Dim oRectangleLines As SketchEntitiesEnumerator
    oRectangleLines = oSketch.SketchLines.AddAsTwoPointRectangle( _
                                oTransGeom.CreatePoint2d(0, 0), _
                                oTransGeom.CreatePoint2d(4, 3))

    <span style="color:blue">' Create a profile.</span>
    Dim oProfile As Profile
    oProfile = oSketch.Profiles.AddForSolid

    <span style="color:blue">' Create a base extrusion 1cm thick.</span>
    Dim oExtrudeDef As ExtrudeDefinition
    oExtrudeDef = oCompDef.Features.ExtrudeFeatures.CreateExtrudeDefinition(oProfile, kNewBodyOperation)
    Call oExtrudeDef.SetDistanceExtent(1, kNegativeExtentDirection)
    Dim oExtrude As ExtrudeFeature
    oExtrude = oCompDef.Features.ExtrudeFeatures.Add(oExtrudeDef)

    Dim oErrorMgr As ErrorManager
    oErrorMgr = ThisApplication.ErrorManager

    Dim oMessageSection As MessageSection
    oMessageSection = oErrorMgr.StartMessageSection

    On Error Resume Next

    Dim oTransaction As Transaction
    oTransaction = ThisApplication.TransactionManager.StartTransaction(oPartDoc, "Edit Feature")

    <span style="color:blue">' Delete all sketch lines making the sketch profile invalid.</span>
    Dim oSketchLine As SketchLine
    For Each oSketchLine In oRectangleLines
        oSketchLine.Delete
    Next

    oPartDoc.Update

    If oMessageSection.HasErrors Or oMessageSection.HasWarnings Then
        <span style="color:blue">' End section by adopting all messages in section</span>
        Call oMessageSection.AdoptMessages("Feature edit failed", True)
        
	<span style="color:blue">' Temporarily enable dialogs.</span>
	ThisApplication.SilentOperation = False
		
        <span style="color:blue">' Display the messages</span>
        Dim kButtonType As ButtonTypeEnum
        kButtonType = oErrorMgr.Show("Sample of Feature Edit Error", True, False)

        If kButtonType = kAcceptButtonType Then
            <span style="color:blue">' Go through with the invalid edit if user accepts</span>
            oTransaction.End
        Else
            oTransaction.Abort
        End If
    Else
        <span style="color:blue">' End section by clearing all messages in section</span>
        oMessageSection.ClearMessages
        oTransaction.End
    End If</pre>
      </div>
    </div><br><br><div id="CopyrightNotice" style="display:none;">
      <hr>
      <table width="100%" style="font-size:15">
        <tr>
          <td align="left">
                Â© Copyright 2025 Autodesk, Inc.
              </td>
          <td align="right"><a href="mailto:mfg.api.help.comments@autodesk.com?subject=Inventor%202026%20API%20Help%20(ErrorManager%20Sample%20Help%20Topic)">Comment on this page.</a></td>
        </tr>
      </table>
    </div>
  </body>
</html>