<html>
  <head>
    <META http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="topic-type" content="reference-adsk">
    <meta name="helpsystempath" content="/view/INVNTOR/2026/ENU/">
    <link rel="canonical" href="/cloudhelp/2026/ENU/Inventor-API/files/GraphicsPrimitive_SetViewSpaceAnchor_Sample.htm#!">
    <meta name="product" content="INVNTOR">
    <meta name="release" content="2026">
    <meta name="book" content="Developer">
    <meta name="component" content="Inventor-API">
    <meta name="created" content="">
    <meta name="user-comments" content="enable">
    <meta name="contextid" content="GraphicsPrimitive_SetViewSpaceAnchor_Sample">
    <meta name="description" content="Anchored Client Grahics Sample">
    <meta name="topicid" content="GraphicsPrimitive_SetViewSpaceAnchor_Sample">
    <meta name="experiencelevel" content="expert">
    <meta name="audience" content="programmer">
    <meta name="language" content="ENU">
    <title>Anchored Client Grahics</title>
    <link rel="stylesheet" href="../Style/jquery-ui.css"><script src="../Scripts/jquery-1.11.1.js"></script><script src="../Scripts/jquery-ui.js"></script><link rel="stylesheet" type="text/css" href="../Style/APIHelp-chm.css">
    <link rel="stylesheet" type="text/css" href="/view/clientframework/client.css"><script type="text/javascript" src="/view/clientframework/client.js"></script><script>
          // This turns on the display of the copyright notice which is not visible by default.
          // Because the head is removed when used in the web help, this function will only exists
          // when the chm help is being created.
          window.onload = function() {
          copyrightElement = document.getElementById('CopyrightNotice');
          copyrightElement.style.display = 'block';
          };
        </script><script>
          $(function() {
          $( "#tabs" ).tabs();
          });
        </script></head>
  <body><script>
          function copyCode(language) {
          // Get the pre element for the specified language.
          var preElement = document.getElementById(language);

          // Get the text from the element and copy it to the clipboard.
          var preText = preElement.innerText;

          var isIE = /*@cc_on!@*/false || !!document.documentMode;

          if (isIE)
          {
            window.clipboardData.setData('Text', preText);
          }
          else
          {
            navigator.clipboard.writeText(preText);
          }

          //alert("Code copied to clipboard");
          }
        </script><link rel="stylesheet" type="text/css" href="../Style/APIHelp.css">
    <h1 class="api">Anchored Client Grahics</h1>
    <h2 class="api">
          Description
        </h2>This sample demonstrates the creation of client graphics that is fully anchored in a view.<h2 class="api">
          Code Samples
        </h2>
    <div id="tabs">
      <ul>
        <li><a href="#VBA">VBA</a></li>
        <li><a href="#iLogic">iLogic</a></li>
      </ul>
      <div id="VBA" class="api-code">This sample anchors some text graphics relative to the top-left corner of the view. Open a part or an assembly document and run the following sample.<table width="100%" style="font-size:15">
          <tr>
            <td align="right"><button onclick="copyCode('VBA_code')" class="copy-code">Copy Code</button></td>
          </tr>
        </table>
        <pre class="api-code" id="VBA_code">Public Sub AnchoredClientGraphics()
  <span style="color:blue">' Set a reference to the document.</span>
  Dim oDoc As Document
  Set oDoc = ThisApplication.ActiveDocument

  <span style="color:blue">' Set a reference to the component definition.</span>
  <span style="color:blue">' This assumes that the active document is a part or an assembly.</span>
  Dim oCompDef As ComponentDefinition
  Set oCompDef = oDoc.ComponentDefinition

  <span style="color:blue">' Attempt to get the existing client graphics object. If it exists</span>
  <span style="color:blue">' delete it so the rest of the code can continue as if it never existed.</span>
  Dim oClientGraphics As ClientGraphics
  On Error Resume Next
  Set oClientGraphics = oCompDef.ClientGraphicsCollection.Item("Anchored Text")
  If Err.Number = 0 Then
    oClientGraphics.Delete
  End If
  On Error GoTo 0
  ThisApplication.ActiveView.Update

  <span style="color:blue">' Create a new ClientGraphics object.</span>
  Set oClientGraphics = oCompDef.ClientGraphicsCollection.Add("Anchored Text")

  <span style="color:blue">' Create a graphics node.</span>
  Dim oNode As GraphicsNode
  Set oNode = oClientGraphics.AddNode(1)

  <span style="color:blue">' Create text graphics.</span>
  Dim oTextGraphics As TextGraphics
  Set oTextGraphics = oNode.AddTextGraphics

  <span style="color:blue">' Set the properties of the text.</span>
  oTextGraphics.Text = "Anchored text."
  oTextGraphics.Bold = True
  oTextGraphics.FontSize = 30
  Call oTextGraphics.PutTextColor(0, 255, 0)

  Dim oAnchorPoint As Point
  Set oAnchorPoint = ThisApplication.TransientGeometry.CreatePoint(1, 1, 1)

  <span style="color:blue">' Set the text's anchor in model space.</span>
  oTextGraphics.Anchor = oAnchorPoint

  <span style="color:blue">' Anchor the text graphics in the view.</span>
  Call oTextGraphics.SetViewSpaceAnchor( _
      oAnchorPoint, ThisApplication.TransientGeometry.CreatePoint2d(30, 30), _
      kTopLeftViewCorner)

  <span style="color:blue">' Update the view to see the text.</span>
  ThisApplication.ActiveView.Update
End Sub</pre>
      </div>
      <div id="iLogic" class="api-code">This sample anchors some text graphics relative to the top-left corner of the view. Open a part or an assembly document and run the following sample.<table width="100%" style="font-size:15">
          <tr>
            <td align="right"><button onclick="copyCode('iLogic_code')" class="copy-code">Copy Code</button></td>
          </tr>
        </table>
        <pre class="api-code" id="iLogic_code">    <span style="color:blue">' Set a reference to the document.</span>
  Dim oDoc As Document
  oDoc = ThisApplication.ActiveDocument

  <span style="color:blue">' Set a reference to the component definition.</span>
  <span style="color:blue">' This assumes that the active document is a part or an assembly.</span>
  Dim oCompDef As ComponentDefinition
  oCompDef = oDoc.ComponentDefinition

  <span style="color:blue">' Attempt to get the existing client graphics object. If it exists</span>
  <span style="color:blue">' delete it so the rest of the code can continue as if it never existed.</span>
  Dim oClientGraphics As ClientGraphics
  On Error Resume Next
  oClientGraphics = oCompDef.ClientGraphicsCollection.Item("Anchored Text")
  If Err.Number = 0 Then
    oClientGraphics.Delete
  End If
  On Error GoTo 0
  ThisApplication.ActiveView.Update

  <span style="color:blue">' Create a new ClientGraphics object.</span>
  oClientGraphics = oCompDef.ClientGraphicsCollection.Add("Anchored Text")

  <span style="color:blue">' Create a graphics node.</span>
  Dim oNode As GraphicsNode
  oNode = oClientGraphics.AddNode(1)

  <span style="color:blue">' Create text graphics.</span>
  Dim oTextGraphics As TextGraphics
  oTextGraphics = oNode.AddTextGraphics

  <span style="color:blue">' Set the properties of the text.</span>
  oTextGraphics.Text = "Anchored text."
  oTextGraphics.Bold = True
  oTextGraphics.FontSize = 30
  Call oTextGraphics.PutTextColor(0, 255, 0)

  Dim oAnchorPoint As Point
  oAnchorPoint = ThisApplication.TransientGeometry.CreatePoint(1, 1, 1)

  <span style="color:blue">' Set the text's anchor in model space.</span>
  oTextGraphics.Anchor = oAnchorPoint

  <span style="color:blue">' Anchor the text graphics in the view.</span>
  Call oTextGraphics.SetViewSpaceAnchor( _
      oAnchorPoint, ThisApplication.TransientGeometry.CreatePoint2d(30, 30), _
      kTopLeftViewCorner)

  <span style="color:blue">' Update the view to see the text.</span>
  ThisApplication.ActiveView.Update</pre>
      </div>
    </div><br><br><div id="CopyrightNotice" style="display:none;">
      <hr>
      <table width="100%" style="font-size:15">
        <tr>
          <td align="left">
                Â© Copyright 2025 Autodesk, Inc.
              </td>
          <td align="right"><a href="mailto:mfg.api.help.comments@autodesk.com?subject=Inventor%202026%20API%20Help%20(GraphicsPrimitive_SetViewSpaceAnchor%20Sample%20Help%20Topic)">Comment on this page.</a></td>
        </tr>
      </table>
    </div>
  </body>
</html>