<html>
  <head>
    <META http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="topic-type" content="reference-adsk">
    <meta name="helpsystempath" content="/view/INVNTOR/2026/ENU/">
    <link rel="canonical" href="/cloudhelp/2026/ENU/Inventor-API/files/GraphicsNode_AddLineGraphics_Sample.htm#!">
    <meta name="product" content="INVNTOR">
    <meta name="release" content="2026">
    <meta name="book" content="Developer">
    <meta name="component" content="Inventor-API">
    <meta name="created" content="">
    <meta name="user-comments" content="enable">
    <meta name="contextid" content="GraphicsNode_AddLineGraphics_Sample">
    <meta name="description" content="Client Graphics - Line Sample">
    <meta name="topicid" content="GraphicsNode_AddLineGraphics_Sample">
    <meta name="experiencelevel" content="expert">
    <meta name="audience" content="programmer">
    <meta name="language" content="ENU">
    <title>Client Graphics - Line</title>
    <link rel="stylesheet" href="../Style/jquery-ui.css"><script src="../Scripts/jquery-1.11.1.js"></script><script src="../Scripts/jquery-ui.js"></script><link rel="stylesheet" type="text/css" href="../Style/APIHelp-chm.css">
    <link rel="stylesheet" type="text/css" href="/view/clientframework/client.css"><script type="text/javascript" src="/view/clientframework/client.js"></script><script>
          // This turns on the display of the copyright notice which is not visible by default.
          // Because the head is removed when used in the web help, this function will only exists
          // when the chm help is being created.
          window.onload = function() {
          copyrightElement = document.getElementById('CopyrightNotice');
          copyrightElement.style.display = 'block';
          };
        </script><script>
          $(function() {
          $( "#tabs" ).tabs();
          });
        </script></head>
  <body><script>
          function copyCode(language) {
          // Get the pre element for the specified language.
          var preElement = document.getElementById(language);

          // Get the text from the element and copy it to the clipboard.
          var preText = preElement.innerText;

          var isIE = /*@cc_on!@*/false || !!document.documentMode;

          if (isIE)
          {
            window.clipboardData.setData('Text', preText);
          }
          else
          {
            navigator.clipboard.writeText(preText);
          }

          //alert("Code copied to clipboard");
          }
        </script><link rel="stylesheet" type="text/css" href="../Style/APIHelp.css">
    <h1 class="api">Client Graphics - Line</h1>
    <h2 class="api">
          Description
        </h2>This sample demonstrates the creation of custom graphics using LineGraphics and LineStripGraphics. The same set of coordinate data is used for both types of graphics. Line graphics use two coordinates to define a line, and then the next two coordinates to define the next line, and so on through the defined coordinates. For the data provided, this results in gaps in the drawn curve. Line strips use the first two coordinates to define the first line and then the last point of the first line becomes the first point of the second line and the next coordinate is used as the end point of the second line. This results in the set of points being connected by a continuous set of lines, drawing a continuous curve. This sample also demonstrates two methods of defining the color for client graphics. In one case it uses an existing appearance asset, and in the other, it explicitly defines a color and assigns it. To use the sample you need to have an assembly or part document open. The program has two behaviors: the first time it is run it will draw the graphics. The second time it is run it deletes the previously drawn graphics.<h2 class="api">
          Code Samples
        </h2>
    <div id="tabs">
      <ul>
        <li><a href="#VBA">VBA</a></li>
        <li><a href="#iLogic">iLogic</a></li>
      </ul>
      <div id="VBA" class="api-code">
        <table width="100%" style="font-size:15">
          <tr>
            <td align="right"><button onclick="copyCode('VBA_code')" class="copy-code">Copy Code</button></td>
          </tr>
        </table>
        <pre class="api-code" id="VBA_code">Public Sub DrawCustomLines()
    Dim oDoc As Document
    Set oDoc = ThisApplication.ActiveDocument

    <span style="color:blue">' Set a reference to component definition of the active document.</span>
    <span style="color:blue">' This assumes that a part or assembly document is active.</span>
    Dim oCompDef As ComponentDefinition
    Set oCompDef = ThisApplication.ActiveDocument.ComponentDefinition
    
    <span style="color:blue">' Check to see if the test graphics data object already exists.</span>
    <span style="color:blue">' If it does clean up by removing all associated of the client graphics</span>
    <span style="color:blue">' from the document.  If it doesn't create it.</span>
    On Error Resume Next
    Dim oGraphicsData As GraphicsDataSets
    Set oGraphicsData = oDoc.GraphicsDataSetsCollection.Item("SampleGraphicsID")
    If Err.Number = 0 Then
        On Error GoTo 0
        <span style="color:blue">' An existing client graphics object was successfully obtained so clean up.</span>
        oGraphicsData.Delete
        oCompDef.ClientGraphicsCollection.Item("SampleGraphicsID").Delete
    
        <span style="color:blue">' update the display to see the results.</span>
        ThisApplication.ActiveView.Update
    Else
        Err.Clear
        On Error GoTo 0
        
        <span style="color:blue">' Set a reference to the transient geometry object for user later.</span>
        Dim oTransGeom As TransientGeometry
        Set oTransGeom = ThisApplication.TransientGeometry
    
        <span style="color:blue">' Create a graphics data set object.  This object contains all of the</span>
        <span style="color:blue">' information used to define the graphics.</span>
        Dim oDataSets As GraphicsDataSets
        Set oDataSets = oDoc.GraphicsDataSetsCollection.Add("SampleGraphicsID")
        
        <span style="color:blue">' Create a coordinate set.</span>
        Dim oCoordSet As GraphicsCoordinateSet
        Set oCoordSet = oDataSets.CreateCoordinateSet(1)
        
        <span style="color:blue">' Create an array that contains coordinates that define a set</span>
        <span style="color:blue">' of outwardly spiraling points.</span>
        Dim oPointCoords(1 To 90) As Double
        Dim i As Long
        Dim dRadius As Double
        dRadius = 1
        Dim dAngle As Double
        For i = 0 To 29
            <span style="color:blue">' Define the X, Y, and Z components of the point.</span>
            oPointCoords(i * 3 + 1) = dRadius * Cos(dAngle)
            oPointCoords(i * 3 + 2) = dRadius * Sin(dAngle)
            oPointCoords(i * 3 + 3) = i / 2
            
            <span style="color:blue">' Increment the angle and radius to create the spiral.</span>
            dRadius = dRadius + 0.25
            dAngle = dAngle + (3.14159265358979 / 6)
        Next
        
        <span style="color:blue">' Assign the points into the coordinate set.</span>
        Call oCoordSet.PutCoordinates(oPointCoords)
        
        <span style="color:blue">' Create the ClientGraphics object.</span>
        Dim oClientGraphics As ClientGraphics
        Set oClientGraphics = oCompDef.ClientGraphicsCollection.Add("SampleGraphicsID")
        
        <span style="color:blue">' Create a new graphics node within the client graphics objects.</span>
        Dim oLineNode As GraphicsNode
        Set oLineNode = oClientGraphics.AddNode(1)
        
        <span style="color:blue">' Create a LineGraphics object within the node.</span>
        Dim oLineSet As LineGraphics
        Set oLineSet = oLineNode.AddLineGraphics
        
        <span style="color:blue">' Assign the coordinate set to the line graphics.</span>
        oLineSet.CoordinateSet = oCoordSet
        
        <span style="color:blue">' Assign a color to the node using an existing appearance asset.</span>
        Dim oAppearance As Asset
        Set oAppearance = oDoc.AppearanceAssets(1)

        oLineNode.Appearance = oAppearance
        
        <span style="color:blue">' Update the view to see the resulting spiral.</span>
        ThisApplication.ActiveView.Update
        
        <span style="color:blue">' Create another graphics node for a line strip.</span>
        Dim oLineStripNode As GraphicsNode
        Set oLineStripNode = oClientGraphics.AddNode(2)
        
        <span style="color:blue">' Create a LineStripGraphics object within the new node.</span>
        Dim oLineStrip As LineStripGraphics
        Set oLineStrip = oLineStripNode.AddLineStripGraphics
        
        <span style="color:blue">' Assign the same coordinate set to the line strip.</span>
        oLineStrip.CoordinateSet = oCoordSet
        
        <span style="color:blue">' Create a color set to use in defining a explicit color to the line strip.</span>
        Dim oColorSet As GraphicsColorSet
        Set oColorSet = oDataSets.CreateColorSet(1)
        
        <span style="color:blue">' Add a single color to the set that is red.</span>
        Call oColorSet.Add(1, 255, 0, 0)
        
        <span style="color:blue">' Assign the color set to the line strip.</span>
        oLineStrip.ColorSet = oColorSet
        
        <span style="color:blue">' The two spirals are currently on top of each other so translate the</span>
        <span style="color:blue">' new one in the x direction so they're side by side.</span>
        Dim oMatrix As Matrix
        Set oMatrix = oLineStripNode.Transformation
        Call oMatrix.SetTranslation(oTransGeom.CreateVector(15, 0, 0))
        oLineStripNode.Transformation = oMatrix
        
        <span style="color:blue">' Update the view to see the resulting spiral.</span>
        ThisApplication.ActiveView.Update
    End If
End Sub</pre>
      </div>
      <div id="iLogic" class="api-code">
        <table width="100%" style="font-size:15">
          <tr>
            <td align="right"><button onclick="copyCode('iLogic_code')" class="copy-code">Copy Code</button></td>
          </tr>
        </table>
        <pre class="api-code" id="iLogic_code">    Dim oDoc As Document
    oDoc = ThisApplication.ActiveDocument

    <span style="color:blue">' Set a reference to component definition of the active document.</span>
    <span style="color:blue">' This assumes that a part or assembly document is active.</span>
    Dim oCompDef As ComponentDefinition
    oCompDef = ThisApplication.ActiveDocument.ComponentDefinition
    
    <span style="color:blue">' Check to see if the test graphics data object already exists.</span>
    <span style="color:blue">' If it does clean up by removing all associated of the client graphics</span>
    <span style="color:blue">' from the document.  If it doesn't create it.</span>
    On Error Resume Next
    Dim oGraphicsData As GraphicsDataSets
    oGraphicsData = oDoc.GraphicsDataSetsCollection.Item("SampleGraphicsID")
    If Err.Number = 0 Then
        On Error GoTo 0
        <span style="color:blue">' An existing client graphics object was successfully obtained so clean up.</span>
        oGraphicsData.Delete
        oCompDef.ClientGraphicsCollection.Item("SampleGraphicsID").Delete
    
        <span style="color:blue">' update the display to see the results.</span>
        ThisApplication.ActiveView.Update
    Else
        Err.Clear
        On Error GoTo 0
        
        <span style="color:blue">' Set a reference to the transient geometry object for user later.</span>
        Dim oTransGeom As TransientGeometry
        oTransGeom = ThisApplication.TransientGeometry
    
        <span style="color:blue">' Create a graphics data set object.  This object contains all of the</span>
        <span style="color:blue">' information used to define the graphics.</span>
        Dim oDataSets As GraphicsDataSets
        oDataSets = oDoc.GraphicsDataSetsCollection.Add("SampleGraphicsID")
        
        <span style="color:blue">' Create a coordinate set.</span>
        Dim oCoordSet As GraphicsCoordinateSet
        oCoordSet = oDataSets.CreateCoordinateSet(1)
        
        <span style="color:blue">' Create an array that contains coordinates that define a set</span>
        <span style="color:blue">' of outwardly spiraling points.</span>
        Dim oPointCoords(0 To 89) As Double
        Dim i As Long
        Dim dRadius As Double
        dRadius = 1
        Dim dAngle As Double
        For i = 0 To 29
            <span style="color:blue">' Define the X, Y, and Z components of the point.</span>
            oPointCoords(i * 3 ) = dRadius * Cos(dAngle)
            oPointCoords(i * 3 + 1) = dRadius * Sin(dAngle)
            oPointCoords(i * 3 + 2) = i / 2
            
            <span style="color:blue">' Increment the angle and radius to create the spiral.</span>
            dRadius = dRadius + 0.25
            dAngle = dAngle + (3.14159265358979 / 6)
        Next
        
        <span style="color:blue">' Assign the points into the coordinate set.</span>
        Call oCoordSet.PutCoordinates(oPointCoords)
        
        <span style="color:blue">' Create the ClientGraphics object.</span>
        Dim oClientGraphics As ClientGraphics
        oClientGraphics = oCompDef.ClientGraphicsCollection.Add("SampleGraphicsID")
        
        <span style="color:blue">' Create a new graphics node within the client graphics objects.</span>
        Dim oLineNode As GraphicsNode
        oLineNode = oClientGraphics.AddNode(1)
        
        <span style="color:blue">' Create a LineGraphics object within the node.</span>
        Dim oLineSet As LineGraphics
        oLineSet = oLineNode.AddLineGraphics
        
        <span style="color:blue">' Assign the coordinate set to the line graphics.</span>
        oLineSet.CoordinateSet = oCoordSet
        
        <span style="color:blue">' Assign a color to the node using an existing appearance asset.</span>
        Dim oAppearance As Asset
        oAppearance = oDoc.AppearanceAssets(1)

        oLineNode.Appearance = oAppearance
        
        <span style="color:blue">' Update the view to see the resulting spiral.</span>
        ThisApplication.ActiveView.Update
        
        <span style="color:blue">' Create another graphics node for a line strip.</span>
        Dim oLineStripNode As GraphicsNode
        oLineStripNode = oClientGraphics.AddNode(2)
        
        <span style="color:blue">' Create a LineStripGraphics object within the new node.</span>
        Dim oLineStrip As LineStripGraphics
        oLineStrip = oLineStripNode.AddLineStripGraphics
        
        <span style="color:blue">' Assign the same coordinate set to the line strip.</span>
        oLineStrip.CoordinateSet = oCoordSet
        
        <span style="color:blue">' Create a color set to use in defining a explicit color to the line strip.</span>
        Dim oColorSet As GraphicsColorSet
        oColorSet = oDataSets.CreateColorSet(1)
        
        <span style="color:blue">' Add a single color to the set that is red.</span>
        Call oColorSet.Add(1, 255, 0, 0)
        
        <span style="color:blue">' Assign the color set to the line strip.</span>
        oLineStrip.ColorSet = oColorSet
        
        <span style="color:blue">' The two spirals are currently on top of each other so translate the</span>
        <span style="color:blue">' new one in the x direction so they're side by side.</span>
        Dim oMatrix As Matrix
        oMatrix = oLineStripNode.Transformation
        Call oMatrix.SetTranslation(oTransGeom.CreateVector(15, 0, 0))
        oLineStripNode.Transformation = oMatrix
        
        <span style="color:blue">' Update the view to see the resulting spiral.</span>
        ThisApplication.ActiveView.Update
    End If</pre>
      </div>
    </div><br><br><div id="CopyrightNotice" style="display:none;">
      <hr>
      <table width="100%" style="font-size:15">
        <tr>
          <td align="left">
                Â© Copyright 2025 Autodesk, Inc.
              </td>
          <td align="right"><a href="mailto:mfg.api.help.comments@autodesk.com?subject=Inventor%202026%20API%20Help%20(GraphicsNode_AddLineGraphics%20Sample%20Help%20Topic)">Comment on this page.</a></td>
        </tr>
      </table>
    </div>
  </body>
</html>