<html>
  <head>
    <META http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="topic-type" content="reference-adsk">
    <meta name="helpsystempath" content="/view/INVNTOR/2026/ENU/">
    <link rel="canonical" href="/cloudhelp/2026/ENU/Inventor-API/files/GraphicsNode_AddSurfaceGraphics_Sample.htm#!">
    <meta name="product" content="INVNTOR">
    <meta name="release" content="2026">
    <meta name="book" content="Developer">
    <meta name="component" content="Inventor-API">
    <meta name="created" content="">
    <meta name="user-comments" content="enable">
    <meta name="contextid" content="GraphicsNode_AddSurfaceGraphics_Sample">
    <meta name="description" content="Client graphics from SAT file body Sample">
    <meta name="topicid" content="GraphicsNode_AddSurfaceGraphics_Sample">
    <meta name="experiencelevel" content="expert">
    <meta name="audience" content="programmer">
    <meta name="language" content="ENU">
    <title>Client graphics from SAT file body</title>
    <link rel="stylesheet" href="../Style/jquery-ui.css"><script src="../Scripts/jquery-1.11.1.js"></script><script src="../Scripts/jquery-ui.js"></script><link rel="stylesheet" type="text/css" href="../Style/APIHelp-chm.css">
    <link rel="stylesheet" type="text/css" href="/view/clientframework/client.css"><script type="text/javascript" src="/view/clientframework/client.js"></script><script>
          // This turns on the display of the copyright notice which is not visible by default.
          // Because the head is removed when used in the web help, this function will only exists
          // when the chm help is being created.
          window.onload = function() {
          copyrightElement = document.getElementById('CopyrightNotice');
          copyrightElement.style.display = 'block';
          };
        </script><script>
          $(function() {
          $( "#tabs" ).tabs();
          });
        </script></head>
  <body><script>
          function copyCode(language) {
          // Get the pre element for the specified language.
          var preElement = document.getElementById(language);

          // Get the text from the element and copy it to the clipboard.
          var preText = preElement.innerText;

          var isIE = /*@cc_on!@*/false || !!document.documentMode;

          if (isIE)
          {
            window.clipboardData.setData('Text', preText);
          }
          else
          {
            navigator.clipboard.writeText(preText);
          }

          //alert("Code copied to clipboard");
          }
        </script><link rel="stylesheet" type="text/css" href="../Style/APIHelp.css">
    <h1 class="api">Client graphics from SAT file body</h1>
    <h2 class="api">
          Description
        </h2>The following sample demonstrates how to display client graphics based on bodies read in from a SAT file.<h2 class="api">
          Code Samples
        </h2>
    <div id="tabs">
      <ul>
        <li><a href="#VBA">VBA</a></li>
        <li><a href="#iLogic">iLogic</a></li>
      </ul>
      <div id="VBA" class="api-code">Make sure you have "C:\temp\block.sat" or change the path in the code below.<table width="100%" style="font-size:15">
          <tr>
            <td align="right"><button onclick="copyCode('VBA_code')" class="copy-code">Copy Code</button></td>
          </tr>
        </table>
        <pre class="api-code" id="VBA_code">Public Sub ClientGraphicsFromSATFileBody()
    <span style="color:blue">' Set a reference to the TransientBRep object</span>
    Dim oTransientBRep As TransientBRep
    Set oTransientBRep = ThisApplication.TransientBRep

    <span style="color:blue">' Get the first body from the specified sat file</span>
    Dim oBody As SurfaceBody
    Set oBody = oTransientBRep.ReadFromFile("C:\temp\block.sat").Item(1)

    <span style="color:blue">' Create a new Part document.</span>
    Dim oPartDoc As PartDocument
    Set oPartDoc = ThisApplication.Documents.Add(kPartDocumentObject)

    <span style="color:blue">' Set a reference to the compdef.</span>
    Dim oCompDef As PartComponentDefinition
    Set oCompDef = oPartDoc.ComponentDefinition

    <span style="color:blue">' Create the ClientGraphics object.</span>
    Dim oClientGraphics As ClientGraphics
    Set oClientGraphics = oCompDef.ClientGraphicsCollection.Add("Sample3DGraphicsID")

    <span style="color:blue">' Create a new graphics node within the client graphics objects.</span>
    Dim oSurfacesNode As GraphicsNode
    Set oSurfacesNode = oClientGraphics.AddNode(1)

    <span style="color:blue">' Create client graphics based on the transient body</span>
    Dim oSurfaceGraphics As SurfaceGraphics
    Set oSurfaceGraphics = oSurfacesNode.AddSurfaceGraphics(oBody)

    <span style="color:blue">' Update the view to see the resulting curves.</span>
    ThisApplication.ActiveView.Update
End Sub</pre>
      </div>
      <div id="iLogic" class="api-code">Make sure you have "C:\temp\block.sat" or change the path in the code below.<table width="100%" style="font-size:15">
          <tr>
            <td align="right"><button onclick="copyCode('iLogic_code')" class="copy-code">Copy Code</button></td>
          </tr>
        </table>
        <pre class="api-code" id="iLogic_code">    <span style="color:blue">' Set a reference to the TransientBRep object</span>
    Dim oTransientBRep As TransientBRep
    oTransientBRep = ThisApplication.TransientBRep

    <span style="color:blue">' Get the first body from the specified sat file</span>
    Dim oBody As SurfaceBody
    oBody = oTransientBRep.ReadFromFile("C:\temp\block.sat").Item(1)

    <span style="color:blue">' Create a new Part document.</span>
    Dim oPartDoc As PartDocument
    oPartDoc = ThisApplication.Documents.Add(kPartDocumentObject)

    <span style="color:blue">' Set a reference to the compdef.</span>
    Dim oCompDef As PartComponentDefinition
    oCompDef = oPartDoc.ComponentDefinition

    <span style="color:blue">' Create the ClientGraphics object.</span>
    Dim oClientGraphics As ClientGraphics
    oClientGraphics = oCompDef.ClientGraphicsCollection.Add("Sample3DGraphicsID")

    <span style="color:blue">' Create a new graphics node within the client graphics objects.</span>
    Dim oSurfacesNode As GraphicsNode
    oSurfacesNode = oClientGraphics.AddNode(1)

    <span style="color:blue">' Create client graphics based on the transient body</span>
    Dim oSurfaceGraphics As SurfaceGraphics
    oSurfaceGraphics = oSurfacesNode.AddSurfaceGraphics(oBody)

    <span style="color:blue">' Update the view to see the resulting curves.</span>
    ThisApplication.ActiveView.Update</pre>
      </div>
    </div><br><br><div id="CopyrightNotice" style="display:none;">
      <hr>
      <table width="100%" style="font-size:15">
        <tr>
          <td align="left">
                Â© Copyright 2025 Autodesk, Inc.
              </td>
          <td align="right"><a href="mailto:mfg.api.help.comments@autodesk.com?subject=Inventor%202026%20API%20Help%20(GraphicsNode_AddSurfaceGraphics%20Sample%20Help%20Topic)">Comment on this page.</a></td>
        </tr>
      </table>
    </div>
  </body>
</html>