<html>
  <head>
    <META http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="topic-type" content="reference-adsk">
    <meta name="helpsystempath" content="/view/INVNTOR/2026/ENU/">
    <link rel="canonical" href="/cloudhelp/2026/ENU/Inventor-API/files/KnitFeature_Sample.htm#!">
    <meta name="product" content="INVNTOR">
    <meta name="release" content="2026">
    <meta name="book" content="Developer">
    <meta name="component" content="Inventor-API">
    <meta name="created" content="">
    <meta name="user-comments" content="enable">
    <meta name="contextid" content="KnitFeature_Sample">
    <meta name="description" content="Adding a new stitch (knit) feature Sample">
    <meta name="topicid" content="KnitFeature_Sample">
    <meta name="experiencelevel" content="expert">
    <meta name="audience" content="programmer">
    <meta name="language" content="ENU">
    <title>Adding a new stitch (knit) feature</title>
    <link rel="stylesheet" href="../Style/jquery-ui.css"><script src="../Scripts/jquery-1.11.1.js"></script><script src="../Scripts/jquery-ui.js"></script><link rel="stylesheet" type="text/css" href="../Style/APIHelp-chm.css">
    <link rel="stylesheet" type="text/css" href="/view/clientframework/client.css"><script type="text/javascript" src="/view/clientframework/client.js"></script><script>
          // This turns on the display of the copyright notice which is not visible by default.
          // Because the head is removed when used in the web help, this function will only exists
          // when the chm help is being created.
          window.onload = function() {
          copyrightElement = document.getElementById('CopyrightNotice');
          copyrightElement.style.display = 'block';
          };
        </script><script>
          $(function() {
          $( "#tabs" ).tabs();
          });
        </script></head>
  <body><script>
          function copyCode(language) {
          // Get the pre element for the specified language.
          var preElement = document.getElementById(language);

          // Get the text from the element and copy it to the clipboard.
          var preText = preElement.innerText;

          var isIE = /*@cc_on!@*/false || !!document.documentMode;

          if (isIE)
          {
            window.clipboardData.setData('Text', preText);
          }
          else
          {
            navigator.clipboard.writeText(preText);
          }

          //alert("Code copied to clipboard");
          }
        </script><link rel="stylesheet" type="text/css" href="../Style/APIHelp.css">
    <h1 class="api">Adding a new stitch (knit) feature</h1>
    <h2 class="api">
          Description
        </h2>This sample demonstrates the creation of a stitch feature (known as the Knit feature in the API). The sample creates two work surfaces using surface extrusions and stitches them together.<h2 class="api">
          Code Samples
        </h2>
    <div id="tabs">
      <ul>
        <li><a href="#VBA">VBA</a></li>
        <li><a href="#iLogic">iLogic</a></li>
      </ul>
      <div id="VBA" class="api-code">
        <table width="100%" style="font-size:15">
          <tr>
            <td align="right"><button onclick="copyCode('VBA_code')" class="copy-code">Copy Code</button></td>
          </tr>
        </table>
        <pre class="api-code" id="VBA_code">Sub StitchFeatureCreate()
    <span style="color:blue">' Create a new part document, using the default part template.</span>
    Dim oPartDoc As PartDocument
    Set oPartDoc = ThisApplication.Documents.Add(kPartDocumentObject, _
                ThisApplication.FileManager.GetTemplateFile(kPartDocumentObject))

    <span style="color:blue">' Set a reference to the component definition.</span>
    Dim oCompDef As PartComponentDefinition
    Set oCompDef = oPartDoc.ComponentDefinition

    <span style="color:blue">' Create a new sketch on the X-Y work plane. Dim oSketch As PlanarSketch</span>
    Dim oSketch As PlanarSketch
    Set oSketch = oCompDef.Sketches.Add(oCompDef.WorkPlanes(3))

    <span style="color:blue">' Set a reference to the transient geometry object.</span>
    Dim oTransGeom As TransientGeometry
    Set oTransGeom = ThisApplication.TransientGeometry

    <span style="color:blue">' Draw two sketch lines that will be used as the</span>
    <span style="color:blue">' open profiles for creating work surfaces.</span>
    Dim oLineOne As SketchLine
    Set oLineOne = oSketch.SketchLines.AddByTwoPoints( _
                                oTransGeom.CreatePoint2d(0, 0), _
                                oTransGeom.CreatePoint2d(2, -2))

    Dim oLineTwo As SketchLine
    Set oLineTwo = oSketch.SketchLines.AddByTwoPoints( _
                                oTransGeom.CreatePoint2d(0, 0), _
                                oTransGeom.CreatePoint2d(-2, -2))
                                
    <span style="color:blue">' Create a profile for the first extrude.</span>
    Dim oProfileOne As Profile
    Set oProfileOne = oSketch.Profiles.AddForSurface(oLineOne)

    <span style="color:blue">' Create an surface extrusion 2 cm thick.</span>
    Dim oExtrudeDef As ExtrudeDefinition
    Set oExtrudeDef = oCompDef.Features.ExtrudeFeatures.CreateExtrudeDefinition(oProfileOne, kSurfaceOperation)
    Call oExtrudeDef.SetDistanceExtent(2, kNegativeExtentDirection)
    Dim oExtrudeOne As ExtrudeFeature
    Set oExtrudeOne = oCompDef.Features.ExtrudeFeatures.Add(oExtrudeDef)

    <span style="color:blue">' Create a profile for the second extrude.</span>
    Dim oProfileTwo As Profile
    Set oProfileTwo = oSketch.Profiles.AddForSurface(oLineTwo)

    <span style="color:blue">' Create an extrusion 2 cm thick.</span>
    Set oExtrudeDef = oCompDef.Features.ExtrudeFeatures.CreateExtrudeDefinition(oProfileTwo, kSurfaceOperation)
    Call oExtrudeDef.SetDistanceExtent(2, kNegativeExtentDirection)
    Dim oExtrudeTwo As ExtrudeFeature
    Set oExtrudeTwo = oCompDef.Features.ExtrudeFeatures.Add(oExtrudeDef)
    
    Dim oSurfaces As ObjectCollection
    Set oSurfaces = ThisApplication.TransientObjects.CreateObjectCollection
    
    <span style="color:blue">' Since we know that the only work surfaces in the document</span>
    <span style="color:blue">' are those created by the above extrusions, use those.</span>
    oSurfaces.Add oCompDef.WorkSurfaces.Item(1)
    oSurfaces.Add oCompDef.WorkSurfaces.Item(2)
    
    <span style="color:blue">' Create a stitch (knit) feature by stitching</span>
    <span style="color:blue">' together the two work surfaces created above.</span>
    Dim oKnitFeature As KnitFeature
    Set oKnitFeature = oCompDef.Features.KnitFeatures.Add(oSurfaces)
End Sub</pre>
      </div>
      <div id="iLogic" class="api-code">
        <table width="100%" style="font-size:15">
          <tr>
            <td align="right"><button onclick="copyCode('iLogic_code')" class="copy-code">Copy Code</button></td>
          </tr>
        </table>
        <pre class="api-code" id="iLogic_code">    <span style="color:blue">' Create a new part document, using the default part template.</span>
    Dim oPartDoc As PartDocument
    oPartDoc = ThisApplication.Documents.Add(kPartDocumentObject, _
                ThisApplication.FileManager.GetTemplateFile(kPartDocumentObject))

    <span style="color:blue">' Set a reference to the component definition.</span>
    Dim oCompDef As PartComponentDefinition
    oCompDef = oPartDoc.ComponentDefinition

    <span style="color:blue">' Create a new sketch on the X-Y work plane. Dim oSketch As PlanarSketch</span>
    Dim oSketch As PlanarSketch
    oSketch = oCompDef.Sketches.Add(oCompDef.WorkPlanes(3))

    <span style="color:blue">' Set a reference to the transient geometry object.</span>
    Dim oTransGeom As TransientGeometry
    oTransGeom = ThisApplication.TransientGeometry

    <span style="color:blue">' Draw two sketch lines that will be used as the</span>
    <span style="color:blue">' open profiles for creating work surfaces.</span>
    Dim oLineOne As SketchLine
    oLineOne = oSketch.SketchLines.AddByTwoPoints( _
                                oTransGeom.CreatePoint2d(0, 0), _
                                oTransGeom.CreatePoint2d(2, -2))

    Dim oLineTwo As SketchLine
    oLineTwo = oSketch.SketchLines.AddByTwoPoints( _
                                oTransGeom.CreatePoint2d(0, 0), _
                                oTransGeom.CreatePoint2d(-2, -2))
                                
    <span style="color:blue">' Create a profile for the first extrude.</span>
    Dim oProfileOne As Profile
    oProfileOne = oSketch.Profiles.AddForSurface(oLineOne)

    <span style="color:blue">' Create an surface extrusion 2 cm thick.</span>
    Dim oExtrudeDef As ExtrudeDefinition
    oExtrudeDef = oCompDef.Features.ExtrudeFeatures.CreateExtrudeDefinition(oProfileOne, kSurfaceOperation)
    Call oExtrudeDef.SetDistanceExtent(2, kNegativeExtentDirection)
    Dim oExtrudeOne As ExtrudeFeature
    oExtrudeOne = oCompDef.Features.ExtrudeFeatures.Add(oExtrudeDef)

    <span style="color:blue">' Create a profile for the second extrude.</span>
    Dim oProfileTwo As Profile
    oProfileTwo = oSketch.Profiles.AddForSurface(oLineTwo)

    <span style="color:blue">' Create an extrusion 2 cm thick.</span>
    oExtrudeDef = oCompDef.Features.ExtrudeFeatures.CreateExtrudeDefinition(oProfileTwo, kSurfaceOperation)
    Call oExtrudeDef.SetDistanceExtent(2, kNegativeExtentDirection)
    Dim oExtrudeTwo As ExtrudeFeature
    oExtrudeTwo = oCompDef.Features.ExtrudeFeatures.Add(oExtrudeDef)
    
    Dim oSurfaces As ObjectCollection
    oSurfaces = ThisApplication.TransientObjects.CreateObjectCollection
    
    <span style="color:blue">' Since we know that the only work surfaces in the document</span>
    <span style="color:blue">' are those created by the above extrusions, use those.</span>
    oSurfaces.Add(oCompDef.WorkSurfaces.Item(1))
    oSurfaces.Add(oCompDef.WorkSurfaces.Item(2))
    
    <span style="color:blue">' Create a stitch (knit) feature by stitching</span>
    <span style="color:blue">' together the two work surfaces created above.</span>
    Dim oKnitFeature As KnitFeature
    oKnitFeature = oCompDef.Features.KnitFeatures.Add(oSurfaces)</pre>
      </div>
    </div><br><br><div id="CopyrightNotice" style="display:none;">
      <hr>
      <table width="100%" style="font-size:15">
        <tr>
          <td align="left">
                Â© Copyright 2025 Autodesk, Inc.
              </td>
          <td align="right"><a href="mailto:mfg.api.help.comments@autodesk.com?subject=Inventor%202026%20API%20Help%20(KnitFeature%20Sample%20Help%20Topic)">Comment on this page.</a></td>
        </tr>
      </table>
    </div>
  </body>
</html>