<html>
  <head>
    <META http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="topic-type" content="reference-adsk">
    <meta name="helpsystempath" content="/view/INVNTOR/2026/ENU/">
    <link rel="canonical" href="/cloudhelp/2026/ENU/Inventor-API/files/Line_IsColinearTo_Sample.htm#!">
    <meta name="product" content="INVNTOR">
    <meta name="release" content="2026">
    <meta name="book" content="Developer">
    <meta name="component" content="Inventor-API">
    <meta name="created" content="">
    <meta name="user-comments" content="enable">
    <meta name="contextid" content="Line_IsColinearTo_Sample">
    <meta name="description" content="Is cylindrical face interior or exterior? Sample">
    <meta name="topicid" content="Line_IsColinearTo_Sample">
    <meta name="experiencelevel" content="expert">
    <meta name="audience" content="programmer">
    <meta name="language" content="ENU">
    <title>Is cylindrical face interior or exterior?</title>
    <link rel="stylesheet" href="../Style/jquery-ui.css"><script src="../Scripts/jquery-1.11.1.js"></script><script src="../Scripts/jquery-ui.js"></script><link rel="stylesheet" type="text/css" href="../Style/APIHelp-chm.css">
    <link rel="stylesheet" type="text/css" href="/view/clientframework/client.css"><script type="text/javascript" src="/view/clientframework/client.js"></script><script>
          // This turns on the display of the copyright notice which is not visible by default.
          // Because the head is removed when used in the web help, this function will only exists
          // when the chm help is being created.
          window.onload = function() {
          copyrightElement = document.getElementById('CopyrightNotice');
          copyrightElement.style.display = 'block';
          };
        </script><script>
          $(function() {
          $( "#tabs" ).tabs();
          });
        </script></head>
  <body><script>
          function copyCode(language) {
          // Get the pre element for the specified language.
          var preElement = document.getElementById(language);

          // Get the text from the element and copy it to the clipboard.
          var preText = preElement.innerText;

          var isIE = /*@cc_on!@*/false || !!document.documentMode;

          if (isIE)
          {
            window.clipboardData.setData('Text', preText);
          }
          else
          {
            navigator.clipboard.writeText(preText);
          }

          //alert("Code copied to clipboard");
          }
        </script><link rel="stylesheet" type="text/css" href="../Style/APIHelp.css">
    <h1 class="api">Is cylindrical face interior or exterior?</h1>
    <h2 class="api">
          Description
        </h2>This sample shows how to determine whether the selected cylindircal face is an exterior face or an interior (hollow) face.<h2 class="api">
          Code Samples
        </h2>
    <div id="tabs">
      <ul>
        <li><a href="#VBA">VBA</a></li>
        <li><a href="#iLogic">iLogic</a></li>
      </ul>
      <div id="VBA" class="api-code">Before running the sample, select a cylindrical face.<table width="100%" style="font-size:15">
          <tr>
            <td align="right"><button onclick="copyCode('VBA_code')" class="copy-code">Copy Code</button></td>
          </tr>
        </table>
        <pre class="api-code" id="VBA_code">Public Sub IsCylindricalFaceInterior()
    Dim oDoc As Document
    Set oDoc = ThisApplication.ActiveDocument
    
    If Not Typeof oDoc.SelectSet(1) Is Face Then
        MsgBox "A face must be selected."
        Exit Sub
    End If
    
    Dim oFace As Face
    Set oFace = oDoc.SelectSet(1)
    
    If Not oFace.SurfaceType = kCylinderSurface Then
        MsgBox "A cylindrical face must be selected."
        Exit Sub
    End If
    
    Dim oCylinder As Cylinder
    Set oCylinder = oFace.Geometry
    
    Dim params(1) As Double
    params(0) = 0.5
    params(1) = 0.5
    
    <span style="color:blue">' Get point on surface at param .5,.5</span>
    Dim points(2) As Double
    Call oFace.Evaluator.GetPointAtParam(params, points)
    
    <span style="color:blue">' Create point object</span>
    Dim oPoint As point
    Set oPoint = ThisApplication.TransientGeometry.CreatePoint(points(0), points(1), points(2))
        
    <span style="color:blue">' Get normal at this point</span>
    Dim normals(2) As Double
    Call oFace.Evaluator.GetNormal(params, normals)
    
    <span style="color:blue">' Create normal vector object</span>
    Dim oNormal As Vector
    Set oNormal = ThisApplication.TransientGeometry.CreateVector(normals(0), normals(1), normals(2))
    
    <span style="color:blue">' Scale vector by radius of the cylinder</span>
    oNormal.ScaleBy oCylinder.Radius
    
    <span style="color:blue">' Find the sampler point on the normal by adding the</span>
    <span style="color:blue">' scaled normal vector to the point at .5,.5 param.</span>
    Dim oSamplePoint As point
    Set oSamplePoint = oPoint
    
    oSamplePoint.TranslateBy oNormal
    
    <span style="color:blue">' Check if the sample point lies on the cylinder axis.</span>
    <span style="color:blue">' If it does, we have a hollow face.</span>
   
    <span style="color:blue">' Create a line describing the cylinder axis</span>
    Dim oAxisLine As Line
    Set oAxisLine = ThisApplication.TransientGeometry.CreateLine _
        (oCylinder.BasePoint, oCylinder.AxisVector.AsVector)
        
    <span style="color:blue">'Create a line parallel to the axis passing thru the sample point.</span>
    Dim oSampleLine As Line
    Set oSampleLine = ThisApplication.TransientGeometry.CreateLine _
        (oSamplePoint, oCylinder.AxisVector.AsVector)
        
    If oSampleLine.IsColinearTo(oAxisLine) Then
        MsgBox "Interior face."
    Else
        MsgBox "Exterior face."
    End If
End Sub</pre>
      </div>
      <div id="iLogic" class="api-code">Before running the sample, select a cylindrical face.<table width="100%" style="font-size:15">
          <tr>
            <td align="right"><button onclick="copyCode('iLogic_code')" class="copy-code">Copy Code</button></td>
          </tr>
        </table>
        <pre class="api-code" id="iLogic_code">    Dim oDoc As Document
    oDoc = ThisApplication.ActiveDocument
    
    If oDoc.SelectSet.Count = 0 Then
        MsgBox("A face must be selected.")
        Exit Sub
    Else
        If oDoc.SelectSet.Item(1).Type &lt;&gt; kFaceObject Then
            MsgBox("A face must be selected.")
            Exit Sub
        End If
    End If
    
    Dim oFace As Face
    oFace = oDoc.SelectSet(1)
    
    If Not oFace.SurfaceType = kCylinderSurface Then
        MsgBox("A cylindrical face must be selected.")
        Exit Sub
    End If
    
    Dim oCylinder As Cylinder
    oCylinder = oFace.Geometry
    
    Dim params(1) As Double
    params(0) = 0.5
    params(1) = 0.5
    
    <span style="color:blue">' Get point on surface at param .5,.5</span>
    Dim points() As Double = New Double() {}
    Call oFace.Evaluator.GetPointAtParam(params, points)
    
    <span style="color:blue">' Create point object</span>
    Dim oPoint As point
    oPoint = ThisApplication.TransientGeometry.CreatePoint(points(0), points(1), points(2))
        
    <span style="color:blue">' Get normal at this point</span>
    Dim normals() As Double = New Double() {}
    Call oFace.Evaluator.GetNormal(params, normals)
    
    <span style="color:blue">' Create normal vector object</span>
    Dim oNormal As Vector
    oNormal = ThisApplication.TransientGeometry.CreateVector(normals(0), normals(1), normals(2))
    
    <span style="color:blue">' Scale vector by radius of the cylinder</span>
    oNormal.ScaleBy(oCylinder.Radius)
    
    <span style="color:blue">' Find the sampler point on the normal by adding the</span>
    <span style="color:blue">' scaled normal vector to the point at .5,.5 param.</span>
    Dim oSamplePoint As point
    oSamplePoint = oPoint
    
    oSamplePoint.TranslateBy(oNormal)
    
    <span style="color:blue">' Check if the sample point lies on the cylinder axis.</span>
    <span style="color:blue">' If it does, we have a hollow face.</span>
   
    <span style="color:blue">' Create a line describing the cylinder axis</span>
    Dim oAxisLine As Line
    oAxisLine = ThisApplication.TransientGeometry.CreateLine _
        (oCylinder.BasePoint, oCylinder.AxisVector.AsVector)
        
    <span style="color:blue">'Create a line parallel to the axis passing thru the sample point.</span>
    Dim oSampleLine As Line
    oSampleLine = ThisApplication.TransientGeometry.CreateLine _
        (oSamplePoint, oCylinder.AxisVector.AsVector)
        
    If oSampleLine.IsColinearTo(oAxisLine) Then
        MsgBox("Interior face.")
    Else
        MsgBox("Exterior face.")
    End If</pre>
      </div>
    </div><br><br><div id="CopyrightNotice" style="display:none;">
      <hr>
      <table width="100%" style="font-size:15">
        <tr>
          <td align="left">
                Â© Copyright 2025 Autodesk, Inc.
              </td>
          <td align="right"><a href="mailto:mfg.api.help.comments@autodesk.com?subject=Inventor%202026%20API%20Help%20(Line_IsColinearTo%20Sample%20Help%20Topic)">Comment on this page.</a></td>
        </tr>
      </table>
    </div>
  </body>
</html>