<html>
  <head>
    <META http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="topic-type" content="reference-adsk">
    <meta name="helpsystempath" content="/view/INVNTOR/2026/ENU/">
    <link rel="canonical" href="/cloudhelp/2026/ENU/Inventor-API/files/LoftedFlangeFeatures_Add_Sample.htm#!">
    <meta name="product" content="INVNTOR">
    <meta name="release" content="2026">
    <meta name="book" content="Developer">
    <meta name="component" content="Inventor-API">
    <meta name="created" content="">
    <meta name="user-comments" content="enable">
    <meta name="contextid" content="LoftedFlangeFeatures_Add_Sample">
    <meta name="description" content="Create sheet metal lofted flange feature Sample">
    <meta name="topicid" content="LoftedFlangeFeatures_Add_Sample">
    <meta name="experiencelevel" content="expert">
    <meta name="audience" content="programmer">
    <meta name="language" content="ENU">
    <title>Create sheet metal lofted flange feature</title>
    <link rel="stylesheet" href="../Style/jquery-ui.css"><script src="../Scripts/jquery-1.11.1.js"></script><script src="../Scripts/jquery-ui.js"></script><link rel="stylesheet" type="text/css" href="../Style/APIHelp-chm.css">
    <link rel="stylesheet" type="text/css" href="/view/clientframework/client.css"><script type="text/javascript" src="/view/clientframework/client.js"></script><script>
          // This turns on the display of the copyright notice which is not visible by default.
          // Because the head is removed when used in the web help, this function will only exists
          // when the chm help is being created.
          window.onload = function() {
          copyrightElement = document.getElementById('CopyrightNotice');
          copyrightElement.style.display = 'block';
          };
        </script><script>
          $(function() {
          $( "#tabs" ).tabs();
          });
        </script></head>
  <body><script>
          function copyCode(language) {
          // Get the pre element for the specified language.
          var preElement = document.getElementById(language);

          // Get the text from the element and copy it to the clipboard.
          var preText = preElement.innerText;

          var isIE = /*@cc_on!@*/false || !!document.documentMode;

          if (isIE)
          {
            window.clipboardData.setData('Text', preText);
          }
          else
          {
            navigator.clipboard.writeText(preText);
          }

          //alert("Code copied to clipboard");
          }
        </script><link rel="stylesheet" type="text/css" href="../Style/APIHelp.css">
    <h1 class="api">Create sheet metal lofted flange feature</h1>
    <h2 class="api">
          Description
        </h2>The following sample demonstrates the creation of a sheet metal lofted flange feature.<h2 class="api">
          Code Samples
        </h2>
    <div id="tabs">
      <ul>
        <li><a href="#VBA">VBA</a></li>
        <li><a href="#iLogic">iLogic</a></li>
      </ul>
      <div id="VBA" class="api-code">
        <table width="100%" style="font-size:15">
          <tr>
            <td align="right"><button onclick="copyCode('VBA_code')" class="copy-code">Copy Code</button></td>
          </tr>
        </table>
        <pre class="api-code" id="VBA_code">Public Sub LoftedFeatureCreation()
    <span style="color:blue">' Create a new sheet metal document, using the default sheet metal template.</span>
    Dim oSheetMetalDoc As PartDocument
    Set oSheetMetalDoc = ThisApplication.Documents.Add(kPartDocumentObject, _
                 ThisApplication.FileManager.GetTemplateFile(kPartDocumentObject, , , "{9C464203-9BAE-11D3-8BAD-0060B0CE6BB4}"))

    <span style="color:blue">' Set a reference to the component definition.</span>
    Dim oCompDef As SheetMetalComponentDefinition
    Set oCompDef = oSheetMetalDoc.ComponentDefinition

    <span style="color:blue">' Set a reference to the sheet metal features collection.</span>
    Dim oSheetMetalFeatures As SheetMetalFeatures
    Set oSheetMetalFeatures = oCompDef.Features

    <span style="color:blue">' Set a reference to the transient geometry object.</span>
    Dim oTransGeom As TransientGeometry
    Set oTransGeom = ThisApplication.TransientGeometry

    <span style="color:blue">' Create the first sketch on the X-Y work plane.</span>
    Dim oSketch1 As PlanarSketch
    Set oSketch1 = oCompDef.Sketches.Add(oCompDef.WorkPlanes.Item(3))

    <span style="color:blue">' Draw a 4cm x 3cm rectangle with the corner at (0,0)</span>
    Dim oSketchLines As SketchEntitiesEnumerator
    Set oSketchLines = oSketch1.SketchLines.AddAsTwoPointRectangle( _
                                oTransGeom.CreatePoint2d(-2, -2), _
                                oTransGeom.CreatePoint2d(2, 2))

    <span style="color:blue">' Create a path.</span>
    Dim oPath1 As Path
    Set oPath1 = oCompDef.Features.CreatePath(oSketchLines.Item(1))

    <span style="color:blue">' Create a workplane offset from the X-Y plane by 2 inches.</span>
    Dim oWorkPlane As WorkPlane
    Set oWorkPlane = oCompDef.WorkPlanes.AddByPlaneAndOffset(oCompDef.WorkPlanes.Item(3), "2 in")
    oWorkPlane.Visible = False

    <span style="color:blue">' Create the second sketch on the new work plane.</span>
    Dim oSketch2 As PlanarSketch
    Set oSketch2 = oCompDef.Sketches.Add(oWorkPlane)

    <span style="color:blue">' Draw a circle with center at (0,0) and radius 5.</span>
    Dim oSketchCircle As SketchCircle
    Set oSketchCircle = oSketch2.SketchCircles.AddByCenterRadius(oTransGeom.CreatePoint2d(0, 0), 5)

    <span style="color:blue">' Create a path.</span>
    Dim oPath2 As Path
    Set oPath2 = oCompDef.Features.CreatePath(oSketchCircle)

    Dim oLoftedFlangeDefinition As LoftedFlangeDefinition
    Set oLoftedFlangeDefinition = oSheetMetalFeatures.LoftedFlangeFeatures.CreateLoftedFlangeDefinition(oPath1, oPath2)

    <span style="color:blue">' Set the output type to press brake with a chord tolerance of .1</span>
    Call oLoftedFlangeDefinition.SetOutputType(kPressBrakeChordToleranceLoftedFlange, "0.1 in")

    <span style="color:blue">' Create a lofted flange feature.</span>
    Dim oLoftedFlangeFeature As LoftedFlangeFeature
    Set oLoftedFlangeFeature = oSheetMetalFeatures.LoftedFlangeFeatures.Add(oLoftedFlangeDefinition)

    ThisApplication.ActiveView.GoHome
End Sub</pre>
      </div>
      <div id="iLogic" class="api-code">
        <table width="100%" style="font-size:15">
          <tr>
            <td align="right"><button onclick="copyCode('iLogic_code')" class="copy-code">Copy Code</button></td>
          </tr>
        </table>
        <pre class="api-code" id="iLogic_code">    <span style="color:blue">' Create a new sheet metal document, using the default sheet metal template.</span>
    Dim oSheetMetalDoc As PartDocument
    oSheetMetalDoc = ThisApplication.Documents.Add(kPartDocumentObject, _
                 ThisApplication.FileManager.GetTemplateFile(kPartDocumentObject, , , "{9C464203-9BAE-11D3-8BAD-0060B0CE6BB4}"))

    <span style="color:blue">' Set a reference to the component definition.</span>
    Dim oCompDef As SheetMetalComponentDefinition
    oCompDef = oSheetMetalDoc.ComponentDefinition

    <span style="color:blue">' Set a reference to the sheet metal features collection.</span>
    Dim oSheetMetalFeatures As SheetMetalFeatures
    oSheetMetalFeatures = oCompDef.Features

    <span style="color:blue">' Set a reference to the transient geometry object.</span>
    Dim oTransGeom As TransientGeometry
    oTransGeom = ThisApplication.TransientGeometry

    <span style="color:blue">' Create the first sketch on the X-Y work plane.</span>
    Dim oSketch1 As PlanarSketch
    oSketch1 = oCompDef.Sketches.Add(oCompDef.WorkPlanes.Item(3))

    <span style="color:blue">' Draw a 4cm x 3cm rectangle with the corner at (0,0)</span>
    Dim oSketchLines As SketchEntitiesEnumerator
    oSketchLines = oSketch1.SketchLines.AddAsTwoPointRectangle( _
                                oTransGeom.CreatePoint2d(-2, -2), _
                                oTransGeom.CreatePoint2d(2, 2))

    <span style="color:blue">' Create a path.</span>
    Dim oPath1 As Path
    oPath1 = oCompDef.Features.CreatePath(oSketchLines.Item(1))

    <span style="color:blue">' Create a workplane offset from the X-Y plane by 2 inches.</span>
    Dim oWorkPlane As WorkPlane
    oWorkPlane = oCompDef.WorkPlanes.AddByPlaneAndOffset(oCompDef.WorkPlanes.Item(3), "2 in")
    oWorkPlane.Visible = False

    <span style="color:blue">' Create the second sketch on the new work plane.</span>
    Dim oSketch2 As PlanarSketch
    oSketch2 = oCompDef.Sketches.Add(oWorkPlane)

    <span style="color:blue">' Draw a circle with center at (0,0) and radius 5.</span>
    Dim oSketchCircle As SketchCircle
    oSketchCircle = oSketch2.SketchCircles.AddByCenterRadius(oTransGeom.CreatePoint2d(0, 0), 5)

    <span style="color:blue">' Create a path.</span>
    Dim oPath2 As Path
    oPath2 = oCompDef.Features.CreatePath(oSketchCircle)

    Dim oLoftedFlangeDefinition As LoftedFlangeDefinition
    oLoftedFlangeDefinition = oSheetMetalFeatures.LoftedFlangeFeatures.CreateLoftedFlangeDefinition(oPath1, oPath2)

    <span style="color:blue">' Set the output type to press brake with a chord tolerance of .1</span>
    Call oLoftedFlangeDefinition.SetOutputType(kPressBrakeChordToleranceLoftedFlange, "0.1 in")

    <span style="color:blue">' Create a lofted flange feature.</span>
    Dim oLoftedFlangeFeature As LoftedFlangeFeature
    oLoftedFlangeFeature = oSheetMetalFeatures.LoftedFlangeFeatures.Add(oLoftedFlangeDefinition)

    ThisApplication.ActiveView.GoHome</pre>
      </div>
    </div><br><br><div id="CopyrightNotice" style="display:none;">
      <hr>
      <table width="100%" style="font-size:15">
        <tr>
          <td align="left">
                Â© Copyright 2025 Autodesk, Inc.
              </td>
          <td align="right"><a href="mailto:mfg.api.help.comments@autodesk.com?subject=Inventor%202026%20API%20Help%20(LoftedFlangeFeatures_Add%20Sample%20Help%20Topic)">Comment on this page.</a></td>
        </tr>
      </table>
    </div>
  </body>
</html>