<html>
  <head>
    <META http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="topic-type" content="reference-adsk">
    <meta name="helpsystempath" content="/view/INVNTOR/2026/ENU/">
    <link rel="canonical" href="/cloudhelp/2026/ENU/Inventor-API/files/MassProperties_CenterOfMass_Sample.htm#!">
    <meta name="product" content="INVNTOR">
    <meta name="release" content="2026">
    <meta name="book" content="Developer">
    <meta name="component" content="Inventor-API">
    <meta name="created" content="">
    <meta name="user-comments" content="enable">
    <meta name="contextid" content="MassProperties_CenterOfMass_Sample">
    <meta name="description" content="Work point at mass center Sample">
    <meta name="topicid" content="MassProperties_CenterOfMass_Sample">
    <meta name="experiencelevel" content="expert">
    <meta name="audience" content="programmer">
    <meta name="language" content="ENU">
    <title>Work point at mass center</title>
    <link rel="stylesheet" href="../Style/jquery-ui.css"><script src="../Scripts/jquery-1.11.1.js"></script><script src="../Scripts/jquery-ui.js"></script><link rel="stylesheet" type="text/css" href="../Style/APIHelp-chm.css">
    <link rel="stylesheet" type="text/css" href="/view/clientframework/client.css"><script type="text/javascript" src="/view/clientframework/client.js"></script><script>
          // This turns on the display of the copyright notice which is not visible by default.
          // Because the head is removed when used in the web help, this function will only exists
          // when the chm help is being created.
          window.onload = function() {
          copyrightElement = document.getElementById('CopyrightNotice');
          copyrightElement.style.display = 'block';
          };
        </script><script>
          $(function() {
          $( "#tabs" ).tabs();
          });
        </script></head>
  <body><script>
          function copyCode(language) {
          // Get the pre element for the specified language.
          var preElement = document.getElementById(language);

          // Get the text from the element and copy it to the clipboard.
          var preText = preElement.innerText;

          var isIE = /*@cc_on!@*/false || !!document.documentMode;

          if (isIE)
          {
            window.clipboardData.setData('Text', preText);
          }
          else
          {
            navigator.clipboard.writeText(preText);
          }

          //alert("Code copied to clipboard");
          }
        </script><link rel="stylesheet" type="text/css" href="../Style/APIHelp.css">
    <h1 class="api">Work point at mass center</h1>
    <h2 class="api">
          Description
        </h2>This sample demonstrates creating a fixed work point and edit its position. It does this by computing the the center of mass of the part and creating a work point at that position. Subsequent runs of the sample reposition the work point at the new center of mass.<h2 class="api">
          Code Samples
        </h2>
    <div id="tabs">
      <ul>
        <li><a href="#C#">C#</a></li>
        <li><a href="#VBA">VBA</a></li>
        <li><a href="#iLogic">iLogic</a></li>
      </ul>
      <div id="C#" class="api-code">The first line of this sample sets the oApp variable to ThisApplication - this should be appropriately changed.<table width="100%" style="font-size:15">
          <tr>
            <td align="right"><button onclick="copyCode('C#_code')" class="copy-code">Copy Code</button></td>
          </tr>
        </table>
        <pre class="api-code" id="C#_code">public void WorkPointAtMassCenter()
{
    Application oApp = ThisApplication;

    <span style="color:blue">// Check to make sure a part document is active.</span>
    if (oApp.ActiveDocumentType != DocumentTypeEnum.kPartDocumentObject)
    {
        System.Windows.Forms.MessageBox.Show("A part document must be active.", "Part not active");
        return;
    }
    
    <span style="color:blue">// Set a reference to the active document.</span>
    PartDocument oDoc = (PartDocument)oApp.ActiveDocument;

    <span style="color:blue">// Get the Center of Mass.</span>
    Point oCenterOfMass = oDoc.ComponentDefinition.MassProperties.CenterOfMass;

    <span style="color:blue">// Check to see if a work point for center of mass already exists.</span>
    <span style="color:blue">// This uses the name of the work feature to identify it.</span>

    WorkPoint oWorkPoint = null;
    try
    {
        oWorkPoint = oDoc.ComponentDefinition.WorkPoints["Center Of Mass"];

        FixedWorkPointDef oFixedDef = (FixedWorkPointDef)oWorkPoint.Definition;
        oFixedDef.Point = oCenterOfMass;
        oDoc.Update();
    }
    catch
    {
        <span style="color:blue">// Create a new workpoint at the location of the center of mass.</span>
        oWorkPoint = oDoc.ComponentDefinition.WorkPoints.AddFixed(oCenterOfMass, false);

        <span style="color:blue">// Rename the work point.</span>
        oWorkPoint.Name = "Center Of Mass";
    }
}</pre>
      </div>
      <div id="VBA" class="api-code">
        <table width="100%" style="font-size:15">
          <tr>
            <td align="right"><button onclick="copyCode('VBA_code')" class="copy-code">Copy Code</button></td>
          </tr>
        </table>
        <pre class="api-code" id="VBA_code">Public Sub WorkPointAtMassCenter()
    <span style="color:blue">' Check to make sure a part document is active.</span>
    If ThisApplication.ActiveDocumentType &lt;&gt; kPartDocumentObject Then
        MsgBox "A part document must be active."
        Exit Sub
    End If

    <span style="color:blue">' Set a reference to the active document.</span>
    Dim oDoc As PartDocument
    Set oDoc = ThisApplication.ActiveDocument

    <span style="color:blue">' Get the Center of Mass.</span>
    Dim oCenterOfMass As Point
    Set oCenterOfMass = oDoc.ComponentDefinition.MassProperties.CenterOfMass

    <span style="color:blue">' Check to see if a work point for center of mass already exists.</span>
    <span style="color:blue">' This uses the name of the work feature to identify it.</span>
    On Error Resume Next
    Dim oWorkPoint As WorkPoint
    Set oWorkPoint = oDoc.ComponentDefinition.WorkPoints.Item("Center Of Mass")
    If Err.Number = 0 Then
        Dim oFixedDef As FixedWorkPointDef
        Set oFixedDef = oWorkPoint.Definition

        oFixedDef.Point = oCenterOfMass
        oDoc.Update
    Else
        <span style="color:blue">' Create a new workpoint at the location of the center of mass.</span>
        Set oWorkPoint = oDoc.ComponentDefinition.WorkPoints.AddFixed(oCenterOfMass)

        <span style="color:blue">' Rename the work point.</span>
        oWorkPoint.Name = "Center Of Mass"
    End If
End Sub</pre>
      </div>
      <div id="iLogic" class="api-code">
        <table width="100%" style="font-size:15">
          <tr>
            <td align="right"><button onclick="copyCode('iLogic_code')" class="copy-code">Copy Code</button></td>
          </tr>
        </table>
        <pre class="api-code" id="iLogic_code">    <span style="color:blue">' Check to make sure a part document is active.</span>
    If ThisApplication.ActiveDocumentType &lt;&gt; kPartDocumentObject Then
        MsgBox("A part document must be active.")
        Exit Sub
    End If

    <span style="color:blue">' Set a reference to the active document.</span>
    Dim oDoc As PartDocument
    oDoc = ThisApplication.ActiveDocument

    <span style="color:blue">' Get the Center of Mass.</span>
    Dim oCenterOfMass As Point
    oCenterOfMass = oDoc.ComponentDefinition.MassProperties.CenterOfMass

    <span style="color:blue">' Check to see if a work point for center of mass already exists.</span>
    <span style="color:blue">' This uses the name of the work feature to identify it.</span>
    On Error Resume Next
    Dim oWorkPoint As WorkPoint
    oWorkPoint = oDoc.ComponentDefinition.WorkPoints.Item("Center Of Mass")
    If Err.Number = 0 Then
        Dim oFixedDef As FixedWorkPointDef
        oFixedDef = oWorkPoint.Definition

        oFixedDef.Point = oCenterOfMass
        oDoc.Update
    Else
        <span style="color:blue">' Create a new workpoint at the location of the center of mass.</span>
        oWorkPoint = oDoc.ComponentDefinition.WorkPoints.AddFixed(oCenterOfMass)

        <span style="color:blue">' Rename the work point.</span>
        oWorkPoint.Name = "Center Of Mass"
    End If</pre>
      </div>
    </div><br><br><div id="CopyrightNotice" style="display:none;">
      <hr>
      <table width="100%" style="font-size:15">
        <tr>
          <td align="left">
                Â© Copyright 2025 Autodesk, Inc.
              </td>
          <td align="right"><a href="mailto:mfg.api.help.comments@autodesk.com?subject=Inventor%202026%20API%20Help%20(MassProperties_CenterOfMass%20Sample%20Help%20Topic)">Comment on this page.</a></td>
        </tr>
      </table>
    </div>
  </body>
</html>