<html>
  <head>
    <META http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="topic-type" content="reference-adsk">
    <meta name="helpsystempath" content="/view/INVNTOR/2026/ENU/">
    <link rel="canonical" href="/cloudhelp/2026/ENU/Inventor-API/files/PlanarSketches_AddWithOrientation_Sample.htm#!">
    <meta name="product" content="INVNTOR">
    <meta name="release" content="2026">
    <meta name="book" content="Developer">
    <meta name="component" content="Inventor-API">
    <meta name="created" content="">
    <meta name="user-comments" content="enable">
    <meta name="contextid" content="PlanarSketches_AddWithOrientation_Sample">
    <meta name="description" content="Sketch Add Oriented Sample">
    <meta name="topicid" content="PlanarSketches_AddWithOrientation_Sample">
    <meta name="experiencelevel" content="expert">
    <meta name="audience" content="programmer">
    <meta name="language" content="ENU">
    <title>Sketch Add Oriented</title>
    <link rel="stylesheet" href="../Style/jquery-ui.css"><script src="../Scripts/jquery-1.11.1.js"></script><script src="../Scripts/jquery-ui.js"></script><link rel="stylesheet" type="text/css" href="../Style/APIHelp-chm.css">
    <link rel="stylesheet" type="text/css" href="/view/clientframework/client.css"><script type="text/javascript" src="/view/clientframework/client.js"></script><script>
          // This turns on the display of the copyright notice which is not visible by default.
          // Because the head is removed when used in the web help, this function will only exists
          // when the chm help is being created.
          window.onload = function() {
          copyrightElement = document.getElementById('CopyrightNotice');
          copyrightElement.style.display = 'block';
          };
        </script><script>
          $(function() {
          $( "#tabs" ).tabs();
          });
        </script></head>
  <body><script>
          function copyCode(language) {
          // Get the pre element for the specified language.
          var preElement = document.getElementById(language);

          // Get the text from the element and copy it to the clipboard.
          var preText = preElement.innerText;

          var isIE = /*@cc_on!@*/false || !!document.documentMode;

          if (isIE)
          {
            window.clipboardData.setData('Text', preText);
          }
          else
          {
            navigator.clipboard.writeText(preText);
          }

          //alert("Code copied to clipboard");
          }
        </script><link rel="stylesheet" type="text/css" href="../Style/APIHelp.css">
    <h1 class="api">Sketch Add Oriented</h1>
    <h2 class="api">
          Description
        </h2>This sample demonstrates the creation of a sketch using the Sketches.AddWithOrientation method.<h2 class="api">
          Code Samples
        </h2>
    <div id="tabs">
      <ul>
        <li><a href="#VBA">VBA</a></li>
        <li><a href="#iLogic">iLogic</a></li>
      </ul>
      <div id="VBA" class="api-code">To use this sample, open a part document that contains a box before running the sample code.<table width="100%" style="font-size:15">
          <tr>
            <td align="right"><button onclick="copyCode('VBA_code')" class="copy-code">Copy Code</button></td>
          </tr>
        </table>
        <pre class="api-code" id="VBA_code">Public Sub AddOrientedSketch()
    <span style="color:blue">' Set a reference to the part component definition.</span>
    <span style="color:blue">' This assumes that a part document is active.</span>
    Dim oCompDef As PartComponentDefinition
    Set oCompDef = ThisApplication.ActiveDocument.ComponentDefinition
    
    <span style="color:blue">' Get the first face of the model.  This sample assumes a simple</span>
    <span style="color:blue">' model where at least the first face is a plane.  (A box is a good</span>
    <span style="color:blue">' test case.)</span>
    Dim oFace As Face
    Set oFace = oCompDef.SurfaceBodies.Item(1).Faces.Item(1)
    
    <span style="color:blue">' Get one of the edges of the face to use as the sketch x-axis.</span>
    Dim oEdge As Edge
    Set oEdge = oFace.Edges.Item(2)
    
    <span style="color:blue">' Get the start vertex of the edge to use as the origin of the sketch.</span>
    Dim oVertex As Vertex
    Set oVertex = oEdge.StartVertex
    
    <span style="color:blue">' Create a new sketch.  This last argument is set to true to cause the</span>
    <span style="color:blue">' creation of sketch geometry from the edges of the face.</span>
    Dim oSketch As PlanarSketch
    Set oSketch = oCompDef.Sketches.AddWithOrientation(oFace, oEdge, True, _
                                                        True, oVertex, True)
    
    <span style="color:blue">' Change the name.</span>
    oSketch.Name = "My Oriented Sketch"
    
    <span style="color:blue">' Draw a circle at the origin of the sketch plane.</span>
    Dim oCircle As SketchCircle
    Set oCircle = oSketch.SketchCircles.AddByCenterRadius( _
                ThisApplication.TransientGeometry.CreatePoint2d(0, 0), 1)
                
    <span style="color:blue">' Draw a line along the X axis.</span>
    Call oSketch.SketchLines.AddByTwoPoints(oCircle.CenterSketchPoint, _
                ThisApplication.TransientGeometry.CreatePoint2d(1, 0))
    
    <span style="color:blue">' Create one more sketch on another face with the origin defined by</span>
    <span style="color:blue">' the center point.  (The first workpoint in the collection is the center</span>
    <span style="color:blue">' point work point.)  In this case, no sketch geometry will be created</span>
    <span style="color:blue">' since the final argument has been left out and it defaults to false.</span>
    Set oFace = oCompDef.SurfaceBodies.Item(1).Faces.Item(5)
    Set oEdge = oFace.Edges.Item(1)
    Set oSketch = oCompDef.Sketches.AddWithOrientation(oFace, oEdge, True, _
                                                True, oCompDef.WorkPoints.Item(1))
                         
    <span style="color:blue">' Change the name.</span>
    oSketch.Name = "My Origin Sketch"

    <span style="color:blue">' Draw a circle at the origin of the sketch plane.</span>
    Set oCircle = oSketch.SketchCircles.AddByCenterRadius( _
                ThisApplication.TransientGeometry.CreatePoint2d(0, 0), 1)

    <span style="color:blue">' Draw a line along the X axis.</span>
    Call oSketch.SketchLines.AddByTwoPoints(oCircle.CenterSketchPoint, _
                ThisApplication.TransientGeometry.CreatePoint2d(1, 0))
End Sub</pre>
      </div>
      <div id="iLogic" class="api-code">To use this sample, open a part document that contains a box before running the sample code.<table width="100%" style="font-size:15">
          <tr>
            <td align="right"><button onclick="copyCode('iLogic_code')" class="copy-code">Copy Code</button></td>
          </tr>
        </table>
        <pre class="api-code" id="iLogic_code">    <span style="color:blue">' Set a reference to the part component definition.</span>
    <span style="color:blue">' This assumes that a part document is active.</span>
    Dim oCompDef As PartComponentDefinition
    oCompDef = ThisApplication.ActiveDocument.ComponentDefinition
    
    <span style="color:blue">' Get the first face of the model.  This sample assumes a simple</span>
    <span style="color:blue">' model where at least the first face is a plane.  (A box is a good</span>
    <span style="color:blue">' test case.)</span>
    Dim oFace As Face
    oFace = oCompDef.SurfaceBodies.Item(1).Faces.Item(1)
    
    <span style="color:blue">' Get one of the edges of the face to use as the sketch x-axis.</span>
    Dim oEdge As Edge
    oEdge = oFace.Edges.Item(2)
    
    <span style="color:blue">' Get the start vertex of the edge to use as the origin of the sketch.</span>
    Dim oVertex As Vertex
    oVertex = oEdge.StartVertex
    
    <span style="color:blue">' Create a new sketch.  This last argument is set to true to cause the</span>
    <span style="color:blue">' creation of sketch geometry from the edges of the face.</span>
    Dim oSketch As PlanarSketch
    oSketch = oCompDef.Sketches.AddWithOrientation(oFace, oEdge, True, _
                                                        True, oVertex, True)
    
    <span style="color:blue">' Change the name.</span>
    oSketch.Name = "My Oriented Sketch"
    
    <span style="color:blue">' Draw a circle at the origin of the sketch plane.</span>
    Dim oCircle As SketchCircle
    oCircle = oSketch.SketchCircles.AddByCenterRadius( _
                ThisApplication.TransientGeometry.CreatePoint2d(0, 0), 1)
                
    <span style="color:blue">' Draw a line along the X axis.</span>
    Call oSketch.SketchLines.AddByTwoPoints(oCircle.CenterSketchPoint, _
                ThisApplication.TransientGeometry.CreatePoint2d(1, 0))
    
    <span style="color:blue">' Create one more sketch on another face with the origin defined by</span>
    <span style="color:blue">' the center point.  (The first workpoint in the collection is the center</span>
    <span style="color:blue">' point work point.)  In this case, no sketch geometry will be created</span>
    <span style="color:blue">' since the final argument has been left out and it defaults to false.</span>
    oFace = oCompDef.SurfaceBodies.Item(1).Faces.Item(5)
    oEdge = oFace.Edges.Item(1)
    oSketch = oCompDef.Sketches.AddWithOrientation(oFace, oEdge, True, _
                                                True, oCompDef.WorkPoints.Item(1))
                         
    <span style="color:blue">' Change the name.</span>
    oSketch.Name = "My Origin Sketch"

    <span style="color:blue">' Draw a circle at the origin of the sketch plane.</span>
    oCircle = oSketch.SketchCircles.AddByCenterRadius( _
                ThisApplication.TransientGeometry.CreatePoint2d(0, 0), 1)

    <span style="color:blue">' Draw a line along the X axis.</span>
    Call oSketch.SketchLines.AddByTwoPoints(oCircle.CenterSketchPoint, _
                ThisApplication.TransientGeometry.CreatePoint2d(1, 0))</pre>
      </div>
    </div><br><br><div id="CopyrightNotice" style="display:none;">
      <hr>
      <table width="100%" style="font-size:15">
        <tr>
          <td align="left">
                Â© Copyright 2025 Autodesk, Inc.
              </td>
          <td align="right"><a href="mailto:mfg.api.help.comments@autodesk.com?subject=Inventor%202026%20API%20Help%20(PlanarSketches_AddWithOrientation%20Sample%20Help%20Topic)">Comment on this page.</a></td>
        </tr>
      </table>
    </div>
  </body>
</html>