<html>
  <head>
    <META http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="topic-type" content="reference-adsk">
    <meta name="helpsystempath" content="/view/INVNTOR/2026/ENU/">
    <link rel="canonical" href="/cloudhelp/2026/ENU/Inventor-API/files/PlanarSketch_NaturalAxisDirection_Sample.htm#!">
    <meta name="product" content="INVNTOR">
    <meta name="release" content="2026">
    <meta name="book" content="Developer">
    <meta name="component" content="Inventor-API">
    <meta name="created" content="">
    <meta name="user-comments" content="enable">
    <meta name="contextid" content="PlanarSketch_NaturalAxisDirection_Sample">
    <meta name="description" content="Sketch Edit Orientation Sample">
    <meta name="topicid" content="PlanarSketch_NaturalAxisDirection_Sample">
    <meta name="experiencelevel" content="expert">
    <meta name="audience" content="programmer">
    <meta name="language" content="ENU">
    <title>Sketch Edit Orientation</title>
    <link rel="stylesheet" href="../Style/jquery-ui.css"><script src="../Scripts/jquery-1.11.1.js"></script><script src="../Scripts/jquery-ui.js"></script><link rel="stylesheet" type="text/css" href="../Style/APIHelp-chm.css">
    <link rel="stylesheet" type="text/css" href="/view/clientframework/client.css"><script type="text/javascript" src="/view/clientframework/client.js"></script><script>
          // This turns on the display of the copyright notice which is not visible by default.
          // Because the head is removed when used in the web help, this function will only exists
          // when the chm help is being created.
          window.onload = function() {
          copyrightElement = document.getElementById('CopyrightNotice');
          copyrightElement.style.display = 'block';
          };
        </script><script>
          $(function() {
          $( "#tabs" ).tabs();
          });
        </script></head>
  <body><script>
          function copyCode(language) {
          // Get the pre element for the specified language.
          var preElement = document.getElementById(language);

          // Get the text from the element and copy it to the clipboard.
          var preText = preElement.innerText;

          var isIE = /*@cc_on!@*/false || !!document.documentMode;

          if (isIE)
          {
            window.clipboardData.setData('Text', preText);
          }
          else
          {
            navigator.clipboard.writeText(preText);
          }

          //alert("Code copied to clipboard");
          }
        </script><link rel="stylesheet" type="text/css" href="../Style/APIHelp.css">
    <h1 class="api">Sketch Edit Orientation</h1>
    <h2 class="api">
          Description
        </h2>This sample demonstrates modifying the orientation of a sketch.<h2 class="api">
          Code Samples
        </h2>
    <div id="tabs">
      <ul>
        <li><a href="#VBA">VBA</a></li>
        <li><a href="#iLogic">iLogic</a></li>
      </ul>
      <div id="VBA" class="api-code">To use this sample, have a part document open that contains a box and run the program.<table width="100%" style="font-size:15">
          <tr>
            <td align="right"><button onclick="copyCode('VBA_code')" class="copy-code">Copy Code</button></td>
          </tr>
        </table>
        <pre class="api-code" id="VBA_code">Public Sub ChangeSketchPlane()
   <span style="color:blue">' Set a reference to the part component definition.</span>
   <span style="color:blue">' This assumes that a part document is active.</span>
   Dim oCompDef As PartComponentDefinition
   Set oCompDef = ThisApplication.ActiveDocument.ComponentDefinition

   <span style="color:blue">' Get the first face of the model. This sample assumes a simple</span>
   <span style="color:blue">' model where at least the first face is a plane. (A box is a good</span>
   <span style="color:blue">' test case.)</span>
   Dim oFace As Face
   Set oFace = oCompDef.SurfaceBodies.Item(1).Faces.Item(1)

   <span style="color:blue">' Create a new sketch</span>
   Dim oSketch As PlanarSketch
   Set oSketch = oCompDef.Sketches.Add(oFace, True)

   <span style="color:blue">' Draw a circle at the origin of the sketch plane.</span>
   Dim oCircle As SketchCircle
   Set oCircle = oSketch.SketchCircles.AddByCenterRadius( _
   ThisApplication.TransientGeometry.CreatePoint2d(0, 0), 1)

   <span style="color:blue">' Draw a line along the X axis.</span>
   Call oSketch.SketchLines.AddByTwoPoints(oCircle.CenterSketchPoint, _
   ThisApplication.TransientGeometry.CreatePoint2d(1, 0))

   MsgBox "The sketch will be moved to another face."

   <span style="color:blue">' Move the sketch to the second face of the model.</span>
   Set oFace = oCompDef.SurfaceBodies.Item(1).Faces.Item(2)
   oSketch.PlanarEntity = oFace

   MsgBox "Current Origin Point: " & oSketch.OriginPointGeometry.X & ", " & _
   oSketch.OriginPointGeometry.Y & ", " & oSketch.OriginPointGeometry.Z & _
   Chr(13) & Chr(13) & _
   "The origin of the sketch will now be set to the center point."

   <span style="color:blue">' Set the origin point to use the center point work point.</span>
   oSketch.OriginPoint = oCompDef.WorkPoints.Item(1)

   MsgBox "New Origin Point: " & oSketch.OriginPointGeometry.X & ", " & _
   oSketch.OriginPointGeometry.Y & ", " & oSketch.OriginPointGeometry.Z & _
   Chr(13) & Chr(13) & _
   "The origin of the sketch will now be set to the center point."

   MsgBox "Current X axis: " & oSketch.AxisEntityGeometry.Direction.X & ", " & _
   oSketch.AxisEntityGeometry.Direction.Y & ", " & _
   oSketch.AxisEntityGeometry.Direction.Z

   MsgBox "The X axis of the sketch will now be redefined."

   <span style="color:blue">' Set the axis to be one of the edges of the face.</span>
   oSketch.AxisEntity = oFace.Edges.Item(2)

   MsgBox "New X axis: " & oSketch.AxisEntityGeometry.Direction.X & ", " & _
   oSketch.AxisEntityGeometry.Direction.Y & ", " & _
   oSketch.AxisEntityGeometry.Direction.Z

   MsgBox "The direction of the axis will now be reversed."

   <span style="color:blue">' Reverse the axis direction.</span>
   oSketch.NaturalAxisDirection = False

   MsgBox "New X axis: " & oSketch.AxisEntityGeometry.Direction.X & ", " & _
   oSketch.AxisEntityGeometry.Direction.Y & ", " & _
   oSketch.AxisEntityGeometry.Direction.Z

   MsgBox "The axis will be changed to define the Y instead of the X axis."

   <span style="color:blue">' Change the axis definition.</span>
   oSketch.AxisIsX = False
End Sub</pre>
      </div>
      <div id="iLogic" class="api-code">To use this sample, have a part document open that contains a box and run the program.<table width="100%" style="font-size:15">
          <tr>
            <td align="right"><button onclick="copyCode('iLogic_code')" class="copy-code">Copy Code</button></td>
          </tr>
        </table>
        <pre class="api-code" id="iLogic_code">    <span style="color:blue">' Set a reference to the part component definition.</span>
   <span style="color:blue">' This assumes that a part document is active.</span>
   Dim oCompDef As PartComponentDefinition
   oCompDef = ThisApplication.ActiveDocument.ComponentDefinition

   <span style="color:blue">' Get the first face of the model. This sample assumes a simple</span>
   <span style="color:blue">' model where at least the first face is a plane. (A box is a good</span>
   <span style="color:blue">' test case.)</span>
   Dim oFace As Face
   oFace = oCompDef.SurfaceBodies.Item(1).Faces.Item(1)

   <span style="color:blue">' Create a new sketch</span>
   Dim oSketch As PlanarSketch
   oSketch = oCompDef.Sketches.Add(oFace, True)

   <span style="color:blue">' Draw a circle at the origin of the sketch plane.</span>
   Dim oCircle As SketchCircle
   oCircle = oSketch.SketchCircles.AddByCenterRadius( _
   ThisApplication.TransientGeometry.CreatePoint2d(0, 0), 1)

   <span style="color:blue">' Draw a line along the X axis.</span>
   Call oSketch.SketchLines.AddByTwoPoints(oCircle.CenterSketchPoint, _
   ThisApplication.TransientGeometry.CreatePoint2d(1, 0))

   MsgBox("The sketch will be moved to another face.")

   <span style="color:blue">' Move the sketch to the second face of the model.</span>
   oFace = oCompDef.SurfaceBodies.Item(1).Faces.Item(2)
   oSketch.PlanarEntity = oFace

   MsgBox("Current Origin Point: " & oSketch.OriginPointGeometry.X & ", " & _
   oSketch.OriginPointGeometry.Y & ", " & oSketch.OriginPointGeometry.Z & _
   Chr(13) & Chr(13) & _
   "The origin of the sketch will now be set to the center point.")

   <span style="color:blue">' Set the origin point to use the center point work point.</span>
   oSketch.OriginPoint = oCompDef.WorkPoints.Item(1)

   MsgBox("New Origin Point: " & oSketch.OriginPointGeometry.X & ", " & _
   oSketch.OriginPointGeometry.Y & ", " & oSketch.OriginPointGeometry.Z & _
   Chr(13) & Chr(13) & _
   "The origin of the sketch will now be set to the center point.")

   MsgBox("Current X axis: " & oSketch.AxisEntityGeometry.Direction.X & ", " & _
   oSketch.AxisEntityGeometry.Direction.Y & ", " & _
   oSketch.AxisEntityGeometry.Direction.Z)

   MsgBox("The X axis of the sketch will now be redefined.")

   <span style="color:blue">' Set the axis to be one of the edges of the face.</span>
   oSketch.AxisEntity = oFace.Edges.Item(2)

   MsgBox("New X axis: " & oSketch.AxisEntityGeometry.Direction.X & ", " & _
   oSketch.AxisEntityGeometry.Direction.Y & ", " & _
   oSketch.AxisEntityGeometry.Direction.Z)

   MsgBox("The direction of the axis will now be reversed.")

   <span style="color:blue">' Reverse the axis direction.</span>
   oSketch.NaturalAxisDirection = False

   MsgBox("New X axis: " & oSketch.AxisEntityGeometry.Direction.X & ", " & _
   oSketch.AxisEntityGeometry.Direction.Y & ", " & _
   oSketch.AxisEntityGeometry.Direction.Z)

   MsgBox("The axis will be changed to define the Y instead of the X axis.")

   <span style="color:blue">' Change the axis definition.</span>
   oSketch.AxisIsX = False</pre>
      </div>
    </div><br><br><div id="CopyrightNotice" style="display:none;">
      <hr>
      <table width="100%" style="font-size:15">
        <tr>
          <td align="left">
                Â© Copyright 2025 Autodesk, Inc.
              </td>
          <td align="right"><a href="mailto:mfg.api.help.comments@autodesk.com?subject=Inventor%202026%20API%20Help%20(PlanarSketch_NaturalAxisDirection%20Sample%20Help%20Topic)">Comment on this page.</a></td>
        </tr>
      </table>
    </div>
  </body>
</html>