<html>
  <head>
    <META http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="topic-type" content="reference-adsk">
    <meta name="helpsystempath" content="/view/INVNTOR/2026/ENU/">
    <link rel="canonical" href="/cloudhelp/2026/ENU/Inventor-API/files/PlanarSketch_AddBySilhouette_Sample.htm#!">
    <meta name="product" content="INVNTOR">
    <meta name="release" content="2026">
    <meta name="book" content="Developer">
    <meta name="component" content="Inventor-API">
    <meta name="created" content="">
    <meta name="user-comments" content="enable">
    <meta name="contextid" content="PlanarSketch_AddBySilhouette_Sample">
    <meta name="description" content="Sketch from Face Silhouette Sample">
    <meta name="topicid" content="PlanarSketch_AddBySilhouette_Sample">
    <meta name="experiencelevel" content="expert">
    <meta name="audience" content="programmer">
    <meta name="language" content="ENU">
    <title>Sketch from Face Silhouette</title>
    <link rel="stylesheet" href="../Style/jquery-ui.css"><script src="../Scripts/jquery-1.11.1.js"></script><script src="../Scripts/jquery-ui.js"></script><link rel="stylesheet" type="text/css" href="../Style/APIHelp-chm.css">
    <link rel="stylesheet" type="text/css" href="/view/clientframework/client.css"><script type="text/javascript" src="/view/clientframework/client.js"></script><script>
          // This turns on the display of the copyright notice which is not visible by default.
          // Because the head is removed when used in the web help, this function will only exists
          // when the chm help is being created.
          window.onload = function() {
          copyrightElement = document.getElementById('CopyrightNotice');
          copyrightElement.style.display = 'block';
          };
        </script><script>
          $(function() {
          $( "#tabs" ).tabs();
          });
        </script></head>
  <body><script>
          function copyCode(language) {
          // Get the pre element for the specified language.
          var preElement = document.getElementById(language);

          // Get the text from the element and copy it to the clipboard.
          var preText = preElement.innerText;

          var isIE = /*@cc_on!@*/false || !!document.documentMode;

          if (isIE)
          {
            window.clipboardData.setData('Text', preText);
          }
          else
          {
            navigator.clipboard.writeText(preText);
          }

          //alert("Code copied to clipboard");
          }
        </script><link rel="stylesheet" type="text/css" href="../Style/APIHelp.css">
    <h1 class="api">Sketch from Face Silhouette</h1>
    <h2 class="api">
          Description
        </h2>This sample creates a cylindrical solid, creates a new sketch plane and creates some new sketch lines from the actual edges and the apparent (silhouette) edges of the cylinder.<h2 class="api">
          Code Samples
        </h2>
    <div id="tabs">
      <ul>
        <li><a href="#VBA">VBA</a></li>
        <li><a href="#iLogic">iLogic</a></li>
      </ul>
      <div id="VBA" class="api-code">
        <table width="100%" style="font-size:15">
          <tr>
            <td align="right"><button onclick="copyCode('VBA_code')" class="copy-code">Copy Code</button></td>
          </tr>
        </table>
        <pre class="api-code" id="VBA_code">Public Sub SilhouetteSample()
    <span style="color:blue">' Create a new part document using the default part template.</span>
    Dim oPartDoc As PartDocument
    Set oPartDoc = ThisApplication.Documents.Add(kPartDocumentObject, _
                ThisApplication.FileManager.GetTemplateFile(kPartDocumentObject))
    
    <span style="color:blue">' Set a reference to the part component definition.</span>
    <span style="color:blue">' This assumes that a part document is active.</span>
    Dim oCompDef As PartComponentDefinition
    Set oCompDef = oPartDoc.ComponentDefinition

    <span style="color:blue">' Create a new sketch on the X-Y work plane.</span>
    Dim oSketch1 As PlanarSketch
    Set oSketch1 = oCompDef.Sketches.Add(oCompDef.WorkPlanes.Item(3))
    
    <span style="color:blue">' Set a reference to the transient geometry object.</span>
    Dim oTransGeom As TransientGeometry
    Set oTransGeom = ThisApplication.TransientGeometry
    
    <span style="color:blue">' Draw a circle on the sketch.</span>
    Dim oCircle As SketchCircle
    Set oCircle = oSketch1.SketchCircles.AddByCenterRadius( _
                                oTransGeom.CreatePoint2d(0, 0), 2)
    
    <span style="color:blue">' Create a profile.</span>
    Dim oProfile As Profile
    Set oProfile = oSketch1.Profiles.AddForSolid
    
    <span style="color:blue">' Create a solid extrusion.</span>
    Dim oExtrudeDef As ExtrudeDefinition
    Set oExtrudeDef = oCompDef.Features.ExtrudeFeatures.CreateExtrudeDefinition(oProfile, kNewBodyOperation)
    Call oExtrudeDef.SetDistanceExtent(3, kSymmetricExtentDirection)
    Dim oExtrusion As ExtrudeFeature
    Set oExtrusion = oCompDef.Features.ExtrudeFeatures.Add(oExtrudeDef)
                    
    <span style="color:blue">' Create another sketch on the Y-Z plane.</span>
    Dim oSketch2 As PlanarSketch
    Set oSketch2 = oCompDef.Sketches.Add(oCompDef.WorkPlanes(1))
    
    <span style="color:blue">' Get the cylindrical face of the solid.</span>
    Dim oCylinder As Face
    Set oCylinder = oExtrusion.SideFaces.Item(1)
    
    <span style="color:blue">' Create a sketch line using the silhouette of the cylinder.  The proximity</span>
    <span style="color:blue">' point determines which of the two silhouette edges will be used.</span>
    Dim oSilhouetteCurve As SketchEntity
    Set oSilhouetteCurve = oSketch2.AddBySilhouette(oCylinder, _
                                    oTransGeom.CreatePoint(0, -1, 0))

    <span style="color:blue">' Create another sketch line from the silhouette on the</span>
    <span style="color:blue">' other side of the cylinder.</span>
    Set oSilhouetteCurve = oSketch2.AddBySilhouette(oCylinder, _
                                    oTransGeom.CreatePoint(0, 1, 0))
                                            
    <span style="color:blue">' Create sketch lines from the ends of the cylinder.  This takes</span>
    <span style="color:blue">' advantage of the fact that a cylinder only has two edges.</span>
    Dim oEndLine As SketchEntity
    Set oEndLine = oSketch2.AddByProjectingEntity( _
                            oExtrusion.StartFaces.Item(1).Edges.Item(1))
    Set oEndLine = oSketch2.AddByProjectingEntity( _
                            oExtrusion.EndFaces.Item(1).Edges.Item(1))
End Sub</pre>
      </div>
      <div id="iLogic" class="api-code">
        <table width="100%" style="font-size:15">
          <tr>
            <td align="right"><button onclick="copyCode('iLogic_code')" class="copy-code">Copy Code</button></td>
          </tr>
        </table>
        <pre class="api-code" id="iLogic_code">    <span style="color:blue">' Create a new part document using the default part template.</span>
    Dim oPartDoc As PartDocument
    oPartDoc = ThisApplication.Documents.Add(kPartDocumentObject, _
                ThisApplication.FileManager.GetTemplateFile(kPartDocumentObject))
    
    <span style="color:blue">' Set a reference to the part component definition.</span>
    <span style="color:blue">' This assumes that a part document is active.</span>
    Dim oCompDef As PartComponentDefinition
    oCompDef = oPartDoc.ComponentDefinition

    <span style="color:blue">' Create a new sketch on the X-Y work plane.</span>
    Dim oSketch1 As PlanarSketch
    oSketch1 = oCompDef.Sketches.Add(oCompDef.WorkPlanes.Item(3))
    
    <span style="color:blue">' Set a reference to the transient geometry object.</span>
    Dim oTransGeom As TransientGeometry
    oTransGeom = ThisApplication.TransientGeometry
    
    <span style="color:blue">' Draw a circle on the sketch.</span>
    Dim oCircle As SketchCircle
    oCircle = oSketch1.SketchCircles.AddByCenterRadius( _
                                oTransGeom.CreatePoint2d(0, 0), 2)
    
    <span style="color:blue">' Create a profile.</span>
    Dim oProfile As Profile
    oProfile = oSketch1.Profiles.AddForSolid
    
    <span style="color:blue">' Create a solid extrusion.</span>
    Dim oExtrudeDef As ExtrudeDefinition
    oExtrudeDef = oCompDef.Features.ExtrudeFeatures.CreateExtrudeDefinition(oProfile, kNewBodyOperation)
    Call oExtrudeDef.SetDistanceExtent(3, kSymmetricExtentDirection)
    Dim oExtrusion As ExtrudeFeature
    oExtrusion = oCompDef.Features.ExtrudeFeatures.Add(oExtrudeDef)
                    
    <span style="color:blue">' Create another sketch on the Y-Z plane.</span>
    Dim oSketch2 As PlanarSketch
    oSketch2 = oCompDef.Sketches.Add(oCompDef.WorkPlanes(1))
    
    <span style="color:blue">' Get the cylindrical face of the solid.</span>
    Dim oCylinder As Face
    oCylinder = oExtrusion.SideFaces.Item(1)
    
    <span style="color:blue">' Create a sketch line using the silhouette of the cylinder.  The proximity</span>
    <span style="color:blue">' point determines which of the two silhouette edges will be used.</span>
    Dim oSilhouetteCurve As SketchEntity
    oSilhouetteCurve = oSketch2.AddBySilhouette(oCylinder, _
                                    oTransGeom.CreatePoint(0, -1, 0))

    <span style="color:blue">' Create another sketch line from the silhouette on the</span>
    <span style="color:blue">' other side of the cylinder.</span>
    oSilhouetteCurve = oSketch2.AddBySilhouette(oCylinder, _
                                    oTransGeom.CreatePoint(0, 1, 0))
                                            
    <span style="color:blue">' Create sketch lines from the ends of the cylinder.  This takes</span>
    <span style="color:blue">' advantage of the fact that a cylinder only has two edges.</span>
    Dim oEndLine As SketchEntity
    oEndLine = oSketch2.AddByProjectingEntity( _
                            oExtrusion.StartFaces.Item(1).Edges.Item(1))
    oEndLine = oSketch2.AddByProjectingEntity( _
                            oExtrusion.EndFaces.Item(1).Edges.Item(1))</pre>
      </div>
    </div><br><br><div id="CopyrightNotice" style="display:none;">
      <hr>
      <table width="100%" style="font-size:15">
        <tr>
          <td align="left">
                Â© Copyright 2025 Autodesk, Inc.
              </td>
          <td align="right"><a href="mailto:mfg.api.help.comments@autodesk.com?subject=Inventor%202026%20API%20Help%20(PlanarSketch_AddBySilhouette%20Sample%20Help%20Topic)">Comment on this page.</a></td>
        </tr>
      </table>
    </div>
  </body>
</html>