<html>
  <head>
    <META http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="topic-type" content="reference-adsk">
    <meta name="helpsystempath" content="/view/INVNTOR/2026/ENU/">
    <link rel="canonical" href="/cloudhelp/2026/ENU/Inventor-API/files/PostPrivateEventSample_Sample.htm#!">
    <meta name="product" content="INVNTOR">
    <meta name="release" content="2026">
    <meta name="book" content="Developer">
    <meta name="component" content="Inventor-API">
    <meta name="created" content="">
    <meta name="user-comments" content="enable">
    <meta name="contextid" content="PostPrivateEventSample_Sample">
    <meta name="description" content="Post Private Event Sample Sample">
    <meta name="topicid" content="PostPrivateEventSample_Sample">
    <meta name="experiencelevel" content="expert">
    <meta name="audience" content="programmer">
    <meta name="language" content="ENU">
    <title>Post Private Event Sample</title>
    <link rel="stylesheet" href="../Style/jquery-ui.css"><script src="../Scripts/jquery-1.11.1.js"></script><script src="../Scripts/jquery-ui.js"></script><link rel="stylesheet" type="text/css" href="../Style/APIHelp-chm.css">
    <link rel="stylesheet" type="text/css" href="/view/clientframework/client.css"><script type="text/javascript" src="/view/clientframework/client.js"></script><script>
          // This turns on the display of the copyright notice which is not visible by default.
          // Because the head is removed when used in the web help, this function will only exists
          // when the chm help is being created.
          window.onload = function() {
          copyrightElement = document.getElementById('CopyrightNotice');
          copyrightElement.style.display = 'block';
          };
        </script><script>
          $(function() {
          $( "#tabs" ).tabs();
          });
        </script></head>
  <body><script>
          function copyCode(language) {
          // Get the pre element for the specified language.
          var preElement = document.getElementById(language);

          // Get the text from the element and copy it to the clipboard.
          var preText = preElement.innerText;

          var isIE = /*@cc_on!@*/false || !!document.documentMode;

          if (isIE)
          {
            window.clipboardData.setData('Text', preText);
          }
          else
          {
            navigator.clipboard.writeText(preText);
          }

          //alert("Code copied to clipboard");
          }
        </script><link rel="stylesheet" type="text/css" href="../Style/APIHelp.css">
    <h1 class="api">Post Private Event Sample</h1>
    <h2 class="api">
          Description
        </h2>This sample demonstrates how to use the PostPrivateEvent to configure the options for placing a part component.<h2 class="api">
          Code Samples
        </h2>
    <div id="tabs">
      <ul>
        <li><a href="#VBA">VBA</a></li>
        <li><a href="#iLogic">iLogic</a></li>
      </ul>
      <div id="VBA" class="api-code">This sample demonstrates how to use the PostPrivateEvent to configure the options for placing a part component.<table width="100%" style="font-size:15">
          <tr>
            <td align="right"><button onclick="copyCode('VBA_code')" class="copy-code">Copy Code</button></td>
          </tr>
        </table>
        <pre class="api-code" id="VBA_code">Sub AssemblyPlaceComponentCmdWithPPE()
    <span style="color:blue">' In UI create a part and create an iMate definition to its face, save it and set its full filename below.</span>
 
    Dim strFullFileName As String
    strFullFileName = "C:\Temp\iMate.ipt"
    
    Dim oAssyDoc As AssemblyDocument
    Set oAssyDoc = ThisApplication.Documents.Add(kAssemblyDocumentObject)
    
        
    Dim oOccu As ComponentOccurrence
    Set oOccu = oAssyDoc.ComponentDefinition.Occurrences.Add(strFullFileName, ThisApplication.TransientGeometry.CreateMatrix)
    
    Dim oCM As CommandManager
    Set oCM = ThisApplication.CommandManager
       
    <span style="color:blue">' clear existing clipboard</span>
    oCM.ClearPrivateEvents
        
    Call oCM.PostPrivateEvent(kFileNameEvent, strFullFileName)
       
    Dim oNV As NameValueMap
    Set oNV = ThisApplication.TransientObjects.CreateNameValueMap
    
    Call oNV.Add("Use iMate", True)
    Call oCM.PostPrivateEvent(kBooleanEvent, oNV)
    
    oNV.Clear
    Call oNV.Add("Generate iMate Results", True)
    Call oCM.PostPrivateEvent(kBooleanEvent, oNV)
      
    Call oCM.PostPrivateEvent(kStringEvent, "Design View Representation|Front")
    
    oNV.Clear
    Call oNV.Add("Associative Design View", True)
    Call oCM.PostPrivateEvent(kBooleanEvent, oNV)
    
    
    Call oCM.PostPrivateEvent(kStringEvent, "Model State|[Primary]")
        
    <span style="color:blue">' Call below command will cause to placing the component using above settings.</span>
    Dim oCat As ControlDefinition
    Set oCat = oCM.ControlDefinitions.Item("AssemblyPlaceComponentCmd")
    Call oCat.Execute2(True)
End Sub</pre>
      </div>
      <div id="iLogic" class="api-code">This sample demonstrates how to use the PostPrivateEvent to configure the options for placing a part component.<table width="100%" style="font-size:15">
          <tr>
            <td align="right"><button onclick="copyCode('iLogic_code')" class="copy-code">Copy Code</button></td>
          </tr>
        </table>
        <pre class="api-code" id="iLogic_code">    <span style="color:blue">' In UI create a part and create an iMate definition to its face, save it and set its full filename below.</span>
 
    Dim strFullFileName As String
    strFullFileName = "C:\Temp\iMate.ipt"
    
    Dim oAssyDoc As AssemblyDocument
    oAssyDoc = ThisApplication.Documents.Add(kAssemblyDocumentObject)
    
    Dim oOccu As ComponentOccurrence
    oOccu = oAssyDoc.ComponentDefinition.Occurrences.Add(strFullFileName, ThisApplication.TransientGeometry.CreateMatrix)
    
    Dim oCM As CommandManager
    oCM = ThisApplication.CommandManager
       
    <span style="color:blue">' clear existing clipboard</span>
    oCM.ClearPrivateEvents
        
    Call oCM.PostPrivateEvent(kFileNameEvent, strFullFileName)
       
    Dim oNV As NameValueMap
    oNV = ThisApplication.TransientObjects.CreateNameValueMap
    
    Call oNV.Add("Use iMate", True)
    Call oCM.PostPrivateEvent(kBooleanEvent, oNV)
    
    oNV.Clear
    Call oNV.Add("Generate iMate Results", True)
    Call oCM.PostPrivateEvent(kBooleanEvent, oNV)
      
    Call oCM.PostPrivateEvent(kStringEvent, "Design View Representation|Front")
    
    oNV.Clear
    Call oNV.Add("Associative Design View", True)
    Call oCM.PostPrivateEvent(kBooleanEvent, oNV)
    
    
    Call oCM.PostPrivateEvent(kStringEvent, "Model State|[Primary]")
        
    <span style="color:blue">' Call below command will cause to placing the component using above settings.</span>
    Dim oCat As ControlDefinition
    oCat = oCM.ControlDefinitions.Item("AssemblyPlaceComponentCmd")
    Call oCat.Execute2(True)</pre>
      </div>
    </div><br><br><div id="CopyrightNotice" style="display:none;">
      <hr>
      <table width="100%" style="font-size:15">
        <tr>
          <td align="left">
                Â© Copyright 2025 Autodesk, Inc.
              </td>
          <td align="right"><a href="mailto:mfg.api.help.comments@autodesk.com?subject=Inventor%202026%20API%20Help%20(PostPrivateEventSample%20Sample%20Help%20Topic)">Comment on this page.</a></td>
        </tr>
      </table>
    </div>
  </body>
</html>