<html>
  <head>
    <META http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="topic-type" content="reference-adsk">
    <meta name="helpsystempath" content="/view/INVNTOR/2026/ENU/">
    <link rel="canonical" href="/cloudhelp/2026/ENU/Inventor-API/files/Profile_RegionProperties_Sample.htm#!">
    <meta name="product" content="INVNTOR">
    <meta name="release" content="2026">
    <meta name="book" content="Developer">
    <meta name="component" content="Inventor-API">
    <meta name="created" content="">
    <meta name="user-comments" content="enable">
    <meta name="contextid" content="Profile_RegionProperties_Sample">
    <meta name="description" content="Querying a sketch profile to get regions. Sample">
    <meta name="topicid" content="Profile_RegionProperties_Sample">
    <meta name="experiencelevel" content="expert">
    <meta name="audience" content="programmer">
    <meta name="language" content="ENU">
    <title>Querying a sketch profile to get regions.</title>
    <link rel="stylesheet" href="../Style/jquery-ui.css"><script src="../Scripts/jquery-1.11.1.js"></script><script src="../Scripts/jquery-ui.js"></script><link rel="stylesheet" type="text/css" href="../Style/APIHelp-chm.css">
    <link rel="stylesheet" type="text/css" href="/view/clientframework/client.css"><script type="text/javascript" src="/view/clientframework/client.js"></script><script>
          // This turns on the display of the copyright notice which is not visible by default.
          // Because the head is removed when used in the web help, this function will only exists
          // when the chm help is being created.
          window.onload = function() {
          copyrightElement = document.getElementById('CopyrightNotice');
          copyrightElement.style.display = 'block';
          };
        </script><script>
          $(function() {
          $( "#tabs" ).tabs();
          });
        </script></head>
  <body><script>
          function copyCode(language) {
          // Get the pre element for the specified language.
          var preElement = document.getElementById(language);

          // Get the text from the element and copy it to the clipboard.
          var preText = preElement.innerText;

          var isIE = /*@cc_on!@*/false || !!document.documentMode;

          if (isIE)
          {
            window.clipboardData.setData('Text', preText);
          }
          else
          {
            navigator.clipboard.writeText(preText);
          }

          //alert("Code copied to clipboard");
          }
        </script><link rel="stylesheet" type="text/css" href="../Style/APIHelp.css">
    <h1 class="api">Querying a sketch profile to get regions.</h1>
    <h2 class="api">
          Description
        </h2>This sample demonstrates getting region properties from a sketch profile.<h2 class="api">
          Code Samples
        </h2>
    <div id="tabs">
      <ul>
        <li><a href="#VBA">VBA</a></li>
        <li><a href="#iLogic">iLogic</a></li>
      </ul>
      <div id="VBA" class="api-code">To run the sample you must have a sketch active that contains some sketch entities.<table width="100%" style="font-size:15">
          <tr>
            <td align="right"><button onclick="copyCode('VBA_code')" class="copy-code">Copy Code</button></td>
          </tr>
        </table>
        <pre class="api-code" id="VBA_code">Public Sub GetProfileRegionProperties()
    <span style="color:blue">' Set a reference to the active sketch.</span>
    <span style="color:blue">' This assumes a 2D sketch is active.</span>
    Dim oSketch As Sketch
    Set oSketch = ThisApplication.ActiveEditObject
    
    <span style="color:blue">' Create a default profile from the sketch.</span>
    Dim oProfile As Profile
    Set oProfile = oSketch.Profiles.AddForSolid
    
    <span style="color:blue">' Set a reference to the region properties object.</span>
    Dim oRegionProps As RegionProperties
    Set oRegionProps = oProfile.RegionProperties

    <span style="color:blue">' Set the accuracy to medium.</span>
    oRegionProps.Accuracy = kMedium

    <span style="color:blue">' Display the region properties of the profile.</span>
    Debug.Print "Area: " & oRegionProps.Area
    
    Debug.Print "Perimeter: " & oRegionProps.Perimeter
    
    Debug.Print "Centroid: " & _
                    oRegionProps.Centroid.X & ", " & _
                    oRegionProps.Centroid.Y

    Dim adPrincipalMoments(1 To 3) As Double
    Call oRegionProps.PrincipalMomentsOfInertia(adPrincipalMoments(1), _
                                                    adPrincipalMoments(2), _
                                                    adPrincipalMoments(3))
    Debug.Print "Principal Moments of Inertia: " & _
                    adPrincipalMoments(1) & ", " & _
                    adPrincipalMoments(2)

    Dim adRadiusOfGyration(1 To 3) As Double
    Call oRegionProps.RadiusOfGyration(adRadiusOfGyration(1), _
                                            adRadiusOfGyration(2), _
                                            adRadiusOfGyration(3))
    Debug.Print "Radius of Gyration: " & _
                    adRadiusOfGyration(1) & ", " & _
                    adRadiusOfGyration(2)

    Dim Ixx As Double
    Dim Iyy As Double
    Dim Izz As Double
    Dim Ixy As Double
    Dim Iyz As Double
    Dim Ixz As Double
    Call oRegionProps.MomentsOfInertia(Ixx, Iyy, Izz, Ixy, Iyz, Ixz)
    Debug.Print "Moments: "
    Debug.Print " Ixx: " & Ixx
    Debug.Print " Iyy: " & Iyy
    Debug.Print " Ixy: " & Ixy
    
    Debug.Print "Rotation Angle from projected Sketch Origin to Principle Axes: " _
    & oRegionProps.RotationAngle
    
End Sub</pre>
      </div>
      <div id="iLogic" class="api-code">To run the sample you must have a sketch active that contains some sketch entities.<table width="100%" style="font-size:15">
          <tr>
            <td align="right"><button onclick="copyCode('iLogic_code')" class="copy-code">Copy Code</button></td>
          </tr>
        </table>
        <pre class="api-code" id="iLogic_code">    <span style="color:blue">' Set a reference to the active sketch.</span>
    <span style="color:blue">' This assumes a 2D sketch is active.</span>
    Dim oSketch As Sketch
    oSketch = ThisApplication.ActiveEditObject
    
    <span style="color:blue">' Create a default profile from the sketch.</span>
    Dim oProfile As Profile
    oProfile = oSketch.Profiles.AddForSolid
    
    <span style="color:blue">' Set a reference to the region properties object.</span>
    Dim oRegionProps As RegionProperties
    oRegionProps = oProfile.RegionProperties

    <span style="color:blue">' Set the accuracy to medium.</span>
    oRegionProps.Accuracy = kMedium

    <span style="color:blue">' Display the region properties of the profile.</span>
    Logger.Info("Area: " & oRegionProps.Area)

    
    Logger.Info("Perimeter: " & oRegionProps.Perimeter)

    
    Logger.Info("Centroid: " & _
                    oRegionProps.Centroid.X & ", " & _
                    oRegionProps.Centroid.Y)

    Dim adPrincipalMoments(0 To 2) As Double
    Call oRegionProps.PrincipalMomentsOfInertia(adPrincipalMoments(0), _
                                                    adPrincipalMoments(1), _
                                                    adPrincipalMoments(2))
    Logger.Info("Principal Moments of Inertia: " & _
                    adPrincipalMoments(1) & ", " & _
                    adPrincipalMoments(2))

    Dim adRadiusOfGyration(0 To 2) As Double
    Call oRegionProps.RadiusOfGyration(adRadiusOfGyration(0), _
                                            adRadiusOfGyration(1), _
                                            adRadiusOfGyration(2))
    Logger.Info("Radius of Gyration: " & _
                    adRadiusOfGyration(0) & ", " & _
                    adRadiusOfGyration(1))

    Dim Ixx As Double
    Dim Iyy As Double
    Dim Izz As Double
    Dim Ixy As Double
    Dim Iyz As Double
    Dim Ixz As Double
    Call oRegionProps.MomentsOfInertia(Ixx, Iyy, Izz, Ixy, Iyz, Ixz)
    Logger.Info("Moments: ")

    Logger.Info(" Ixx: " & Ixx)

    Logger.Info(" Iyy: " & Iyy)

    Logger.Info(" Ixy: " & Ixy)

    
    Logger.Info("Rotation Angle from projected Sketch Origin to Principle Axes: " _
    & oRegionProps.RotationAngle)</pre>
      </div>
    </div><br><br><div id="CopyrightNotice" style="display:none;">
      <hr>
      <table width="100%" style="font-size:15">
        <tr>
          <td align="left">
                Â© Copyright 2025 Autodesk, Inc.
              </td>
          <td align="right"><a href="mailto:mfg.api.help.comments@autodesk.com?subject=Inventor%202026%20API%20Help%20(Profile_RegionProperties%20Sample%20Help%20Topic)">Comment on this page.</a></td>
        </tr>
      </table>
    </div>
  </body>
</html>