<html>
  <head>
    <META http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="topic-type" content="reference-adsk">
    <meta name="helpsystempath" content="/view/INVNTOR/2026/ENU/">
    <link rel="canonical" href="/cloudhelp/2026/ENU/Inventor-API/files/SelectSurfaceGraphicsPrimitives_Sample.htm#!">
    <meta name="product" content="INVNTOR">
    <meta name="release" content="2026">
    <meta name="book" content="Developer">
    <meta name="component" content="Inventor-API">
    <meta name="created" content="">
    <meta name="user-comments" content="enable">
    <meta name="contextid" content="SelectSurfaceGraphicsPrimitives_Sample">
    <meta name="description" content="Selection of Surface Graphics Primitives Sample">
    <meta name="topicid" content="SelectSurfaceGraphicsPrimitives_Sample">
    <meta name="experiencelevel" content="expert">
    <meta name="audience" content="programmer">
    <meta name="language" content="ENU">
    <title>Selection of Surface Graphics Primitives</title>
    <link rel="stylesheet" href="../Style/jquery-ui.css"><script src="../Scripts/jquery-1.11.1.js"></script><script src="../Scripts/jquery-ui.js"></script><link rel="stylesheet" type="text/css" href="../Style/APIHelp-chm.css">
    <link rel="stylesheet" type="text/css" href="/view/clientframework/client.css"><script type="text/javascript" src="/view/clientframework/client.js"></script><script>
          // This turns on the display of the copyright notice which is not visible by default.
          // Because the head is removed when used in the web help, this function will only exists
          // when the chm help is being created.
          window.onload = function() {
          copyrightElement = document.getElementById('CopyrightNotice');
          copyrightElement.style.display = 'block';
          };
        </script><script>
          $(function() {
          $( "#tabs" ).tabs();
          });
        </script></head>
  <body><script>
          function copyCode(language) {
          // Get the pre element for the specified language.
          var preElement = document.getElementById(language);

          // Get the text from the element and copy it to the clipboard.
          var preText = preElement.innerText;

          var isIE = /*@cc_on!@*/false || !!document.documentMode;

          if (isIE)
          {
            window.clipboardData.setData('Text', preText);
          }
          else
          {
            navigator.clipboard.writeText(preText);
          }

          //alert("Code copied to clipboard");
          }
        </script><link rel="stylesheet" type="text/css" href="../Style/APIHelp.css">
    <h1 class="api">Selection of Surface Graphics Primitives</h1>
    <h2 class="api">
          Description
        </h2>This demonstrates the ability to select client graphic primitives, by creating SurfaceGraphics and showing how you can select B-Rep entities within the graphics. You must have a part or assembly open and select a part of sat file which will be read in and displayed as client graphics.  Depending on our responses to the program it will create the graphics so that only the node is selectable (which is all that was supported before), so that all of the primitives are selected, or so that only certain primitives are selectable (every other face in this case).<h2 class="api">
          Code Samples
        </h2>
    <div id="tabs">
      <ul>
        <li><a href="#VBA">VBA</a></li>
        <li><a href="#iLogic">iLogic</a></li>
      </ul>
      <div id="VBA" class="api-code">To use this sample a part or assembly must be active.<table width="100%" style="font-size:15">
          <tr>
            <td align="right"><button onclick="copyCode('VBA_code')" class="copy-code">Copy Code</button></td>
          </tr>
        </table>
        <pre class="api-code" id="VBA_code">Public Sub SelectablePrimitives()
    <span style="color:blue">' Make sure a part or assembly is active.</span>
    If ThisApplication.ActiveDocumentType &lt;&gt; kAssemblyDocumentObject And ThisApplication.ActiveDocumentType &lt;&gt; kPartDocumentObject Then
        MsgBox "A part or assembly must be active."
        Exit Sub
    End If
    
    <span style="color:blue">' Get the document and it's associated definition.</span>
    Dim doc As Document
    Set doc = ThisApplication.ActiveDocument
    Dim def As ComponentDefinition
    Set def = doc.ComponentDefinition
    
    <span style="color:blue">' Get an .ipt or SAT filename from the user.</span>
    Dim dialog As FileDialog
    Dim filename As String
    Call ThisApplication.CreateFileDialog(dialog)
    With dialog
        .Filter = "Inventor Part File (*.ipt)|*.ipt|ACIS SAT File (*.sat)|*.sat"
        .FilterIndex = 0
        .ShowOpen
        If .filename = "" Then
            Exit Sub
        Else
            filename = .filename
        End If
    End With
    
    <span style="color:blue">' Get the transient B-Rep object.</span>
    Dim tb As TransientBRep
    Set tb = ThisApplication.TransientBRep
    
    <span style="color:blue">' If a part was selected, open it inivisibly and get the body.</span>
    Dim body As SurfaceBody
    If UCase(Right$(filename, 4)) = ".IPT" Then
        Dim newPart As PartDocument
        Set newPart = ThisApplication.Documents.Open(filename, False)
        
        <span style="color:blue">' Copy out the first body of the part.</span>
        Set body = tb.Copy(newPart.ComponentDefinition.SurfaceBodies.Item(1))
    Else
        <span style="color:blue">' Read in the sat file.</span>
        Dim bodies As SurfaceBodies
        Set bodies = tb.ReadFromFile(filename)
        
        Set body = bodies.Item(1)
    End If
        
    <span style="color:blue">' Create the client graphics object.</span>
    Dim graphics As ClientGraphics
    On Error Resume Next
    Set graphics = def.ClientGraphicsCollection.Item("Test")
    If Err.Number = 0 Then
        graphics.Delete
    End If
    On Error GoTo 0
    
    Set graphics = def.ClientGraphicsCollection.Add("Test")
    Dim node As GraphicsNode
    Set node = graphics.AddNode(1)
    node.Selectable = True
    node.DisplayName = "My Solid"
    
    Dim answer As VbMsgBoxResult
    answer = MsgBox("Yes=Node Selectable, No=All Selectable, Cancel=Every other face selectable", vbYesNoCancel + vbQuestion)
    
    Dim solidGraphics As SurfaceGraphics
    Set solidGraphics = node.AddSurfaceGraphics(body)
    ThisApplication.ActiveView.Update
    
    If answer = vbYes Then
        solidGraphics.ChildrenAreSelectable = False
    Else
        solidGraphics.ChildrenAreSelectable = True
    
        If answer = vbCancel Then
            Dim i As Integer
            For i = 1 To solidGraphics.DisplayedVertices.Count
                solidGraphics.DisplayedVertices.Item(i).Selectable = False
            Next
            
            For i = 1 To solidGraphics.DisplayedEdges.Count
                solidGraphics.DisplayedEdges.Item(i).Selectable = False
            Next
        
            For i = 1 To solidGraphics.DisplayedFaces.Count
                If i Mod 2 = 0 Then
                    solidGraphics.DisplayedFaces.Item(i).Selectable = False
                End If
            Next
        End If
    End If
End Sub</pre>
      </div>
      <div id="iLogic" class="api-code">To use this sample a part or assembly must be active.<table width="100%" style="font-size:15">
          <tr>
            <td align="right"><button onclick="copyCode('iLogic_code')" class="copy-code">Copy Code</button></td>
          </tr>
        </table>
        <pre class="api-code" id="iLogic_code">    <span style="color:blue">' Make sure a part or assembly is active.</span>
    If ThisApplication.ActiveDocumentType &lt;&gt; kAssemblyDocumentObject And ThisApplication.ActiveDocumentType &lt;&gt; kPartDocumentObject Then
        MsgBox("A part or assembly must be active.")
        Exit Sub
    End If
    
    <span style="color:blue">' Get the document and it's associated definition.</span>
    Dim doc As Document
    doc = ThisApplication.ActiveDocument
    Dim def As ComponentDefinition
    def = doc.ComponentDefinition
    
    <span style="color:blue">' Get an .ipt or SAT filename from the user.</span>
    Dim dialog As FileDialog
    Dim filename As String
    Call ThisApplication.CreateFileDialog(dialog)
    With dialog
        .Filter = "Inventor Part File (*.ipt)|*.ipt|ACIS SAT File (*.sat)|*.sat"
        .FilterIndex = 0
        .ShowOpen
        If .filename = "" Then
            Exit Sub
        Else
            filename = .filename
        End If
    End With
    
    <span style="color:blue">' Get the transient B-Rep object.</span>
    Dim tb As TransientBRep
    tb = ThisApplication.TransientBRep
    
    <span style="color:blue">' If a part was selected, open it inivisibly and get the body.</span>
    Dim body As SurfaceBody
    If UCase(Right$(filename, 4)) = ".IPT" Then
        Dim newPart As PartDocument
        newPart = ThisApplication.Documents.Open(filename, False)
        
        <span style="color:blue">' Copy out the first body of the part.</span>
        body = tb.Copy(newPart.ComponentDefinition.SurfaceBodies.Item(1))
    Else
        <span style="color:blue">' Read in the sat file.</span>
        Dim bodies As SurfaceBodies
        bodies = tb.ReadFromFile(filename)
        
        body = bodies.Item(1)
    End If
        
    <span style="color:blue">' Create the client graphics object.</span>
    Dim graphics As ClientGraphics
    On Error Resume Next
    graphics = def.ClientGraphicsCollection.Item("Test")
    If Err.Number = 0 Then
        graphics.Delete
    End If
    On Error GoTo 0
    
    graphics = def.ClientGraphicsCollection.Add("Test")
    Dim node As GraphicsNode
    node = graphics.AddNode(1)
    node.Selectable = True
    node.DisplayName = "My Solid"
    
    Dim answer As MsgBoxResult
    answer = MsgBox("Yes=Node Selectable, No=All Selectable, Cancel=Every other face selectable", vbYesNoCancel + vbQuestion)
    
    Dim solidGraphics As SurfaceGraphics
    solidGraphics = node.AddSurfaceGraphics(body)
    ThisApplication.ActiveView.Update
    
    If answer = vbYes Then
        solidGraphics.ChildrenAreSelectable = False
    Else
        solidGraphics.ChildrenAreSelectable = True
    
        If answer = vbCancel Then
            Dim i As Integer
            For i = 1 To solidGraphics.DisplayedVertices.Count
                solidGraphics.DisplayedVertices.Item(i).Selectable = False
            Next
            
            For i = 1 To solidGraphics.DisplayedEdges.Count
                solidGraphics.DisplayedEdges.Item(i).Selectable = False
            Next
        
            For i = 1 To solidGraphics.DisplayedFaces.Count
                If i Mod 2 = 0 Then
                    solidGraphics.DisplayedFaces.Item(i).Selectable = False
                End If
            Next
        End If
    End If</pre>
      </div>
    </div><br><br><div id="CopyrightNotice" style="display:none;">
      <hr>
      <table width="100%" style="font-size:15">
        <tr>
          <td align="left">
                Â© Copyright 2025 Autodesk, Inc.
              </td>
          <td align="right"><a href="mailto:mfg.api.help.comments@autodesk.com?subject=Inventor%202026%20API%20Help%20(SelectSurfaceGraphicsPrimitives%20Sample%20Help%20Topic)">Comment on this page.</a></td>
        </tr>
      </table>
    </div>
  </body>
</html>