<html>
  <head>
    <META http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="topic-type" content="reference-adsk">
    <meta name="helpsystempath" content="/view/INVNTOR/2026/ENU/">
    <link rel="canonical" href="/cloudhelp/2026/ENU/Inventor-API/files/SheetMetalComponentDefinition_Sample.htm#!">
    <meta name="product" content="INVNTOR">
    <meta name="release" content="2026">
    <meta name="book" content="Developer">
    <meta name="component" content="Inventor-API">
    <meta name="created" content="">
    <meta name="user-comments" content="enable">
    <meta name="contextid" content="SheetMetalComponentDefinition_Sample">
    <meta name="description" content="Sheet Metal Feature Display Sample">
    <meta name="topicid" content="SheetMetalComponentDefinition_Sample">
    <meta name="experiencelevel" content="expert">
    <meta name="audience" content="programmer">
    <meta name="language" content="ENU">
    <title>Sheet Metal Feature Display</title>
    <link rel="stylesheet" href="../Style/jquery-ui.css"><script src="../Scripts/jquery-1.11.1.js"></script><script src="../Scripts/jquery-ui.js"></script><link rel="stylesheet" type="text/css" href="../Style/APIHelp-chm.css">
    <link rel="stylesheet" type="text/css" href="/view/clientframework/client.css"><script type="text/javascript" src="/view/clientframework/client.js"></script><script>
          // This turns on the display of the copyright notice which is not visible by default.
          // Because the head is removed when used in the web help, this function will only exists
          // when the chm help is being created.
          window.onload = function() {
          copyrightElement = document.getElementById('CopyrightNotice');
          copyrightElement.style.display = 'block';
          };
        </script><script>
          $(function() {
          $( "#tabs" ).tabs();
          });
        </script></head>
  <body><script>
          function copyCode(language) {
          // Get the pre element for the specified language.
          var preElement = document.getElementById(language);

          // Get the text from the element and copy it to the clipboard.
          var preText = preElement.innerText;

          var isIE = /*@cc_on!@*/false || !!document.documentMode;

          if (isIE)
          {
            window.clipboardData.setData('Text', preText);
          }
          else
          {
            navigator.clipboard.writeText(preText);
          }

          //alert("Code copied to clipboard");
          }
        </script><link rel="stylesheet" type="text/css" href="../Style/APIHelp.css">
    <h1 class="api">Sheet Metal Feature Display</h1>
    <h2 class="api">
          Description
        </h2>This sample illustrates getting basic information from the various sheet metal features.<h2 class="api">
          Code Samples
        </h2>
    <div id="tabs">
      <ul>
        <li><a href="#VBA">VBA</a></li>
        <li><a href="#iLogic">iLogic</a></li>
      </ul>
      <div id="VBA" class="api-code">Before running the sample, open a sheet metal document that contains some features.<table width="100%" style="font-size:15">
          <tr>
            <td align="right"><button onclick="copyCode('VBA_code')" class="copy-code">Copy Code</button></td>
          </tr>
        </table>
        <pre class="api-code" id="VBA_code">Public Sub SheetMetalFeatureDisplay()
    <span style="color:blue">' Set a reference to the sheet metal document.</span>
    <span style="color:blue">' This assumes a part document is active.</span>
    Dim oPartDoc As PartDocument
    Set oPartDoc = ThisApplication.ActiveDocument
    
    <span style="color:blue">' Make sure the document is a sheet metal document.</span>
    If oPartDoc.SubType &lt;&gt; "{9C464203-9BAE-11D3-8BAD-0060B0CE6BB4}" Then
        MsgBox "A sheet metal document must be open."
        Exit Sub
    End If
    
    <span style="color:blue">' Get the sheet metal component definition.  Because this is a part document whose</span>
    <span style="color:blue">' sub type is sheet metal, the document will return a SheetMetalComponentDefinition</span>
    <span style="color:blue">' instead of a PartComponentDefinition.</span>
    Dim oSheetMetalCompDef As SheetMetalComponentDefinition
    Set oSheetMetalCompDef = oPartDoc.ComponentDefinition
    
    <span style="color:blue">' Iterate through the features looking specifically for sheet metal features.</span>
    Dim oFeature As PartFeature
    For Each oFeature In oSheetMetalCompDef.Features
        Select Case oFeature.Type
            Case kFaceFeatureObject
                Dim oFaceFeature As FaceFeature
                Set oFaceFeature = oFeature
                Debug.Print "Face Feature: " & oFaceFeature.Name
                Debug.Print "   Adaptive: " & oFaceFeature.Adaptive
                Debug.Print "   Face Count: " & oFaceFeature.Faces.Count
                Debug.Print "   HealthStatus: " & oFaceFeature.HealthStatus
                Debug.Print "   RangeBox: (" & Format(oFaceFeature.RangeBox.MinPoint.X, "0.00000") & ", " & _
                                        Format(oFaceFeature.RangeBox.MinPoint.Y, "0.00000") & ", " & _
                                        Format(oFaceFeature.RangeBox.MinPoint.Z, "0.00000") & ")-(" & _
                                        Format(oFaceFeature.RangeBox.MaxPoint.X, "0.00000") & ", " & _
                                        Format(oFaceFeature.RangeBox.MaxPoint.Y, "0.00000") & ", " & _
                                        Format(oFaceFeature.RangeBox.MaxPoint.Z, "0.00000") & ")"
                Debug.Print "   Suppressed: " & oFaceFeature.Suppressed
            Case kContourFlangeFeatureObject
                Dim oContourFlangeFeature As ContourFlangeFeature
                Set oContourFlangeFeature = oFeature
                Debug.Print "Contour Flange Feature: " & oContourFlangeFeature.Name
                Debug.Print "   Adaptive: " & oContourFlangeFeature.Adaptive
                Debug.Print "   Face Count: " & oContourFlangeFeature.Faces.Count
                Debug.Print "   HealthStatus: " & oContourFlangeFeature.HealthStatus
                Debug.Print "   RangeBox: (" & Format(oContourFlangeFeature.RangeBox.MinPoint.X, "0.00000") & ", " & _
                                        Format(oContourFlangeFeature.RangeBox.MinPoint.Y, "0.00000") & ", " & _
                                        Format(oContourFlangeFeature.RangeBox.MinPoint.Z, "0.00000") & ")-(" & _
                                        Format(oContourFlangeFeature.RangeBox.MaxPoint.X, "0.00000") & ", " & _
                                        Format(oContourFlangeFeature.RangeBox.MaxPoint.Y, "0.00000") & ", " & _
                                        Format(oContourFlangeFeature.RangeBox.MaxPoint.Z, "0.00000") & ")"
                Debug.Print "   Suppressed: " & oContourFlangeFeature.Suppressed
            Case kCutFeatureObject
                Dim oCutFeature As CutFeature
                Set oCutFeature = oFeature
                Debug.Print "Cut Feature: " & oCutFeature.Name
                Debug.Print "   Adaptive: " & oCutFeature.Adaptive
                Debug.Print "   Face Count: " & oCutFeature.Faces.Count
                Debug.Print "   HealthStatus: " & oCutFeature.HealthStatus
                Debug.Print "   RangeBox: (" & Format(oCutFeature.RangeBox.MinPoint.X, "0.00000") & ", " & _
                                        Format(oCutFeature.RangeBox.MinPoint.Y, "0.00000") & ", " & _
                                        Format(oCutFeature.RangeBox.MinPoint.Z, "0.00000") & ")-(" & _
                                        Format(oCutFeature.RangeBox.MaxPoint.X, "0.00000") & ", " & _
                                        Format(oCutFeature.RangeBox.MaxPoint.Y, "0.00000") & ", " & _
                                        Format(oCutFeature.RangeBox.MaxPoint.Z, "0.00000") & ")"
                Debug.Print "   Suppressed: " & oCutFeature.Suppressed
            Case kFlangeFeatureObject
                Dim oFlangeFeature As FlangeFeature
                Set oFlangeFeature = oFeature
                Debug.Print "Flange Feature: " & oFlangeFeature.Name
                Debug.Print "   Adaptive: " & oFlangeFeature.Adaptive
                Debug.Print "   Face Count: " & oFlangeFeature.Faces.Count
                Debug.Print "   HealthStatus: " & oFlangeFeature.HealthStatus
                Debug.Print "   RangeBox: (" & Format(oFlangeFeature.RangeBox.MinPoint.X, "0.00000") & ", " & _
                                        Format(oFlangeFeature.RangeBox.MinPoint.Y, "0.00000") & ", " & _
                                        Format(oFlangeFeature.RangeBox.MinPoint.Z, "0.00000") & ")-(" & _
                                        Format(oFlangeFeature.RangeBox.MaxPoint.X, "0.00000") & ", " & _
                                        Format(oFlangeFeature.RangeBox.MaxPoint.Y, "0.00000") & ", " & _
                                        Format(oFlangeFeature.RangeBox.MaxPoint.Z, "0.00000") & ")"
                Debug.Print "   Suppressed: " & oFlangeFeature.Suppressed
            Case kHemFeatureObject
                Dim oHemFeature As HemFeature
                Set oHemFeature = oFeature
                Debug.Print "Hem Feature: " & oHemFeature.Name
                Debug.Print "   Adaptive: " & oHemFeature.Adaptive
                Debug.Print "   Face Count: " & oHemFeature.Faces.Count
                Debug.Print "   HealthStatus: " & oHemFeature.HealthStatus
                Debug.Print "   RangeBox: (" & Format(oHemFeature.RangeBox.MinPoint.X, "0.00000") & ", " & _
                                        Format(oHemFeature.RangeBox.MinPoint.Y, "0.00000") & ", " & _
                                        Format(oHemFeature.RangeBox.MinPoint.Z, "0.00000") & ")-(" & _
                                        Format(oHemFeature.RangeBox.MaxPoint.X, "0.00000") & ", " & _
                                        Format(oHemFeature.RangeBox.MaxPoint.Y, "0.00000") & ", " & _
                                        Format(oHemFeature.RangeBox.MaxPoint.Z, "0.00000") & ")"
                Debug.Print "   Suppressed: " & oHemFeature.Suppressed
            Case kFoldFeatureObject
                Dim oFoldFeature As FoldFeature
                Set oFoldFeature = oFeature
                Debug.Print "Fold Feature: " & oFoldFeature.Name
                Debug.Print "   Adaptive: " & oFoldFeature.Adaptive
                Debug.Print "   Face Count: " & oFoldFeature.Faces.Count
                Debug.Print "   HealthStatus: " & oFoldFeature.HealthStatus
                Debug.Print "   RangeBox: (" & Format(oFoldFeature.RangeBox.MinPoint.X, "0.00000") & ", " & _
                                        Format(oFoldFeature.RangeBox.MinPoint.Y, "0.00000") & ", " & _
                                        Format(oFoldFeature.RangeBox.MinPoint.Z, "0.00000") & ")-(" & _
                                        Format(oFoldFeature.RangeBox.MaxPoint.X, "0.00000") & ", " & _
                                        Format(oFoldFeature.RangeBox.MaxPoint.Y, "0.00000") & ", " & _
                                        Format(oFoldFeature.RangeBox.MaxPoint.Z, "0.00000") & ")"
                Debug.Print "   Suppressed: " & oFoldFeature.Suppressed
            Case kCornerFeatureObject
                Dim oCornerFeature As CornerFeature
                Set oCornerFeature = oFeature
                Debug.Print "Corner Seam Feature: " & oCornerFeature.Name
                Debug.Print "   Adaptive: " & oCornerFeature.Adaptive
                Debug.Print "   Face Count: " & oCornerFeature.Faces.Count
                Debug.Print "   HealthStatus: " & oCornerFeature.HealthStatus
                Debug.Print "   RangeBox: (" & Format(oCornerFeature.RangeBox.MinPoint.X, "0.00000") & ", " & _
                                        Format(oCornerFeature.RangeBox.MinPoint.Y, "0.00000") & ", " & _
                                        Format(oCornerFeature.RangeBox.MinPoint.Z, "0.00000") & ")-(" & _
                                        Format(oCornerFeature.RangeBox.MaxPoint.X, "0.00000") & ", " & _
                                        Format(oCornerFeature.RangeBox.MaxPoint.Y, "0.00000") & ", " & _
                                        Format(oCornerFeature.RangeBox.MaxPoint.Z, "0.00000") & ")"
                Debug.Print "   Suppressed: " & oCornerFeature.Suppressed
            Case kBendFeatureObject
                Dim oBendFeature As BendFeature
                Set oBendFeature = oFeature
                Debug.Print "Bend Feature: " & oBendFeature.Name
                Debug.Print "   Adaptive: " & oBendFeature.Adaptive
                Debug.Print "   Face Count: " & oBendFeature.Faces.Count
                Debug.Print "   HealthStatus: " & oBendFeature.HealthStatus
                Debug.Print "   RangeBox: (" & Format(oBendFeature.RangeBox.MinPoint.X, "0.00000") & ", " & _
                                        Format(oBendFeature.RangeBox.MinPoint.Y, "0.00000") & ", " & _
                                        Format(oBendFeature.RangeBox.MinPoint.Z, "0.00000") & ")-(" & _
                                        Format(oBendFeature.RangeBox.MaxPoint.X, "0.00000") & ", " & _
                                        Format(oBendFeature.RangeBox.MaxPoint.Y, "0.00000") & ", " & _
                                        Format(oBendFeature.RangeBox.MaxPoint.Z, "0.00000") & ")"
                Debug.Print "   Suppressed: " & oBendFeature.Suppressed
            Case kCornerRoundFeatureObject
                Dim oCornerRoundFeature As CornerRoundFeature
                Set oCornerRoundFeature = oFeature
                Debug.Print "Corner Round Feature: " & oCornerRoundFeature.Name
                Debug.Print "   Adaptive: " & oCornerRoundFeature.Adaptive
                Debug.Print "   Face Count: " & oCornerRoundFeature.Faces.Count
                Debug.Print "   HealthStatus: " & oCornerRoundFeature.HealthStatus
                Debug.Print "   RangeBox: (" & Format(oCornerRoundFeature.RangeBox.MinPoint.X, "0.00000") & ", " & _
                                        Format(oCornerRoundFeature.RangeBox.MinPoint.Y, "0.00000") & ", " & _
                                        Format(oCornerRoundFeature.RangeBox.MinPoint.Z, "0.00000") & ")-(" & _
                                        Format(oCornerRoundFeature.RangeBox.MaxPoint.X, "0.00000") & ", " & _
                                        Format(oCornerRoundFeature.RangeBox.MaxPoint.Y, "0.00000") & ", " & _
                                        Format(oCornerRoundFeature.RangeBox.MaxPoint.Z, "0.00000") & ")"
                Debug.Print "   Suppressed: " & oCornerRoundFeature.Suppressed
            Case kCornerChamferFeatureObject
                Dim oCornerChamferFeature As CornerChamferFeature
                Set oCornerChamferFeature = oFeature
                Debug.Print "Corner Chamfer Feature: " & oCornerChamferFeature.Name
                Debug.Print "   Adaptive: " & oCornerChamferFeature.Adaptive
                Debug.Print "   Face Count: " & oCornerChamferFeature.Faces.Count
                Debug.Print "   HealthStatus: " & oCornerChamferFeature.HealthStatus
                Debug.Print "   RangeBox: (" & Format(oCornerChamferFeature.RangeBox.MinPoint.X, "0.00000") & ", " & _
                                        Format(oCornerChamferFeature.RangeBox.MinPoint.Y, "0.00000") & ", " & _
                                        Format(oCornerChamferFeature.RangeBox.MinPoint.Z, "0.00000") & ")-(" & _
                                        Format(oCornerChamferFeature.RangeBox.MaxPoint.X, "0.00000") & ", " & _
                                        Format(oCornerChamferFeature.RangeBox.MaxPoint.Y, "0.00000") & ", " & _
                                        Format(oCornerChamferFeature.RangeBox.MaxPoint.Z, "0.00000") & ")"
                Debug.Print "   Suppressed: " & oCornerChamferFeature.Suppressed
            Case kPunchToolFeatureObject
                Dim oPunchToolFeature As PunchToolFeature
                Set oPunchToolFeature = oFeature
                Debug.Print "Punch Tool Feature: " & oPunchToolFeature.Name
                Debug.Print "   Adaptive: " & oPunchToolFeature.Adaptive
                Debug.Print "   Face Count: " & oPunchToolFeature.Faces.Count
                Debug.Print "   HealthStatus: " & oPunchToolFeature.HealthStatus
                Debug.Print "   RangeBox: (" & Format(oPunchToolFeature.RangeBox.MinPoint.X, "0.00000") & ", " & _
                                        Format(oPunchToolFeature.RangeBox.MinPoint.Y, "0.00000") & ", " & _
                                        Format(oPunchToolFeature.RangeBox.MinPoint.Z, "0.00000") & ")-(" & _
                                        Format(oPunchToolFeature.RangeBox.MaxPoint.X, "0.00000") & ", " & _
                                        Format(oPunchToolFeature.RangeBox.MaxPoint.Y, "0.00000") & ", " & _
                                        Format(oPunchToolFeature.RangeBox.MaxPoint.Z, "0.00000") & ")"
                Debug.Print "   Suppressed: " & oPunchToolFeature.Suppressed
            Case Else
                Debug.Print "Non Sheetmetal Feature: " & oFeature.Name
                Debug.Print "   Adaptive: " & oFeature.Adaptive
                Debug.Print "   Face Count: " & oFeature.Faces.Count
                Debug.Print "   HealthStatus: " & oFeature.HealthStatus
                Debug.Print "   RangeBox: (" & Format(oFeature.RangeBox.MinPoint.X, "0.00000") & ", " & _
                                        Format(oFeature.RangeBox.MinPoint.Y, "0.00000") & ", " & _
                                        Format(oFeature.RangeBox.MinPoint.Z, "0.00000") & ")-(" & _
                                        Format(oFeature.RangeBox.MaxPoint.X, "0.00000") & ", " & _
                                        Format(oFeature.RangeBox.MaxPoint.Y, "0.00000") & ", " & _
                                        Format(oFeature.RangeBox.MaxPoint.Z, "0.00000") & ")"
                Debug.Print "   Suppressed: " & oFeature.Suppressed
        End Select
    Next
End Sub</pre>
      </div>
      <div id="iLogic" class="api-code">Before running the sample, open a sheet metal document that contains some features.<table width="100%" style="font-size:15">
          <tr>
            <td align="right"><button onclick="copyCode('iLogic_code')" class="copy-code">Copy Code</button></td>
          </tr>
        </table>
        <pre class="api-code" id="iLogic_code">    <span style="color:blue">' Set a reference to the sheet metal document.</span>
    <span style="color:blue">' This assumes a part document is active.</span>
    Dim oPartDoc As PartDocument
    oPartDoc = ThisApplication.ActiveDocument
    
    <span style="color:blue">' Make sure the document is a sheet metal document.</span>
    If oPartDoc.SubType &lt;&gt; "{9C464203-9BAE-11D3-8BAD-0060B0CE6BB4}" Then
        MsgBox("A sheet metal document must be open.")
        Exit Sub
    End If
    
    <span style="color:blue">' Get the sheet metal component definition.  Because this is a part document whose</span>
    <span style="color:blue">' sub type is sheet metal, the document will return a SheetMetalComponentDefinition</span>
    <span style="color:blue">' instead of a PartComponentDefinition.</span>
    Dim oSheetMetalCompDef As SheetMetalComponentDefinition
    oSheetMetalCompDef = oPartDoc.ComponentDefinition
    
    <span style="color:blue">' Iterate through the features looking specifically for sheet metal features.</span>
    Dim oFeature As PartFeature
    For Each oFeature In oSheetMetalCompDef.Features
        Select Case oFeature.Type
            Case kFaceFeatureObject
                Dim oFaceFeature As FaceFeature
                oFaceFeature = oFeature
                Logger.Info("Face Feature: " & oFaceFeature.Name)

                Logger.Info("   Adaptive: " & oFaceFeature.Adaptive)

                Logger.Info("   Face Count: " & oFaceFeature.Faces.Count)

                Logger.Info("   HealthStatus: " & oFaceFeature.HealthStatus)
                Logger.Info("   RangeBox: (" & Strings.FormatNumber(oFaceFeature.RangeBox.MinPoint.X, 5) & ", " & _
                                        FormatNumber(oFaceFeature.RangeBox.MinPoint.Y, 5) & ", " & _
                                        FormatNumber(oFaceFeature.RangeBox.MinPoint.Z, 5) & ")-(" & _
                                        FormatNumber(oFaceFeature.RangeBox.MaxPoint.X, 5) & ", " & _
                                        FormatNumber(oFaceFeature.RangeBox.MaxPoint.Y, 5) & ", " & _
                                        FormatNumber(oFaceFeature.RangeBox.MaxPoint.Z, 5) & ")")
                Logger.Info("   Suppressed: " & oFaceFeature.Suppressed)

            Case kContourFlangeFeatureObject
                Dim oContourFlangeFeature As ContourFlangeFeature
                oContourFlangeFeature = oFeature
                Logger.Info("Contour Flange Feature: " & oContourFlangeFeature.Name)

                Logger.Info("   Adaptive: " & oContourFlangeFeature.Adaptive)

                Logger.Info("   Face Count: " & oContourFlangeFeature.Faces.Count)

                Logger.Info("   HealthStatus: " & oContourFlangeFeature.HealthStatus)

                Logger.Info("   RangeBox: (" & FormatNumber(oContourFlangeFeature.RangeBox.MinPoint.X, 5) & ", " & _
                                        FormatNumber(oContourFlangeFeature.RangeBox.MinPoint.Y, 5) & ", " & _
                                        FormatNumber(oContourFlangeFeature.RangeBox.MinPoint.Z, 5) & ")-(" & _
                                        FormatNumber(oContourFlangeFeature.RangeBox.MaxPoint.X, 5) & ", " & _
                                        FormatNumber(oContourFlangeFeature.RangeBox.MaxPoint.Y, 5) & ", " & _
                                        FormatNumber(oContourFlangeFeature.RangeBox.MaxPoint.Z, 5) & ")")
                Logger.Info("   Suppressed: " & oContourFlangeFeature.Suppressed)

            Case kCutFeatureObject
                Dim oCutFeature As CutFeature
                oCutFeature = oFeature
                Logger.Info("Cut Feature: " & oCutFeature.Name)

                Logger.Info("   Adaptive: " & oCutFeature.Adaptive)

                Logger.Info("   Face Count: " & oCutFeature.Faces.Count)

                Logger.Info("   HealthStatus: " & oCutFeature.HealthStatus)

                Logger.Info("   RangeBox: (" & FormatNumber(oCutFeature.RangeBox.MinPoint.X, 5) & ", " & _
                                        FormatNumber(oCutFeature.RangeBox.MinPoint.Y, 5) & ", " & _
                                        FormatNumber(oCutFeature.RangeBox.MinPoint.Z, 5) & ")-(" & _
                                        FormatNumber(oCutFeature.RangeBox.MaxPoint.X, 5) & ", " & _
                                        FormatNumber(oCutFeature.RangeBox.MaxPoint.Y, 5) & ", " & _
                                        FormatNumber(oCutFeature.RangeBox.MaxPoint.Z, 5) & ")")
                Logger.Info("   Suppressed: " & oCutFeature.Suppressed)

            Case kFlangeFeatureObject
                Dim oFlangeFeature As FlangeFeature
                oFlangeFeature = oFeature
                Logger.Info("Flange Feature: " & oFlangeFeature.Name)

                Logger.Info("   Adaptive: " & oFlangeFeature.Adaptive)

                Logger.Info("   Face Count: " & oFlangeFeature.Faces.Count)

                Logger.Info("   HealthStatus: " & oFlangeFeature.HealthStatus)

                Logger.Info("   RangeBox: (" & FormatNumber(oFlangeFeature.RangeBox.MinPoint.X, 5) & ", " & _
                                        FormatNumber(oFlangeFeature.RangeBox.MinPoint.Y, 5) & ", " & _
                                        FormatNumber(oFlangeFeature.RangeBox.MinPoint.Z, 5) & ")-(" & _
                                        FormatNumber(oFlangeFeature.RangeBox.MaxPoint.X, 5) & ", " & _
                                        FormatNumber(oFlangeFeature.RangeBox.MaxPoint.Y, 5) & ", " & _
                                        FormatNumber(oFlangeFeature.RangeBox.MaxPoint.Z, 5) & ")")
                Logger.Info("   Suppressed: " & oFlangeFeature.Suppressed)

            Case kHemFeatureObject
                Dim oHemFeature As HemFeature
                oHemFeature = oFeature
                Logger.Info("Hem Feature: " & oHemFeature.Name)

                Logger.Info("   Adaptive: " & oHemFeature.Adaptive)

                Logger.Info("   Face Count: " & oHemFeature.Faces.Count)

                Logger.Info("   HealthStatus: " & oHemFeature.HealthStatus)

                Logger.Info("   RangeBox: (" & FormatNumber(oHemFeature.RangeBox.MinPoint.X, 5) & ", " & _
                                        FormatNumber(oHemFeature.RangeBox.MinPoint.Y, 5) & ", " & _
                                        FormatNumber(oHemFeature.RangeBox.MinPoint.Z, 5) & ")-(" & _
                                        FormatNumber(oHemFeature.RangeBox.MaxPoint.X, 5) & ", " & _
                                        FormatNumber(oHemFeature.RangeBox.MaxPoint.Y, 5) & ", " & _
                                        FormatNumber(oHemFeature.RangeBox.MaxPoint.Z, 5) & ")")
                Logger.Info("   Suppressed: " & oHemFeature.Suppressed)

            Case kFoldFeatureObject
                Dim oFoldFeature As FoldFeature
                oFoldFeature = oFeature
                Logger.Info("Fold Feature: " & oFoldFeature.Name)

                Logger.Info("   Adaptive: " & oFoldFeature.Adaptive)

                Logger.Info("   Face Count: " & oFoldFeature.Faces.Count)

                Logger.Info("   HealthStatus: " & oFoldFeature.HealthStatus)

                Logger.Info("   RangeBox: (" & FormatNumber(oFoldFeature.RangeBox.MinPoint.X, 5) & ", " & _
                                        FormatNumber(oFoldFeature.RangeBox.MinPoint.Y, 5) & ", " & _
                                        FormatNumber(oFoldFeature.RangeBox.MinPoint.Z, 5) & ")-(" & _
                                        FormatNumber(oFoldFeature.RangeBox.MaxPoint.X, 5) & ", " & _
                                        FormatNumber(oFoldFeature.RangeBox.MaxPoint.Y, 5) & ", " & _
                                        FormatNumber(oFoldFeature.RangeBox.MaxPoint.Z, 5) & ")")
                Logger.Info("   Suppressed: " & oFoldFeature.Suppressed)

            Case kCornerFeatureObject
                Dim oCornerFeature As CornerFeature
                oCornerFeature = oFeature
                Logger.Info("Corner Seam Feature: " & oCornerFeature.Name)

                Logger.Info("   Adaptive: " & oCornerFeature.Adaptive)

                Logger.Info("   Face Count: " & oCornerFeature.Faces.Count)

                Logger.Info("   HealthStatus: " & oCornerFeature.HealthStatus)

                Logger.Info("   RangeBox: (" & FormatNumber(oCornerFeature.RangeBox.MinPoint.X, 5) & ", " & _
                                        FormatNumber(oCornerFeature.RangeBox.MinPoint.Y, 5) & ", " & _
                                        FormatNumber(oCornerFeature.RangeBox.MinPoint.Z, 5) & ")-(" & _
                                        FormatNumber(oCornerFeature.RangeBox.MaxPoint.X, 5) & ", " & _
                                        FormatNumber(oCornerFeature.RangeBox.MaxPoint.Y, 5) & ", " & _
                                        FormatNumber(oCornerFeature.RangeBox.MaxPoint.Z, 5) & ")")
                Logger.Info("   Suppressed: " & oCornerFeature.Suppressed)

            Case kBendFeatureObject
                Dim oBendFeature As BendFeature
                oBendFeature = oFeature
                Logger.Info("Bend Feature: " & oBendFeature.Name)

                Logger.Info("   Adaptive: " & oBendFeature.Adaptive)

                Logger.Info("   Face Count: " & oBendFeature.Faces.Count)

                Logger.Info("   HealthStatus: " & oBendFeature.HealthStatus)

                Logger.Info("   RangeBox: (" & FormatNumber(oBendFeature.RangeBox.MinPoint.X, 5) & ", " & _
                                        FormatNumber(oBendFeature.RangeBox.MinPoint.Y, 5) & ", " & _
                                        FormatNumber(oBendFeature.RangeBox.MinPoint.Z, 5) & ")-(" & _
                                        FormatNumber(oBendFeature.RangeBox.MaxPoint.X, 5) & ", " & _
                                        FormatNumber(oBendFeature.RangeBox.MaxPoint.Y, 5) & ", " & _
                                        FormatNumber(oBendFeature.RangeBox.MaxPoint.Z, 5) & ")")
                Logger.Info("   Suppressed: " & oBendFeature.Suppressed)

            Case kCornerRoundFeatureObject
                Dim oCornerRoundFeature As CornerRoundFeature
                oCornerRoundFeature = oFeature
                Logger.Info("Corner Round Feature: " & oCornerRoundFeature.Name)

                Logger.Info("   Adaptive: " & oCornerRoundFeature.Adaptive)

                Logger.Info("   Face Count: " & oCornerRoundFeature.Faces.Count)

                Logger.Info("   HealthStatus: " & oCornerRoundFeature.HealthStatus)

                Logger.Info("   RangeBox: (" & FormatNumber(oCornerRoundFeature.RangeBox.MinPoint.X, 5) & ", " & _
                                        FormatNumber(oCornerRoundFeature.RangeBox.MinPoint.Y, 5) & ", " & _
                                        FormatNumber(oCornerRoundFeature.RangeBox.MinPoint.Z, 5) & ")-(" & _
                                        FormatNumber(oCornerRoundFeature.RangeBox.MaxPoint.X, 5) & ", " & _
                                        FormatNumber(oCornerRoundFeature.RangeBox.MaxPoint.Y, 5) & ", " & _
                                        FormatNumber(oCornerRoundFeature.RangeBox.MaxPoint.Z, 5) & ")")
                Logger.Info("   Suppressed: " & oCornerRoundFeature.Suppressed)

            Case kCornerChamferFeatureObject
                Dim oCornerChamferFeature As CornerChamferFeature
                oCornerChamferFeature = oFeature
                Logger.Info("Corner Chamfer Feature: " & oCornerChamferFeature.Name)

                Logger.Info("   Adaptive: " & oCornerChamferFeature.Adaptive)

                Logger.Info("   Face Count: " & oCornerChamferFeature.Faces.Count)

                Logger.Info("   HealthStatus: " & oCornerChamferFeature.HealthStatus)

                Logger.Info("   RangeBox: (" & FormatNumber(oCornerChamferFeature.RangeBox.MinPoint.X, 5) & ", " & _
                                        FormatNumber(oCornerChamferFeature.RangeBox.MinPoint.Y, 5) & ", " & _
                                        FormatNumber(oCornerChamferFeature.RangeBox.MinPoint.Z, 5) & ")-(" & _
                                        FormatNumber(oCornerChamferFeature.RangeBox.MaxPoint.X, 5) & ", " & _
                                        FormatNumber(oCornerChamferFeature.RangeBox.MaxPoint.Y, 5) & ", " & _
                                        FormatNumber(oCornerChamferFeature.RangeBox.MaxPoint.Z, 5) & ")")
                Logger.Info("   Suppressed: " & oCornerChamferFeature.Suppressed)

            Case kPunchToolFeatureObject
                Dim oPunchToolFeature As PunchToolFeature
                oPunchToolFeature = oFeature
                Logger.Info("Punch Tool Feature: " & oPunchToolFeature.Name)

                Logger.Info("   Adaptive: " & oPunchToolFeature.Adaptive)

                Logger.Info("   Face Count: " & oPunchToolFeature.Faces.Count)

                Logger.Info("   HealthStatus: " & oPunchToolFeature.HealthStatus)

                Logger.Info("   RangeBox: (" & FormatNumber(oPunchToolFeature.RangeBox.MinPoint.X, 5) & ", " & _
                                        FormatNumber(oPunchToolFeature.RangeBox.MinPoint.Y, 5) & ", " & _
                                        FormatNumber(oPunchToolFeature.RangeBox.MinPoint.Z, 5) & ")-(" & _
                                        FormatNumber(oPunchToolFeature.RangeBox.MaxPoint.X, 5) & ", " & _
                                        FormatNumber(oPunchToolFeature.RangeBox.MaxPoint.Y, 5) & ", " & _
                                        FormatNumber(oPunchToolFeature.RangeBox.MaxPoint.Z, 5) & ")")
                Logger.Info("   Suppressed: " & oPunchToolFeature.Suppressed)

            Case Else
                Logger.Info("Non Sheetmetal Feature: " & oFeature.Name)

                Logger.Info("   Adaptive: " & oFeature.Adaptive)

                Logger.Info("   Face Count: " & oFeature.Faces.Count)

                Logger.Info("   HealthStatus: " & oFeature.HealthStatus)

                Logger.Info("   RangeBox: (" & FormatNumber(oFeature.RangeBox.MinPoint.X, 5) & ", " & _
                                        FormatNumber(oFeature.RangeBox.MinPoint.Y, 5) & ", " & _
                                        FormatNumber(oFeature.RangeBox.MinPoint.Z, 5) & ")-(" & _
                                        FormatNumber(oFeature.RangeBox.MaxPoint.X, 5) & ", " & _
                                        FormatNumber(oFeature.RangeBox.MaxPoint.Y, 5) & ", " & _
                                        FormatNumber(oFeature.RangeBox.MaxPoint.Z, 5) & ")")
                Logger.Info("   Suppressed: " & oFeature.Suppressed)

        End Select
    Next</pre>
      </div>
    </div><br><br><div id="CopyrightNotice" style="display:none;">
      <hr>
      <table width="100%" style="font-size:15">
        <tr>
          <td align="left">
                Â© Copyright 2025 Autodesk, Inc.
              </td>
          <td align="right"><a href="mailto:mfg.api.help.comments@autodesk.com?subject=Inventor%202026%20API%20Help%20(SheetMetalComponentDefinition%20Sample%20Help%20Topic)">Comment on this page.</a></td>
        </tr>
      </table>
    </div>
  </body>
</html>