<html>
  <head>
    <META http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="topic-type" content="reference-adsk">
    <meta name="helpsystempath" content="/view/INVNTOR/2026/ENU/">
    <link rel="canonical" href="/cloudhelp/2026/ENU/Inventor-API/files/SheetMetalStyles_Sample.htm#!">
    <meta name="product" content="INVNTOR">
    <meta name="release" content="2026">
    <meta name="book" content="Developer">
    <meta name="component" content="Inventor-API">
    <meta name="created" content="">
    <meta name="user-comments" content="enable">
    <meta name="contextid" content="SheetMetalStyles_Sample">
    <meta name="description" content="Sheet Metal Style Creation Sample">
    <meta name="topicid" content="SheetMetalStyles_Sample">
    <meta name="experiencelevel" content="expert">
    <meta name="audience" content="programmer">
    <meta name="language" content="ENU">
    <title>Sheet Metal Style Creation</title>
    <link rel="stylesheet" href="../Style/jquery-ui.css"><script src="../Scripts/jquery-1.11.1.js"></script><script src="../Scripts/jquery-ui.js"></script><link rel="stylesheet" type="text/css" href="../Style/APIHelp-chm.css">
    <link rel="stylesheet" type="text/css" href="/view/clientframework/client.css"><script type="text/javascript" src="/view/clientframework/client.js"></script><script>
          // This turns on the display of the copyright notice which is not visible by default.
          // Because the head is removed when used in the web help, this function will only exists
          // when the chm help is being created.
          window.onload = function() {
          copyrightElement = document.getElementById('CopyrightNotice');
          copyrightElement.style.display = 'block';
          };
        </script><script>
          $(function() {
          $( "#tabs" ).tabs();
          });
        </script></head>
  <body><script>
          function copyCode(language) {
          // Get the pre element for the specified language.
          var preElement = document.getElementById(language);

          // Get the text from the element and copy it to the clipboard.
          var preText = preElement.innerText;

          var isIE = /*@cc_on!@*/false || !!document.documentMode;

          if (isIE)
          {
            window.clipboardData.setData('Text', preText);
          }
          else
          {
            navigator.clipboard.writeText(preText);
          }

          //alert("Code copied to clipboard");
          }
        </script><link rel="stylesheet" type="text/css" href="../Style/APIHelp.css">
    <h1 class="api">Sheet Metal Style Creation</h1>
    <h2 class="api">
          Description
        </h2>This sample illustrates creating a new sheet metal style. It uses a bend table and assumes the sample bend table delivered with Inventor is available. You can edit the path below to reference any existing bend table. To use the sample make sure a bend table is available at the specified path, open a sheet metal document, and run the sample.<h2 class="api">
          Code Samples
        </h2>
    <div id="tabs">
      <ul>
        <li><a href="#VBA">VBA</a></li>
        <li><a href="#iLogic">iLogic</a></li>
      </ul>
      <div id="VBA" class="api-code">
        <table width="100%" style="font-size:15">
          <tr>
            <td align="right"><button onclick="copyCode('VBA_code')" class="copy-code">Copy Code</button></td>
          </tr>
        </table>
        <pre class="api-code" id="VBA_code">Public Sub CreateSheetMetalStyle()
    <span style="color:blue">' Set a reference to the sheet metal document.</span>
    <span style="color:blue">' This assumes a part document is active.</span>
    Dim oPartDoc As PartDocument
    Set oPartDoc = ThisApplication.ActiveDocument

    <span style="color:blue">' Make sure the document is a sheet metal document.</span>
    If oPartDoc.SubType &lt;&gt; "{9C464203-9BAE-11D3-8BAD-0060B0CE6BB4}" Then
        MsgBox "A sheet metal document must be open."
        Exit Sub
    End If

    <span style="color:blue">' Get the sheet metal component definition. Because this is a part document whose</span>
    <span style="color:blue">' sub type is sheet metal, the document will return a SheetMetalComponentDefinition</span>
    <span style="color:blue">' instead of a PartComponentDefinition.</span>
    Dim oSheetMetalCompDef As SheetMetalComponentDefinition
    Set oSheetMetalCompDef = oPartDoc.ComponentDefinition

    <span style="color:blue">' Create a new unfold method.</span>
    Dim okFactorUnfoldMethod As UnfoldMethod
    Set okFactorUnfoldMethod = oSheetMetalCompDef.UnfoldMethods.AddLinearUnfoldMethod("kFactorTest", "0.43")
    
    <span style="color:blue">' Create a new unfold method using a bend table.</span>
    Dim oTableUnfoldMethod As UnfoldMethod
    On Error Resume Next
    Set oTableUnfoldMethod = oSheetMetalCompDef.UnfoldMethods.AddBendTableFromFile("Table Sample", "C:\Users\Public\Documents\Autodesk\Inventor 2026\Design Data\Bend Tables\Bend Table (in).txt")
    If Err Then
        MsgBox "Unable to load bend table"
    End If
    On Error Goto 0

    <span style="color:blue">' Copy a sheet metal style to create a new one. This arbitrarily uses the</span>
    <span style="color:blue">' first style in the collection.</span>
    Dim oStyle As SheetMetalStyle
    Set oStyle = oSheetMetalCompDef.SheetMetalStyles.Item(1).Copy("Sample Style")

    <span style="color:blue">' Set the value for the thickness. This is an expression that will be used to</span>
    <span style="color:blue">' set a parameter when this style is activated.</span>
    oStyle.Thickness = ".1 in"

    <span style="color:blue">' The name "Thickness" as used below is handled specially when the style</span>
    <span style="color:blue">' is used so it will behave as expected for all languages.</span>
    oStyle.BendRadius = "Thickness * 1.5"
    oStyle.BendReliefDepth = "Thickness * 1.5"
    oStyle.BendReliefShape = kRoundBendReliefShape
    oStyle.BendReliefWidth = "Thickness / 2"
    oStyle.BendTransition = kArcBendTransition
    oStyle.BendTransitionArcRadius = "Thickness * 2.0"
    oStyle.CornerReliefShape = kRoundCornerReliefShape
    oStyle.CornerReliefSize = "Thickness * 2.0"
    oStyle.MinimumRemnant = "Thickness * 2.0"

    <span style="color:blue">' Set the material.  For this example it arbitrarily uses the first material in the collection.</span>
    oStyle.Material = oPartDoc.Materials.Item(1)

    oStyle.PunchRepresentationType = kFormedFeaturePunchRepresentation
    oStyle.ThreeBendCornerReliefShape = kFullRoundCornerReliefShape
    oStyle.ThreeBendCornerReliefSize = "Thickness * 2.0"

    <span style="color:blue">' Activate this style.</span>
    oStyle.Activate

    <span style="color:blue">' This section will override some of the settings defined by the style.</span>
    Dim bOverrideStyle As Boolean
    bOverrideStyle = True
    If bOverrideStyle Then
        <span style="color:blue">' Set the unfold method to use the unfold method created above.</span>
        oSheetMetalCompDef.UnfoldMethod = okFactorUnfoldMethod

        <span style="color:blue">' Set the thickness.</span>
        oSheetMetalCompDef.UseSheetMetalStyleThickness = False
        oSheetMetalCompDef.Thickness.Expression = ".12 in"
        
        <span style="color:blue">' Set the material.</span>
        oSheetMetalCompDef.Material = oPartDoc.Materials.Item(2)
    End If
End Sub</pre>
      </div>
      <div id="iLogic" class="api-code">
        <table width="100%" style="font-size:15">
          <tr>
            <td align="right"><button onclick="copyCode('iLogic_code')" class="copy-code">Copy Code</button></td>
          </tr>
        </table>
        <pre class="api-code" id="iLogic_code">    <span style="color:blue">' Set a reference to the sheet metal document.</span>
    <span style="color:blue">' This assumes a part document is active.</span>
    Dim oPartDoc As PartDocument
    oPartDoc = ThisApplication.ActiveDocument

    <span style="color:blue">' Make sure the document is a sheet metal document.</span>
    If oPartDoc.SubType &lt;&gt; "{9C464203-9BAE-11D3-8BAD-0060B0CE6BB4}" Then
        MsgBox("A sheet metal document must be open.")
        Exit Sub
    End If

    <span style="color:blue">' Get the sheet metal component definition. Because this is a part document whose</span>
    <span style="color:blue">' sub type is sheet metal, the document will return a SheetMetalComponentDefinition</span>
    <span style="color:blue">' instead of a PartComponentDefinition.</span>
    Dim oSheetMetalCompDef As SheetMetalComponentDefinition
    oSheetMetalCompDef = oPartDoc.ComponentDefinition

    <span style="color:blue">' Create a new unfold method.</span>
    Dim okFactorUnfoldMethod As UnfoldMethod
    okFactorUnfoldMethod = oSheetMetalCompDef.UnfoldMethods.AddLinearUnfoldMethod("kFactorTest", "0.43")
    
    <span style="color:blue">' Create a new unfold method using a bend table.</span>
    Dim oTableUnfoldMethod As UnfoldMethod
    On Error Resume Next
    oTableUnfoldMethod = oSheetMetalCompDef.UnfoldMethods.AddBendTableFromFile("Table Sample", "C:\Users\Public\Documents\Autodesk\Inventor 2026\Design Data\Bend Tables\Bend Table (in).txt")
    If Err.Number &gt;0 Then
        MsgBox("Unable to load bend table")
    End If
    On Error Goto 0

    <span style="color:blue">' Copy a sheet metal style to create a new one. This arbitrarily uses the</span>
    <span style="color:blue">' first style in the collection.</span>
    Dim oStyle As SheetMetalStyle
    oStyle = oSheetMetalCompDef.SheetMetalStyles.Item(1).Copy("Sample Style")

    <span style="color:blue">' Set the value for the thickness. This is an expression that will be used to</span>
    <span style="color:blue">' set a parameter when this style is activated.</span>
    oStyle.Thickness = ".1 in"

    <span style="color:blue">' The name "Thickness" as used below is handled specially when the style</span>
    <span style="color:blue">' is used so it will behave as expected for all languages.</span>
    oStyle.BendRadius = "Thickness * 1.5"
    oStyle.BendReliefDepth = "Thickness * 1.5"
    oStyle.BendReliefShape = kRoundBendReliefShape
    oStyle.BendReliefWidth = "Thickness / 2"
    oStyle.BendTransition = kArcBendTransition
    oStyle.BendTransitionArcRadius = "Thickness * 2.0"
    oStyle.CornerReliefShape = kRoundCornerReliefShape
    oStyle.CornerReliefSize = "Thickness * 2.0"
    oStyle.MinimumRemnant = "Thickness * 2.0"

    <span style="color:blue">' Set the material.  For this example it arbitrarily uses the first material in the collection.</span>
    oStyle.Material = oPartDoc.Materials.Item(1)

    oStyle.PunchRepresentationType = kFormedFeaturePunchRepresentation
    oStyle.ThreeBendCornerReliefShape = kFullRoundCornerReliefShape
    oStyle.ThreeBendCornerReliefSize = "Thickness * 2.0"

    <span style="color:blue">' Activate this style.</span>
    oStyle.Activate

    <span style="color:blue">' This section will override some of the settings defined by the style.</span>
    Dim bOverrideStyle As Boolean
    bOverrideStyle = True
    If bOverrideStyle Then
        <span style="color:blue">' Set the unfold method to use the unfold method created above.</span>
        oSheetMetalCompDef.UnfoldMethod = okFactorUnfoldMethod

        <span style="color:blue">' Set the thickness.</span>
        oSheetMetalCompDef.UseSheetMetalStyleThickness = False
        oSheetMetalCompDef.Thickness.Expression = ".12 in"
        
        <span style="color:blue">' Set the material.</span>
        oSheetMetalCompDef.Material = oPartDoc.Materials.Item(2)
    End If</pre>
      </div>
    </div><br><br><div id="CopyrightNotice" style="display:none;">
      <hr>
      <table width="100%" style="font-size:15">
        <tr>
          <td align="left">
                Â© Copyright 2025 Autodesk, Inc.
              </td>
          <td align="right"><a href="mailto:mfg.api.help.comments@autodesk.com?subject=Inventor%202026%20API%20Help%20(SheetMetalStyles%20Sample%20Help%20Topic)">Comment on this page.</a></td>
        </tr>
      </table>
    </div>
  </body>
</html>