<html>
  <head>
    <META http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="topic-type" content="reference-adsk">
    <meta name="helpsystempath" content="/view/INVNTOR/2026/ENU/">
    <link rel="canonical" href="/cloudhelp/2026/ENU/Inventor-API/files/SheetMetalStyle_Sample.htm#!">
    <meta name="product" content="INVNTOR">
    <meta name="release" content="2026">
    <meta name="book" content="Developer">
    <meta name="component" content="Inventor-API">
    <meta name="created" content="">
    <meta name="user-comments" content="enable">
    <meta name="contextid" content="SheetMetalStyle_Sample">
    <meta name="description" content="Sheet Metal Style Display Sample">
    <meta name="topicid" content="SheetMetalStyle_Sample">
    <meta name="experiencelevel" content="expert">
    <meta name="audience" content="programmer">
    <meta name="language" content="ENU">
    <title>Sheet Metal Style Display</title>
    <link rel="stylesheet" href="../Style/jquery-ui.css"><script src="../Scripts/jquery-1.11.1.js"></script><script src="../Scripts/jquery-ui.js"></script><link rel="stylesheet" type="text/css" href="../Style/APIHelp-chm.css">
    <link rel="stylesheet" type="text/css" href="/view/clientframework/client.css"><script type="text/javascript" src="/view/clientframework/client.js"></script><script>
          // This turns on the display of the copyright notice which is not visible by default.
          // Because the head is removed when used in the web help, this function will only exists
          // when the chm help is being created.
          window.onload = function() {
          copyrightElement = document.getElementById('CopyrightNotice');
          copyrightElement.style.display = 'block';
          };
        </script><script>
          $(function() {
          $( "#tabs" ).tabs();
          });
        </script></head>
  <body><script>
          function copyCode(language) {
          // Get the pre element for the specified language.
          var preElement = document.getElementById(language);

          // Get the text from the element and copy it to the clipboard.
          var preText = preElement.innerText;

          var isIE = /*@cc_on!@*/false || !!document.documentMode;

          if (isIE)
          {
            window.clipboardData.setData('Text', preText);
          }
          else
          {
            navigator.clipboard.writeText(preText);
          }

          //alert("Code copied to clipboard");
          }
        </script><link rel="stylesheet" type="text/css" href="../Style/APIHelp.css">
    <h1 class="api">Sheet Metal Style Display</h1>
    <h2 class="api">
          Description
        </h2>This sample illustrates getting information about sheet metal styles.<h2 class="api">
          Code Samples
        </h2>
    <div id="tabs">
      <ul>
        <li><a href="#VBA">VBA</a></li>
        <li><a href="#iLogic">iLogic</a></li>
      </ul>
      <div id="VBA" class="api-code">
        <table width="100%" style="font-size:15">
          <tr>
            <td align="right"><button onclick="copyCode('VBA_code')" class="copy-code">Copy Code</button></td>
          </tr>
        </table>
        <pre class="api-code" id="VBA_code">Public Sub SheetMetalStyleDisplay()
    <span style="color:blue">' Set a reference to the sheet metal document.</span>
    <span style="color:blue">' This assumes a part document is active.</span>
    Dim oPartDoc As PartDocument
    Set oPartDoc = ThisApplication.ActiveDocument

    <span style="color:blue">' Make sure the document is a sheet metal document.</span>
    If oPartDoc.SubType &lt;&gt; "{9C464203-9BAE-11D3-8BAD-0060B0CE6BB4}" Then
        MsgBox "A sheet metal document must be open."
        Exit Sub
    End If

    <span style="color:blue">' Get the sheet metal component definition. Because this is a part document whose</span>
    <span style="color:blue">' sub type is sheet metal, the document will return a SheetMetalComponentDefinition</span>
    <span style="color:blue">' instead of a PartComponentDefinition.</span>
    Dim oSheetMetalCompDef As SheetMetalComponentDefinition
    Set oSheetMetalCompDef = oPartDoc.ComponentDefinition

    <span style="color:blue">' Display then name of the active style.</span>
    Debug.Print "Active Sheet Metal Style: " & oSheetMetalCompDef.ActiveSheetMetalStyle.Name

    <span style="color:blue">' Iterate through the sheet metal styles.</span>
    Debug.Print ""
    Debug.Print "Sheet Metal Styles"
    Dim oStyle As SheetMetalStyle
    
    On Error Resume Next
    For Each oStyle In oSheetMetalCompDef.SheetMetalStyles
        Debug.Print "  " & oStyle.Name
        Debug.Print "     In Use: " & oStyle.InUse
        Debug.Print "     Up to Date: " & oStyle.UpToDate

        Select Case oStyle.StyleLocation
            Case kBothStyleLocation
                Debug.Print "     Style Location: Both Local and in Library"
            Case kLibraryStyleLocation
                Debug.Print "     Style Location: Library"
            Case kLocalStyleLocation
                Debug.Print "     Style Location: Local"
        End Select

        Debug.Print "     Bend Radius: " & oStyle.BendRadius
        Debug.Print "     Bend Relief Depth: " & oStyle.BendReliefDepth
        Debug.Print "     Bend Relief Width: " & oStyle.BendReliefWidth

        Select Case oStyle.BendReliefShape
            Case kRoundBendReliefShape
                Debug.Print "     Bend Relief Shape: Round"
            Case kStraightBendReliefShape
                Debug.Print "     Bend Relief Shape: Straight"
        End Select

        Select Case oStyle.BendTransition
            Case kArcBendTransition
                Debug.Print "     Bend Transition: Arc"
            Case kDefaultBendTransition
                Debug.Print "     Bend Transition: Default"
            Case kIntersectionBendTransition
                Debug.Print "     Bend Transition: Intersection"
            Case kNoBendTransition
                Debug.Print "     Bend Transition: None"
            Case kStraightLineBendTransition
                Debug.Print "     Bend Transition: Straight Line"
            Case kTrimToBendBendTransition
                Debug.Print "     Bend Transition: Trim to Bend"
        End Select

        Debug.Print "     Bend Transition Arc Radius: " & oStyle.BendTransitionArcRadius

        Debug.Print "     Corner Relief Size: " & oStyle.CornerReliefSize
        Select Case oStyle.CornerReliefShape
            Case kArcWeldCornerReliefShape
                Debug.Print "     Corner Relief Shape: Arc Weld"
            Case kDefaultCornerReliefShape
                Debug.Print "     Corner Relief Shape: Default"
            Case kFullRoundCornerReliefShape
                Debug.Print "     Corner Relief Shape: Full Round"
            Case kIntersectionCornerReliefShape
                Debug.Print "     Corner Relief Shape: Intersection"
            Case kLinearWeldReliefShape
                Debug.Print "     Corner Relief Shape: Linear Weld"
            Case kNoReplacementCornerReliefShape
                Debug.Print "     Corner Relief Shape: No Replacement"
            Case kRoundCornerReliefShape
                Debug.Print "     Corner Relief Shape: Round"
            Case kRoundWithRadiusCornerReliefShape
                Debug.Print "     Corner Relief Shape: Round with Radius"
            Case kSquareCornerReliefShape
                Debug.Print "     Corner Relief Shape: Square"
            Case kTearCornerReliefShape
                Debug.Print "     Corner Relief Shape: Tear"
            Case kTrimToBendReliefShape
                Debug.Print "     Corner Relief Shape: Trim"
        End Select

        Debug.Print "     Corner Relief Size: " & oStyle.ThreeBendCornerReliefSize
        Select Case oStyle.ThreeBendCornerReliefShape
            Case kArcWeldCornerReliefShape
                Debug.Print "     Three Bend Corner Relief Shape: Arc Weld"
            Case kDefaultCornerReliefShape
                Debug.Print "     Three Bend Corner Relief Shape: Default"
            Case kFullRoundCornerReliefShape
                Debug.Print "     Three Bend Corner Relief Shape: Full Round"
            Case kIntersectionCornerReliefShape
                Debug.Print "     Three Bend Corner Relief Shape: Intersection"
            Case kLinearWeldReliefShape
                Debug.Print "     Three Bend Corner Relief Shape: Linear Weld"
            Case kNoReplacementCornerReliefShape
                Debug.Print "     Three Bend Corner Relief Shape: No Replacement"
            Case kRoundCornerReliefShape
                Debug.Print "     Three Bend Corner Relief Shape: Round"
            Case kRoundWithRadiusCornerReliefShape
                Debug.Print "     Three Bend Corner Relief Shape: Round with Radius"
            Case kSquareCornerReliefShape
                Debug.Print "     Three Bend Corner Relief Shape: Square"
            Case kTearCornerReliefShape
                Debug.Print "     Three Bend Corner Relief Shape: Tear"
            Case kTrimToBendReliefShape
                Debug.Print "     Three Bend Corner Relief Shape: Trim"
        End Select

        Debug.Print "     Material: " & oStyle.Material.Name
        Debug.Print "     Minimum Remnant: " & oStyle.MinimumRemnant
        Debug.Print "     Thickness: " & oStyle.Thickness

        Select Case oStyle.PunchRepresentationType
            Case k2DSketchAndCenterMarkPunchRepresentation
                Debug.Print "     Punch Representation Type: 2D Sketch and Center Mark"
            Case k2DSketchPunchRepresentation
                Debug.Print "     Punch Representation Type: 2D Sketch"
            Case kCentermarkPunchRepresentation
                Debug.Print "     Punch Representation Type: Center Mark"
            Case kDefaultPunchRepresentation
                Debug.Print "     Punch Representation Type: Default"
            Case kFormedFeaturePunchRepresentation
                Debug.Print "     Punch Representation Type: Formed Feature"
        End Select

        Debug.Print "     Unfold Method: " & oStyle.UnfoldMethod.Name
    Next

    <span style="color:blue">' Display information about the unfold methods.</span>
    Debug.Print ""
    Debug.Print "Unfold Methods"
    Dim oUnfoldMethod As UnfoldMethod
    For Each oUnfoldMethod In oSheetMetalCompDef.UnfoldMethods
        Debug.Print "  " & oUnfoldMethod.Name
        Debug.Print "     In Use: " & oUnfoldMethod.InUse
        Debug.Print "     Up to Date: " & oUnfoldMethod.UpToDate

        Select Case oUnfoldMethod.StyleLocation
            Case kBothStyleLocation
                Debug.Print "     Location: Both Local and in Library"
            Case kLibraryStyleLocation
                Debug.Print "     Location: Library"
            Case kLocalStyleLocation
                Debug.Print "     Location: Local"
        End Select

        Select Case oUnfoldMethod.UnfoldMethodType
            Case kBendTableUnfoldMethod
                Debug.Print "     Unfold Method Type: Bend Table"
            Case kLinearUnfoldMethod
                Debug.Print "     Unfold Method Type: Linear"
        End Select
        Debug.Print "     kFactor: " & oUnfoldMethod.kFactor
    Next
End Sub</pre>
      </div>
      <div id="iLogic" class="api-code">
        <table width="100%" style="font-size:15">
          <tr>
            <td align="right"><button onclick="copyCode('iLogic_code')" class="copy-code">Copy Code</button></td>
          </tr>
        </table>
        <pre class="api-code" id="iLogic_code">    <span style="color:blue">' Set a reference to the sheet metal document.</span>
    <span style="color:blue">' This assumes a part document is active.</span>
    Dim oPartDoc As PartDocument
    oPartDoc = ThisApplication.ActiveDocument

    <span style="color:blue">' Make sure the document is a sheet metal document.</span>
    If oPartDoc.SubType &lt;&gt; "{9C464203-9BAE-11D3-8BAD-0060B0CE6BB4}" Then
        MsgBox("A sheet metal document must be open.")
        Exit Sub
    End If

    <span style="color:blue">' Get the sheet metal component definition. Because this is a part document whose</span>
    <span style="color:blue">' sub type is sheet metal, the document will return a SheetMetalComponentDefinition</span>
    <span style="color:blue">' instead of a PartComponentDefinition.</span>
    Dim oSheetMetalCompDef As SheetMetalComponentDefinition
    oSheetMetalCompDef = oPartDoc.ComponentDefinition

    <span style="color:blue">' Display then name of the active style.</span>
    Logger.Info("Active Sheet Metal Style: " & oSheetMetalCompDef.ActiveSheetMetalStyle.Name)

    <span style="color:blue">' Iterate through the sheet metal styles.</span>
    Logger.Info("")
    Logger.Info("Sheet Metal Styles")

    Dim oStyle As SheetMetalStyle
    
    On Error Resume Next
    For Each oStyle In oSheetMetalCompDef.SheetMetalStyles
        Logger.Info("  " & oStyle.Name)
        Logger.Info("     In Use: " & oStyle.InUse)
        Logger.Info("     Up to Date: " & oStyle.UpToDate)

        Select Case oStyle.StyleLocation
            Case kBothStyleLocation
                Logger.Info("     Style Location: Both Local and in Library")

            Case kLibraryStyleLocation
                Logger.Info("     Style Location: Library")

            Case kLocalStyleLocation
                Logger.Info("     Style Location: Local")

        End Select

        Logger.Info("     Bend Radius: " & oStyle.BendRadius)
        Logger.Info("     Bend Relief Depth: " & oStyle.BendReliefDepth)
        Logger.Info("     Bend Relief Width: " & oStyle.BendReliefWidth)
        
        Select Case oStyle.BendReliefShape
            Case kRoundBendReliefShape
                Logger.Info("     Bend Relief Shape: Round")
            Case kStraightBendReliefShape
                Logger.Info("     Bend Relief Shape: Straight")
        End Select

        Select Case oStyle.BendTransition
            Case kArcBendTransition
                Logger.Info("     Bend Transition: Arc")
            Case kDefaultBendTransition
                Logger.Info("     Bend Transition: Default")
            Case kIntersectionBendTransition
                Logger.Info("     Bend Transition: Intersection")
            Case kNoBendTransition
                Logger.Info("     Bend Transition: None")
            Case kStraightLineBendTransition
                Logger.Info("     Bend Transition: Straight Line")
            Case kTrimToBendBendTransition
                Logger.Info("     Bend Transition: Trim to Bend")
        End Select

        Logger.Info("     Bend Transition Arc Radius: " & oStyle.BendTransitionArcRadius)
        Logger.Info("     Corner Relief Size: " & oStyle.CornerReliefSize)
        
        Select Case oStyle.CornerReliefShape
            Case kArcWeldCornerReliefShape
                Logger.Info("     Corner Relief Shape: Arc Weld")
            Case kDefaultCornerReliefShape
                Logger.Info("     Corner Relief Shape: Default")
            Case kFullRoundCornerReliefShape
                Logger.Info("     Corner Relief Shape: Full Round")
            Case kIntersectionCornerReliefShape
                Logger.Info("     Corner Relief Shape: Intersection")
            Case kLinearWeldReliefShape
                Logger.Info("     Corner Relief Shape: Linear Weld")
            Case kNoReplacementCornerReliefShape
                Logger.Info("     Corner Relief Shape: No Replacement")
            Case kRoundCornerReliefShape
                Logger.Info("     Corner Relief Shape: Round")
            Case kRoundWithRadiusCornerReliefShape
                Logger.Info("     Corner Relief Shape: Round with Radius")
            Case kSquareCornerReliefShape
                Logger.Info("     Corner Relief Shape: Square")
            Case kTearCornerReliefShape
                Logger.Info("     Corner Relief Shape: Tear")
            Case kTrimToBendReliefShape
                Logger.Info("     Corner Relief Shape: Trim")
        End Select

        Logger.Info("     Corner Relief Size: " & oStyle.ThreeBendCornerReliefSize)

        Select Case oStyle.ThreeBendCornerReliefShape
            Case kArcWeldCornerReliefShape
                Logger.Info("     Three Bend Corner Relief Shape: Arc Weld")
            Case kDefaultCornerReliefShape
                Logger.Info("     Three Bend Corner Relief Shape: Default")
            Case kFullRoundCornerReliefShape
                Logger.Info("     Three Bend Corner Relief Shape: Full Round")
            Case kIntersectionCornerReliefShape
                Logger.Info("     Three Bend Corner Relief Shape: Intersection")
            Case kLinearWeldReliefShape
                Logger.Info("     Three Bend Corner Relief Shape: Linear Weld")
            Case kNoReplacementCornerReliefShape
                Logger.Info("     Three Bend Corner Relief Shape: No Replacement")
            Case kRoundCornerReliefShape
                Logger.Info("     Three Bend Corner Relief Shape: Round")
            Case kRoundWithRadiusCornerReliefShape
                Logger.Info("     Three Bend Corner Relief Shape: Round with Radius")
            Case kSquareCornerReliefShape
                Logger.Info("     Three Bend Corner Relief Shape: Square")
            Case kTearCornerReliefShape
                Logger.Info("     Three Bend Corner Relief Shape: Tear")
            Case kTrimToBendReliefShape
                Logger.Info("     Three Bend Corner Relief Shape: Trim")
        End Select

        Logger.Info("     Material: " & oStyle.Material.Name)
        Logger.Info("     Minimum Remnant: " & oStyle.MinimumRemnant)
        Logger.Info("     Thickness: " & oStyle.Thickness)

        Select Case oStyle.PunchRepresentationType
            Case k2DSketchAndCenterMarkPunchRepresentation
                Logger.Info("     Punch Representation Type: 2D Sketch and Center Mark")
            Case k2DSketchPunchRepresentation
                Logger.Info("     Punch Representation Type: 2D Sketch")
            Case kCentermarkPunchRepresentation
                Logger.Info("     Punch Representation Type: Center Mark")
            Case kDefaultPunchRepresentation
                Logger.Info("     Punch Representation Type: Default")
            Case kFormedFeaturePunchRepresentation
                Logger.Info("     Punch Representation Type: Formed Feature")
        End Select

        Logger.Info("     Unfold Method: " & oStyle.UnfoldMethod.Name)
    Next

    <span style="color:blue">' Display information about the unfold methods.</span>
    Logger.Info("")
    Logger.Info("Unfold Methods")

    Dim oUnfoldMethod As UnfoldMethod
    For Each oUnfoldMethod In oSheetMetalCompDef.UnfoldMethods
        Logger.Info("  " & oUnfoldMethod.Name)
        Logger.Info("     In Use: " & oUnfoldMethod.InUse)
        Logger.Info("     Up to Date: " & oUnfoldMethod.UpToDate)

        Select Case oUnfoldMethod.StyleLocation
            Case kBothStyleLocation
                Logger.Info("     Location: Both Local and in Library")
            Case kLibraryStyleLocation
                Logger.Info("     Location: Library")
            Case kLocalStyleLocation
                Logger.Info("     Location: Local")
        End Select

        Select Case oUnfoldMethod.UnfoldMethodType
            Case kBendTableUnfoldMethod
                Logger.Info("     Unfold Method Type: Bend Table")
            Case kLinearUnfoldMethod
                Logger.Info("     Unfold Method Type: Linear")
        End Select
        Logger.Info("     kFactor: " & oUnfoldMethod.kFactor)
    Next</pre>
      </div>
    </div><br><br><div id="CopyrightNotice" style="display:none;">
      <hr>
      <table width="100%" style="font-size:15">
        <tr>
          <td align="left">
                Â© Copyright 2025 Autodesk, Inc.
              </td>
          <td align="right"><a href="mailto:mfg.api.help.comments@autodesk.com?subject=Inventor%202026%20API%20Help%20(SheetMetalStyle%20Sample%20Help%20Topic)">Comment on this page.</a></td>
        </tr>
      </table>
    </div>
  </body>
</html>