<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="topic-type" content="reference-adsk">
    <meta name="helpsystempath" content="/view/INVNTOR/2026/ENU">
    <link rel="canonical" href="http://help.autodesk.com/cloudhelp/2026/ENU/Inventor-API/files/SketchConstraints_Overview.htm">
    <meta name="product" content="INVNTOR">
    <meta name="release" content="2026">
    <meta name="book" content="Developer">
    <meta name="component" content="Inventor-API">
    <meta name="created" content="27/4/2016">
    <meta name="user-comments" content="enable">
    <meta name="description" content="">
    <meta name="topicid" content="GUID-30082FDF-9476-49C6-BB3E-0DE90A3CC812">
    <meta name="experiencelevel" content="expert">
    <meta name="audience" content="programmer">
    <meta name="language" content="ENU">
    <title>Sketch Constraints</title>
    <link rel="stylesheet" type="text/css" href="../Style/APIHelp-chm.css">
    <link rel="stylesheet" type="text/css" href="/view/clientframework/client.css"/>
    <script type="text/javascript" src="/view/clientframework/client.js"><!--filler--></script>
	<script>
	  // This turns on the display of the copyright notice which is not visible by default.
	  // Because the head is removed when used in the web help, this function will only exists
	  // when the chm help is being created.
	  window.onload = function() {
		copyrightElement = document.getElementById('CopyrightNotice');
		copyrightElement.style.display = 'block';
	  };
	</script>
</head>
<body>
<link rel="stylesheet" type="text/css" href="../Style/APIHelp.css">

<H1>Sketch Constraints</h1>
<h3>Introduction to sketch constraints</h3>
<p Class="Normal">Objects in Autodesk Inventor often relate to each other. The relationship may be as simple as being adjacent to each other, but it may be more complex, such as a combined tangential and vertical alignment. These relationships constrain objects and geometry together, so that any changes to the model cause the constraints to be recomputed and reapplied. If something changes sufficiently to prevent a constraint from being resolved, Autodesk Inventor flags that constraint.</p>

<h3>The purpose of sketch constraints</h3>
<p Class="Normal">Sketches are the base geometry in Autodesk Inventor - they are the building blocks for parts. Placing geometric constraints on sketches enables and ensures that basic rules for the design and shape of the sketch are enforced. Consequently, the resultant profiles with which part features may be defined follow the same rules. Think of constraints as rules that govern the position, slope, tangency, dimensions, and relationships among sketch geometry. Geometric constraints control the shapes and relationships among sketch elements, effectively removing successive degrees of freedom. The Autodesk Inventor API has a suite of constraint objects, and their proxies, that can be applied to sketches.</p>

<p Class="Normal">There are other types of constraints not covered by this overview, but they perform a similar function. Geometric constraints can also be applied to assembly components, defining relationships between parts in an assembly. See the <a href="AssemblingParts_Overview.htm" data-topic-id="GUID-BDA5283B-D32F-462A-B8EA-8DDBE0CE2E69"> Assembling Parts</a> overview for more information on working with parts in the assembly environment. </p>

<p Class="Normal">Dimensional constraints in sketches control size, for example, the radius of an arc or the width of a part.  All these types of constraints are resolved sequentially during a model compute to achieve the final model structure.</p>


<!--<br>
<table cellspacing="4" cellpadding="4" border="1">
<tr>
    <td  bgcolor="Yellow"><b>Note:</b> 
Balloon notation referencing properties (specified through styles) currently cannot be changed through the API.
</td>
</tr>
</table>
<br>-->

<h3>Sketch Constraints Object Model Diagram</h3>

<br>
<div align="center"> <img src="../images/ov.SketchConstraints_diag.png" border=0></div>
 <br>

<h3>Working with sketch constraints through the API</h3>

<p Class="Normal">The API has objects for each type of constraint. The GeometricConstraints collection has add methods corresponding to each constraint object type.  For example, to create a tangent constraint, call GeometricConstraints.AddTangent.  These add methods accept SketchLines, SketchArcs, and SketchPoints as appropriate to their type.  For example, a Tangent constraint accepts a SketchLine and SketchArc.</p>

<h3>A sample - the effects of constraining a sketch</h3>

<p Class="Normal">The following code creates a sketch in a new part document. It defines a number of sketch points within a SketchPoints collection, and then creates SketchLine objects and an arc based on those sketch points. The code omits error checking for the sake of clarity and brevity.  Always check that return values are of the expected type.</p>

<p Class="Normal">First, create the new part document, and then add a new sketch:</p>

 
<br>
<table Class="Code">
<tr valign="middle">
	<td Class="Code">
	<pre>
Dim oApp As Inventor.Application
Set oApp = ThisApplication
Dim oPartDoc As PartDocument
Set oPartDoc = oApp.Documents.Add(kPartDocumentObject, _
    oApp.GetTemplateFile(kPartDocumentObject))
Dim oSketch As PlanarSketch
Set oSketch = oPartDoc.ComponentDefinition.Sketches.Add _
   (oPartDoc.ComponentDefinition.WorkPlanes.Item(3))
</pre></td></tr>
</table>
<br>

<!--
<br>
<table Class="Code">
<tr valign="middle">
	<td Class="Code">
	<pre>

</pre></td></tr>
</table>
<br>
-->

<p Class="Normal">The code creates a number of arbitrary 2D points, using transient geometry to create the points, so create the transient geometry object.</p>

<br>
<table Class="Code">
<tr valign="middle">
	<td Class="Code">
	<pre>
Dim oTG As TransientGeometry
Set oTG = oApp.TransientGeometry
</pre></td></tr>
</table>
<br>

<p Class="Normal">Now get the SketchPoints collection for the new sketch, and add some points.</p>

<br>
<table Class="Code">
<tr valign="middle">
	<td Class="Code">
	<pre>
Dim oSkPnts As SketchPoints
Set oSkPnts = oSketch.SketchPoints
Call oSkPnts.Add(oTG.CreatePoint2d(0, 0), False)
Call oSkPnts.Add(oTG.CreatePoint2d(1.0, 0), False)
Call oSkPnts.Add(oTG.CreatePoint2d(1.0, 0.5), False)
Call oSkPnts.Add(oTG.CreatePoint2d(2.2, 0.5), False)
Call oSkPnts.Add(oTG.CreatePoint2d(0.5, 1.5), False)
Call oSkPnts.Add(oTG.CreatePoint2d(0, 1.0), False)
Call oSkPnts.Add(oTG.CreatePoint2d(2.7, 1.5), False)
Call oSkPnts.Add(oTG.CreatePoint2d(0.5, 1.0), False)
</pre></td></tr>
</table>
<br>

<p Class="Normal">Using the previously defined sketch points, add some lines to the SketchLines collection. Here the SketchLine objects are added to an array for easy reference later.</p>

<br>
<table Class="Code">
<tr valign="middle">
	<td Class="Code">
	<pre>
Dim oLines As SketchLines
Set oLines = oSketch.SketchLines
Dim oLine(1 To 6) As SketchLine
Set oLine(1) = oLines.AddByTwoPoints(oSkPnts(1), oSkPnts(2))
Set oLine(2) = oLines.AddByTwoPoints(oSkPnts(2), oSkPnts(3))
Set oLine(3) = oLines.AddByTwoPoints(oSkPnts(3), oSkPnts(4))
Set oLine(4) = oLines.AddByTwoPoints(oSkPnts(4), oSkPnts(7))
Set oLine(5) = oLines.AddByTwoPoints(oSkPnts(7), oSkPnts(5))
Set oLine(6) = oLines.AddByTwoPoints(oSkPnts(6), oSkPnts(1))
</pre></td></tr>
</table>
<br>

<p Class="Normal">Add an arc to the SketchArcs collection.</p>

<br>
<table Class="Code">
<tr valign="middle">
	<td Class="Code">
	<pre>
Dim oArc As SketchArc
Dim oArcs As SketchArcs
Set oArcs = oSketch.SketchArcs
Set oArc = oArcs.AddByCenterStartEndPoint(oSkPnts(8), oSkPnts(5), oSkPnts(6))
</pre></td></tr>
</table>
<br>

<p Class="Normal">The code to this point creates a sketch with no constraints, appearing as follows:</p>

<br>
<div align="center"> <img src="../images/ov.cons1.png" border=0></div>
<br>

<p Class="Normal">Now add some constraints. First, add a perpendicular constraint between two lines.</p>

<br>
<table Class="Code">
<tr valign="middle">
	<td Class="Code">
	<pre>
Call oSketch.GeometricConstraints.AddPerpendicular(oLine(4), oLine(5))
oApp.ActiveView.Update
</pre></td></tr>
</table>
<br>

<p Class="Normal">The preceding code modifies the appearance of the sketch as follows:</p>

<br>
<div align="center"> <img src="../images/ov.cons2.png" border=0></div>
<br>

<p Class="Normal">Add tangent constraints to the two lines that join to both ends of the arc.</p>

<br>
<table Class="Code">
<tr valign="middle">
	<td Class="Code">
	<pre>
Call oSketch.GeometricConstraints.AddTangent(oLine(5), oArc)
Call oSketch.GeometricConstraints.AddTangent(oLine(6), oArc)
oApp.ActiveView.Update
</pre></td></tr>
</table>
<br>

<p Class="Normal">This has no apparent effect - yet - since the lines and arc are already tangential. To see the effect of the tangent constraints, add a parallel constraint between two lines:</p>

<br>
<table Class="Code">
<tr valign="middle">
	<td Class="Code">
	<pre>
Call oSketch.GeometricConstraints.AddParallel(oLine(3), oLine(5))
oApp.ActiveView.Update
</pre></td></tr>
</table>
<br>

The cumulative effect of these tangential and parallel constraints is as follows:

<br>
<div align="center"> <img src="../images/ov.cons3.png" border=0></div>
<br>

<p Class="Normal">Now constrain the lower angled line to always be horizontal.</p>

<br>
<table Class="Code">
<tr valign="middle">
	<td Class="Code">
	<pre>
Call oSketch.GeometricConstraints.AddHorizontal(oLine(5))
oApp.ActiveView.Update
</pre></td></tr>
</table>
<br>

The horizontal constraint results in the following change to the sketch:

<br>
<div align="center"> <img src="../images/ov.cons4.png" border=0></div>
<br>

<p Class="Normal">Add breakpoints or comment out some of the preceding constraint code to see the effect of different constraints, including the effect of changing the order in which they are applied.  The sketch points, unless grounded with a GroundConstraint, are not fixed despite the preceding code having supplied absolute coordinate points. The shape of the sketch is governed by the constraints.</p>

<h3>API versus the User Interface</h3>

<p Class="Normal">There are some situations, typically involving sketch points, where applying a constraint through the UI works, but the same constraint applied through the API apparently fails. This is not an error, but a reflection of the fact that the UI hides some of the complexities of constraints from the user, while the API does not.  For example, creating a coincident constraint between two sketch line endpoints through the API may fail, while the same operation through the UI succeeds. The UI lets you apply a coincident constraint between these two points, but if you look at the results, there is no coincident constraint. In fact, Autodesk Inventor deleted one sketch point and changed both lines to share the remaining point.  The API does not hide this from the user since the API expects to return the coincident constraint object, but cannot do that if none were really created.  To emulate the UI, merge the sketch points using SketchPoint.Merge.</p>

<h3>Summary</h3>

<p Class="Normal">Sketch constraints remove successive degrees of freedom in how the sketch is evaluated. It is possible to overconstrain a sketch, so that constraints conflict and cannot be resolved.  The UI provides a dialog box to resolve the conflict, while the corresponding API call fails. Sketches can also have dimensional (size) constraints applied to them.</p>

<h3>Also consider -</h3>

<p Class="Normal">The Autodesk Inventor user interface automatically highlights those parts of a sketch that are appropriate for creating a part feature, such as an extrusion.  The API has a specific object to define what constitutes the input for feature creation - the <a href="Profile.htm" data-topic-id="GUID-Profile">Profile</a> object.</p>

<br />
<br />
<div id="CopyrightNotice" style="display:none;">
  <hr />
  <table width="100%" style="font-size:15">
	<tr>
	  <td align="left">
		&copy; Copyright 2025 Autodesk, Inc.
	  </td>
	  <td align="right">
		<a href="mailto:mfg.api.help.comments@autodesk.com?subject=Inventor%202026%20API%20Help%20(SketchConstraints_Overview)">Comment on this page.</a>
	  </td>
	</tr>
  </table>
</div>

</body>
</html>
