<html>
  <head>
    <META http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="topic-type" content="reference-adsk">
    <meta name="helpsystempath" content="/view/INVNTOR/2026/ENU/">
    <link rel="canonical" href="/cloudhelp/2026/ENU/Inventor-API/files/SketchedSymbolDefinition_Sample.htm#!">
    <meta name="product" content="INVNTOR">
    <meta name="release" content="2026">
    <meta name="book" content="Developer">
    <meta name="component" content="Inventor-API">
    <meta name="created" content="">
    <meta name="user-comments" content="enable">
    <meta name="contextid" content="SketchedSymbolDefinition_Sample">
    <meta name="description" content="Create SketchedSymbol Definition Sample">
    <meta name="topicid" content="SketchedSymbolDefinition_Sample">
    <meta name="experiencelevel" content="expert">
    <meta name="audience" content="programmer">
    <meta name="language" content="ENU">
    <title>Create SketchedSymbol Definition</title>
    <link rel="stylesheet" href="../Style/jquery-ui.css"><script src="../Scripts/jquery-1.11.1.js"></script><script src="../Scripts/jquery-ui.js"></script><link rel="stylesheet" type="text/css" href="../Style/APIHelp-chm.css">
    <link rel="stylesheet" type="text/css" href="/view/clientframework/client.css"><script type="text/javascript" src="/view/clientframework/client.js"></script><script>
          // This turns on the display of the copyright notice which is not visible by default.
          // Because the head is removed when used in the web help, this function will only exists
          // when the chm help is being created.
          window.onload = function() {
          copyrightElement = document.getElementById('CopyrightNotice');
          copyrightElement.style.display = 'block';
          };
        </script><script>
          $(function() {
          $( "#tabs" ).tabs();
          });
        </script></head>
  <body><script>
          function copyCode(language) {
          // Get the pre element for the specified language.
          var preElement = document.getElementById(language);

          // Get the text from the element and copy it to the clipboard.
          var preText = preElement.innerText;

          var isIE = /*@cc_on!@*/false || !!document.documentMode;

          if (isIE)
          {
            window.clipboardData.setData('Text', preText);
          }
          else
          {
            navigator.clipboard.writeText(preText);
          }

          //alert("Code copied to clipboard");
          }
        </script><link rel="stylesheet" type="text/css" href="../Style/APIHelp.css">
    <h1 class="api">Create SketchedSymbol Definition</h1>
    <h2 class="api">
          Description
        </h2>This sample illustrates creating a new sketched symbol definition object and inserting it into the active sheet.<h2 class="api">
          Code Samples
        </h2>
    <div id="tabs">
      <ul>
        <li><a href="#VBA">VBA</a></li>
        <li><a href="#iLogic">iLogic</a></li>
      </ul>
      <div id="VBA" class="api-code">This sample consists of two subs. The first demonstrates the creation of a sketched symbol definition and the second inserts it into the active sheet. To run the sample have a drawing document open and run the CreateSketchedSymbolDefinition Sub. After this you can run the InsertSketchedSymbolOnSheet to insert the sketched symbol into the active sheet. The insertion sub demonstrates the use of the insertion point in the symbol's definition while inserting the symbol.<table width="100%" style="font-size:15">
          <tr>
            <td align="right"><button onclick="copyCode('VBA_code')" class="copy-code">Copy Code</button></td>
          </tr>
        </table>
        <pre class="api-code" id="VBA_code">Public Sub CreateSketchedSymbolDefinition()
    <span style="color:blue">' Set a reference to the drawing document.</span>
    <span style="color:blue">' This assumes a drawing document is active.</span>
    Dim oDrawDoc As DrawingDocument
    Set oDrawDoc = ThisApplication.ActiveDocument

    <span style="color:blue">' Create the new sketched symbol definition.</span>
    Dim oSketchedSymbolDef As SketchedSymbolDefinition
    Set oSketchedSymbolDef = oDrawDoc.SketchedSymbolDefinitions.Add("Circular Callout")

    <span style="color:blue">' Open the sketched symbol definition's sketch for edit. This is done by calling the Edit</span>
    <span style="color:blue">' method of the SketchedSymbolDefinition to obtain a DrawingSketch. This actually creates</span>
    <span style="color:blue">' a copy of the sketched symbol definition's and opens it for edit.</span>
    Dim oSketch As DrawingSketch
    Call oSketchedSymbolDef.Edit(oSketch)

    Dim oTG As TransientGeometry
    Set oTG = ThisApplication.TransientGeometry

    <span style="color:blue">' Use the functionality of the sketch to add sketched symbol graphics.</span>
    Dim oSketchLine As SketchLine
    Set oSketchLine = oSketch.SketchLines.AddByTwoPoints(oTG.CreatePoint2d(0, 0), oTG.CreatePoint2d(20, 0))

    Dim oSketchCircle As SketchCircle
    Set oSketchCircle = oSketch.SketchCircles.AddByCenterRadius(oTG.CreatePoint2d(22, 0), 2)

    Call oSketch.GeometricConstraints.AddCoincident(oSketchLine.EndSketchPoint, oSketchCircle)

    <span style="color:blue">' Make the starting point of the sketch line the insertion point</span>
    oSketchLine.StartSketchPoint.InsertionPoint = True

    <span style="color:blue">' Add a prompted text field at the center of the sketch circle.</span>
    Dim sText As String
    sText = "&lt;Prompt&gt;Enter text 1&lt;/Prompt&gt;"
    Dim oTextBox As TextBox
    Set oTextBox = oSketch.TextBoxes.AddFitted(oTG.CreatePoint2d(22, 0), sText)
    oTextBox.VerticalJustification = kAlignTextMiddle
    oTextBox.HorizontalJustification = kAlignTextCenter

    Call oSketchedSymbolDef.ExitEdit(True)
End Sub

Public Sub InsertSketchedSymbolOnSheet()
    <span style="color:blue">' Set a reference to the drawing document.</span>
    <span style="color:blue">' This assumes a drawing document is active.</span>
    Dim oDrawDoc As DrawingDocument
    Set oDrawDoc = ThisApplication.ActiveDocument

    <span style="color:blue">' Obtain a reference to the desired sketched symbol definition.</span>
    Dim oSketchedSymbolDef As SketchedSymbolDefinition
    Set oSketchedSymbolDef = oDrawDoc.SketchedSymbolDefinitions.Item("Circular Callout")

    Dim oSheet As Sheet
    Set oSheet = oDrawDoc.ActiveSheet

    <span style="color:blue">' This sketched symbol definition contains one prompted string input. An array</span>
    <span style="color:blue">' must be input that contains the strings for the prompted strings.</span>
    Dim sPromptStrings(0) As String
    sPromptStrings(0) = "A"

    Dim oTG As TransientGeometry
    Set oTG = ThisApplication.TransientGeometry

    <span style="color:blue">' Add an instance of the sketched symbol definition to the sheet.</span>
    <span style="color:blue">' Rotate the instance by 45 degrees and scale by .75 when adding.</span>
    <span style="color:blue">' The symbol will be inserted at (0,0) on the sheet. Since the</span>
    <span style="color:blue">' start point of the line was marked as the insertion point, the</span>
    <span style="color:blue">' start point should end up at (0,0).</span>
    Dim oSketchedSymbol As SketchedSymbol
    Set oSketchedSymbol = oSheet.SketchedSymbols.Add(oSketchedSymbolDef, oTG.CreatePoint2d(0, 0), (3.14159 / 4), 0.75, sPromptStrings)
End Sub</pre>
      </div>
      <div id="iLogic" class="api-code">This sample consists of two subs. The first demonstrates the creation of a sketched symbol definition and the second inserts it into the active sheet. To run the sample have a drawing document open and run the CreateSketchedSymbolDefinition Sub. After this you can run the InsertSketchedSymbolOnSheet to insert the sketched symbol into the active sheet. The insertion sub demonstrates the use of the insertion point in the symbol's definition while inserting the symbol.<table width="100%" style="font-size:15">
          <tr>
            <td align="right"><button onclick="copyCode('iLogic_code')" class="copy-code">Copy Code</button></td>
          </tr>
        </table>
        <pre class="api-code" id="iLogic_code">Sub Main
    <span style="color:blue">' Set a reference to the drawing document.</span>
    <span style="color:blue">' This assumes a drawing document is active.</span>
    Dim oDrawDoc As DrawingDocument
    oDrawDoc = ThisApplication.ActiveDocument

    <span style="color:blue">' Create the new sketched symbol definition.</span>
    Dim oSketchedSymbolDef As SketchedSymbolDefinition
    oSketchedSymbolDef = oDrawDoc.SketchedSymbolDefinitions.Add("Circular Callout")

    <span style="color:blue">' Open the sketched symbol definition's sketch for edit. This is done by calling the Edit</span>
    <span style="color:blue">' method of the SketchedSymbolDefinition to obtain a DrawingSketch. This actually creates</span>
    <span style="color:blue">' a copy of the sketched symbol definition's and opens it for edit.</span>
    Dim oSketch As DrawingSketch
    Call oSketchedSymbolDef.Edit(oSketch)

    Dim oTG As TransientGeometry
    oTG = ThisApplication.TransientGeometry

    <span style="color:blue">' Use the functionality of the sketch to add sketched symbol graphics.</span>
    Dim oSketchLine As SketchLine
    oSketchLine = oSketch.SketchLines.AddByTwoPoints(oTG.CreatePoint2d(0, 0), oTG.CreatePoint2d(20, 0))

    Dim oSketchCircle As SketchCircle
    oSketchCircle = oSketch.SketchCircles.AddByCenterRadius(oTG.CreatePoint2d(22, 0), 2)

    Call oSketch.GeometricConstraints.AddCoincident(oSketchLine.EndSketchPoint, oSketchCircle)

    <span style="color:blue">' Make the starting point of the sketch line the insertion point</span>
    oSketchLine.StartSketchPoint.InsertionPoint = True

    <span style="color:blue">' Add a prompted text field at the center of the sketch circle.</span>
    Dim sText As String
    sText = "&lt;Prompt&gt;Enter text 1&lt;/Prompt&gt;"
    Dim oTextBox As TextBox
    oTextBox = oSketch.TextBoxes.AddFitted(oTG.CreatePoint2d(22, 0), sText)
    oTextBox.VerticalJustification = kAlignTextMiddle
    oTextBox.HorizontalJustification = kAlignTextCenter

    Call oSketchedSymbolDef.ExitEdit(True)
End Sub

Public Sub InsertSketchedSymbolOnSheet()
    <span style="color:blue">' Set a reference to the drawing document.</span>
    <span style="color:blue">' This assumes a drawing document is active.</span>
    Dim oDrawDoc As DrawingDocument
    oDrawDoc = ThisApplication.ActiveDocument

    <span style="color:blue">' Obtain a reference to the desired sketched symbol definition.</span>
    Dim oSketchedSymbolDef As SketchedSymbolDefinition
    oSketchedSymbolDef = oDrawDoc.SketchedSymbolDefinitions.Item("Circular Callout")

    Dim oSheet As Sheet
    oSheet = oDrawDoc.ActiveSheet

    <span style="color:blue">' This sketched symbol definition contains one prompted string input. An array</span>
    <span style="color:blue">' must be input that contains the strings for the prompted strings.</span>
    Dim sPromptStrings(0) As String
    sPromptStrings(0) = "A"

    Dim oTG As TransientGeometry
    oTG = ThisApplication.TransientGeometry

    <span style="color:blue">' Add an instance of the sketched symbol definition to the sheet.</span>
    <span style="color:blue">' Rotate the instance by 45 degrees and scale by .75 when adding.</span>
    <span style="color:blue">' The symbol will be inserted at (0,0) on the sheet. Since the</span>
    <span style="color:blue">' start point of the line was marked as the insertion point, the</span>
    <span style="color:blue">' start point should end up at (0,0).</span>
    Dim oSketchedSymbol As SketchedSymbol
    oSketchedSymbol = oSheet.SketchedSymbols.Add(oSketchedSymbolDef, oTG.CreatePoint2d(0, 0), (3.14159 / 4), 0.75, sPromptStrings)
End Sub</pre>
      </div>
    </div><br><br><div id="CopyrightNotice" style="display:none;">
      <hr>
      <table width="100%" style="font-size:15">
        <tr>
          <td align="left">
                Â© Copyright 2025 Autodesk, Inc.
              </td>
          <td align="right"><a href="mailto:mfg.api.help.comments@autodesk.com?subject=Inventor%202026%20API%20Help%20(SketchedSymbolDefinition%20Sample%20Help%20Topic)">Comment on this page.</a></td>
        </tr>
      </table>
    </div>
  </body>
</html>