<html>
  <head>
    <META http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="topic-type" content="reference-adsk">
    <meta name="helpsystempath" content="/view/INVNTOR/2026/ENU/">
    <link rel="canonical" href="/cloudhelp/2026/ENU/Inventor-API/files/Sketch_SketchLines_Sample.htm#!">
    <meta name="product" content="INVNTOR">
    <meta name="release" content="2026">
    <meta name="book" content="Developer">
    <meta name="component" content="Inventor-API">
    <meta name="created" content="">
    <meta name="user-comments" content="enable">
    <meta name="contextid" content="Sketch_SketchLines_Sample">
    <meta name="description" content="Sketch Lines Sample">
    <meta name="topicid" content="Sketch_SketchLines_Sample">
    <meta name="experiencelevel" content="expert">
    <meta name="audience" content="programmer">
    <meta name="language" content="ENU">
    <title>Sketch Lines</title>
    <link rel="stylesheet" href="../Style/jquery-ui.css"><script src="../Scripts/jquery-1.11.1.js"></script><script src="../Scripts/jquery-ui.js"></script><link rel="stylesheet" type="text/css" href="../Style/APIHelp-chm.css">
    <link rel="stylesheet" type="text/css" href="/view/clientframework/client.css"><script type="text/javascript" src="/view/clientframework/client.js"></script><script>
          // This turns on the display of the copyright notice which is not visible by default.
          // Because the head is removed when used in the web help, this function will only exists
          // when the chm help is being created.
          window.onload = function() {
          copyrightElement = document.getElementById('CopyrightNotice');
          copyrightElement.style.display = 'block';
          };
        </script><script>
          $(function() {
          $( "#tabs" ).tabs();
          });
        </script></head>
  <body><script>
          function copyCode(language) {
          // Get the pre element for the specified language.
          var preElement = document.getElementById(language);

          // Get the text from the element and copy it to the clipboard.
          var preText = preElement.innerText;

          var isIE = /*@cc_on!@*/false || !!document.documentMode;

          if (isIE)
          {
            window.clipboardData.setData('Text', preText);
          }
          else
          {
            navigator.clipboard.writeText(preText);
          }

          //alert("Code copied to clipboard");
          }
        </script><link rel="stylesheet" type="text/css" href="../Style/APIHelp.css">
    <h1 class="api">Sketch Lines</h1>
    <h2 class="api">
          Description
        </h2>This sample demonstrates creating lines. It uses all of the various methods to create lines, both singly and as rectangles.<h2 class="api">
          Code Samples
        </h2>
    <div id="tabs">
      <ul>
        <li><a href="#VBA">VBA</a></li>
        <li><a href="#iLogic">iLogic</a></li>
      </ul>
      <div id="VBA" class="api-code">To run this sample you must have a sketch active.<table width="100%" style="font-size:15">
          <tr>
            <td align="right"><button onclick="copyCode('VBA_code')" class="copy-code">Copy Code</button></td>
          </tr>
        </table>
        <pre class="api-code" id="VBA_code">Public Sub DrawSketchLine()
    <span style="color:blue">' Check to make sure a sketch is open.</span>
    If Not TypeOf ThisApplication.ActiveEditObject Is PlanarSketch Then
      MsgBox "A sketch must be active."
      Exit Sub
    End If

    <span style="color:blue">' Set a reference to the active sketch.</span>
    Dim oSketch As PlanarSketch
    Set oSketch = ThisApplication.ActiveEditObject

    <span style="color:blue">' Set a reference to the transient geometry collection.</span>
    Dim oTransGeom As TransientGeometry
    Set oTransGeom = ThisApplication.TransientGeometry

    <span style="color:blue">' Create a new transaction to wrap the construction of the three lines</span>
    <span style="color:blue">' into a single undo.</span>
    Dim oTrans As Transaction
    Set oTrans = ThisApplication.TransactionManager.StartTransaction( _
    ThisApplication.ActiveDocument, _
    "Create Triangle Sample")

    <span style="color:blue">' Create the first line of the triangle. This uses two transient points as</span>
    <span style="color:blue">' input to definethe coordinates of the ends of the line. Since a transient</span>
    <span style="color:blue">' point is input a sketch point is automatically created at that location and</span>
    <span style="color:blue">' the line is attached to it.</span>
    Dim oLines(1 To 3) As SketchLine
    Set oLines(1) = oSketch.SketchLines.AddByTwoPoints(oTransGeom.CreatePoint2d(0, 0), _
    oTransGeom.CreatePoint2d(4, 0))

    <span style="color:blue">' Create a sketch line that is connected to the sketch point the previous lines</span>
    <span style="color:blue">' end point is connected to. This will automatically create the constraint to</span>
    <span style="color:blue">' tie the new line to the sketch point the previous line is also connected to.</span>
    <span style="color:blue">' This will result in the the two lines being connected since they're both tied</span>
    <span style="color:blue">' to the same sketch point.</span>
    Set oLines(2) = oSketch.SketchLines.AddByTwoPoints(oLines(1).EndSketchPoint, _
    oTransGeom.CreatePoint2d(2, 3))

    <span style="color:blue">' Create a third line and connect it to the start point of the first line and the</span>
    <span style="color:blue">' end point of the second line. This will result in a connected triangle.</span>
    Set oLines(3) = oSketch.SketchLines.AddByTwoPoints(oLines(2).EndSketchPoint, _
    oLines(1).StartSketchPoint)

    <span style="color:blue">' End the transaction for the triangle.</span>
    oTrans.End

    <span style="color:blue">' Create a rectangle whose lines are parallel to the sketch planes x and y axes</span>
    <span style="color:blue">' by using the SketchLines.AddAsTwoPointRectangle method. The top point of the</span>
    <span style="color:blue">' triangle will be used as input for one of the points so the rectangle will be</span>
    <span style="color:blue">' tied to that point.</span>
    Dim oRectangleLines As SketchEntitiesEnumerator
    Set oRectangleLines = oSketch.SketchLines.AddAsTwoPointRectangle( _
    oLines(3).StartSketchPoint, _
    oTransGeom.CreatePoint2d(5, 5))

    <span style="color:blue">' Create a rotated rectangle by using the SketchLines.AddAsTwoRectangle method.</span>
    <span style="color:blue">' One of the corners of this rectangle will be tied to the corner of the previous</span>
    <span style="color:blue">' rectangle.</span>
    Set oRectangleLines = oSketch.SketchLines.AddAsThreePointRectangle( _
    oRectangleLines(2).EndSketchPoint, _
    oTransGeom.CreatePoint2d(7, 3), _
    oTransGeom.CreatePoint2d(8, 8))
End Sub</pre>
      </div>
      <div id="iLogic" class="api-code">To run this sample you must have a sketch active.<table width="100%" style="font-size:15">
          <tr>
            <td align="right"><button onclick="copyCode('iLogic_code')" class="copy-code">Copy Code</button></td>
          </tr>
        </table>
        <pre class="api-code" id="iLogic_code">    <span style="color:blue">' Check to make sure a sketch is open.</span>
    If Not TypeOf ThisApplication.ActiveEditObject Is PlanarSketch Then
      MsgBox("A sketch must be active.")
      Exit Sub
    End If

    <span style="color:blue">' Set a reference to the active sketch.</span>
    Dim oSketch As PlanarSketch
    oSketch = ThisApplication.ActiveEditObject

    <span style="color:blue">' Set a reference to the transient geometry collection.</span>
    Dim oTransGeom As TransientGeometry
    oTransGeom = ThisApplication.TransientGeometry

    <span style="color:blue">' Create a new transaction to wrap the construction of the three lines</span>
    <span style="color:blue">' into a single undo.</span>
    Dim oTrans As Transaction
    oTrans = ThisApplication.TransactionManager.StartTransaction( _
    ThisApplication.ActiveDocument, _
    "Create Triangle Sample")

    <span style="color:blue">' Create the first line of the triangle. This uses two transient points as</span>
    <span style="color:blue">' input to definethe coordinates of the ends of the line. Since a transient</span>
    <span style="color:blue">' point is input a sketch point is automatically created at that location and</span>
    <span style="color:blue">' the line is attached to it.</span>
    Dim oLines(0 To 2) As SketchLine
    oLines(0) = oSketch.SketchLines.AddByTwoPoints(oTransGeom.CreatePoint2d(0, 0), _
    oTransGeom.CreatePoint2d(4, 0))

    <span style="color:blue">' Create a sketch line that is connected to the sketch point the previous lines</span>
    <span style="color:blue">' end point is connected to. This will automatically create the constraint to</span>
    <span style="color:blue">' tie the new line to the sketch point the previous line is also connected to.</span>
    <span style="color:blue">' This will result in the the two lines being connected since they're both tied</span>
    <span style="color:blue">' to the same sketch point.</span>
    oLines(1) = oSketch.SketchLines.AddByTwoPoints(oLines(0).EndSketchPoint, _
    oTransGeom.CreatePoint2d(2, 3))

    <span style="color:blue">' Create a third line and connect it to the start point of the first line and the</span>
    <span style="color:blue">' end point of the second line. This will result in a connected triangle.</span>
    oLines(2) = oSketch.SketchLines.AddByTwoPoints(oLines(1).EndSketchPoint, _
    oLines(0).StartSketchPoint)

    <span style="color:blue">' End the transaction for the triangle.</span>
    oTrans.End

    <span style="color:blue">' Create a rectangle whose lines are parallel to the sketch planes x and y axes</span>
    <span style="color:blue">' by using the SketchLines.AddAsTwoPointRectangle method. The top point of the</span>
    <span style="color:blue">' triangle will be used as input for one of the points so the rectangle will be</span>
    <span style="color:blue">' tied to that point.</span>
    Dim oRectangleLines As SketchEntitiesEnumerator
    oRectangleLines = oSketch.SketchLines.AddAsTwoPointRectangle( _
    oLines(2).StartSketchPoint, _
    oTransGeom.CreatePoint2d(5, 5))

    <span style="color:blue">' Create a rotated rectangle by using the SketchLines.AddAsTwoRectangle method.</span>
    <span style="color:blue">' One of the corners of this rectangle will be tied to the corner of the previous</span>
    <span style="color:blue">' rectangle.</span>
    oRectangleLines = oSketch.SketchLines.AddAsThreePointRectangle( _
    oRectangleLines(2).EndSketchPoint, _
    oTransGeom.CreatePoint2d(7, 3), _
    oTransGeom.CreatePoint2d(8, 8))</pre>
      </div>
    </div><br><br><div id="CopyrightNotice" style="display:none;">
      <hr>
      <table width="100%" style="font-size:15">
        <tr>
          <td align="left">
                Â© Copyright 2025 Autodesk, Inc.
              </td>
          <td align="right"><a href="mailto:mfg.api.help.comments@autodesk.com?subject=Inventor%202026%20API%20Help%20(Sketch_SketchLines%20Sample%20Help%20Topic)">Comment on this page.</a></td>
        </tr>
      </table>
    </div>
  </body>
</html>