<html>
  <head>
    <META http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="topic-type" content="reference-adsk">
    <meta name="helpsystempath" content="/view/INVNTOR/2026/ENU/">
    <link rel="canonical" href="/cloudhelp/2026/ENU/Inventor-API/files/Sketch_OffsetSketchEntitiesUsingDistance_Sample.htm#!">
    <meta name="product" content="INVNTOR">
    <meta name="release" content="2026">
    <meta name="book" content="Developer">
    <meta name="component" content="Inventor-API">
    <meta name="created" content="">
    <meta name="user-comments" content="enable">
    <meta name="contextid" content="Sketch_OffsetSketchEntitiesUsingDistance_Sample">
    <meta name="description" content="Offset a 2D sketch Sample">
    <meta name="topicid" content="Sketch_OffsetSketchEntitiesUsingDistance_Sample">
    <meta name="experiencelevel" content="expert">
    <meta name="audience" content="programmer">
    <meta name="language" content="ENU">
    <title>Offset a 2D sketch</title>
    <link rel="stylesheet" href="../Style/jquery-ui.css"><script src="../Scripts/jquery-1.11.1.js"></script><script src="../Scripts/jquery-ui.js"></script><link rel="stylesheet" type="text/css" href="../Style/APIHelp-chm.css">
    <link rel="stylesheet" type="text/css" href="/view/clientframework/client.css"><script type="text/javascript" src="/view/clientframework/client.js"></script><script>
          // This turns on the display of the copyright notice which is not visible by default.
          // Because the head is removed when used in the web help, this function will only exists
          // when the chm help is being created.
          window.onload = function() {
          copyrightElement = document.getElementById('CopyrightNotice');
          copyrightElement.style.display = 'block';
          };
        </script><script>
          $(function() {
          $( "#tabs" ).tabs();
          });
        </script></head>
  <body><script>
          function copyCode(language) {
          // Get the pre element for the specified language.
          var preElement = document.getElementById(language);

          // Get the text from the element and copy it to the clipboard.
          var preText = preElement.innerText;

          var isIE = /*@cc_on!@*/false || !!document.documentMode;

          if (isIE)
          {
            window.clipboardData.setData('Text', preText);
          }
          else
          {
            navigator.clipboard.writeText(preText);
          }

          //alert("Code copied to clipboard");
          }
        </script><link rel="stylesheet" type="text/css" href="../Style/APIHelp.css">
    <h1 class="api">Offset a 2D sketch</h1>
    <h2 class="api">
          Description
        </h2>This sample demonstrates the creation of offsets in 2d sketches. Two ways of creating the offset are shown - one uses a distance and the other uses the input point.<h2 class="api">
          Code Samples
        </h2>
    <div id="tabs">
      <ul>
        <li><a href="#VBA">VBA</a></li>
        <li><a href="#iLogic">iLogic</a></li>
      </ul>
      <div id="VBA" class="api-code">
        <table width="100%" style="font-size:15">
          <tr>
            <td align="right"><button onclick="copyCode('VBA_code')" class="copy-code">Copy Code</button></td>
          </tr>
        </table>
        <pre class="api-code" id="VBA_code">Public Sub Offset()
    <span style="color:blue">' Check to make sure a sketch is open.</span>
    If Not Typeof ThisApplication.ActiveEditObject Is PlanarSketch Then
        MsgBox "A sketch must be active."
        Exit Sub
    End If

    <span style="color:blue">' Set a reference to the active sketch.</span>
    Dim oSketch As PlanarSketch
    Set oSketch = ThisApplication.ActiveEditObject

    <span style="color:blue">' Set a reference to the transient geometry collection.</span>
    Dim oTransGeom As TransientGeometry
    Set oTransGeom = ThisApplication.TransientGeometry

    <span style="color:blue">' Create a rectangle</span>
    Dim oRectangleLines As SketchEntitiesEnumerator
    Set oRectangleLines = oSketch.SketchLines.AddAsTwoPointRectangle( _
                                                oTransGeom.CreatePoint2d(0, 0), _
                                                oTransGeom.CreatePoint2d(10, -10))
                                                
    <span style="color:blue">' Create a new object collection</span>
    Dim oCollection As ObjectCollection
    Set oCollection = ThisApplication.TransientObjects.CreateObjectCollection
    
    <span style="color:blue">' Add the first sketch line of the rectangle to the collection</span>
    oCollection.Add oRectangleLines.Item(1)
    
    <span style="color:blue">' Create a point at (0,3). The entity resulting</span>
    <span style="color:blue">' from the offset of the first sketch line must</span>
    <span style="color:blue">' pass thru this point.</span>
    Dim oOffsetPoint As Point2d
    Set oOffsetPoint = oTransGeom.CreatePoint2d(0, 3)
    
    <span style="color:blue">' Create an offset rectangle using the offset point.</span>
    Call oSketch.OffsetSketchEntitiesUsingPoint(oCollection, oOffsetPoint, True)
    
    <span style="color:blue">' Get the sketch normal</span>
    Dim oNormalVector As UnitVector
    Set oNormalVector = oSketch.PlanarEntityGeometry.Normal
    
    <span style="color:blue">' Get the direction of the sketch line being offset</span>
    Dim oLineDir As UnitVector2d
    Set oLineDir = oRectangleLines.Item(1).Geometry.Direction
    
    Dim oLineVector As UnitVector
    Set oLineVector = oTransGeom.CreateUnitVector(oLineDir.X, oLineDir.Y, 0)
    
    <span style="color:blue">' The cross product of these vectors is the</span>
    <span style="color:blue">' natural offset direction for the sketch line.</span>
    Dim oOffsetVector As UnitVector
    Set oOffsetVector = oLineVector.CrossProduct(oNormalVector)
    
    <span style="color:blue">' Get the desired offset vector (the +ve y-axis)</span>
    Dim oDesiredVector As UnitVector
    Set oDesiredVector = oTransGeom.CreateUnitVector(0, 1, 0)
    
    Dim bNaturalOffsetDir As Boolean
    
    If oOffsetVector.IsEqualTo(oDesiredVector) Then
        bNaturalOffsetDir = True
    Else
        bNaturalOffsetDir = False
    End If
    
    <span style="color:blue">' Create an offset at a distance of 6 cms.</span>
    Call oSketch.OffsetSketchEntitiesUsingDistance(oCollection, 6, bNaturalOffsetDir, True)
End Sub</pre>
      </div>
      <div id="iLogic" class="api-code">
        <table width="100%" style="font-size:15">
          <tr>
            <td align="right"><button onclick="copyCode('iLogic_code')" class="copy-code">Copy Code</button></td>
          </tr>
        </table>
        <pre class="api-code" id="iLogic_code">    <span style="color:blue">' Check to make sure a sketch is open.</span>
    If Not Typeof ThisApplication.ActiveEditObject Is PlanarSketch Then
        MsgBox("A sketch must be active.")
        Exit Sub
    End If

    <span style="color:blue">' Set a reference to the active sketch.</span>
    Dim oSketch As PlanarSketch
    oSketch = ThisApplication.ActiveEditObject

    <span style="color:blue">' Set a reference to the transient geometry collection.</span>
    Dim oTransGeom As TransientGeometry
    oTransGeom = ThisApplication.TransientGeometry

    <span style="color:blue">' Create a rectangle</span>
    Dim oRectangleLines As SketchEntitiesEnumerator
    oRectangleLines = oSketch.SketchLines.AddAsTwoPointRectangle( _
                                                oTransGeom.CreatePoint2d(0, 0), _
                                                oTransGeom.CreatePoint2d(10, -10))
                                                
    <span style="color:blue">' Create a new object collection</span>
    Dim oCollection As ObjectCollection
    oCollection = ThisApplication.TransientObjects.CreateObjectCollection
    
    <span style="color:blue">' Add the first sketch line of the rectangle to the collection</span>
    oCollection.Add(oRectangleLines.Item(1))
    
    <span style="color:blue">' Create a point at (0,3). The entity resulting</span>
    <span style="color:blue">' from the offset of the first sketch line must</span>
    <span style="color:blue">' pass thru this point.</span>
    Dim oOffsetPoint As Point2d
    oOffsetPoint = oTransGeom.CreatePoint2d(0, 3)
    
    <span style="color:blue">' Create an offset rectangle using the offset point.</span>
    Call oSketch.OffsetSketchEntitiesUsingPoint(oCollection, oOffsetPoint, True)
    
    <span style="color:blue">' Get the sketch normal</span>
    Dim oNormalVector As UnitVector
    oNormalVector = oSketch.PlanarEntityGeometry.Normal
    
    <span style="color:blue">' Get the direction of the sketch line being offset</span>
    Dim oLineDir As UnitVector2d
    oLineDir = oRectangleLines.Item(1).Geometry.Direction
    
    Dim oLineVector As UnitVector
    oLineVector = oTransGeom.CreateUnitVector(oLineDir.X, oLineDir.Y, 0)
    
    <span style="color:blue">' The cross product of these vectors is the</span>
    <span style="color:blue">' natural offset direction for the sketch line.</span>
    Dim oOffsetVector As UnitVector
    oOffsetVector = oLineVector.CrossProduct(oNormalVector)
    
    <span style="color:blue">' Get the desired offset vector (the +ve y-axis)</span>
    Dim oDesiredVector As UnitVector
    oDesiredVector = oTransGeom.CreateUnitVector(0, 1, 0)
    
    Dim bNaturalOffsetDir As Boolean
    
    If oOffsetVector.IsEqualTo(oDesiredVector) Then
        bNaturalOffsetDir = True
    Else
        bNaturalOffsetDir = False
    End If
    
    <span style="color:blue">' Create an offset at a distance of 6 cms.</span>
    Call oSketch.OffsetSketchEntitiesUsingDistance(oCollection, 6, bNaturalOffsetDir, True)</pre>
      </div>
    </div><br><br><div id="CopyrightNotice" style="display:none;">
      <hr>
      <table width="100%" style="font-size:15">
        <tr>
          <td align="left">
                Â© Copyright 2025 Autodesk, Inc.
              </td>
          <td align="right"><a href="mailto:mfg.api.help.comments@autodesk.com?subject=Inventor%202026%20API%20Help%20(Sketch_OffsetSketchEntitiesUsingDistance%20Sample%20Help%20Topic)">Comment on this page.</a></td>
        </tr>
      </table>
    </div>
  </body>
</html>