<html>
  <head>
    <META http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="topic-type" content="reference-adsk">
    <meta name="helpsystempath" content="/view/INVNTOR/2026/ENU/">
    <link rel="canonical" href="/cloudhelp/2026/ENU/Inventor-API/files/SketchEllipticalArc_Sample.htm#!">
    <meta name="product" content="INVNTOR">
    <meta name="release" content="2026">
    <meta name="book" content="Developer">
    <meta name="component" content="Inventor-API">
    <meta name="created" content="">
    <meta name="user-comments" content="enable">
    <meta name="contextid" content="SketchEllipticalArc_Sample">
    <meta name="description" content="Create sketch elliptical arc Sample">
    <meta name="topicid" content="SketchEllipticalArc_Sample">
    <meta name="experiencelevel" content="expert">
    <meta name="audience" content="programmer">
    <meta name="language" content="ENU">
    <title>Create sketch elliptical arc</title>
    <link rel="stylesheet" href="../Style/jquery-ui.css"><script src="../Scripts/jquery-1.11.1.js"></script><script src="../Scripts/jquery-ui.js"></script><link rel="stylesheet" type="text/css" href="../Style/APIHelp-chm.css">
    <link rel="stylesheet" type="text/css" href="/view/clientframework/client.css"><script type="text/javascript" src="/view/clientframework/client.js"></script><script>
          // This turns on the display of the copyright notice which is not visible by default.
          // Because the head is removed when used in the web help, this function will only exists
          // when the chm help is being created.
          window.onload = function() {
          copyrightElement = document.getElementById('CopyrightNotice');
          copyrightElement.style.display = 'block';
          };
        </script><script>
          $(function() {
          $( "#tabs" ).tabs();
          });
        </script></head>
  <body><script>
          function copyCode(language) {
          // Get the pre element for the specified language.
          var preElement = document.getElementById(language);

          // Get the text from the element and copy it to the clipboard.
          var preText = preElement.innerText;

          var isIE = /*@cc_on!@*/false || !!document.documentMode;

          if (isIE)
          {
            window.clipboardData.setData('Text', preText);
          }
          else
          {
            navigator.clipboard.writeText(preText);
          }

          //alert("Code copied to clipboard");
          }
        </script><link rel="stylesheet" type="text/css" href="../Style/APIHelp.css">
    <h1 class="api">Create sketch elliptical arc</h1>
    <h2 class="api">
          Description
        </h2>This sample demonstrates creating an elliptical arc in a sketch and dimensioning its minor radius.<h2 class="api">
          Code Samples
        </h2>
    <div id="tabs">
      <ul>
        <li><a href="#VBA">VBA</a></li>
        <li><a href="#iLogic">iLogic</a></li>
      </ul>
      <div id="VBA" class="api-code">To run this sample you must have a sketch active.<table width="100%" style="font-size:15">
          <tr>
            <td align="right"><button onclick="copyCode('VBA_code')" class="copy-code">Copy Code</button></td>
          </tr>
        </table>
        <pre class="api-code" id="VBA_code">Sub DrawSketchEllipticalArc()
    <span style="color:blue">' Check to make sure a sketch is open.</span>
    If Not Typeof ThisApplication.ActiveEditObject Is PlanarSketch Then
        MsgBox "A sketch must be active."
        Exit Sub
    End If
    
    <span style="color:blue">' Set a reference to the active sketch.</span>
    Dim oSketch As PlanarSketch
    Set oSketch = ThisApplication.ActiveEditObject
    
    <span style="color:blue">' Set a reference to the transient geometry collection.</span>
    Dim oTransGeom As TransientGeometry
    Set oTransGeom = ThisApplication.TransientGeometry
    
    <span style="color:blue">' Arc center point at 0,0</span>
    Dim oCenter As Point2d
    Set oCenter = oTransGeom.CreatePoint2d(0, 0)
    
    <span style="color:blue">' Arc major axis as the y-axis</span>
    Dim oMajorAxis As UnitVector2d
    Set oMajorAxis = oTransGeom.CreateUnitVector2d(0, 1)
    
    Dim PI As Double
    PI = 4# * Atn(1#)

    <span style="color:blue">' Create the elliptical arc</span>
    Dim oEllipticalArc As SketchEllipticalArc
    Set oEllipticalArc = oSketch.SketchEllipticalArcs.Add(oCenter, oMajorAxis, 5, 2, 0, PI / 2)
    
    Dim oTextPt As Point2d
    Set oTextPt = oTransGeom.CreatePoint2d(-1, -0.5)
    
    <span style="color:blue">' Create a radius dimension</span>
    Dim oEllipseRadiusDim As EllipseRadiusDimConstraint
    Set oEllipseRadiusDim = oSketch.DimensionConstraints.AddEllipseRadius(oEllipticalArc, False, oTextPt)
End Sub</pre>
      </div>
      <div id="iLogic" class="api-code">To run this sample you must have a sketch active.<table width="100%" style="font-size:15">
          <tr>
            <td align="right"><button onclick="copyCode('iLogic_code')" class="copy-code">Copy Code</button></td>
          </tr>
        </table>
        <pre class="api-code" id="iLogic_code">    <span style="color:blue">' Check to make sure a sketch is open.</span>
    If Not Typeof ThisApplication.ActiveEditObject Is PlanarSketch Then
        MsgBox("A sketch must be active.")
        Exit Sub
    End If
    
    <span style="color:blue">' Set a reference to the active sketch.</span>
    Dim oSketch As PlanarSketch
    oSketch = ThisApplication.ActiveEditObject
    
    <span style="color:blue">' Set a reference to the transient geometry collection.</span>
    Dim oTransGeom As TransientGeometry
    oTransGeom = ThisApplication.TransientGeometry
    
    <span style="color:blue">' Arc center point at 0,0</span>
    Dim oCenter As Point2d
    oCenter = oTransGeom.CreatePoint2d(0, 0)
    
    <span style="color:blue">' Arc major axis as the y-axis</span>
    Dim oMajorAxis As UnitVector2d
    oMajorAxis = oTransGeom.CreateUnitVector2d(0, 1)
    
    Dim PI As Double
    PI = 4# * Math.Atan(1#)

    <span style="color:blue">' Create the elliptical arc</span>
    Dim oEllipticalArc As SketchEllipticalArc
    oEllipticalArc = oSketch.SketchEllipticalArcs.Add(oCenter, oMajorAxis, 5, 2, 0, PI / 2)
    
    Dim oTextPt As Point2d
    oTextPt = oTransGeom.CreatePoint2d(-1, -0.5)
    
    <span style="color:blue">' Create a radius dimension</span>
    Dim oEllipseRadiusDim As EllipseRadiusDimConstraint
    oEllipseRadiusDim = oSketch.DimensionConstraints.AddEllipseRadius(oEllipticalArc, False, oTextPt)</pre>
      </div>
    </div><br><br><div id="CopyrightNotice" style="display:none;">
      <hr>
      <table width="100%" style="font-size:15">
        <tr>
          <td align="left">
                Â© Copyright 2025 Autodesk, Inc.
              </td>
          <td align="right"><a href="mailto:mfg.api.help.comments@autodesk.com?subject=Inventor%202026%20API%20Help%20(SketchEllipticalArc%20Sample%20Help%20Topic)">Comment on this page.</a></td>
        </tr>
      </table>
    </div>
  </body>
</html>