<html>
  <head>
    <META http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="topic-type" content="reference-adsk">
    <meta name="helpsystempath" content="/view/INVNTOR/2026/ENU/">
    <link rel="canonical" href="/cloudhelp/2026/ENU/Inventor-API/files/Split2DCurve_Sample.htm#!">
    <meta name="product" content="INVNTOR">
    <meta name="release" content="2026">
    <meta name="book" content="Developer">
    <meta name="component" content="Inventor-API">
    <meta name="created" content="">
    <meta name="user-comments" content="enable">
    <meta name="contextid" content="Split2DCurve_Sample">
    <meta name="description" content="Split a 2D Curve Sample">
    <meta name="topicid" content="Split2DCurve_Sample">
    <meta name="experiencelevel" content="expert">
    <meta name="audience" content="programmer">
    <meta name="language" content="ENU">
    <title>Split a 2D Curve</title>
    <link rel="stylesheet" href="../Style/jquery-ui.css"><script src="../Scripts/jquery-1.11.1.js"></script><script src="../Scripts/jquery-ui.js"></script><link rel="stylesheet" type="text/css" href="../Style/APIHelp-chm.css">
    <link rel="stylesheet" type="text/css" href="/view/clientframework/client.css"><script type="text/javascript" src="/view/clientframework/client.js"></script><script>
          // This turns on the display of the copyright notice which is not visible by default.
          // Because the head is removed when used in the web help, this function will only exists
          // when the chm help is being created.
          window.onload = function() {
          copyrightElement = document.getElementById('CopyrightNotice');
          copyrightElement.style.display = 'block';
          };
        </script><script>
          $(function() {
          $( "#tabs" ).tabs();
          });
        </script></head>
  <body><script>
          function copyCode(language) {
          // Get the pre element for the specified language.
          var preElement = document.getElementById(language);

          // Get the text from the element and copy it to the clipboard.
          var preText = preElement.innerText;

          var isIE = /*@cc_on!@*/false || !!document.documentMode;

          if (isIE)
          {
            window.clipboardData.setData('Text', preText);
          }
          else
          {
            navigator.clipboard.writeText(preText);
          }

          //alert("Code copied to clipboard");
          }
        </script><link rel="stylesheet" type="text/css" href="../Style/APIHelp.css">
    <h1 class="api">Split a 2D Curve</h1>
    <h2 class="api">
          Description
        </h2>Demonstrates the ability to extract split curves from a transient geometry curve.  This sample has you select an existing sketch spline and splits it at the midpoint of parametric space. It then creates real curves using the split curve results and deletes the original sketch curve.<h2 class="api">
          Code Samples
        </h2>
    <div id="tabs">
      <ul>
        <li><a href="#VBA">VBA</a></li>
        <li><a href="#iLogic">iLogic</a></li>
      </ul>
      <div id="VBA" class="api-code">To use this sample a part must be active.<table width="100%" style="font-size:15">
          <tr>
            <td align="right"><button onclick="copyCode('VBA_code')" class="copy-code">Copy Code</button></td>
          </tr>
        </table>
        <pre class="api-code" id="VBA_code">Public Sub SplitCurve2D()
    Dim partDoc As PartDocument
    Set partDoc = ThisApplication.ActiveDocument
    
    Dim spline As Object
    Set spline = ThisApplication.CommandManager.Pick(kSketchCurveSplineFilter, "Select 2d spline")
    
    <span style="color:blue">' Get the spline geometry from the entity.</span>
    Dim splineCurve As BSplineCurve2d
    Set splineCurve = spline.Geometry
    
    <span style="color:blue">' Determine the parameter value for geometric midpoint of the curve.</span>
    Dim curveEval As Curve2dEvaluator
    Set curveEval = splineCurve.Evaluator
    Dim startParam As Double
    Dim endParam As Double
    Call curveEval.GetParamExtents(startParam, endParam)
    Dim midParam As Double
    Call curveEval.GetParamAtLength(startParam, spline.Length / 2, midParam)
    
    <span style="color:blue">' Split the curve.</span>
    Dim curve1 As BSplineCurve2d
    Dim curve2 As BSplineCurve2d
    Call splineCurve.Split(midParam, curve1, curve2)
    
    <span style="color:blue">' Create new sketch curves using the extracted splines.</span>
    Dim splineSketch As sketch
    Set splineSketch = spline.Parent
    Call splineSketch.SketchFixedSplines.Add(curve1)
    Call splineSketch.SketchFixedSplines.Add(curve2)
    
    <span style="color:blue">' Delete the original curve.</span>
    spline.Delete
End Sub</pre>
      </div>
      <div id="iLogic" class="api-code">To use this sample a part must be active.<table width="100%" style="font-size:15">
          <tr>
            <td align="right"><button onclick="copyCode('iLogic_code')" class="copy-code">Copy Code</button></td>
          </tr>
        </table>
        <pre class="api-code" id="iLogic_code">    Dim partDoc As PartDocument
    partDoc = ThisApplication.ActiveDocument
    
    Dim spline As Object
    spline = ThisApplication.CommandManager.Pick(kSketchCurveSplineFilter, "Select 2d spline")
    
    <span style="color:blue">' Get the spline geometry from the entity.</span>
    Dim splineCurve As BSplineCurve2d
    splineCurve = spline.Geometry
    
    <span style="color:blue">' Determine the parameter value for geometric midpoint of the curve.</span>
    Dim curveEval As Curve2dEvaluator
    curveEval = splineCurve.Evaluator
    Dim startParam As Double
    Dim endParam As Double
    Call curveEval.GetParamExtents(startParam, endParam)
    Dim midParam As Double
    Call curveEval.GetParamAtLength(startParam, spline.Length / 2, midParam)
    
    <span style="color:blue">' Split the curve.</span>
    Dim curve1 As BSplineCurve2d
    Dim curve2 As BSplineCurve2d
    Call splineCurve.Split(midParam, curve1, curve2)
    
    <span style="color:blue">' Create new sketch curves using the extracted splines.</span>
    Dim splineSketch As sketch
    splineSketch = spline.Parent
    Call splineSketch.SketchFixedSplines.Add(curve1)
    Call splineSketch.SketchFixedSplines.Add(curve2)
    
    <span style="color:blue">' Delete the original curve.</span>
    spline.Delete</pre>
      </div>
    </div><br><br><div id="CopyrightNotice" style="display:none;">
      <hr>
      <table width="100%" style="font-size:15">
        <tr>
          <td align="left">
                Â© Copyright 2025 Autodesk, Inc.
              </td>
          <td align="right"><a href="mailto:mfg.api.help.comments@autodesk.com?subject=Inventor%202026%20API%20Help%20(Split2DCurve%20Sample%20Help%20Topic)">Comment on this page.</a></td>
        </tr>
      </table>
    </div>
  </body>
</html>