<html>
  <head>
    <META http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="topic-type" content="reference-adsk">
    <meta name="helpsystempath" content="/view/INVNTOR/2026/ENU/">
    <link rel="canonical" href="/cloudhelp/2026/ENU/Inventor-API/files/TransientBRep_Sample.htm#!">
    <meta name="product" content="INVNTOR">
    <meta name="release" content="2026">
    <meta name="book" content="Developer">
    <meta name="component" content="Inventor-API">
    <meta name="created" content="">
    <meta name="user-comments" content="enable">
    <meta name="contextid" content="TransientBRep_Sample">
    <meta name="description" content="Create primitive BRep Sample">
    <meta name="topicid" content="TransientBRep_Sample">
    <meta name="experiencelevel" content="expert">
    <meta name="audience" content="programmer">
    <meta name="language" content="ENU">
    <title>Create primitive BRep</title>
    <link rel="stylesheet" href="../Style/jquery-ui.css"><script src="../Scripts/jquery-1.11.1.js"></script><script src="../Scripts/jquery-ui.js"></script><link rel="stylesheet" type="text/css" href="../Style/APIHelp-chm.css">
    <link rel="stylesheet" type="text/css" href="/view/clientframework/client.css"><script type="text/javascript" src="/view/clientframework/client.js"></script><script>
          // This turns on the display of the copyright notice which is not visible by default.
          // Because the head is removed when used in the web help, this function will only exists
          // when the chm help is being created.
          window.onload = function() {
          copyrightElement = document.getElementById('CopyrightNotice');
          copyrightElement.style.display = 'block';
          };
        </script><script>
          $(function() {
          $( "#tabs" ).tabs();
          });
        </script></head>
  <body><script>
          function copyCode(language) {
          // Get the pre element for the specified language.
          var preElement = document.getElementById(language);

          // Get the text from the element and copy it to the clipboard.
          var preText = preElement.innerText;

          var isIE = /*@cc_on!@*/false || !!document.documentMode;

          if (isIE)
          {
            window.clipboardData.setData('Text', preText);
          }
          else
          {
            navigator.clipboard.writeText(preText);
          }

          //alert("Code copied to clipboard");
          }
        </script><link rel="stylesheet" type="text/css" href="../Style/APIHelp.css">
    <h1 class="api">Create primitive BRep</h1>
    <h2 class="api">
          Description
        </h2>This sample demonstrates the creation of primitive (solid) BRep.<h2 class="api">
          Code Samples
        </h2>
    <div id="tabs">
      <ul>
        <li><a href="#VBA">VBA</a></li>
        <li><a href="#iLogic">iLogic</a></li>
      </ul>
      <div id="VBA" class="api-code">
        <table width="100%" style="font-size:15">
          <tr>
            <td align="right"><button onclick="copyCode('VBA_code')" class="copy-code">Copy Code</button></td>
          </tr>
        </table>
        <pre class="api-code" id="VBA_code">Public Sub CreateBRep()
    <span style="color:blue">' Create a new part document, using the default part template.</span>
    Dim oPartDoc As PartDocument
    Set oPartDoc = ThisApplication.Documents.Add(kPartDocumentObject, _
                ThisApplication.FileManager.GetTemplateFile(kPartDocumentObject))

    <span style="color:blue">' Set a reference to the component definition.</span>
    Dim oCompDef As PartComponentDefinition
    Set oCompDef = oPartDoc.ComponentDefinition

    <span style="color:blue">' Set a reference to the TransientBRep object.</span>
    Dim oTransientBRep As TransientBRep
    Set oTransientBRep = ThisApplication.TransientBRep
    
    <span style="color:blue">' Create a range box that will define the extents of a block.</span>
    Dim oBox As Box
    Set oBox = ThisApplication.TransientGeometry.CreateBox
    
    <span style="color:blue">' Expand in all directions by 1 cm.</span>
    oBox.Expand 1
    
    <span style="color:blue">' Create the block.</span>
    Dim oBody As SurfaceBody
    Set oBody = oTransientBRep.CreateSolidBlock(oBox)
    
    <span style="color:blue">' Create bottom and top points for a cylinder.</span>
    Dim oBottomPt As Point
    Set oBottomPt = ThisApplication.TransientGeometry.CreatePoint(0, 1, 0)
    
    Dim oTopPt As Point
    Set oTopPt = ThisApplication.TransientGeometry.CreatePoint(0, 3, 0)
    
    <span style="color:blue">' Create the cylinder body.</span>
    Dim oCylinder As SurfaceBody
    Set oCylinder = oTransientBRep.CreateSolidCylinderCone(oBottomPt, oTopPt, 0.5, 0.5, 0.5)
    
    <span style="color:blue">' Boolean the bodies; "oBody" will return the result</span>
    Call oTransientBRep.DoBoolean(oBody, oCylinder, kBooleanTypeUnion)
    
    <span style="color:blue">' Create a base feature with the result body.</span>
    Dim oBaseFeature As NonParametricBaseFeature
    Set oBaseFeature = oCompDef.Features.NonParametricBaseFeatures.Add(oBody)
End Sub</pre>
      </div>
      <div id="iLogic" class="api-code">
        <table width="100%" style="font-size:15">
          <tr>
            <td align="right"><button onclick="copyCode('iLogic_code')" class="copy-code">Copy Code</button></td>
          </tr>
        </table>
        <pre class="api-code" id="iLogic_code">    <span style="color:blue">' Create a new part document, using the default part template.</span>
    Dim oPartDoc As PartDocument
    oPartDoc = ThisApplication.Documents.Add(kPartDocumentObject, _
                ThisApplication.FileManager.GetTemplateFile(kPartDocumentObject))

    <span style="color:blue">' Set a reference to the component definition.</span>
    Dim oCompDef As PartComponentDefinition
    oCompDef = oPartDoc.ComponentDefinition

    <span style="color:blue">' Set a reference to the TransientBRep object.</span>
    Dim oTransientBRep As TransientBRep
    oTransientBRep = ThisApplication.TransientBRep
    
    <span style="color:blue">' Create a range box that will define the extents of a block.</span>
    Dim oBox As Box
    oBox = ThisApplication.TransientGeometry.CreateBox
    
    <span style="color:blue">' Expand in all directions by 1 cm.</span>
    oBox.Expand(1)
    
    <span style="color:blue">' Create the block.</span>
    Dim oBody As SurfaceBody
    oBody = oTransientBRep.CreateSolidBlock(oBox)
    
    <span style="color:blue">' Create bottom and top points for a cylinder.</span>
    Dim oBottomPt As Point
    oBottomPt = ThisApplication.TransientGeometry.CreatePoint(0, 1, 0)
    
    Dim oTopPt As Point
    oTopPt = ThisApplication.TransientGeometry.CreatePoint(0, 3, 0)
    
    <span style="color:blue">' Create the cylinder body.</span>
    Dim oCylinder As SurfaceBody
    oCylinder = oTransientBRep.CreateSolidCylinderCone(oBottomPt, oTopPt, 0.5, 0.5, 0.5)
    
    <span style="color:blue">' Boolean the bodies; "oBody" will return the result</span>
    Call oTransientBRep.DoBoolean(oBody, oCylinder, kBooleanTypeUnion)
    
    <span style="color:blue">' Create a base feature with the result body.</span>
    Dim oBaseFeature As NonParametricBaseFeature
    oBaseFeature = oCompDef.Features.NonParametricBaseFeatures.Add(oBody)</pre>
      </div>
    </div><br><br><div id="CopyrightNotice" style="display:none;">
      <hr>
      <table width="100%" style="font-size:15">
        <tr>
          <td align="left">
                Â© Copyright 2025 Autodesk, Inc.
              </td>
          <td align="right"><a href="mailto:mfg.api.help.comments@autodesk.com?subject=Inventor%202026%20API%20Help%20(TransientBRep%20Sample%20Help%20Topic)">Comment on this page.</a></td>
        </tr>
      </table>
    </div>
  </body>
</html>