<html>
  <head>
    <META http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="topic-type" content="reference-adsk">
    <meta name="helpsystempath" content="/view/INVNTOR/2026/ENU/">
    <link rel="canonical" href="/cloudhelp/2026/ENU/Inventor-API/files/TransformOccurrence_Sample.htm#!">
    <meta name="product" content="INVNTOR">
    <meta name="release" content="2026">
    <meta name="book" content="Developer">
    <meta name="component" content="Inventor-API">
    <meta name="created" content="">
    <meta name="user-comments" content="enable">
    <meta name="contextid" content="TransformOccurrence_Sample">
    <meta name="description" content="Assembly Move Occurrence Sample">
    <meta name="topicid" content="TransformOccurrence_Sample">
    <meta name="experiencelevel" content="expert">
    <meta name="audience" content="programmer">
    <meta name="language" content="ENU">
    <title>Assembly Move Occurrence</title>
    <link rel="stylesheet" href="../Style/jquery-ui.css"><script src="../Scripts/jquery-1.11.1.js"></script><script src="../Scripts/jquery-ui.js"></script><link rel="stylesheet" type="text/css" href="../Style/APIHelp-chm.css">
    <link rel="stylesheet" type="text/css" href="/view/clientframework/client.css"><script type="text/javascript" src="/view/clientframework/client.js"></script><script>
          // This turns on the display of the copyright notice which is not visible by default.
          // Because the head is removed when used in the web help, this function will only exists
          // when the chm help is being created.
          window.onload = function() {
          copyrightElement = document.getElementById('CopyrightNotice');
          copyrightElement.style.display = 'block';
          };
        </script><script>
          $(function() {
          $( "#tabs" ).tabs();
          });
        </script></head>
  <body><script>
          function copyCode(language) {
          // Get the pre element for the specified language.
          var preElement = document.getElementById(language);

          // Get the text from the element and copy it to the clipboard.
          var preText = preElement.innerText;

          var isIE = /*@cc_on!@*/false || !!document.documentMode;

          if (isIE)
          {
            window.clipboardData.setData('Text', preText);
          }
          else
          {
            navigator.clipboard.writeText(preText);
          }

          //alert("Code copied to clipboard");
          }
        </script><link rel="stylesheet" type="text/css" href="../Style/APIHelp.css">
    <h1 class="api">Assembly Move Occurrence</h1>
    <h2 class="api">
          Description
        </h2>This sample demonstrates moving a component occurrence. This sample performs a translate, but a rotate can also be performed since the transform is defined using a matrix.<h2 class="api">
          Code Samples
        </h2>
    <div id="tabs">
      <ul>
        <li><a href="#VBA">VBA</a></li>
        <li><a href="#iLogic">iLogic</a></li>
      </ul>
      <div id="VBA" class="api-code">Before running the sample you need to open an assembly and select the occurrence to move. The sample code first moves the occurrence honoring any existing constraints and then moves it ignoring any constraints.<table width="100%" style="font-size:15">
          <tr>
            <td align="right"><button onclick="copyCode('VBA_code')" class="copy-code">Copy Code</button></td>
          </tr>
        </table>
        <pre class="api-code" id="VBA_code">Public Sub MoveOccurrence()
   <span style="color:blue">' Set a reference to the assembly component definintion.</span>
   Dim oAsmCompDef As AssemblyComponentDefinition
   Set oAsmCompDef = ThisApplication.ActiveDocument.ComponentDefinition

   <span style="color:blue">' Get an occurrence from the select set.</span>
   On Error Resume Next
   Dim oOccurrence As ComponentOccurrence
   Set oOccurrence = ThisApplication.ActiveDocument.SelectSet.Item(1)
   If Err Then
      MsgBox "An occurrence must be selected."
      Exit Sub
   End If
   On Error GoTo 0

   <span style="color:blue">' Get the current transformation matrix from the occurrence.</span>
   Dim oTransform As Matrix
   Set oTransform = oOccurrence.Transformation

   <span style="color:blue">' Move the occurrence honoring any existing constraints.</span>
   oTransform.SetTranslation ThisApplication.TransientGeometry.CreateVector(2, 2, 3)
   oOccurrence.Transformation = oTransform

   <span style="color:blue">' Move the occurrence ignoring any constraints.</span>
   <span style="color:blue">' Anything that causes the assembly to recompute will cause the</span>
   <span style="color:blue">' occurrence to reposition itself to honor the constraints.</span>
   oTransform.SetTranslation ThisApplication.TransientGeometry.CreateVector(3, 4, 5)
   Call oOccurrence.SetTransformWithoutConstraints(oTransform)
End Sub</pre>
      </div>
      <div id="iLogic" class="api-code">Before running the sample you need to open an assembly and select the occurrence to move. The sample code first moves the occurrence honoring any existing constraints and then moves it ignoring any constraints.<table width="100%" style="font-size:15">
          <tr>
            <td align="right"><button onclick="copyCode('iLogic_code')" class="copy-code">Copy Code</button></td>
          </tr>
        </table>
        <pre class="api-code" id="iLogic_code">    <span style="color:blue">' Set a reference to the assembly component definintion.</span>
   Dim oAsmCompDef As AssemblyComponentDefinition
   oAsmCompDef = ThisApplication.ActiveDocument.ComponentDefinition

   <span style="color:blue">' Get an occurrence from the select set.</span>
   On Error Resume Next
   Dim oOccurrence As ComponentOccurrence
   oOccurrence = ThisApplication.ActiveDocument.SelectSet.Item(1)
   If Err.Number &gt; 0 Then
      MsgBox("An occurrence must be selected.")
      Exit Sub
   End If
   On Error GoTo 0

   <span style="color:blue">' Get the current transformation matrix from the occurrence.</span>
   Dim oTransform As Matrix
   oTransform = oOccurrence.Transformation

   <span style="color:blue">' Move the occurrence honoring any existing constraints.</span>
   oTransform.SetTranslation(ThisApplication.TransientGeometry.CreateVector(2, 2, 3))
   oOccurrence.Transformation = oTransform

   <span style="color:blue">' Move the occurrence ignoring any constraints.</span>
   <span style="color:blue">' Anything that causes the assembly to recompute will cause the</span>
   <span style="color:blue">' occurrence to reposition itself to honor the constraints.</span>
   oTransform.SetTranslation(ThisApplication.TransientGeometry.CreateVector(3, 4, 5))
   Call oOccurrence.SetTransformWithoutConstraints(oTransform)</pre>
      </div>
    </div><br><br><div id="CopyrightNotice" style="display:none;">
      <hr>
      <table width="100%" style="font-size:15">
        <tr>
          <td align="left">
                Â© Copyright 2025 Autodesk, Inc.
              </td>
          <td align="right"><a href="mailto:mfg.api.help.comments@autodesk.com?subject=Inventor%202026%20API%20Help%20(TransformOccurrence%20Sample%20Help%20Topic)">Comment on this page.</a></td>
        </tr>
      </table>
    </div>
  </body>
</html>