<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="topic-type" content="reference-adsk">
    <meta name="helpsystempath" content="/view/INVNTOR/2026/ENU">
    <link rel="canonical" href="http://help.autodesk.com/cloudhelp/2026/ENU/Inventor-API/files/TriadEvents_Overview.htm">
    <meta name="product" content="INVNTOR">
    <meta name="release" content="2026">
    <meta name="book" content="Developer">
    <meta name="component" content="Inventor-API">
    <meta name="created" content="27/4/2016">
    <meta name="user-comments" content="enable">
    <meta name="description" content="">
    <meta name="topicid" content="GUID-DEC7591D-A875-4C41-8522-ABB4D4751CF2">
    <meta name="experiencelevel" content="expert">
    <meta name="audience" content="programmer">
    <meta name="language" content="ENU">
    <title>Triad Events</title>
    <link rel="stylesheet" type="text/css" href="../Style/APIHelp-chm.css">
    <link rel="stylesheet" type="text/css" href="/view/clientframework/client.css"/>
    <script type="text/javascript" src="/view/clientframework/client.js"><!--filler--></script>
	<script>
	  // This turns on the display of the copyright notice which is not visible by default.
	  // Because the head is removed when used in the web help, this function will only exists
	  // when the chm help is being created.
	  window.onload = function() {
		copyrightElement = document.getElementById('CopyrightNotice');
		copyrightElement.style.display = 'block';
	  };
	</script>
</head>
<body>
<link rel="stylesheet" type="text/css" href="../Style/APIHelp.css">

<H1>Triad Events</h1>
<h3>Introduction to TriadEvents - the 3D move and rotate tool</h3>

<p Class="Normal">The Autodesk Inventor user interface has a 3D move and rotate tool, available when you create or edit a grounded work point in a part or 3D sketch. A triad symbol is displayed. Select or drag a triad segment to indicate the type of transform required, or click it to open a dialog box. In the dialog box, you can enter coordinates to precisely position a grounded work point. In addition to entering coordinates, you can drag the triad along the X, Y, and Z coordinates to dynamically update the dialog box. Movement is not limited to the part axes. The 3D Move/Rotate tool can be rotated about any axis to realign the direction of subsequent moves.</p>

<p Class="Normal">The Autodesk Inventor API supports the 3D Move/Rotate tool through the TriadEvents object.</p>

<h3>The purpose of  TriadEvents</h3>

<p Class="Normal">The ability of the developer to control the triad affords many advantages to the user. An example is the routing of piping.  As each segment is placed, the triad can be positioned at the end of the pipe so the user can indicate, graphically but precisely, the axis of the next segment. The user can do this using the triad tool - something already familiar through the user interface. In addition to programmatically positioning the triad, the developer can receive notification of a number of triad events - for example, if the user interactively moves the triad.</p>

<h3>TriadEvents Object Model Diagram</h3>

 <br>
<div align="center"> <img src="../images/ov.triadevents_diag.png" border=0 ></div>
 <br>
 
<h3>Working with the TriadEvents API</h3>

<p Class="Normal">The TriadEvents object is used in a similar manner to other interaction events such as mouse and keyboard events.  It is obtained through the TriadEvents property of the InteractionEvents object.</p>
<p Class="Normal">Selection and other interaction events cannot be active while triad events are enabled. Start the InteractionEvents object  and set its InteractionDisabled property to True to start receiving triad events. </p>
<p Class="Normal">You can position the triad by calling the Reposition method of the TriadEvent object.</p>
<p Class="Normal">You can register a number of triad events,  including the following:</p>

<table>
	<tr><td><b>OnActivate</b> - Fires when the triad is activated.</td></tr>
	<tr><td><b>OnEndSequence</b> - Fires when the user ends a move sequence of the triad.</td></tr>
	<tr><td><b>OnStartSequence</b> - Fires when the user starts a move sequence of the triad. </td></tr>
	<tr><td><b>OnMove</b> - Fires when the triad moves as a result of a drag, reposition or if the user enters values for translation and rotation.</td></tr>
	<tr><td><b>OnMoveTriadOnlyToggle</b> - Fires when the Move Triad Only option is toggled.</td></tr>
	<tr><td><b>OnStartMove</b> - Fires when the triad begins to move as a result of a drag, reposition or if the user enters values for translation and rotation.</td></tr>
	<tr><td><b>OnEndMove</b> - Fires when the user ends an intermediate move of the triad.</td></tr>
	<tr><td><b>OnTerminate</b> - Fires when the triad is terminated.</td></tr>
	<tr><td><b>OnSegmentSelectionChange</b> - Fires every time a segment of a triad is selected.</td></tr>
	<tr><td></td></tr>
</table>

<h3>Using the TriadEvents object</h3>

<p Class="Normal">This example provides skeletal code demonstrating how to set up triad interaction events.  It enables the triad and implements the triad move event.  The code omits error checking for the sake of clarity and brevity.  Always check that return values are of the expected type.</p>
<p Class="Normal">Start a new VBA project and add a blank form (here named UserForm1).  Add the following code to the form, starting with declarations of the interaction and triad event objects:</p>
  
<br>
<table Class="Code">
<tr valign="middle">
	<td Class="Code">
	<pre>
Private WithEvents oInteraction As InteractionEvents
Private WithEvents oTriadEvents As TriadEvents
</pre></td></tr>
</table>
<br>

<p Class="Normal">Add a subroutine to be called when the form is initialized.  Obtain the InteractionEvents object from the CommandManager object, and turn of selection and interaction.  This means that the triad can still be manipulated by the user.</p>

<br>
<table Class="Code">
<tr valign="middle">
	<td Class="Code">
	<pre>
Sub UserForm_Initialize()
  Set oInteraction = ThisApplication.CommandManager.CreateInteractionEvents
  oInteraction.SelectionActive = False
  oInteraction.InteractionDisabled = True
</pre></td></tr>
</table>
<br>

<p Class="Normal">Obtain the TriadEvents object from the InteractionEvents object, and then set its Repeat and Enabled properties to True.  The Repeat property indicates that triad events should continue after a move sequence completes.</p>

<br>
<table Class="Code">
<tr valign="middle">
	<td Class="Code">
	<pre>
Set oTriadEvents = oInteraction.TriadEvents
  oTriadEvents.Repeat = True
  oTriadEvents.Enabled = True
</pre></td></tr>
</table>
<br>

<p Class="Normal">Now start interaction events, and call DoEvents so the process can be terminated when required.</p>

<br>
<table Class="Code">
<tr valign="middle">
	<td Class="Code">
	<pre>
  oInteraction.Start

  While UserForm1.Enabled = True
    DoEvents
  Wend
End Sub
</pre></td></tr>
</table>
<br>

<p Class="Normal">Add another subroutine, this time the OnMove event of the TriadEvents object.  When the user moves the triad through the user interface, this code is called.  This code prints a message, but other more significant actions can take place depending on context.</p>

<br>
<table Class="Code">
<tr valign="middle">
	<td Class="Code">
	<pre>
Private Sub oTriadEvents_OnMove(ByVal SelectedTriadSegment _
            As TriadSegmentEnum, _
            ByVal ShiftKeys As ShiftStateEnum, _
            ByVal CoordinateSystem As Matrix, _
            ByVal Context As NameValueMap, _
            HandlingCode As HandlingCodeEnum)

  Debug.Print "3D move / rotate tool has been moved."
End Sub
</pre></td></tr>
</table>
<br>

<p Class="Normal">The last subroutine to add to the form cleans up once the form is closed, and it stops the InteractionEvents object.</p>

<br>
<table Class="Code">
<tr valign="middle">
	<td Class="Code">
	<pre>
Private Sub UserForm1_Terminate()
  oInteraction.Stop
  Set oTriadEvents = Nothing
  Set oInteraction = Nothing
End Sub
</pre></td></tr>
</table>
<br>

<p Class="Normal">Finally, add the following code to a code module (not the form).  To run the sample code, run this TriadEventsTest subroutine.</p>

<br>
<table Class="Code">
<tr valign="middle">
	<td Class="Code">
	<pre>
Public Sub TriadEventsTest()
    UserForm1.Show vbModeless
End Sub
</pre></td></tr>
</table>
<br>

<p Class="Normal">When this sample is run in an open part document, the 3D Move/Rotate triad tool and dialog is displayed as follows:</p>

 <br>
<div align="center"> <img src="../images/ov.triadevents_shot1.png" border=0 ></div>
 <br>

<p Class="Normal">When the triad tool is moved by the user, the OnMove event is called and the code prints a short message to the VBA debug screen (the 'immeadiate' window, if open).</p>

<h3>Summary</h3>

<p Class="Normal">The TriadEvents object and API provide a convenient means of obtaining location and transformation data in a fashion already familiar to the user.  The triad can be activated and controlled through the API, and also provides a set of events to respond to changes to the triad made through the user interface.</p>

<h3>Also consider</h3>

<p Class="Normal">The InteractionEvents object provides selection, mouse and keyboard event callbacks, but also exposes the InteractionGraphics API.  Like the ClientGraphics API, this API can be used to display transient geometry as visual cues. Used with TriadEvents, a lot of contextual information can be provided to the user in the form of visual cues and guidance.</p>

<br />
<br />
<div id="CopyrightNotice" style="display:none;">
  <hr />
  <table width="100%" style="font-size:15">
	<tr>
	  <td align="left">
		&copy; Copyright 2025 Autodesk, Inc.
	  </td>
	  <td align="right">
		<a href="mailto:mfg.api.help.comments@autodesk.com?subject=Inventor%202026%20API%20Help%20(TriadEvents_Overview)">Comment on this page.</a>
	  </td>
	</tr>
  </table>
</div>

</body>
</html>
